/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file upsample_bilinear2d_grad_apt.cpp
 * \brief kernel entry for upsample_bilinear2d_grad
 *        R007: TilingKey encodes dtype + alignCorners (6 modes)
 */

#include "arch35/upsample_bilinear2d_grad_simt.h"

template <uint32_t schMode>
__global__ __aicore__ void upsample_bilinear2d_grad(GM_ADDR gradOutput, GM_ADDR gradInput, GM_ADDR workspace,
                                                    GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(UpsampleBilinear2dGradTilingData);
    GET_TILING_DATA_WITH_STRUCT(UpsampleBilinear2dGradTilingData, tilingData, tiling);

    // R007: compile-time dispatch by dtype + alignCorners
    if constexpr (schMode == UPSAMPLE_BILINEAR2D_GRAD_MODE_FP16_ALIGN) {
        NsUpsampleBilinear2dGrad::Process<half, 1>(gradOutput, gradInput, &tilingData);
    }
    if constexpr (schMode == UPSAMPLE_BILINEAR2D_GRAD_MODE_FP16_NOALIGN) {
        NsUpsampleBilinear2dGrad::Process<half, 0>(gradOutput, gradInput, &tilingData);
    }
    if constexpr (schMode == UPSAMPLE_BILINEAR2D_GRAD_MODE_FP32_ALIGN) {
        NsUpsampleBilinear2dGrad::Process<float, 1>(gradOutput, gradInput, &tilingData);
    }
    if constexpr (schMode == UPSAMPLE_BILINEAR2D_GRAD_MODE_FP32_NOALIGN) {
        NsUpsampleBilinear2dGrad::Process<float, 0>(gradOutput, gradInput, &tilingData);
    }
    if constexpr (schMode == UPSAMPLE_BILINEAR2D_GRAD_MODE_BF16_ALIGN) {
        NsUpsampleBilinear2dGrad::Process<bfloat16_t, 1>(gradOutput, gradInput, &tilingData);
    }
    if constexpr (schMode == UPSAMPLE_BILINEAR2D_GRAD_MODE_BF16_NOALIGN) {
        NsUpsampleBilinear2dGrad::Process<bfloat16_t, 0>(gradOutput, gradInput, &tilingData);
    }
}
