/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file roi_align_simt.h
 * \brief SIMT kernel for ROIAlign operator
 *        Grid-Stride pattern, bilinear interpolation, avg/max pooling
 *        POOL_MODE and ROI_END_MODE are compile-time template parameters
 */

#ifndef ROI_ALIGN_SIMT_H_
#define ROI_ALIGN_SIMT_H_

#include <type_traits>
#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "simt_api/common_functions.h"
#include "simt_api/math_functions.h"
#include "simt_api/asc_fp16.h"
#include "simt_api/asc_simt.h"
#include "roi_align_tiling_data.h"
#include "roi_align_tiling_key.h"

namespace NsROIAlign {
using namespace AscendC;

static constexpr uint32_t THREAD_NUM = 512;

// ROI structure: [batch_id, x1, y1, x2, y2]
static constexpr int32_t COORDS_PER_ROI = 5;
static constexpr int32_t ROI_IDX_BATCH = 0;
static constexpr int32_t ROI_IDX_X1 = 1;
static constexpr int32_t ROI_IDX_Y1 = 2;
static constexpr int32_t ROI_IDX_X2 = 3;
static constexpr int32_t ROI_IDX_Y2 = 4;

// Bilinear interpolation boundary margin and offsets
static constexpr float OUT_OF_BOUNDS_MARGIN = -1.0f;
static constexpr int32_t NEXT_PIXEL_OFFSET = 1;

// ROI end mode algorithm constants
static constexpr float MIN_ROI_SIZE = 1.0f;
static constexpr float ROI_PLUS1_OFFSET = 1.0f;
static constexpr float ROI_HALF_OFFSET = 0.5f;

// Sampling constants
static constexpr float BIN_CENTER_OFFSET = 0.5f;
static constexpr int32_t ADAPTIVE_SAMPLE_NUM = 0;
static constexpr int32_t MIN_SAMPLE_COUNT = 1;

// ===== Type conversion helpers =====
__simt_callee__ __aicore__ inline float ToFloat(float v) { return v; }
__simt_callee__ __aicore__ inline float ToFloat(half v) { return __half2float(v); }

// ===== Convert T to float for reading from GM =====
__simt_callee__ __aicore__ inline float ReadAsFloat(float v) { return v; }
__simt_callee__ __aicore__ inline float ReadAsFloat(half v) { return __half2float(v); }

// ===== Convert float back to T for writing =====
__simt_callee__ __aicore__ inline float WriteAsType(float v, float) { return v; }
__simt_callee__ __aicore__ inline half WriteAsType(float v, half) { return __float2half(v); }

// ===== Bilinear interpolation — always computes in float32 =====
template <typename T>
__simt_callee__ __aicore__ inline float BilinearInterpolate(__gm__ const T* data, int64_t height, int64_t width,
                                                            float y, float x)
{
    if (y < OUT_OF_BOUNDS_MARGIN || y > height || x < OUT_OF_BOUNDS_MARGIN || x > width) {
        return 0.0f;
    }
    if (y <= 0) {
        y = 0;
    }
    if (x <= 0) {
        x = 0;
    }
    int32_t yLow = static_cast<int32_t>(y);
    int32_t xLow = static_cast<int32_t>(x);
    int32_t yHigh = 0;
    int32_t xHigh = 0;

    if (yLow >= static_cast<int32_t>(height - 1)) {
        yLow = static_cast<int32_t>(height - 1);
        yHigh = yLow;
        y = static_cast<float>(yLow);
    } else {
        yHigh = yLow + 1;
    }

    if (xLow >= static_cast<int32_t>(width - 1)) {
        xLow = static_cast<int32_t>(width - 1);
        xHigh = xLow;
        x = static_cast<float>(xLow);
    } else {
        xHigh = xLow + 1;
    }

    float ly = y - static_cast<float>(yLow);
    float lx = x - static_cast<float>(xLow);
    float hy = 1.0f - ly;
    float hx = 1.0f - lx;
    float v1 = ReadAsFloat(data[yLow * width + xLow]);
    float v2 = ReadAsFloat(data[yLow * width + xHigh]);
    float v3 = ReadAsFloat(data[yHigh * width + xLow]);
    float v4 = ReadAsFloat(data[yHigh * width + xHigh]);

    return hy * hx * v1 + hy * lx * v2 + ly * hx * v3 + ly * lx * v4;
}

// ===== ROI coordinate computation — always in float32 =====
template <typename T, int32_t ROI_END_MODE>
__simt_callee__ __aicore__ inline void ComputeRoiCoords(__gm__ const T* roi, float spatialScale, int32_t pooledHeight,
                                                        int32_t pooledWidth, float& roiStartW, float& roiStartH,
                                                        float& binSizeH, float& binSizeW, int32_t& roiBinGridH,
                                                        int32_t& roiBinGridW, int32_t& count, int32_t sampleNum)
{
    float x1 = ReadAsFloat(roi[ROI_IDX_X1]);
    float y1 = ReadAsFloat(roi[ROI_IDX_Y1]);
    float x2 = ReadAsFloat(roi[ROI_IDX_X2]);
    float y2 = ReadAsFloat(roi[ROI_IDX_Y2]);
    float roiW = 0.0f;
    float roiH = 0.0f;
    if constexpr (ROI_END_MODE == ROI_ALIGN_MODE_0) {
        roiStartW = x1 * spatialScale;
        roiStartH = y1 * spatialScale;
        float roiEndW = x2 * spatialScale;
        float roiEndH = y2 * spatialScale;
        roiW = roiEndW - roiStartW;
        roiH = roiEndH - roiStartH;
        if (roiW < MIN_ROI_SIZE) {
            roiW = MIN_ROI_SIZE;
        }
        if (roiH < MIN_ROI_SIZE) {
            roiH = MIN_ROI_SIZE;
        }
        binSizeH = roiH / static_cast<float>(pooledHeight);
        binSizeW = roiW / static_cast<float>(pooledWidth);
    } else if constexpr (ROI_END_MODE == ROI_ALIGN_MODE_1) {
        roiStartW = (x1 + ROI_PLUS1_OFFSET) * spatialScale;
        roiStartH = (y1 + ROI_PLUS1_OFFSET) * spatialScale;
        float roiEndW = (x2 + ROI_PLUS1_OFFSET) * spatialScale;
        float roiEndH = (y2 + ROI_PLUS1_OFFSET) * spatialScale;
        roiW = roiEndW - roiStartW;
        roiH = roiEndH - roiStartH;
        if (roiW < MIN_ROI_SIZE) {
            roiW = MIN_ROI_SIZE;
        }
        if (roiH < MIN_ROI_SIZE) {
            roiH = MIN_ROI_SIZE;
        }
        binSizeH = roiH / static_cast<float>(pooledHeight);
        binSizeW = roiW / static_cast<float>(pooledWidth);
    } else {
        roiStartW = x1 * spatialScale - ROI_HALF_OFFSET;
        roiStartH = y1 * spatialScale - ROI_HALF_OFFSET;
        float roiEndW = x2 * spatialScale - ROI_HALF_OFFSET;
        float roiEndH = y2 * spatialScale - ROI_HALF_OFFSET;
        roiW = roiEndW - roiStartW;
        roiH = roiEndH - roiStartH;
        binSizeH = roiH / static_cast<float>(pooledHeight);
        binSizeW = roiW / static_cast<float>(pooledWidth);
    }
    if (sampleNum > ADAPTIVE_SAMPLE_NUM) {
        roiBinGridH = sampleNum;
        roiBinGridW = sampleNum;
    } else {
        float adaptiveH = ceilf(roiH / static_cast<float>(pooledHeight));
        float adaptiveW = ceilf(roiW / static_cast<float>(pooledWidth));
        roiBinGridH = static_cast<int32_t>(adaptiveH);
        roiBinGridW = static_cast<int32_t>(adaptiveW);
    }
    count = roiBinGridH * roiBinGridW;
    count = (count > MIN_SAMPLE_COUNT) ? count : MIN_SAMPLE_COUNT;
}

// ===== Average pooling aggregation — accumulates in float32 =====
template <typename T>
__simt_callee__ __aicore__ inline float SampleAndPoolAvg(__gm__ const T* featuresNC, int64_t height, int64_t width,
                                                         float roiStartH, float roiStartW, float binSizeH,
                                                         float binSizeW, int32_t ph, int32_t pw, int32_t roiBinGridH,
                                                         int32_t roiBinGridW, int32_t count)
{
    float outputVal = 0.0f;
    for (int32_t iy = 0; iy < roiBinGridH; iy++) {
        float yy = roiStartH + static_cast<float>(ph) * binSizeH +
                   (static_cast<float>(iy) + BIN_CENTER_OFFSET) * binSizeH / static_cast<float>(roiBinGridH);
        for (int32_t ix = 0; ix < roiBinGridW; ix++) {
            float xx = roiStartW + static_cast<float>(pw) * binSizeW +
                       (static_cast<float>(ix) + BIN_CENTER_OFFSET) * binSizeW / static_cast<float>(roiBinGridW);
            outputVal += BilinearInterpolate<T>(featuresNC, height, width, yy, xx);
        }
    }
    return outputVal / static_cast<float>(count);
}

// ===== Max pooling aggregation — computes in float32 =====
template <typename T>
__simt_callee__ __aicore__ inline float SampleAndPoolMax(__gm__ const T* featuresNC, int64_t height, int64_t width,
                                                         float roiStartH, float roiStartW, float binSizeH,
                                                         float binSizeW, int32_t ph, int32_t pw, int32_t roiBinGridH,
                                                         int32_t roiBinGridW)
{
    float maxVal = -ASCRT_INF_F;
    for (int32_t iy = 0; iy < roiBinGridH; iy++) {
        float yy = roiStartH + static_cast<float>(ph) * binSizeH +
                   (static_cast<float>(iy) + BIN_CENTER_OFFSET) * binSizeH / static_cast<float>(roiBinGridH);
        for (int32_t ix = 0; ix < roiBinGridW; ix++) {
            float xx = roiStartW + static_cast<float>(pw) * binSizeW +
                       (static_cast<float>(ix) + BIN_CENTER_OFFSET) * binSizeW / static_cast<float>(roiBinGridW);
            float val = BilinearInterpolate<T>(featuresNC, height, width, yy, xx);
            if (val > maxVal || val != val) {
                maxVal = val;
            }
        }
    }
    return maxVal;
}

// ===== Get batch index from rois or rois_n (__simt_callee__) =====
template <typename T>
__simt_callee__ __aicore__ inline int32_t GetBatchIdx(__gm__ const T* roi, __gm__ const int32_t* roisN, int32_t n,
                                                      int32_t hasRoisN)
{
    if (hasRoisN != 0 && roisN != nullptr) {
        return roisN[n];
    }
    return static_cast<int32_t>(ReadAsFloat(roi[ROI_IDX_BATCH]));
}

// ===== SIMT VF main kernel — all intermediate computation in float32 =====
template <typename T, int32_t POOL_MODE, int32_t ROI_END_MODE, int32_t IDX_MODE>
__simt_vf__ __aicore__ __launch_bounds__(THREAD_NUM) inline void OpROIAlignSimtKernel(
    int64_t totalElements, int64_t channels, int64_t height, int64_t width, int32_t pooledHeight, int32_t pooledWidth,
    int32_t sampleNum, float spatialScale, int32_t hasRoisN, __gm__ const T* features, __gm__ const T* rois,
    __gm__ const int32_t* roisN, __gm__ T* y)
{
    using IdxType = std::conditional_t<IDX_MODE == ROI_ALIGN_IDX_INT64, int64_t, int32_t>;
    uint64_t localIdx = static_cast<uint64_t>(blockIdx.x) * static_cast<uint64_t>(blockDim.x) +
                        static_cast<uint64_t>(threadIdx.x);
    uint64_t gridStep = static_cast<uint64_t>(blockDim.x) * static_cast<uint64_t>(gridDim.x);
    for (uint64_t index = localIdx; index < static_cast<uint64_t>(totalElements); index += gridStep) {
        IdxType pw = static_cast<IdxType>(index % static_cast<uint64_t>(pooledWidth));
        IdxType ph = static_cast<IdxType>((index / static_cast<uint64_t>(pooledWidth)) %
                                          static_cast<uint64_t>(pooledHeight));
        IdxType c = static_cast<IdxType>(
            (index / static_cast<uint64_t>(pooledWidth) / static_cast<uint64_t>(pooledHeight)) %
            static_cast<uint64_t>(channels));
        IdxType n = static_cast<IdxType>(index / static_cast<uint64_t>(pooledWidth) /
                                         static_cast<uint64_t>(pooledHeight) / static_cast<uint64_t>(channels));
        __gm__ const T* roi = rois + n * COORDS_PER_ROI;
        IdxType batchIdx = static_cast<IdxType>(GetBatchIdx<T>(roi, roisN, static_cast<int32_t>(n), hasRoisN));
        float roiStartW, roiStartH, binSizeH, binSizeW;
        int32_t roiBinGridH, roiBinGridW, count;
        ComputeRoiCoords<T, ROI_END_MODE>(roi, spatialScale, pooledHeight, pooledWidth, roiStartW, roiStartH, binSizeH,
                                          binSizeW, roiBinGridH, roiBinGridW, count, sampleNum);
        __gm__ const T* featuresNC = features + (batchIdx * channels + c) * height * width;
        float result;
        if constexpr (POOL_MODE == ROI_ALIGN_POOL_AVG) {
            result = SampleAndPoolAvg<T>(featuresNC, height, width, roiStartH, roiStartW, binSizeH, binSizeW,
                                         static_cast<int32_t>(ph), static_cast<int32_t>(pw), roiBinGridH, roiBinGridW,
                                         count);
        } else {
            result = SampleAndPoolMax<T>(featuresNC, height, width, roiStartH, roiStartW, binSizeH, binSizeW,
                                         static_cast<int32_t>(ph), static_cast<int32_t>(pw), roiBinGridH, roiBinGridW);
        }
        y[index] = WriteAsType(result, static_cast<T>(0));
    }
}

// ===== Process entry =====
template <typename T, int32_t POOL_MODE, int32_t ROI_END_MODE, int32_t IDX_MODE>
__aicore__ inline void Process(GM_ADDR features, GM_ADDR rois, GM_ADDR roisN, GM_ADDR y,
                               const ROIAlignTilingData* tilingData)
{
    __gm__ const T* featuresGm = (__gm__ const T*)features;
    __gm__ const T* roisGm = (__gm__ const T*)rois;
    __gm__ const int32_t* roisNGm = (tilingData->hasRoisN != 0) ? (__gm__ const int32_t*)roisN : nullptr;
    __gm__ T* yGm = (__gm__ T*)y;
    asc_vf_call<OpROIAlignSimtKernel<T, POOL_MODE, ROI_END_MODE, IDX_MODE>>(
        dim3(THREAD_NUM), tilingData->totalElements, tilingData->channels, tilingData->height, tilingData->width,
        tilingData->pooledHeight, tilingData->pooledWidth, tilingData->sampleNum, tilingData->spatialScale,
        tilingData->hasRoisN, featuresGm, roisGm, roisNGm, yGm);
}

} // namespace NsROIAlign

#endif // ROI_ALIGN_SIMT_H_
