/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file extract_image_patches_tiling.cpp
 * \brief Tiling implementation for extract_image_patches operator
 */

#include <array>
#include <cstring>
#include <string>
#include "log/log.h"
#include "platform/platform_ascendc.h"
#include "util/math_util.h"
#include "util/platform_util.h"
#include "op_host/tiling_util.h"
#include "op_host/tiling_templates_registry.h"
#include "../../op_kernel/arch35/extract_image_patches_tiling_data.h"
#include "../../op_kernel/arch35/extract_image_patches_tiling_key.h"

namespace optiling {

using namespace Ops::Base;

static constexpr int64_t PER_CORE_MIN_ELEMENTS = 1024;
static constexpr uint32_t DCACHE_SIZE = 128 * 1024;
static constexpr uint32_t STATIC_UB_ESTIMATE = 0;
static constexpr int64_t IDX_0 = 0;
static constexpr int64_t ATTR_IDX_KSIZES = 0;
static constexpr int64_t ATTR_IDX_STRIDES = 1;
static constexpr int64_t ATTR_IDX_RATES = 2;
static constexpr int64_t ATTR_IDX_PADDING = 3;
static constexpr size_t ATTR_LIST_LEN = 4;
static constexpr size_t DIM_NUM = 4;
static constexpr int32_t DIM_IDX_N = 0;
static constexpr int32_t NHWC_IDX_H = 1;
static constexpr int32_t NHWC_IDX_W = 2;
static constexpr int32_t NHWC_IDX_C = 3;
static constexpr int32_t NCHW_IDX_C = 1;
static constexpr int32_t NCHW_IDX_H = 2;
static constexpr int32_t NCHW_IDX_W = 3;
static constexpr int64_t BLOCK_ALIGN = 32;
static constexpr size_t WORKSPACE_NUM = 1;

static std::string FormatAttrList(const int64_t* values)
{
    return "[" + std::to_string(values[0]) + ", " + std::to_string(values[1]) + ", " + std::to_string(values[2]) +
           ", " + std::to_string(values[3]) + "]";
}

struct ExtractImagePatchesCompileInfo {};

struct ParsedAttrs {
    int64_t kH = 0;
    int64_t kW = 0;
    int64_t strideH = 0;
    int64_t strideW = 0;
    int64_t rateH = 0;
    int64_t rateW = 0;
    bool isSame = false;
};

struct ParsedInput {
    int64_t inN = 0;
    int64_t inH = 0;
    int64_t inW = 0;
    int64_t inC = 0;
    bool isStorageNhwc = false;
    bool needAttrNchwToNhwc = false;
};

struct OutputParams {
    int64_t outH = 0;
    int64_t outW = 0;
    int64_t outC = 0;
    int64_t totalElements = 0;
    int64_t padHTop = 0;
    int64_t padWLeft = 0;
    int64_t inStrideN = 0;
    int64_t inStrideH = 0;
    int64_t inStrideW = 0;
    int64_t inStrideC = 0;
};

static std::array<int64_t, ATTR_LIST_LEN> GetAttrByStorageFormat(const int64_t* attr, bool needAttrNchwToNhwc)
{
    if (needAttrNchwToNhwc) {
        // Origin NCHW attr [N, C, H, W] -> storage NHWC attr [N, H, W, C].
        return {attr[DIM_IDX_N], attr[NCHW_IDX_H], attr[NCHW_IDX_W], attr[NCHW_IDX_C]};
    }
    return {attr[DIM_IDX_N], attr[NHWC_IDX_H], attr[NHWC_IDX_W], attr[NHWC_IDX_C]};
}

static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t& ubSize, int64_t& coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ParseInputShape(gert::TilingContext* context, ParsedInput& pi)
{
    auto inputShape = context->GetInputShape(IDX_0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputShape);
    auto storageShape = inputShape->GetStorageShape();
    OP_CHECK_IF(storageShape.GetDimNum() != DIM_NUM,
                OP_LOGE_FOR_INVALID_SHAPEDIM(context->GetNodeName(), "x.storage_shape",
                                             (std::to_string(storageShape.GetDimNum()) + "D").c_str(), "4D"),
                return ge::GRAPH_FAILED);

    auto inputDesc = context->GetInputDesc(IDX_0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDesc);
    const ge::DataType xDtype = inputDesc->GetDataType();
    OP_CHECK_IF(xDtype != ge::DT_FLOAT16 && xDtype != ge::DT_FLOAT && xDtype != ge::DT_BF16 && xDtype != ge::DT_INT8 &&
                    xDtype != ge::DT_UINT8,
                OP_LOGE_FOR_INVALID_DTYPE(context->GetNodeName(), "x", Ops::Base::ToString(xDtype).c_str(),
                                          "float16, float32, bfloat16, int8 or uint8"),
                return ge::GRAPH_FAILED);
    const ge::Format originFormat = inputDesc->GetOriginFormat();
    const ge::Format storageFormat = inputDesc->GetStorageFormat();
    if (originFormat != ge::FORMAT_NHWC && originFormat != ge::FORMAT_NCHW) {
        OP_LOGE_FOR_INVALID_FORMAT(context->GetNodeName(), "x.origin_format", Ops::Base::ToString(originFormat).c_str(),
                                   "NHWC or NCHW");
        return ge::GRAPH_FAILED;
    }
    if (storageFormat != ge::FORMAT_NHWC && storageFormat != ge::FORMAT_NCHW) {
        OP_LOGE_FOR_INVALID_FORMAT(context->GetNodeName(), "x.storage_format",
                                   Ops::Base::ToString(storageFormat).c_str(), "NHWC or NCHW");
        return ge::GRAPH_FAILED;
    }
    if (originFormat == ge::FORMAT_NHWC && storageFormat == ge::FORMAT_NCHW) {
        OP_LOGE_FOR_INVALID_FORMATS_WITH_REASON(
            context->GetNodeName(), "x.origin_format and x.storage_format",
            ("origin=" + Ops::Base::ToString(originFormat) + ", storage=" + Ops::Base::ToString(storageFormat)).c_str(),
            "origin NHWC with storage NCHW is not supported");
        return ge::GRAPH_FAILED;
    }

    pi.isStorageNhwc = (storageFormat == ge::FORMAT_NHWC);
    pi.needAttrNchwToNhwc = (originFormat == ge::FORMAT_NCHW && storageFormat == ge::FORMAT_NHWC);

    int32_t idxH = pi.isStorageNhwc ? NHWC_IDX_H : NCHW_IDX_H;
    int32_t idxW = pi.isStorageNhwc ? NHWC_IDX_W : NCHW_IDX_W;
    int32_t idxC = pi.isStorageNhwc ? NHWC_IDX_C : NCHW_IDX_C;
    pi.inN = storageShape.GetDim(DIM_IDX_N);
    pi.inH = storageShape.GetDim(idxH);
    pi.inW = storageShape.GetDim(idxW);
    pi.inC = storageShape.GetDim(idxC);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ParseAttrs(gert::TilingContext* context, const ParsedInput& pi, ParsedAttrs& pa)
{
    auto attrs = context->GetAttrs();
    OP_CHECK_NULL_WITH_CONTEXT(context, attrs);

    const auto* ksizesVec = attrs->GetListInt(ATTR_IDX_KSIZES);
    OP_CHECK_NULL_WITH_CONTEXT(context, ksizesVec);
    OP_CHECK_IF(ksizesVec->GetSize() != ATTR_LIST_LEN,
                OP_LOGE_FOR_INVALID_LISTSIZE(context->GetNodeName(), "ksizes",
                                             std::to_string(ksizesVec->GetSize()).c_str(), "4"),
                return ge::GRAPH_FAILED);
    const int64_t* ksizesData = ksizesVec->GetData();

    const auto* stridesVec = attrs->GetListInt(ATTR_IDX_STRIDES);
    OP_CHECK_NULL_WITH_CONTEXT(context, stridesVec);
    OP_CHECK_IF(stridesVec->GetSize() != ATTR_LIST_LEN,
                OP_LOGE_FOR_INVALID_LISTSIZE(context->GetNodeName(), "strides",
                                             std::to_string(stridesVec->GetSize()).c_str(), "4"),
                return ge::GRAPH_FAILED);
    const int64_t* stridesData = stridesVec->GetData();

    const auto* ratesVec = attrs->GetListInt(ATTR_IDX_RATES);
    OP_CHECK_NULL_WITH_CONTEXT(context, ratesVec);
    OP_CHECK_IF(
        ratesVec->GetSize() != ATTR_LIST_LEN,
        OP_LOGE_FOR_INVALID_LISTSIZE(context->GetNodeName(), "rates", std::to_string(ratesVec->GetSize()).c_str(), "4"),
        return ge::GRAPH_FAILED);
    const int64_t* ratesData = ratesVec->GetData();

    const char* paddingStr = attrs->GetStr(ATTR_IDX_PADDING);
    OP_CHECK_NULL_WITH_CONTEXT(context, paddingStr);

    const auto ksizes = GetAttrByStorageFormat(ksizesData, pi.needAttrNchwToNhwc);
    const auto strides = GetAttrByStorageFormat(stridesData, pi.needAttrNchwToNhwc);
    const auto rates = GetAttrByStorageFormat(ratesData, pi.needAttrNchwToNhwc);
    int32_t idxH = pi.isStorageNhwc ? NHWC_IDX_H : NCHW_IDX_H;
    int32_t idxW = pi.isStorageNhwc ? NHWC_IDX_W : NCHW_IDX_W;
    int32_t idxC = pi.isStorageNhwc ? NHWC_IDX_C : NCHW_IDX_C;
    const bool isAttrNhwc = pi.isStorageNhwc && !pi.needAttrNchwToNhwc;
    const int32_t attrIdxH = isAttrNhwc ? NHWC_IDX_H : NCHW_IDX_H;
    const int32_t attrIdxW = isAttrNhwc ? NHWC_IDX_W : NCHW_IDX_W;
    const int32_t attrIdxC = isAttrNhwc ? NHWC_IDX_C : NCHW_IDX_C;
    const char* attrFormatName = isAttrNhwc ? "NHWC" : "NCHW";
    OP_CHECK_IF(
        ksizes[DIM_IDX_N] != 1 || ksizes[idxC] != 1,
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "ksizes", FormatAttrList(ksizesData).c_str(),
                                              ("batch/channel elements at indices 0 and " + std::to_string(attrIdxC) +
                                               " must both be 1 for " + attrFormatName)
                                                  .c_str()),
        return ge::GRAPH_FAILED);
    OP_CHECK_IF(strides[idxH] <= 0 || strides[idxW] <= 0,
                OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(
                    context->GetNodeName(), "strides", FormatAttrList(stridesData).c_str(),
                    ("spatial elements at indices " + std::to_string(attrIdxH) + " and " + std::to_string(attrIdxW) +
                     " must both be greater than 0 for " + attrFormatName)
                        .c_str()),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(rates[idxH] < 1 || rates[idxW] < 1,
                OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(
                    context->GetNodeName(), "rates", FormatAttrList(ratesData).c_str(),
                    ("spatial elements at indices " + std::to_string(attrIdxH) + " and " + std::to_string(attrIdxW) +
                     " must both be at least 1 for " + attrFormatName)
                        .c_str()),
                return ge::GRAPH_FAILED);

    pa.kH = ksizes[idxH];
    pa.kW = ksizes[idxW];
    pa.strideH = strides[idxH];
    pa.strideW = strides[idxW];
    pa.rateH = rates[idxH];
    pa.rateW = rates[idxW];
    pa.isSame = (strcmp(paddingStr, "SAME") == 0);
    OP_CHECK_IF(!pa.isSame && strcmp(paddingStr, "VALID") != 0,
                OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "padding", paddingStr, "SAME or VALID"),
                return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static void ComputeOutputParams(const ParsedInput& pi, const ParsedAttrs& pa, OutputParams& op)
{
    int64_t effFilterH = (pa.kH - 1) * pa.rateH + 1;
    int64_t effFilterW = (pa.kW - 1) * pa.rateW + 1;
    if (pa.isSame) {
        op.outH = (pi.inH + pa.strideH - 1) / pa.strideH;
        op.outW = (pi.inW + pa.strideW - 1) / pa.strideW;
        int64_t padTotalH = std::max((op.outH - 1) * pa.strideH + effFilterH - pi.inH, (int64_t)0);
        int64_t padTotalW = std::max((op.outW - 1) * pa.strideW + effFilterW - pi.inW, (int64_t)0);
        op.padHTop = padTotalH / 2;
        op.padWLeft = padTotalW / 2;
    } else {
        op.outH = (pi.inH - effFilterH + pa.strideH) / pa.strideH;
        op.outW = (pi.inW - effFilterW + pa.strideW) / pa.strideW;
        op.padHTop = 0;
        op.padWLeft = 0;
    }
    if (op.outH <= 0 || op.outW <= 0) {
        op.outH = 0;
        op.outW = 0;
    }
    op.outC = pi.inC * pa.kH * pa.kW;
    op.totalElements = pi.inN * op.outH * op.outW * op.outC;
    // 输入物理步长（逻辑 N/H/W/C 维在 GM 中的步长）
    if (pi.isStorageNhwc) {
        op.inStrideN = pi.inH * pi.inW * pi.inC;
        op.inStrideH = pi.inW * pi.inC;
        op.inStrideW = pi.inC;
        op.inStrideC = 1;
    } else {
        op.inStrideN = pi.inC * pi.inH * pi.inW;
        op.inStrideH = pi.inW;
        op.inStrideW = 1;
        op.inStrideC = pi.inH * pi.inW;
    }
}

static void FillTilingData(ExtractImagePatchesTilingData* t, const ParsedInput& pi, const ParsedAttrs& pa,
                           const OutputParams& op, int32_t needCoreNum, int64_t perCoreElements,
                           int64_t lastCoreElements)
{
    t->needCoreNum = static_cast<int64_t>(needCoreNum);
    t->totalElements = op.totalElements;
    t->divNhc = op.outH * op.outW * op.outC;
    t->divWc = op.outW * op.outC;
    t->divNcHw = op.outC * op.outH * op.outW;
    t->divHw = op.outH * op.outW;
    t->outC = op.outC;
    t->outW = op.outW;
    t->khKw = pa.kH * pa.kW;
    t->kW = pa.kW;
    t->inH = pi.inH;
    t->inW = pi.inW;
    t->strideH = pa.strideH;
    t->strideW = pa.strideW;
    t->rateH = pa.rateH;
    t->rateW = pa.rateW;
    t->padHTop = op.padHTop;
    t->padWLeft = op.padWLeft;
    t->inStrideN = op.inStrideN;
    t->inStrideH = op.inStrideH;
    t->inStrideW = op.inStrideW;
    t->inStrideC = op.inStrideC;
    // Process partitions work by block using these element counts.
    t->perCoreElements = perCoreElements;
    t->lastCoreElements = lastCoreElements;
}

static ge::graphStatus GetWorkspaceSize(gert::TilingContext* context)
{
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(context->GetPlatformInfo());
    uint64_t sysWorkspaceSize = ascendcPlatform.GetLibApiWorkSpaceSize();
    size_t* currentWorkspace = context->GetWorkspaceSizes(WORKSPACE_NUM);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[IDX_0] = static_cast<size_t>(sysWorkspaceSize);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ExtractImagePatchesTilingFunc(gert::TilingContext* context)
{
    uint64_t ubSize = 0;
    int64_t coreNum = 0;
    OP_CHECK_IF(GetPlatformInfo(context, ubSize, coreNum) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetPlatformInfo error"), return ge::GRAPH_FAILED);

    ParsedInput pi;
    OP_CHECK_IF(ParseInputShape(context, pi) != ge::GRAPH_SUCCESS, (void)0, return ge::GRAPH_FAILED);

    ParsedAttrs pa;
    OP_CHECK_IF(ParseAttrs(context, pi, pa) != ge::GRAPH_SUCCESS, (void)0, return ge::GRAPH_FAILED);

    OutputParams op;
    ComputeOutputParams(pi, pa, op);

    int64_t perCoreElements = (op.totalElements > 0) ? Ops::Base::CeilDiv(op.totalElements, coreNum) : 0;
    if (perCoreElements > 0 && perCoreElements < PER_CORE_MIN_ELEMENTS) {
        perCoreElements = PER_CORE_MIN_ELEMENTS;
    }
    perCoreElements = (perCoreElements + BLOCK_ALIGN - 1) / BLOCK_ALIGN * BLOCK_ALIGN;
    int32_t needCoreNum = (op.totalElements > 0) ?
                              static_cast<int32_t>(Ops::Base::CeilDiv(op.totalElements, perCoreElements)) :
                              1;

    int64_t lastCoreElements = 0;
    if (op.totalElements > 0 && needCoreNum > 0) {
        lastCoreElements = op.totalElements - static_cast<int64_t>(needCoreNum - 1) * perCoreElements;
        if (lastCoreElements < 0) {
            lastCoreElements = 0;
        }
    }

    ExtractImagePatchesTilingData* tiling = context->GetTilingData<ExtractImagePatchesTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(
        memset_s(tiling, sizeof(ExtractImagePatchesTilingData), 0, sizeof(ExtractImagePatchesTilingData)) != EOK,
        OP_LOGE(context, "memset_s tiling data error"), return ge::GRAPH_FAILED);

    FillTilingData(tiling, pi, pa, op, needCoreNum, perCoreElements, lastCoreElements);

    OP_CHECK_IF(GetWorkspaceSize(context) != ge::GRAPH_SUCCESS, OP_LOGE(context, "GetWorkspaceSize error"),
                return ge::GRAPH_FAILED);

    context->SetBlockDim(static_cast<uint32_t>(needCoreNum));
    OP_CHECK_IF((ubSize <= DCACHE_SIZE + STATIC_UB_ESTIMATE), OP_LOGE(context, "ubSize %lu too small", ubSize),
                return ge::GRAPH_FAILED);
    auto res = context->SetLocalMemorySize(static_cast<uint32_t>(ubSize - DCACHE_SIZE - STATIC_UB_ESTIMATE));
    OP_CHECK_IF((res != ge::GRAPH_SUCCESS), OP_LOGE(context, "SetLocalMemorySize failed"), return ge::GRAPH_FAILED);

    // Use 32-bit indices when the output element count fits.
    bool use32Bit = (op.totalElements > 0 && op.totalElements <= INT32_MAX);
    uint64_t formatMode = pi.isStorageNhwc ? EXTRACT_IMAGE_PATCHES_TPL_FORMAT_NHWC :
                                             EXTRACT_IMAGE_PATCHES_TPL_FORMAT_NCHW;
    uint64_t idxBit = use32Bit ? EXTRACT_IMAGE_PATCHES_TPL_IDX_32BIT : EXTRACT_IMAGE_PATCHES_TPL_IDX_64BIT;
    uint64_t tilingKey = GET_TPL_TILING_KEY(formatMode, idxBit);
    context->SetTilingKey(tilingKey);

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForExtractImagePatches([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_OPTILING(ExtractImagePatches)
    .Tiling(ExtractImagePatchesTilingFunc)
    .TilingParse<ExtractImagePatchesCompileInfo>(TilingParseForExtractImagePatches);
} // namespace optiling
