/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file deformable_roi_pool_grad_graph_infer.cpp
 * \brief deformable_roi_pool_grad operator graph infer resource
 *
 * 输出 Dtype 推导规则（SE §5.6）：
 *   grad_x.dtype = x.dtype          (输入索引 1)
 *   grad_offset.dtype = offset.dtype (输入索引 3)
 */

#include "register/op_impl_registry.h"
#include "log/log.h"

namespace ops {
using namespace ge;

// 输入索引：grad=0, x=1, rois=2, offset=3
// 输出索引：grad_x=0, grad_offset=1
static constexpr int64_t IDX_GRAD = 0;
static constexpr int64_t IDX_X = 1;
static constexpr int64_t IDX_OFFSET = 3;
static constexpr int64_t IDX_OUT_GRAD_X = 0;
static constexpr int64_t IDX_OUT_GRAD_OFFSET = 1;

static ge::graphStatus InferDataTypeDeformableRoiPoolGrad(gert::InferDataTypeContext* context)
{
    OP_LOGD(context->GetNodeName(), "Begin to do InferDataTypeDeformableRoiPoolGrad");

    // grad_x.dtype = x.dtype
    ge::DataType xDtype = context->GetInputDataType(IDX_X);
    OP_CHECK_IF(context->SetOutputDataType(IDX_OUT_GRAD_X, xDtype) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "Set grad_x dtype failed"), return ge::GRAPH_FAILED);

    // grad_offset.dtype = offset.dtype；offset 为空时与 grad 的 dtype 一致
    ge::DataType gradOffsetDtype = context->GetInputDataType(IDX_GRAD);
    if (context->GetInputDataType(IDX_OFFSET) != ge::DT_UNDEFINED) {
        gradOffsetDtype = context->GetInputDataType(IDX_OFFSET);
    }
    OP_CHECK_IF(context->SetOutputDataType(IDX_OUT_GRAD_OFFSET, gradOffsetDtype) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "Set grad_offset dtype failed"), return ge::GRAPH_FAILED);

    OP_LOGD(context->GetNodeName(), "End to do InferDataTypeDeformableRoiPoolGrad");
    return GRAPH_SUCCESS;
}

IMPL_OP(DeformableRoiPoolGrad).InferDataType(InferDataTypeDeformableRoiPoolGrad);

} // namespace ops
