/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <iostream>
#include <gtest/gtest.h>
#include "tiling_context_faker.h"
#include "tiling_case_executor.h"
#include "any_value.h"
#include "../../../../op_kernel/arch35/iou3d_tiling_data.h"

using namespace std;
using namespace ge;

class Iou3DTiling : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "Iou3DTiling SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "Iou3DTiling TearDown" << std::endl; }
};

namespace {
constexpr uint64_t CORE_NUM = 64;
constexpr uint64_t UB_SIZE = 262144;
constexpr uint32_t IOU3D_TILE_LEN = 256U; // 与 tiling 源码 IOU3D_TILE_LEN 一致

// CeilDiv（与 tiling 源码 Ops::Base::CeilDiv 语义一致）
int64_t CeilDiv(int64_t a, int64_t b) { return (b == 0) ? 0 : (a + b - 1) / b; }

// Iou3D 的 CompileInfo（与 tiling 源码 struct Iou3DCompileInfo {} 对应，入图/tiling 场景需非空指针）。
struct Iou3DCompileInfo {};
static Iou3DCompileInfo g_iou3dCompileInfo;

// 构造一个 Iou3D 的 TilingContextPara（无 attr，float32/ND，Ascend950）。
// bboxes[B,7,N] + gtboxes[B,7,K] -> iou[B,N,K]。gert::StorageShape 只接受 initializer_list，故显式传维。
gert::TilingContextPara MakePara(int64_t batch, int64_t numN, int64_t channelB, int64_t batchG, int64_t numK,
                                 int64_t channelG, ge::DataType dtype = ge::DT_FLOAT)
{
    return gert::TilingContextPara(
        "Iou3D",
        {
            {gert::StorageShape({batch, channelB, numN}, {batch, channelB, numN}), dtype, ge::FORMAT_ND},
            {gert::StorageShape({batchG, channelG, numK}, {batchG, channelG, numK}), dtype, ge::FORMAT_ND},
        },
        {
            {gert::StorageShape({batch, numN, numK}, {batch, numN, numK}), ge::DT_FLOAT, ge::FORMAT_ND},
        },
        {}, &g_iou3dCompileInfo, "Ascend950", CORE_NUM, UB_SIZE);
}

// 常规同 batch / channel=7 的便捷构造：MakeParaBNK(B, N, K)
gert::TilingContextPara MakeParaBNK(int64_t batch, int64_t numN, int64_t numK, ge::DataType dtype = ge::DT_FLOAT)
{
    return MakePara(batch, numN, 7, batch, numK, 7, dtype);
}

const Iou3DTilingData* AsTiling(const TilingInfo& info)
{
    EXPECT_EQ(info.tilingDataSize, sizeof(Iou3DTilingData));
    return reinterpret_cast<const Iou3DTilingData*>(info.tilingData.get());
}
} // namespace

// 正例：小 shape [1,7,4] + [1,7,4]。校验 B/N/K、非空、tileLen>0、workspace==0。
TEST_F(Iou3DTiling, iou3d_tiling_small)
{
    auto para = MakeParaBNK(1, 4, 4);
    TilingInfo info;
    ASSERT_TRUE(ExecuteTiling(para, info));
    const Iou3DTilingData* t = AsTiling(info);

    EXPECT_EQ(t->batch, 1U);
    EXPECT_EQ(t->numBboxes, 4U);
    EXPECT_EQ(t->numGtboxes, 4U);
    EXPECT_EQ(t->isEmpty, 0U);
    EXPECT_GT(t->tileLen, 0U);
    EXPECT_GE(t->coreNum, 1U);
    // totalPairs=16 < coreNum=64 -> pairsPerCore=1, tileLen=min(1,256)=1
    const int64_t totalPairs = 1 * 4 * 4;
    const int64_t pairsPerCore = CeilDiv(totalPairs, CORE_NUM);
    EXPECT_EQ(t->pairsPerCore, static_cast<uint32_t>(pairsPerCore));
    EXPECT_EQ(t->tileLen, static_cast<uint32_t>(std::min<int64_t>(pairsPerCore, IOU3D_TILE_LEN)));
    ASSERT_EQ(info.workspaceSizes.size(), 1U);
    EXPECT_EQ(info.workspaceSizes[0], 0U);
    EXPECT_EQ(info.blockNum, static_cast<size_t>(CeilDiv(totalPairs, pairsPerCore)));
}

// 正例：大 shape [2,7,256] + [2,7,256]。校验多核切分 + tileLen 封顶 256。
TEST_F(Iou3DTiling, iou3d_tiling_large_multicore)
{
    auto para = MakeParaBNK(2, 256, 256);
    TilingInfo info;
    ASSERT_TRUE(ExecuteTiling(para, info));
    const Iou3DTilingData* t = AsTiling(info);

    EXPECT_EQ(t->batch, 2U);
    EXPECT_EQ(t->numBboxes, 256U);
    EXPECT_EQ(t->numGtboxes, 256U);
    EXPECT_EQ(t->isEmpty, 0U);
    const int64_t totalPairs = 2 * 256 * 256; // 131072
    const int64_t pairsPerCore = CeilDiv(totalPairs, CORE_NUM);
    const int64_t usedCore = CeilDiv(totalPairs, pairsPerCore);
    EXPECT_EQ(t->pairsPerCore, static_cast<uint32_t>(pairsPerCore));
    EXPECT_EQ(t->coreNum, static_cast<uint32_t>(usedCore));
    // pairsPerCore(2048) > 256 -> tileLen 封顶 IOU3D_TILE_LEN
    EXPECT_EQ(t->tileLen, IOU3D_TILE_LEN);
    EXPECT_EQ(info.blockNum, static_cast<size_t>(usedCore));
}

// 正例：大 K（D5 已移除 K<=2000 上限，K=4096 应成功）。
TEST_F(Iou3DTiling, iou3d_tiling_large_k)
{
    auto para = MakeParaBNK(1, 8, 4096);
    TilingInfo info;
    ASSERT_TRUE(ExecuteTiling(para, info));
    const Iou3DTilingData* t = AsTiling(info);
    EXPECT_EQ(t->numGtboxes, 4096U);
    EXPECT_EQ(t->isEmpty, 0U);
}

// 正例：空 Tensor（N==0）-> isEmpty=1, blockNum=1。
TEST_F(Iou3DTiling, iou3d_tiling_empty_n)
{
    auto para = MakeParaBNK(1, 0, 4);
    TilingInfo info;
    ASSERT_TRUE(ExecuteTiling(para, info));
    const Iou3DTilingData* t = AsTiling(info);
    EXPECT_EQ(t->isEmpty, 1U);
    EXPECT_EQ(info.blockNum, 1U);
}

// 正例：空 Tensor（batch==0）-> isEmpty=1, blockNum=1（batch=0 若不短路会 SetBlockDim(0) 非法）。
TEST_F(Iou3DTiling, iou3d_tiling_empty_batch)
{
    auto para = MakeParaBNK(0, 4, 4);
    TilingInfo info;
    ASSERT_TRUE(ExecuteTiling(para, info));
    const Iou3DTilingData* t = AsTiling(info);
    EXPECT_EQ(t->isEmpty, 1U);
    EXPECT_EQ(info.blockNum, 1U);
}

// 反例：channel != 7 -> tiling FAILED
TEST_F(Iou3DTiling, iou3d_tiling_neg_channel_not_7)
{
    // channel=5（dim1≠7），bboxes[1,5,4] + gtboxes[1,5,4]
    auto para = MakePara(1, 4, 5, 1, 4, 5);
    TilingInfo info;
    EXPECT_FALSE(ExecuteTiling(para, info));
}

// 反例：batch 不一致 -> tiling FAILED
TEST_F(Iou3DTiling, iou3d_tiling_neg_batch_mismatch)
{
    // bboxes[2,7,4] + gtboxes[3,7,4]
    auto para = MakePara(2, 4, 7, 3, 4, 7);
    TilingInfo info;
    EXPECT_FALSE(ExecuteTiling(para, info));
}

// 反例：dtype != float32（float16）-> tiling FAILED
TEST_F(Iou3DTiling, iou3d_tiling_neg_dtype_fp16)
{
    auto para = MakeParaBNK(1, 4, 4, ge::DT_FLOAT16);
    TilingInfo info;
    EXPECT_FALSE(ExecuteTiling(para, info));
}
