/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file test_deformable_roi_pool_grad_infershape.cpp
 * \brief DeformableRoiPoolGrad 算子 InferShape UT 测试
 *
 * 验证规则（SE §5.5）：
 *   grad_x.shape = x.shape              // (B, C, H, W)
 *   grad_offset.shape = offset.shape    // (N, 2, pH, pW)；offset 为空时 (N, 2, pH, pW)
 */

#include <gtest/gtest.h>
#include <iostream>
#include "infershape_context_faker.h"
#include "infershape_case_executor.h"

class DeformableRoiPoolGradInfershape : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "DeformableRoiPoolGradInfershape SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "DeformableRoiPoolGradInfershape TearDown" << std::endl; }
};

static std::vector<gert::InfershapeContextPara::OpAttr> MakeAttrs(int64_t pooledHeight, int64_t pooledWidth)
{
    std::vector<gert::InfershapeContextPara::OpAttr> attrs;
    attrs.emplace_back("output_size", Ops::Cv::AnyValue::CreateFrom(std::vector<int64_t>{pooledHeight, pooledWidth}));
    attrs.emplace_back("spatial_scale", Ops::Cv::AnyValue::CreateFrom(1.0f));
    attrs.emplace_back("sampling_ratio", Ops::Cv::AnyValue::CreateFrom(static_cast<int64_t>(0)));
    attrs.emplace_back("gamma", Ops::Cv::AnyValue::CreateFrom(0.1f));
    return attrs;
}

TEST_F(DeformableRoiPoolGradInfershape, deformable_roi_pool_grad_infershape_with_offset)
{
    // 输入：grad(N,C,pH,pW), x(B,C,H,W), rois(N,5), offset(N,2,pH,pW)
    // grad_x.shape = x.shape = (2, 4, 8, 8)
    // grad_offset.shape = offset.shape = (2, 2, 3, 3)
    gert::InfershapeContextPara infershapeContextPara(
        "DeformableRoiPoolGrad",
        {
            {{{2, 4, 3, 3}, {2, 4, 3, 3}}, ge::DT_FLOAT, ge::FORMAT_ND}, // grad
            {{{2, 4, 8, 8}, {2, 4, 8, 8}}, ge::DT_FLOAT, ge::FORMAT_ND}, // x
            {{{2, 5}, {2, 5}}, ge::DT_FLOAT, ge::FORMAT_ND},             // rois
            {{{2, 2, 3, 3}, {2, 2, 3, 3}}, ge::DT_FLOAT, ge::FORMAT_ND}, // offset
        },
        {
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND}, // grad_x
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND}, // grad_offset
        },
        MakeAttrs(3, 3));
    std::vector<std::vector<int64_t>> expectOutputShape = {
        {2, 4, 8, 8}, // grad_x = x.shape
        {2, 2, 3, 3}, // grad_offset = offset.shape
    };
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_SUCCESS, expectOutputShape);
}

TEST_F(DeformableRoiPoolGradInfershape, deformable_roi_pool_grad_infershape_no_offset)
{
    // offset 为空：grad_offset = (N, 2, pH, pW)，从 grad 推导
    // grad: (N=3, C=8, pH=4, pW=4), x: (B=2, C=8, H=16, W=16)
    // grad_x.shape = (2, 8, 16, 16)
    // grad_offset.shape = (3, 2, 4, 4)
    gert::InfershapeContextPara infershapeContextPara(
        "DeformableRoiPoolGrad",
        {
            {{{3, 8, 4, 4}, {3, 8, 4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},     // grad
            {{{2, 8, 16, 16}, {2, 8, 16, 16}}, ge::DT_FLOAT, ge::FORMAT_ND}, // x
            {{{3, 5}, {3, 5}}, ge::DT_FLOAT, ge::FORMAT_ND},                 // rois
        },
        {
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND}, // grad_x
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND}, // grad_offset
        },
        MakeAttrs(4, 4), {1, 1, 1, 0}, {1, 1});
    std::vector<std::vector<int64_t>> expectOutputShape = {
        {2, 8, 16, 16}, // grad_x = x.shape
        {3, 2, 4, 4},   // grad_offset = (N, 2, pH, pW)
    };
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_SUCCESS, expectOutputShape);
}

TEST_F(DeformableRoiPoolGradInfershape, rejects_invalid_x_rank)
{
    gert::InfershapeContextPara para("DeformableRoiPoolGrad",
                                     {
                                         {{{2, 4, 3, 3}, {2, 4, 3, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{2, 4, 8}, {2, 4, 8}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{2, 5}, {2, 5}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{2, 2, 3, 3}, {2, 2, 3, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                     },
                                     {
                                         {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                     },
                                     MakeAttrs(3, 3));
    ExecuteTestCase(para, ge::GRAPH_FAILED);
}

TEST_F(DeformableRoiPoolGradInfershape, rejects_invalid_offset_rank)
{
    gert::InfershapeContextPara para("DeformableRoiPoolGrad",
                                     {
                                         {{{2, 4, 3, 3}, {2, 4, 3, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{2, 4, 8, 8}, {2, 4, 8, 8}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{2, 5}, {2, 5}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{2, 2, 9}, {2, 2, 9}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                     },
                                     {
                                         {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                     },
                                     MakeAttrs(3, 3));
    ExecuteTestCase(para, ge::GRAPH_FAILED);
}

TEST_F(DeformableRoiPoolGradInfershape, empty_vector_offset_uses_grad_shape)
{
    gert::InfershapeContextPara para("DeformableRoiPoolGrad",
                                     {
                                         {{{3, 8, 4, 4}, {3, 8, 4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{2, 8, 16, 16}, {2, 8, 16, 16}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{3, 5}, {3, 5}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{0}, {0}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                     },
                                     {
                                         {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                     },
                                     MakeAttrs(4, 4));
    std::vector<std::vector<int64_t>> expected = {{2, 8, 16, 16}, {3, 2, 4, 4}};
    ExecuteTestCase(para, ge::GRAPH_SUCCESS, expected);
}

TEST_F(DeformableRoiPoolGradInfershape, supports_unknown_shape)
{
    gert::InfershapeContextPara para("DeformableRoiPoolGrad",
                                     {
                                         {{{-1, 4, -1, 3}, {-1, 4, -1, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{-1, 4, -1, 8}, {-1, 4, -1, 8}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{-1, 5}, {-1, 5}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{-1, 2, -1, 3}, {-1, 2, -1, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                     },
                                     {
                                         {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                     },
                                     MakeAttrs(2, 3));
    std::vector<std::vector<int64_t>> expected = {{-1, 4, -1, 8}, {-1, 2, -1, 3}};
    ExecuteTestCase(para, ge::GRAPH_SUCCESS, expected);
}

TEST_F(DeformableRoiPoolGradInfershape, supports_unknown_rank)
{
    gert::InfershapeContextPara para("DeformableRoiPoolGrad",
                                     {
                                         {{{-2}, {-2}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{-2}, {-2}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{-2}, {-2}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{-2}, {-2}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                     },
                                     {
                                         {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                     },
                                     MakeAttrs(3, 3));
    std::vector<std::vector<int64_t>> expected = {{-2}, {-2}};
    ExecuteTestCase(para, ge::GRAPH_SUCCESS, expected);
}

TEST_F(DeformableRoiPoolGradInfershape, rejects_mismatched_rois_shape)
{
    gert::InfershapeContextPara para("DeformableRoiPoolGrad",
                                     {
                                         {{{2, 4, 3, 3}, {2, 4, 3, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{2, 4, 8, 8}, {2, 4, 8, 8}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{3, 5}, {3, 5}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{2, 2, 3, 3}, {2, 2, 3, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                     },
                                     {
                                         {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                     },
                                     MakeAttrs(3, 3));
    ExecuteTestCase(para, ge::GRAPH_FAILED);
}

TEST_F(DeformableRoiPoolGradInfershape, rejects_mismatched_channel)
{
    gert::InfershapeContextPara para("DeformableRoiPoolGrad",
                                     {
                                         {{{2, 4, 3, 3}, {2, 4, 3, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{2, 5, 8, 8}, {2, 5, 8, 8}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{2, 5}, {2, 5}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{2, 2, 3, 3}, {2, 2, 3, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                     },
                                     {
                                         {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                     },
                                     MakeAttrs(3, 3));
    ExecuteTestCase(para, ge::GRAPH_FAILED);
}

TEST_F(DeformableRoiPoolGradInfershape, rejects_mismatched_output_size)
{
    gert::InfershapeContextPara para("DeformableRoiPoolGrad",
                                     {
                                         {{{2, 4, 3, 3}, {2, 4, 3, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{2, 4, 8, 8}, {2, 4, 8, 8}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{2, 5}, {2, 5}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{2, 2, 3, 3}, {2, 2, 3, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                     },
                                     {
                                         {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                     },
                                     MakeAttrs(4, 3));
    ExecuteTestCase(para, ge::GRAPH_FAILED);
}

TEST_F(DeformableRoiPoolGradInfershape, supports_empty_batch)
{
    gert::InfershapeContextPara para("DeformableRoiPoolGrad",
                                     {
                                         {{{2, 4, 3, 3}, {2, 4, 3, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{0, 4, 8, 8}, {0, 4, 8, 8}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{2, 5}, {2, 5}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{2, 2, 3, 3}, {2, 2, 3, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                     },
                                     {
                                         {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                         {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                     },
                                     MakeAttrs(3, 3));
    std::vector<std::vector<int64_t>> expected = {{0, 4, 8, 8}, {2, 2, 3, 3}};
    ExecuteTestCase(para, ge::GRAPH_SUCCESS, expected);
}
