/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file anchor_response_flags_simt.h
 * \brief SIMT kernel implementation for anchor_response_flags operator
 *
 * Gather algorithm:
 *   Each thread processes one output grid position (featH * featW total),
 *   checks all N bboxes to determine if any maps to this position.
 *   Writes flag (0 or 1) for all numBaseAnchors at this position.
 *
 * Advantages over scatter:
 *   - No write conflicts (each output element written by exactly one thread)
 *   - Deterministic results (no cache coherence issues)
 *   - No SyncAll/DCCI needed
 */

#ifndef __ANCHOR_RESPONSE_FLAGS_SIMT_H__
#define __ANCHOR_RESPONSE_FLAGS_SIMT_H__

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "simt_api/common_functions.h"
#include "simt_api/math_functions.h"
#include "simt_api/asc_fp16.h"
#include "anchor_response_flags_tiling_data.h"
#include "anchor_response_flags_tiling_key.h"

namespace NsAnchorResponseFlags {

using namespace AscendC;

template <typename IDX_T>
static constexpr uint32_t THREADS = (sizeof(IDX_T) == 4) ? 1024 : 512;

__simt_callee__ __aicore__ inline float ReadAsFloat(float val)
{
    return val;
}

__simt_callee__ __aicore__ inline float ReadAsFloat(half val)
{
    return __half2float(val);
}

__simt_callee__ __aicore__ inline int32_t SafeGridCoord(float center, int32_t stride,
                                                          int32_t featSize)
{
    if (isnan(center) || isinf(center)) {
        return 0;
    }
    float fgrid = floorf(center / static_cast<float>(stride));
    if (fgrid <= 0.0f) { return 0; }
    if (fgrid >= static_cast<float>(featSize)) { return featSize - 1; }
    return static_cast<int32_t>(fgrid);
}

template <typename T, typename IDX_T>
__simt_vf__ __aicore__ __launch_bounds__(THREADS<IDX_T>)
inline void OpGatherCheckKernel(
    int32_t n, int32_t featH, int32_t featW,
    int32_t strideH, int32_t strideW, int32_t numBaseAnchors,
    IDX_T featW_magic, IDX_T featW_shift,
    __gm__ T* gtBboxes, __gm__ uint8_t* flags)
{
    IDX_T featHW = static_cast<IDX_T>(featH) * featW;

    for (IDX_T idx = static_cast<IDX_T>(blockIdx.x * blockDim.x + threadIdx.x);
         idx < featHW;
         idx += static_cast<IDX_T>(blockDim.x * gridDim.x)) {
        IDX_T gridY = Simt::UintDiv(idx, featW_magic, featW_shift);
        IDX_T gridX = idx - gridY * static_cast<IDX_T>(featW);

        uint8_t flag = 0;
        for (int32_t i = 0; i < n; i++) {
            float x1 = ReadAsFloat(gtBboxes[i * 4 + 0]);
            float y1 = ReadAsFloat(gtBboxes[i * 4 + 1]);
            float x2 = ReadAsFloat(gtBboxes[i * 4 + 2]);
            float y2 = ReadAsFloat(gtBboxes[i * 4 + 3]);

            float cx = (x1 + x2) * 0.5f;
            float cy = (y1 + y2) * 0.5f;

            int32_t bx = SafeGridCoord(cx, strideH, featW);
            int32_t by = SafeGridCoord(cy, strideW, featH);

            if (static_cast<IDX_T>(bx) == gridX && static_cast<IDX_T>(by) == gridY) {
                flag = 1;
                break;
            }
        }

        IDX_T baseOffset = idx * static_cast<IDX_T>(numBaseAnchors);
        for (int32_t j = 0; j < numBaseAnchors; j++) {
            flags[baseOffset + j] = flag;
        }
    }
}

template <typename T>
__aicore__ inline void ProcessGather(GM_ADDR gtBboxes, GM_ADDR flags,
                                      const AnchorResponseFlagsTilingData* tilingData,
                                      bool use32Bit)
{
    __gm__ T* gtBboxesGm = (__gm__ T*)gtBboxes;
    __gm__ uint8_t* flagsGm = (__gm__ uint8_t*)flags;

    int32_t featW = tilingData->featW;

    if (use32Bit) {
        uint32_t magic = 0;
        uint32_t shift = 0;
        GetUintDivMagicAndShift(magic, shift, static_cast<uint32_t>(featW));
        asc_vf_call<OpGatherCheckKernel<T, uint32_t>>(
            dim3(THREADS<uint32_t>),
            tilingData->n, tilingData->featH, tilingData->featW,
            tilingData->strideH, tilingData->strideW, tilingData->numBaseAnchors,
            magic, shift,
            gtBboxesGm, flagsGm);
    } else {
        uint64_t magic = 0;
        uint64_t shift = 0;
        GetUintDivMagicAndShift(magic, shift, static_cast<uint64_t>(featW));
        asc_vf_call<OpGatherCheckKernel<T, uint64_t>>(
            dim3(THREADS<uint64_t>),
            tilingData->n, tilingData->featH, tilingData->featW,
            tilingData->strideH, tilingData->strideW, tilingData->numBaseAnchors,
            magic, shift,
            gtBboxesGm, flagsGm);
    }
}

} // namespace NsAnchorResponseFlags

#endif // __ANCHOR_RESPONSE_FLAGS_SIMT_H__
