/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/**
 * @file test_geir_combined_non_max_suppression.cpp
 * @brief GE IR graph-mode calling example for CombinedNonMaxSuppression on arch35.
 */

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <ctime>
#include <map>
#include <string>
#include <vector>

#include "array_ops.h"
#include "ge_api.h"
#include "ge_api_types.h"
#include "ge_error_codes.h"
#include "graph.h"
#include "tensor.h"
#include "types.h"

#include "../../op_graph/combined_non_max_suppression_proto.h"

#define FAILED (-1)
#define SUCCESS 0

using namespace ge;
using std::string;
using std::vector;

static string GetTime()
{
    time_t timep;
    time(&timep);
    char tmp[64];
    strftime(tmp, sizeof(tmp), "%Y-%m-%d %H:%M:%S", localtime(&timep));
    return tmp;
}

template <typename T>
static Tensor MakeTensor(const vector<int64_t>& shape, DataType dataType, const vector<T>& data)
{
    TensorDesc desc(ge::Shape(shape), FORMAT_ND, dataType);
    desc.SetPlacement(ge::kPlacementHost);
    desc.SetRealDimCnt(shape.size());
    Tensor tensor(desc);
    tensor.SetData(reinterpret_cast<const uint8_t*>(data.data()), data.size() * sizeof(T));
    return tensor;
}

static bool CheckFloatOutput(const Tensor& output, const vector<float>& expected)
{
    if (output.GetSize() != expected.size() * sizeof(float) || output.GetData() == nullptr) {
        return false;
    }
    const float* actual = reinterpret_cast<const float*>(output.GetData());
    for (size_t i = 0; i < expected.size(); ++i) {
        if (std::fabs(actual[i] - expected[i]) > 1e-5F) {
            return false;
        }
    }
    return true;
}

static bool CheckIntOutput(const Tensor& output, const vector<int32_t>& expected)
{
    if (output.GetSize() != expected.size() * sizeof(int32_t) || output.GetData() == nullptr) {
        return false;
    }
    const int32_t* actual = reinterpret_cast<const int32_t*>(output.GetData());
    for (size_t i = 0; i < expected.size(); ++i) {
        if (actual[i] != expected[i]) {
            return false;
        }
    }
    return true;
}

int main()
{
    const vector<int64_t> boxesShape = {1, 3, 1, 4};
    const vector<int64_t> scoresShape = {1, 3, 1};
    const vector<int64_t> scalarShape = {};
    const vector<float> boxesData = {
        0.0F, 0.0F, 1.0F, 1.0F, 0.1F, 0.1F, 0.9F, 0.9F, 0.0F, 0.0F, 0.2F, 0.2F,
    };
    const vector<float> scoresData = {0.9F, 0.8F, 0.7F};

    std::map<AscendString, AscendString> globalOptions = {
        {"ge.exec.deviceId", "0"},
        {"ge.graphRunMode", "1"},
    };
    Status ret = ge::GEInitialize(globalOptions);
    if (ret != SUCCESS) {
        printf("%s - ERROR - [GEIR]: GEInitialize failed\n", GetTime().c_str());
        return FAILED;
    }

    Graph graph("combined_non_max_suppression_geir_graph");
    auto boxes = op::Data("boxes").set_attr_index(0);
    auto scores = op::Data("scores").set_attr_index(1);
    auto maxPerClass = op::Data("max_output_size_per_class").set_attr_index(2);
    auto maxTotal = op::Data("max_total_size").set_attr_index(3);
    auto iouThreshold = op::Data("iou_threshold").set_attr_index(4);
    auto scoreThreshold = op::Data("score_threshold").set_attr_index(5);

    TensorDesc boxesDesc(ge::Shape(boxesShape), FORMAT_ND, DT_FLOAT);
    TensorDesc scoresDesc(ge::Shape(scoresShape), FORMAT_ND, DT_FLOAT);
    TensorDesc intScalarDesc(ge::Shape(scalarShape), FORMAT_ND, DT_INT32);
    TensorDesc floatScalarDesc(ge::Shape(scalarShape), FORMAT_ND, DT_FLOAT);
    boxes.update_input_desc_x(boxesDesc);
    scores.update_input_desc_x(scoresDesc);
    maxPerClass.update_input_desc_x(intScalarDesc);
    maxTotal.update_input_desc_x(intScalarDesc);
    iouThreshold.update_input_desc_x(floatScalarDesc);
    scoreThreshold.update_input_desc_x(floatScalarDesc);

    auto nms = op::CombinedNonMaxSuppression("combined_non_max_suppression");
    nms.set_input_boxes(boxes);
    nms.set_input_scores(scores);
    nms.set_input_max_output_size_per_class(maxPerClass);
    nms.set_input_max_total_size(maxTotal);
    nms.set_input_iou_threshold(iouThreshold);
    nms.set_input_score_threshold(scoreThreshold);
    nms.set_attr_pad_per_class(false);
    nms.set_attr_clip_boxes(true);
    nms.update_input_desc_boxes(boxesDesc);
    nms.update_input_desc_scores(scoresDesc);
    nms.update_input_desc_max_output_size_per_class(intScalarDesc);
    nms.update_input_desc_max_total_size(intScalarDesc);
    nms.update_input_desc_iou_threshold(floatScalarDesc);
    nms.update_input_desc_score_threshold(floatScalarDesc);
    nms.update_output_desc_nmsed_boxes(TensorDesc(ge::Shape({1, 3, 4}), FORMAT_ND, DT_FLOAT));
    nms.update_output_desc_nmsed_scores(TensorDesc(ge::Shape({1, 3}), FORMAT_ND, DT_FLOAT));
    nms.update_output_desc_nmsed_classes(TensorDesc(ge::Shape({1, 3}), FORMAT_ND, DT_FLOAT));
    nms.update_output_desc_valid_detections(TensorDesc(ge::Shape({1}), FORMAT_ND, DT_INT32));
    graph.SetInputs({boxes, scores, maxPerClass, maxTotal, iouThreshold, scoreThreshold}).SetOutputs({nms});

    std::map<AscendString, AscendString> buildOptions;
    ge::Session* session = new Session(buildOptions);
    if (session == nullptr) {
        ge::GEFinalize();
        return FAILED;
    }

    constexpr uint32_t graphId = 0;
    std::map<AscendString, AscendString> graphOptions;
    ret = session->AddGraph(graphId, graph, graphOptions);
    if (ret != SUCCESS) {
        printf("%s - ERROR - [GEIR]: AddGraph failed: %s\n", GetTime().c_str(), ge::GEGetErrorMsgV2().GetString());
        delete session;
        ge::GEFinalize();
        return FAILED;
    }

    vector<Tensor> inputs = {
        MakeTensor(boxesShape, DT_FLOAT, boxesData),
        MakeTensor(scoresShape, DT_FLOAT, scoresData),
        MakeTensor(scalarShape, DT_INT32, vector<int32_t>{3}),
        MakeTensor(scalarShape, DT_INT32, vector<int32_t>{3}),
        MakeTensor(scalarShape, DT_FLOAT, vector<float>{0.5F}),
        MakeTensor(scalarShape, DT_FLOAT, vector<float>{0.0F}),
    };
    vector<Tensor> outputs;
    ret = session->RunGraph(graphId, inputs, outputs);
    const bool passed = ret == SUCCESS && outputs.size() == 4 &&
                        CheckFloatOutput(outputs[0],
                                         {0.0F, 0.0F, 1.0F, 1.0F, 0.0F, 0.0F, 0.2F, 0.2F, 0.0F, 0.0F, 0.0F, 0.0F}) &&
                        CheckFloatOutput(outputs[1], {0.9F, 0.7F, 0.0F}) &&
                        CheckFloatOutput(outputs[2], {0.0F, 0.0F, 0.0F}) && CheckIntOutput(outputs[3], {2});
    printf("%s - INFO - [GEIR]: CombinedNonMaxSuppression graph-mode example %s\n", GetTime().c_str(),
           passed ? "PASSED" : "FAILED");

    delete session;
    ret = ge::GEFinalize();
    return passed && ret == SUCCESS ? SUCCESS : FAILED;
}
