/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file img_warp_resize_tiling.cpp
 * \brief Tiling implementation for img_warp_resize operator
 *
 * Grid-Stride tiling: two-step core allocation + PER_CORE_MIN protection.
 * totalElements <= INT32_MAX (uint32_t UintDiv value range constraint).
 */

#include "log/log.h"
#include "platform/platform_ascendc.h"
#include "util/math_util.h"
#include "op_host/tiling_util.h"
#include "op_host/tiling_templates_registry.h"
#include "../../op_kernel/arch35/img_warp_resize_tiling_data.h"
#include "../../op_kernel/arch35/img_warp_resize_tiling_key.h"

namespace optiling {

constexpr int64_t PER_CORE_MIN_ELEMENTS = 1024; // 下限保护，对齐到 32
constexpr uint32_t DCACHE_SIZE = 128 * 1024;
constexpr uint32_t STATIC_UB_ESTIMATE = 0;

struct IMGWarpResizeCompileInfo {};

static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t& ubSize, int64_t& coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

/*!
 * \brief Validate input shapes and extract N, C, H, W dimensions.
 */
static ge::graphStatus ValidateAndExtractDims(gert::TilingContext* context, int64_t& N, int64_t& C, int64_t& H,
                                              int64_t& W)
{
    auto imgShape = context->GetInputShape(0)->GetStorageShape();       // [N, 4, C, H, W]
    auto warpIndexShape = context->GetInputShape(1)->GetStorageShape(); // [N, 2, H, W]

    OP_CHECK_IF(imgShape.GetDimNum() != 5, OP_LOGE(context, "img must be 5D, got %zu dims", imgShape.GetDimNum()),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(warpIndexShape.GetDimNum() != 4,
                OP_LOGE(context, "warp_index must be 4D, got %zu dims", warpIndexShape.GetDimNum()),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(imgShape.GetDim(1) != 4, OP_LOGE(context, "img.shape[1] must be 4, got %ld", imgShape.GetDim(1)),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(warpIndexShape.GetDim(1) != 2,
                OP_LOGE(context, "warp_index.shape[1] must be 2, got %ld", warpIndexShape.GetDim(1)),
                return ge::GRAPH_FAILED);

    N = imgShape.GetDim(0);
    C = imgShape.GetDim(2);
    H = imgShape.GetDim(3);
    W = imgShape.GetDim(4);

    // Validate N/H/W consistency
    OP_CHECK_IF(warpIndexShape.GetDim(0) != N,
                OP_LOGE(context, "N mismatch: img=%ld, warp_index=%ld", N, warpIndexShape.GetDim(0)),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(warpIndexShape.GetDim(2) != H,
                OP_LOGE(context, "H mismatch: img=%ld, warp_index=%ld", H, warpIndexShape.GetDim(2)),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(warpIndexShape.GetDim(3) != W,
                OP_LOGE(context, "W mismatch: img=%ld, warp_index=%ld", W, warpIndexShape.GetDim(3)),
                return ge::GRAPH_FAILED);
    // Validate no zero dimensions
    OP_CHECK_IF(N <= 0 || C <= 0 || H <= 0 || W <= 0,
                OP_LOGE(context, "0 or negative dim: N=%ld C=%ld H=%ld W=%ld", N, C, H, W), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ValidateDtypes(gert::TilingContext* context)
{
    const auto* imgDesc = context->GetInputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, imgDesc);
    const auto* warpIndexDesc = context->GetInputDesc(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, warpIndexDesc);
    ge::DataType imgDtype = imgDesc->GetDataType();
    OP_CHECK_IF(imgDtype != ge::DT_FLOAT16 && imgDtype != ge::DT_FLOAT,
                OP_LOGE(context, "img.dtype must be float16 or float32, got %d", static_cast<int32_t>(imgDtype)),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(warpIndexDesc->GetDataType() != ge::DT_FLOAT,
                OP_LOGE(context, "warp_index.dtype must be float32, got %d",
                        static_cast<int32_t>(warpIndexDesc->GetDataType())),
                return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus GetWorkspaceSize(gert::TilingContext* context)
{
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(context->GetPlatformInfo());
    uint64_t sysWorkspaceSize = ascendcPlatform.GetLibApiWorkSpaceSize();
    size_t* currentWorkspace = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = static_cast<size_t>(sysWorkspaceSize);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus IMGWarpResizeTilingFunc(gert::TilingContext* context)
{
    OP_LOGD(context, "Enter TilingIMGWarpResize");
    uint64_t ubSize;
    int64_t coreNum;
    OP_CHECK_IF(GetPlatformInfo(context, ubSize, coreNum) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetPlatformInfo error"), return ge::GRAPH_FAILED);

    int64_t N = 0, C = 0, H = 0, W = 0;
    OP_CHECK_IF(ValidateAndExtractDims(context, N, C, H, W) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "ValidateAndExtractDims error"), return ge::GRAPH_FAILED);

    OP_CHECK_IF(ValidateDtypes(context) != ge::GRAPH_SUCCESS, OP_LOGE(context, "ValidateDtypes error"),
                return ge::GRAPH_FAILED);

    int64_t totalElements = N * C * H * W;
    int64_t imageArea = H * W;
    // UintDiv<uint32_t> value range constraint
    OP_CHECK_IF(totalElements > static_cast<int64_t>(INT32_MAX),
                OP_LOGE(context, "totalElements %ld exceeds INT32_MAX", totalElements), return ge::GRAPH_FAILED);

    // Two-step core allocation
    int64_t perCoreElements = Ops::Base::CeilDiv(totalElements, coreNum);
    if (perCoreElements > 0 && perCoreElements < PER_CORE_MIN_ELEMENTS) {
        perCoreElements = PER_CORE_MIN_ELEMENTS;
    }
    int64_t needCoreNum = Ops::Base::CeilDiv(totalElements, perCoreElements);

    // Fill TilingData
    IMGWarpResizeTilingData* tiling = context->GetTilingData<IMGWarpResizeTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    tiling->needCoreNum = static_cast<int32_t>(needCoreNum);
    tiling->batchNum = static_cast<int32_t>(N);
    tiling->channelNum = static_cast<int32_t>(C);
    tiling->imageArea = static_cast<int32_t>(imageArea);
    tiling->totalElements = totalElements;

    // Workspace (system only, no user workspace)
    OP_CHECK_IF(GetWorkspaceSize(context) != ge::GRAPH_SUCCESS, OP_LOGE(context, "GetWorkspaceSize error"),
                return ge::GRAPH_FAILED);

    // Set BlockDim, LocalMemory, TilingKey
    context->SetBlockDim(static_cast<int32_t>(needCoreNum));
    OP_CHECK_IF((ubSize <= DCACHE_SIZE + STATIC_UB_ESTIMATE),
                OP_LOGE(context, "ubSize %lu <= DCACHE_SIZE + STATIC_UB_ESTIMATE", ubSize), return ge::GRAPH_FAILED);
    auto res = context->SetLocalMemorySize(static_cast<uint32_t>(ubSize - DCACHE_SIZE - STATIC_UB_ESTIMATE));
    OP_CHECK_IF((res != ge::GRAPH_SUCCESS), OP_LOGE(context, "SetLocalMemorySize failed"), return ge::GRAPH_FAILED);
    context->SetTilingKey(GET_TPL_TILING_KEY(IMG_WARP_RESIZE_TPL_DEFAULT));

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForIMGWarpResize([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_OPTILING(IMGWarpResize)
    .Tiling(IMGWarpResizeTilingFunc)
    .TilingParse<IMGWarpResizeCompileInfo>(TilingParseForIMGWarpResize);
} // namespace optiling
