/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file yolox_bounding_box_decode_proto.h
 * \brief
 * \date 2026
 * \copyright
 * This file was generated by CANNBot.
 */
#ifndef OPS_OP_PROTO_INC_YOLOXBOUNDINGBOXDECODE_H_
#define OPS_OP_PROTO_INC_YOLOXBOUNDINGBOXDECODE_H_

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
*@brief Decodes predicted bounding boxes based on the YOLOX decode formula.
*@par Inputs:
*Two inputs, including:
* @li priors: A Tensor of shape (N, 4), indicating the center_x, center_y, width and height
*of the prior boxes. Must be one of the following types: float16, float32.
* @li bboxes: A Tensor of shape (B, N, 4), indicating the predicted offsets. Must be one of the
*following types: float16, float32. \n

*@par Outputs:
*decoded_bboxes: A Tensor of shape (B, N, 4) with the decoded bounding boxes. Must be one of the
*following types: float16, float32.
*@par Third-party framework compatibility
*Compatible with the YOLOX model bounding box decode logic.
*/
REG_OP(YoloxBoundingBoxDecode)
    .INPUT(priors, TensorType({DT_FLOAT16, DT_FLOAT}))
    .INPUT(bboxes, TensorType({DT_FLOAT16, DT_FLOAT}))
    .OUTPUT(decoded_bboxes, TensorType({DT_FLOAT16, DT_FLOAT}))
    .OP_END_FACTORY_REG(YoloxBoundingBoxDecode)

} // namespace ge

#endif // OPS_OP_PROTO_INC_YOLOXBOUNDINGBOXDECODE_H_
