/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file yuv4442_yuv422_apt.cpp
 * \brief Kernel entry point for YUV444 to YUV422 conversion
 */

#include "arch35/yuv4442_yuv422_simt.h"

enum class Yuv4442yuv422TilingKey : uint32_t {
    TILING_KEY_DEFAULT = 0, // Single scenario: float16 -> uint8
};

template <uint32_t schMode>
__global__ __aicore__ void yuv4442_yuv422(GM_ADDR x, GM_ADDR y, GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(Yuv4442yuv422TilingData);
    GET_TILING_DATA_WITH_STRUCT(Yuv4442yuv422TilingData, tilingData, tiling);

    if constexpr (schMode == static_cast<uint32_t>(Yuv4442yuv422TilingKey::TILING_KEY_DEFAULT)) {
        NsYuv4442yuv422::Process<half, uint8_t>(x, y, &tilingData);
    }
}
