/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file dilation2_d_backprop_input_tiling.cpp
 * \brief Tiling implementation for dilation2_d_backprop_input operator
 *        MDE §3 Tiling 数据结构设计 + §7.3 Tiling 实现要点
 */
/* Generated By CANNBot */

#include "log/log.h"
#include "platform/platform_ascendc.h"
#include "util/math_util.h"
#include "util/platform_util.h"
#include "op_host/tiling_util.h"
#include "op_host/tiling_templates_registry.h"
#include "image/dilation2_d_backprop_input/op_kernel/arch35/dilation2_d_backprop_input_tiling_data.h"
#include "image/dilation2_d_backprop_input/op_kernel/arch35/dilation2_d_backprop_input_tiling_key.h"

#include <string>
#include <algorithm>

namespace optiling {

using namespace Ops::Cv::OpTiling;

constexpr int64_t PER_CORE_MIN = 1024;
constexpr uint32_t DCACHE_SIZE = 32 * 1024;
constexpr uint32_t STATIC_UB_ESTIMATE = 0;
constexpr int32_t WS_ALIGN = 128;
constexpr int32_t SCHEDULE_MODE_MULTI_CORE_SYNC = 1;
constexpr int32_t EXPECTED_X_RANK = 4;
constexpr int32_t EXPECTED_FILTER_RANK = 3;
constexpr size_t ATTR_LIST_LEN = 4;
constexpr int32_t PADDING_MODE_SAME = 0;
constexpr int32_t PADDING_MODE_VALID = 1;
constexpr int32_t PADDING_MODE_CALCULATED = 2;

struct Dilation2DBackpropInputCompileInfo {};

// ========== 输入索引常量（SE §6.3 单参数约束表） ==========
static constexpr int32_t kXIdx = 0;
static constexpr int32_t kFilterIdx = 1;
static constexpr int32_t kOutBackpropIdx = 2;

// ========== 解析后的属性 ==========
struct ParsedAttrs {
    int32_t strides[4] = {1, 1, 1, 1};
    int32_t rates[4] = {1, 1, 1, 1};
    int32_t pads[4] = {0, 0, 0, 0};
    std::string paddingMode = "SAME";
    std::string dataFormat = "NHWC";
    bool ceilMode = false;
    bool isNCHW = false;
};

// ========== GetPlatformInfo ==========
static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t& ubSize, int64_t& coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// ========== ValidateDtype（SE §6.3 单参数约束 dtype 列 + 跨参数约束 dtype 关系） ==========
static ge::graphStatus ValidateDtype(gert::TilingContext* context, ge::DataType& dataType)
{
    auto xDesc = context->GetInputDesc(kXIdx);
    OP_CHECK_NULL_WITH_CONTEXT(context, xDesc);
    dataType = xDesc->GetDataType();
    OP_CHECK_IF(
        dataType != ge::DT_FLOAT,
        OP_LOGE_FOR_INVALID_DTYPE(context->GetNodeName(), "x", Ops::Base::ToString(dataType).c_str(), "float32"),
        return ge::GRAPH_FAILED);
    // filter dtype == x dtype
    auto filterDesc = context->GetInputDesc(kFilterIdx);
    OP_CHECK_NULL_WITH_CONTEXT(context, filterDesc);
    OP_CHECK_IF(
        filterDesc->GetDataType() != dataType,
        OP_LOGE_FOR_INVALID_DTYPES_WITH_REASON(context->GetNodeName(), "filter", "x", "filter dtype must match x"),
        return ge::GRAPH_FAILED);
    // out_backprop dtype == x dtype
    auto outBpDesc = context->GetInputDesc(kOutBackpropIdx);
    OP_CHECK_NULL_WITH_CONTEXT(context, outBpDesc);
    OP_CHECK_IF(outBpDesc->GetDataType() != dataType,
                OP_LOGE_FOR_INVALID_DTYPES_WITH_REASON(context->GetNodeName(), "out_backprop", "x",
                                                       "out_backprop dtype must match x"),
                return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// ========== ValidateShape（SE §6.3 单参数约束 shape 列） ==========
static ge::graphStatus ValidateShape(gert::TilingContext* context)
{
    auto xShape = context->GetInputShape(kXIdx);
    OP_CHECK_NULL_WITH_CONTEXT(context, xShape);
    // SE §6.3 单参数约束: x rank=4
    OP_CHECK_IF(xShape->GetStorageShape().GetDimNum() != EXPECTED_X_RANK,
                OP_LOGE_FOR_INVALID_SHAPEDIM(context->GetNodeName(), "x",
                                             std::to_string(xShape->GetStorageShape().GetDimNum()).c_str(), "4"),
                return ge::GRAPH_FAILED);
    auto filterShape = context->GetInputShape(kFilterIdx);
    OP_CHECK_NULL_WITH_CONTEXT(context, filterShape);
    // SE §6.3 单参数约束: filter rank=3
    OP_CHECK_IF(filterShape->GetStorageShape().GetDimNum() != EXPECTED_FILTER_RANK,
                OP_LOGE_FOR_INVALID_SHAPEDIM(context->GetNodeName(), "filter",
                                             std::to_string(filterShape->GetStorageShape().GetDimNum()).c_str(), "3"),
                return ge::GRAPH_FAILED);
    auto outBpShape = context->GetInputShape(kOutBackpropIdx);
    OP_CHECK_NULL_WITH_CONTEXT(context, outBpShape);
    // SE §6.3 单参数约束: out_backprop rank=4
    OP_CHECK_IF(outBpShape->GetStorageShape().GetDimNum() != EXPECTED_X_RANK,
                OP_LOGE_FOR_INVALID_SHAPEDIM(context->GetNodeName(), "out_backprop",
                                             std::to_string(outBpShape->GetStorageShape().GetDimNum()).c_str(), "4"),
                return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// ========== ValidateAttr（SE §6.3 单参数约束属性行值域列） ==========
static ge::graphStatus ValidateAttr(gert::TilingContext* context, ParsedAttrs& parsed)
{
    const auto* runtimeAttrs = context->GetAttrs();
    OP_CHECK_NULL_WITH_CONTEXT(context, runtimeAttrs);
    // SE §6.3 单参数约束: strides 长度=4
    auto stridesVec = runtimeAttrs->GetListInt(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, stridesVec);
    OP_CHECK_IF(stridesVec->GetSize() != ATTR_LIST_LEN,
                OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "strides",
                                          std::to_string(stridesVec->GetSize()).c_str(), "length=4"),
                return ge::GRAPH_FAILED);
    auto stridesData = stridesVec->GetData();
    OP_CHECK_NULL_WITH_CONTEXT(context, stridesData);
    for (size_t i = 0; i < ATTR_LIST_LEN; i++) {
        parsed.strides[i] = static_cast<int32_t>(stridesData[i]);
    }
    // SE §6.3 单参数约束: rates 长度=4
    auto ratesVec = runtimeAttrs->GetListInt(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, ratesVec);
    OP_CHECK_IF(ratesVec->GetSize() != ATTR_LIST_LEN,
                OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "rates", std::to_string(ratesVec->GetSize()).c_str(),
                                          "length=4"),
                return ge::GRAPH_FAILED);
    auto ratesData = ratesVec->GetData();
    OP_CHECK_NULL_WITH_CONTEXT(context, ratesData);
    for (size_t i = 0; i < ATTR_LIST_LEN; i++) {
        parsed.rates[i] = static_cast<int32_t>(ratesData[i]);
    }
    // SE §6.3 单参数约束: padding_mode ∈ {SAME, VALID, CALCULATED}
    const char* padModeStr = runtimeAttrs->GetStr(2);
    OP_CHECK_NULL_WITH_CONTEXT(context, padModeStr);
    parsed.paddingMode = std::string(padModeStr);
    OP_CHECK_IF(parsed.paddingMode != "SAME" && parsed.paddingMode != "VALID" && parsed.paddingMode != "CALCULATED",
                OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "padding_mode", parsed.paddingMode.c_str(),
                                          "SAME/VALID/CALCULATED"),
                return ge::GRAPH_FAILED);
    // SE §6.3 单参数约束: pads 长度=4
    auto padsVec = runtimeAttrs->GetListInt(3);
    OP_CHECK_NULL_WITH_CONTEXT(context, padsVec);
    OP_CHECK_IF(padsVec->GetSize() != ATTR_LIST_LEN,
                OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "pads", std::to_string(padsVec->GetSize()).c_str(),
                                          "length=4"),
                return ge::GRAPH_FAILED);
    auto padsData = padsVec->GetData();
    OP_CHECK_NULL_WITH_CONTEXT(context, padsData);
    for (size_t i = 0; i < ATTR_LIST_LEN; i++) {
        parsed.pads[i] = static_cast<int32_t>(padsData[i]);
    }
    // SE §6.3 单参数约束: ceil_mode
    const bool* ceilModePtr = runtimeAttrs->GetBool(4);
    OP_CHECK_NULL_WITH_CONTEXT(context, ceilModePtr);
    parsed.ceilMode = *ceilModePtr;
    // SE §6.3 单参数约束: data_format ∈ {NHWC, NCHW}
    const char* dataFmtStr = runtimeAttrs->GetStr(5);
    OP_CHECK_NULL_WITH_CONTEXT(context, dataFmtStr);
    parsed.dataFormat = std::string(dataFmtStr);
    OP_CHECK_IF(
        parsed.dataFormat != "NHWC" && parsed.dataFormat != "NCHW",
        OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "data_format", parsed.dataFormat.c_str(), "NHWC or NCHW"),
        return ge::GRAPH_FAILED);
    parsed.isNCHW = (parsed.dataFormat == "NCHW");
    return ge::GRAPH_SUCCESS;
}

// ========== ValidateStridesRatesN/C（SE §6.3 跨参数约束: strides/rates N/C=1, H/W>0） ==========
static ge::graphStatus ValidateStridesRates(const ParsedAttrs& parsed, gert::TilingContext* context)
{
    int32_t cDimIdx = parsed.isNCHW ? 1 : 3;
    int32_t hDimIdx = parsed.isNCHW ? 2 : 1;
    int32_t wDimIdx = parsed.isNCHW ? 3 : 2;
    // SE §6.3 单参数约束: strides N/C 维度必须为 1
    OP_CHECK_IF(parsed.strides[0] != 1 || parsed.strides[cDimIdx] != 1,
                OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "strides", "N/C must be 1", "1"),
                return ge::GRAPH_FAILED);
    // SE §6.3 单参数约束: strides H/W 维度必须 > 0（防止 kernel/infershape 除零崩溃）
    OP_CHECK_IF(parsed.strides[hDimIdx] <= 0 || parsed.strides[wDimIdx] <= 0,
                OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "strides", "H/W must be > 0", "positive"),
                return ge::GRAPH_FAILED);
    // SE §6.3 单参数约束: rates N/C 维度必须为 1
    OP_CHECK_IF(parsed.rates[0] != 1 || parsed.rates[cDimIdx] != 1,
                OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "rates", "N/C must be 1", "1"),
                return ge::GRAPH_FAILED);
    // SE §6.3 单参数约束: rates H/W 维度必须 > 0
    OP_CHECK_IF(parsed.rates[hDimIdx] <= 0 || parsed.rates[wDimIdx] <= 0,
                OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "rates", "H/W must be > 0", "positive"),
                return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// ========== ValidateInputs 调度器 ==========
static ge::graphStatus ValidateInputs(gert::TilingContext* context, ge::DataType& dataType)
{
    OP_CHECK_IF(ValidateDtype(context, dataType) != ge::GRAPH_SUCCESS, OP_LOGE(context, "ValidateDtype failed"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(ValidateShape(context) != ge::GRAPH_SUCCESS, OP_LOGE(context, "ValidateShape failed"),
                return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// ========== ComputePadding（MDE §3.2） ==========
static void ComputePadding(const ParsedAttrs& parsed, int64_t inputH, int64_t inputW, int64_t filterH, int64_t filterW,
                           int64_t strideH, int64_t strideW, int64_t rateH, int64_t rateW, int64_t& padTop,
                           int64_t& padLeft, int64_t& outputH, int64_t& outputW)
{
    int64_t windowH = (filterH - 1) * rateH + 1;
    int64_t windowW = (filterW - 1) * rateW + 1;
    if (parsed.paddingMode == "SAME") {
        outputH = (inputH + strideH - 1) / strideH;
        outputW = (inputW + strideW - 1) / strideW;
        int64_t padTotalH = std::max((outputH - 1) * strideH + windowH - inputH, static_cast<int64_t>(0));
        int64_t padTotalW = std::max((outputW - 1) * strideW + windowW - inputW, static_cast<int64_t>(0));
        padTop = padTotalH / 2;
        padLeft = padTotalW / 2;
    } else if (parsed.paddingMode == "VALID") {
        outputH = (inputH - windowH + strideH) / strideH;
        outputW = (inputW - windowW + strideW) / strideW;
        padTop = 0;
        padLeft = 0;
    } else { // CALCULATED
        padTop = parsed.pads[0];
        padLeft = parsed.pads[2];
        if (parsed.ceilMode) {
            outputH = (inputH - windowH + padTop + parsed.pads[1] + strideH - 1) / strideH + 1;
            outputW = (inputW - windowW + padLeft + parsed.pads[3] + strideW - 1) / strideW + 1;
        } else {
            outputH = (inputH - windowH + padTop + parsed.pads[1]) / strideH + 1;
            outputW = (inputW - windowW + padLeft + parsed.pads[3]) / strideW + 1;
        }
        outputH = std::max(outputH, static_cast<int64_t>(1));
        outputW = std::max(outputW, static_cast<int64_t>(1));
    }
}

// ========== FillTilingData ==========
static void FillTilingData(Dilation2DBackpropInputTilingData* tiling, int64_t needCoreNum, int64_t outTotalNum,
                           int64_t inTotalNum, int64_t batch, int64_t inputH, int64_t inputW, int64_t depth,
                           int64_t outputH, int64_t outputW, int64_t filterH, int64_t filterW, int64_t strideH,
                           int64_t strideW, int64_t rateH, int64_t rateW, int64_t padTop, int64_t padLeft,
                           int64_t paddingMode)
{
    tiling->needCoreNum = needCoreNum;
    tiling->outTotalNum = outTotalNum;
    tiling->inTotalNum = inTotalNum;
    tiling->batch = batch;
    tiling->inputH = inputH;
    tiling->inputW = inputW;
    tiling->depth = depth;
    tiling->outputH = outputH;
    tiling->outputW = outputW;
    tiling->filterH = filterH;
    tiling->filterW = filterW;
    tiling->strideH = strideH;
    tiling->strideW = strideW;
    tiling->rateH = rateH;
    tiling->rateW = rateW;
    tiling->padTop = padTop;
    tiling->padLeft = padLeft;
    tiling->paddingMode = paddingMode;
}

// ========== DumpTilingData (DFX) ==========
static void DumpTilingData(gert::TilingContext* context, const Dilation2DBackpropInputTilingData* tiling)
{
    OP_LOGD(context,
            "Dilation2DBackpropInputTilingData: needCoreNum=%ld, outTotalNum=%ld, inTotalNum=%ld, "
            "batch=%ld, inputH=%ld, inputW=%ld, depth=%ld, outputH=%ld, outputW=%ld, "
            "filterH=%ld, filterW=%ld, strideH=%ld, strideW=%ld, "
            "rateH=%ld, rateW=%ld, padTop=%ld, padLeft=%ld, paddingMode=%ld",
            tiling->needCoreNum, tiling->outTotalNum, tiling->inTotalNum, tiling->batch, tiling->inputH, tiling->inputW,
            tiling->depth, tiling->outputH, tiling->outputW, tiling->filterH, tiling->filterW, tiling->strideH,
            tiling->strideW, tiling->rateH, tiling->rateW, tiling->padTop, tiling->padLeft, tiling->paddingMode);
}

// ========== GetTilingKey ==========
static uint64_t GetTilingKey(bool isNCHW)
{
    return GET_TPL_TILING_KEY(static_cast<uint64_t>(isNCHW ? DILATION2_D_BACKPROP_INPUT_SCH_MODE_NCHW :
                                                             DILATION2_D_BACKPROP_INPUT_SCH_MODE_NHWC));
}

// ========== GetWorkspaceSize（MDE §3.2 Workspace 大小计算） ==========
static ge::graphStatus GetWorkspaceSize(gert::TilingContext* context, int64_t outTotalNum)
{
    int64_t userWsSize = outTotalNum * static_cast<int64_t>(sizeof(int64_t));
    userWsSize = (userWsSize + WS_ALIGN - 1) & ~(static_cast<int64_t>(WS_ALIGN - 1));
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(context->GetPlatformInfo());
    uint64_t sysWsSize = ascendcPlatform.GetLibApiWorkSpaceSize();
    size_t* ws = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, ws);
    ws[0] = static_cast<size_t>(userWsSize + static_cast<int64_t>(sysWsSize));
    return ge::GRAPH_SUCCESS;
}

// ========== 维度信息结构体 ==========
struct DimsInfo {
    int64_t batch = 0;
    int64_t inputH = 0;
    int64_t inputW = 0;
    int64_t depth = 0;
    int64_t filterH = 0;
    int64_t filterW = 0;
    int64_t strideH = 0;
    int64_t strideW = 0;
    int64_t rateH = 0;
    int64_t rateW = 0;
    int64_t padTop = 0;
    int64_t padLeft = 0;
    int64_t outputH = 0;
    int64_t outputW = 0;
};

// ========== ExtractDimsAndComputePadding ==========
static ge::graphStatus ExtractDimsAndComputePadding(gert::TilingContext* context, const ParsedAttrs& parsed,
                                                    DimsInfo& dims)
{
    auto xShape = context->GetInputShape(kXIdx)->GetStorageShape();
    auto filterShape = context->GetInputShape(kFilterIdx)->GetStorageShape();
    if (parsed.isNCHW) {
        dims.batch = xShape.GetDim(0);
        dims.depth = xShape.GetDim(1);
        dims.inputH = xShape.GetDim(2);
        dims.inputW = xShape.GetDim(3);
        dims.filterH = filterShape.GetDim(1);
        dims.filterW = filterShape.GetDim(2);
    } else {
        dims.batch = xShape.GetDim(0);
        dims.inputH = xShape.GetDim(1);
        dims.inputW = xShape.GetDim(2);
        dims.depth = xShape.GetDim(3);
        dims.filterH = filterShape.GetDim(0);
        dims.filterW = filterShape.GetDim(1);
    }
    dims.strideH = parsed.isNCHW ? parsed.strides[2] : parsed.strides[1];
    dims.strideW = parsed.isNCHW ? parsed.strides[3] : parsed.strides[2];
    dims.rateH = parsed.isNCHW ? parsed.rates[2] : parsed.rates[1];
    dims.rateW = parsed.isNCHW ? parsed.rates[3] : parsed.rates[2];
    ComputePadding(parsed, dims.inputH, dims.inputW, dims.filterH, dims.filterW, dims.strideH, dims.strideW, dims.rateH,
                   dims.rateW, dims.padTop, dims.padLeft, dims.outputH, dims.outputW);
    return ge::GRAPH_SUCCESS;
}

// ========== ValidateCrossParams（SE §6.3 跨参数约束） ==========
static ge::graphStatus ValidateCrossParams(gert::TilingContext* context, const ParsedAttrs& parsed,
                                           const DimsInfo& dims)
{
    auto xShape = context->GetInputShape(kXIdx)->GetStorageShape();
    auto filterShape = context->GetInputShape(kFilterIdx)->GetStorageShape();
    auto outBpShape = context->GetInputShape(kOutBackpropIdx)->GetStorageShape();
    // SE §6.3 跨参数约束: x C 维度 = filter depth 维度
    int64_t xCDim = parsed.isNCHW ? xShape.GetDim(1) : xShape.GetDim(3);
    int64_t filterCDim = parsed.isNCHW ? filterShape.GetDim(0) : filterShape.GetDim(2);
    OP_CHECK_IF(xCDim != filterCDim,
                OP_LOGE_FOR_INVALID_SHAPES_WITH_REASON(context->GetNodeName(), "x", "filter",
                                                       "x C dim must match filter depth dim"),
                return ge::GRAPH_FAILED);
    // SE §6.3 跨参数约束: out_backprop N/C 维度与 x 一致
    OP_CHECK_IF(outBpShape.GetDim(0) != dims.batch,
                OP_LOGE_FOR_INVALID_SHAPES_WITH_REASON(context->GetNodeName(), "out_backprop", "x", "N must match"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(outBpShape.GetDim(parsed.isNCHW ? 1 : 3) != dims.depth,
                OP_LOGE_FOR_INVALID_SHAPES_WITH_REASON(context->GetNodeName(), "out_backprop", "x", "C must match"),
                return ge::GRAPH_FAILED);
    // SE §6.3 跨参数约束: out_backprop Ho/Wo 由推导得出
    int32_t obpHoIdx = parsed.isNCHW ? 2 : 1;
    int32_t obpWoIdx = parsed.isNCHW ? 3 : 2;
    OP_CHECK_IF(outBpShape.GetDim(obpHoIdx) != dims.outputH,
                OP_LOGE_FOR_INVALID_SHAPES_WITH_REASON(context->GetNodeName(), "out_backprop", "x",
                                                       "Ho must match computed outputH"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(outBpShape.GetDim(obpWoIdx) != dims.outputW,
                OP_LOGE_FOR_INVALID_SHAPES_WITH_REASON(context->GetNodeName(), "out_backprop", "x",
                                                       "Wo must match computed outputW"),
                return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// ========== ComputeNeedCoreNum（MDE §3.2 两步法） ==========
static int64_t ComputeNeedCoreNum(int64_t outTotalNum, int64_t inTotalNum, int64_t coreNum)
{
    int64_t blockFactor1 = (outTotalNum > 0) ? (outTotalNum + coreNum - 1) / coreNum : 0;
    if (blockFactor1 > 0 && blockFactor1 < PER_CORE_MIN) {
        blockFactor1 = PER_CORE_MIN;
    }
    int64_t needCoreNum1 = (outTotalNum > 0) ? (outTotalNum + blockFactor1 - 1) / blockFactor1 : 1;
    int64_t blockFactor2 = (inTotalNum > 0) ? (inTotalNum + coreNum - 1) / coreNum : 0;
    if (blockFactor2 > 0 && blockFactor2 < PER_CORE_MIN) {
        blockFactor2 = PER_CORE_MIN;
    }
    int64_t needCoreNum2 = (inTotalNum > 0) ? (inTotalNum + blockFactor2 - 1) / blockFactor2 : 1;
    int64_t needCoreNum = std::max(std::max(needCoreNum1, needCoreNum2), static_cast<int64_t>(1));
    if (needCoreNum > coreNum) {
        needCoreNum = coreNum;
    }
    return needCoreNum;
}

// ========== 主 Tiling 函数 ==========
static ge::graphStatus Dilation2DBackpropInputTilingFunc(gert::TilingContext* context)
{
    uint64_t ubSize = 0;
    int64_t coreNum = 0;
    OP_CHECK_IF(GetPlatformInfo(context, ubSize, coreNum) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetPlatformInfo error"), return ge::GRAPH_FAILED);

    ge::DataType dataType;
    OP_CHECK_IF(ValidateInputs(context, dataType) != ge::GRAPH_SUCCESS, OP_LOGE(context, "ValidateInputs failed"),
                return ge::GRAPH_FAILED);

    ParsedAttrs parsed;
    OP_CHECK_IF(ValidateAttr(context, parsed) != ge::GRAPH_SUCCESS, OP_LOGE(context, "ValidateAttr failed"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(ValidateStridesRates(parsed, context) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "ValidateStridesRates failed"), return ge::GRAPH_FAILED);

    DimsInfo dims;
    OP_CHECK_IF(ExtractDimsAndComputePadding(context, parsed, dims) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "ExtractDimsAndComputePadding failed"), return ge::GRAPH_FAILED);

    OP_CHECK_IF(ValidateCrossParams(context, parsed, dims) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "ValidateCrossParams failed"), return ge::GRAPH_FAILED);

    int64_t inTotalNum = dims.batch * dims.inputH * dims.inputW * dims.depth;
    int64_t outTotalNum = dims.batch * dims.outputH * dims.outputW * dims.depth;
    int64_t needCoreNum = ComputeNeedCoreNum(outTotalNum, inTotalNum, coreNum);

    Dilation2DBackpropInputTilingData* tiling = context->GetTilingData<Dilation2DBackpropInputTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(memset_s(tiling, sizeof(*tiling), 0, sizeof(*tiling)) != EOK,
                OP_LOGE(context, "memset_s tiling data failed"), return ge::GRAPH_FAILED);

    int64_t paddingMode = (parsed.paddingMode == "SAME")  ? PADDING_MODE_SAME :
                          (parsed.paddingMode == "VALID") ? PADDING_MODE_VALID :
                                                            PADDING_MODE_CALCULATED;
    FillTilingData(tiling, needCoreNum, outTotalNum, inTotalNum, dims.batch, dims.inputH, dims.inputW, dims.depth,
                   dims.outputH, dims.outputW, dims.filterH, dims.filterW, dims.strideH, dims.strideW, dims.rateH,
                   dims.rateW, dims.padTop, dims.padLeft, paddingMode);
    DumpTilingData(context, tiling);

    OP_CHECK_IF(GetWorkspaceSize(context, outTotalNum) != ge::GRAPH_SUCCESS, OP_LOGE(context, "GetWorkspaceSize error"),
                return ge::GRAPH_FAILED);

    context->SetBlockDim(static_cast<int32_t>(needCoreNum));
    OP_CHECK_IF(ubSize <= DCACHE_SIZE + STATIC_UB_ESTIMATE,
                OP_LOGE(context, "ubSize %lu <= DCACHE + STATIC_UB", ubSize), return ge::GRAPH_FAILED);
    auto res = context->SetLocalMemorySize(static_cast<uint32_t>(ubSize - DCACHE_SIZE - STATIC_UB_ESTIMATE));
    OP_CHECK_IF(res != ge::GRAPH_SUCCESS, OP_LOGE(context, "SetLocalMemorySize failed"), return ge::GRAPH_FAILED);
    // MDE §7.3 步骤12: 启用多核同步，Phase 1->Phase 2 需要 SyncAll
    context->SetScheduleMode(SCHEDULE_MODE_MULTI_CORE_SYNC);
    context->SetTilingKey(GetTilingKey(parsed.isNCHW));
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForDilation2DBackpropInput([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_OPTILING(Dilation2DBackpropInput)
    .Tiling(Dilation2DBackpropInputTilingFunc)
    .TilingParse<Dilation2DBackpropInputCompileInfo>(TilingParseForDilation2DBackpropInput);
} // namespace optiling
