/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file roi_align_rotated_simt.h
 * \brief RoiAlignRotated SIMT kernel 实现
 *        布局: x NCHW (N,C,H,W)、rois (R,6) 行主序、y (R,C,ph,pw)，float32 唯一
 *
 * 精度架构：
 *   - RoI 标量链全 float32；center 显式 fmaf 单次舍入
 *   - bin_size 朴素除法、采样步长 (i+0.5)*bin_size/grid 逐点内联除法、sin/cos 用
 *     SIMT sincosf
 *   - 采样累加为 mmcv 语义顺序累加（iy 外层、ix 内层，output_val += 四点加权和）；
 *   - 不做任何跨实现位级对齐：sin/cos 硬件单元差异、编译器 FMA 融合决策等固有
 *     位差由容差模型覆盖
 */

#ifndef ROI_ALIGN_ROTATED_SIMT_H
#define ROI_ALIGN_ROTATED_SIMT_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "simt_api/common_functions.h"
#include "simt_api/math_functions.h" // sincosf / ceilf / fmaxf / fmaf
#include "roi_align_rotated_tiling_data.h"

namespace NsRoiAlignRotated {

using namespace AscendC;

// VF 线程数
static constexpr uint32_t THREAD_NUM = 512;

// ========== VF 属性参数 UB 布局 ==========
// VF 标量参数须 ≤8 个且限整型，
// 9 个属性参数超出直传预算，统一打包进单个 __ubuf__ int32_t 线性缓冲区传递：
//   整型字段按值存放；spatialScale 以 float 位模式（union）存放；bool 以 0/1 存放。
static constexpr uint32_t OFF_POOLED_W = 0;       // 属性 pooled_w
static constexpr uint32_t OFF_POOLED_H = 1;       // 属性 pooled_h
static constexpr uint32_t OFF_CHANNELS = 2;       // C = x.dim(1)
static constexpr uint32_t OFF_HEIGHT = 3;         // H = x.dim(2)
static constexpr uint32_t OFF_WIDTH = 4;          // W = x.dim(3)
static constexpr uint32_t OFF_SAMPLING_RATIO = 5; // 属性 sampling_ratio
static constexpr uint32_t OFF_SPATIAL_SCALE = 6;  // 属性 spatial_scale（float 位模式）
static constexpr uint32_t OFF_ALIGNED = 7;        // 属性 aligned（0/1）
static constexpr uint32_t OFF_CLOCKWISE = 8;      // 属性 clockwise（0/1）
static constexpr uint32_t PARAMS_UB_ELEMS = 16;   // 9×4B=36B → 32B 对齐上取整到 64B（16 元素）

// float/int32 位模式互转（无损，禁手写 bf16 位拼接约束不适用）
union RoiParamWord {
    int32_t i;
    float f;
};

/*!
 * \brief RoI 参数预处理
 *   P1 先缩放后偏移禁止取整（center 显式 fmaf 单次舍入）/ P2 offset / P3 clockwise 取负 /
 *   P4 !aligned 强制 1x1（fmaxf）/ P5 ceilf 密集采样 / P6 count 下限 1 / P8 sincosf 一次调用
 */
template <typename T>
__simt_callee__ inline void DecodeRoiParams(__gm__ T* roisGm, uint64_t r, float spatialScale, bool aligned,
                                            bool clockwise, int32_t pooledH, int32_t pooledW, int32_t samplingRatio,
                                            int32_t& batchIdx, float& roiCenterW, float& roiCenterH, float& binSizeH,
                                            float& binSizeW, int32_t& gridH, int32_t& gridW, float& count,
                                            float& roiStartH, float& roiStartW, float& sinT, float& cosT)
{
    const __gm__ T* roiPtr = roisGm + r * 6UL; // (R,6) 行主序寻址，行内 6 字段连续
    // batch_idx 不校验范围
    batchIdx = static_cast<int32_t>(roiPtr[0]);
    // 像素对齐
    const float offset = aligned ? 0.5f : 0.0f;
    // 先缩放后偏移；fmaf 单次舍入
    roiCenterW = fmaf(static_cast<float>(roiPtr[1]), spatialScale, -offset);
    roiCenterH = fmaf(static_cast<float>(roiPtr[2]), spatialScale, -offset);
    float roiW = static_cast<float>(roiPtr[3]) * spatialScale;
    float roiH = static_cast<float>(roiPtr[4]) * spatialScale;
    float theta = static_cast<float>(roiPtr[5]);
    if (clockwise) {
        theta = -theta; // 顺时针角度取负（在 sin/cos 之前执行）
    }
    if (!aligned) { // 兼容模式: ROI 强制 >= 1x1
        roiW = fmaxf(roiW, 1.0f);
        roiH = fmaxf(roiH, 1.0f);
    }
    // 朴素除法
    binSizeH = roiH / static_cast<float>(pooledH);
    binSizeW = roiW / static_cast<float>(pooledW);
    // 采样网格数: sr>0 固定值; sr=0 按 ceil(bin_size) 密集采样（ceilf 为 float32 向上取整）
    gridH = (samplingRatio > 0) ? samplingRatio : static_cast<int32_t>(ceilf(binSizeH));
    gridW = (samplingRatio > 0) ? samplingRatio : static_cast<int32_t>(ceilf(binSizeW));
    // 平均池化分母: int64 乘法防溢出，< 1 时置 1（grid=0 时采样循环不执行，输出 0）
    count = static_cast<float>(static_cast<int64_t>(gridH) * gridW);
    if (count < 1.0f) {
        count = 1.0f;
    }
    roiStartH = -roiH * 0.5f; // 相对 ROI 中心的起始坐标
    roiStartW = -roiW * 0.5f;
    sincosf(theta, &sinT, &cosT);
}

/*!
 * \brief NCHW 双线性插值
 *   ① 越界（sy<-1 ∥ sy>H ∥ sx<-1 ∥ sx>W）贡献 0；
 *   ② 负坐标 clamp 到 0；
 *   ③ floor >= size-1 时单点采样（high=floor=size-1 且坐标重置使小数部分为 0）
 *   四点加权求和树（P10）: w1*v1 + w2*v2 + w3*v3 + w4*v4（C++ 左结合，编译器自由融合）
 */
template <typename T>
__simt_callee__ inline float BilinearSample(const __gm__ T* chBase, int32_t height, int32_t width, float sy, float sx)
{
    // ① 越界采样点贡献 0（仍计入 count 分母）
    if (sy < -1.0f || sy > static_cast<float>(height) || sx < -1.0f || sx > static_cast<float>(width)) {
        return 0.0f;
    }
    if (sy < 0.0f) { // ② 负坐标 clamp 到 0
        sy = 0.0f;
    }
    if (sx < 0.0f) {
        sx = 0.0f;
    }
    int32_t yLow = static_cast<int32_t>(sy); // sy >= 0，截断即 floor
    int32_t xLow = static_cast<int32_t>(sx);
    int32_t yHigh = 0;
    int32_t xHigh = 0;
    if (yLow >= height - 1) { // ③ 边界单点采样（坐标重置为 floor，小数部分为 0）
        yLow = height - 1;
        yHigh = yLow;
        sy = static_cast<float>(yLow);
    } else {
        yHigh = yLow + 1;
    }
    if (xLow >= width - 1) {
        xLow = width - 1;
        xHigh = xLow;
        sx = static_cast<float>(xLow);
    } else {
        xHigh = xLow + 1;
    }
    const float ly = sy - static_cast<float>(yLow);
    const float lx = sx - static_cast<float>(xLow);
    const float hy = 1.0f - ly;
    const float hx = 1.0f - lx;
    const __gm__ T* rowLo = chBase + static_cast<int64_t>(yLow) * width;
    const __gm__ T* rowHi = chBase + static_cast<int64_t>(yHigh) * width;
    // 四点加权（先四项求和再由调用方累加）
    return (hy * hx) * static_cast<float>(rowLo[xLow]) + (hy * lx) * static_cast<float>(rowLo[xHigh]) +
           (ly * hx) * static_cast<float>(rowHi[xLow]) + (ly * lx) * static_cast<float>(rowHi[xHigh]);
}

/*!
 * \brief 计算单个输出元素 (r, c, ph, pw) 的池化值
 *   采样循环 P11: iy 外层、ix 内层固定顺序，
 *   返回 outputVal / count
 */
template <typename T>
__simt_callee__ inline float ComputeBinValue(__gm__ T* xGm, __gm__ T* roisGm, uint64_t r, int32_t c, int32_t ph,
                                             int32_t pw, int32_t pooledW, int32_t pooledH, int32_t channels,
                                             int32_t height, int32_t width, int32_t samplingRatio, float spatialScale,
                                             bool aligned, bool clockwise)
{
    int32_t batchIdx = 0;
    float roiCenterW = 0.0f;
    float roiCenterH = 0.0f;
    float binSizeH = 0.0f;
    float binSizeW = 0.0f;
    int32_t gridH = 0;
    int32_t gridW = 0;
    float count = 1.0f;
    float roiStartH = 0.0f;
    float roiStartW = 0.0f;
    float sinT = 0.0f;
    float cosT = 0.0f;
    DecodeRoiParams<T>(roisGm, r, spatialScale, aligned, clockwise, pooledH, pooledW, samplingRatio, batchIdx,
                       roiCenterW, roiCenterH, binSizeH, binSizeW, gridH, gridW, count, roiStartH, roiStartW, sinT,
                       cosT);
    if (gridH <= 0 || gridW <= 0) {
        return 0.0f; // grid=0（如 aligned=true 时 ROI 宽高为 0）：采样循环不执行，输出 0
    }
    // NCHW 特征图寻址: feat[n][c][y][x] = xGm + ((batchIdx*C + c)*H + y)*W + x
    const int64_t hw = static_cast<int64_t>(height) * width;
    const __gm__ T* chBase = xGm + (static_cast<int64_t>(batchIdx) * channels + c) * hw;
    float outputVal = 0.0f;
    for (int32_t iy = 0; iy < gridH; iy++) { // P11: iy 外层
        // 采样点局部坐标（P7: (i+0.5) 半像素中心偏移；(i+0.5)*bin_size/grid 逐点内联除法）
        const float yy = roiStartH + ph * binSizeH + (iy + 0.5f) * binSizeH / static_cast<float>(gridH);
        for (int32_t ix = 0; ix < gridW; ix++) { // P11: ix 内层
            const float xx = roiStartW + pw * binSizeW + (ix + 0.5f) * binSizeW / static_cast<float>(gridW);
            // 旋转 theta（逆时针）后平移到特征图坐标（P8）
            const float sy = yy * cosT - xx * sinT + roiCenterH;
            const float sx = yy * sinT + xx * cosT + roiCenterW;
            outputVal += BilinearSample<T>(chBase, height, width, sy, sx);
        }
    }
    return outputVal / count; // 平均池化
}

/*!
 * \brief VF 主函数：Grid-Stride 循环，每线程独立计算一个输出元素
 *   坐标分解（步骤 1）: pw 最内层 → ph → c → r
 *   属性参数经单个 __ubuf__ int32_t 缓冲区传入
 */
template <typename T>
__simt_vf__ __aicore__ __launch_bounds__(THREAD_NUM) inline void OpRoiAlignRotatedSimt(uint64_t totalElements,
                                                                                       __gm__ T* xGm, __gm__ T* roisGm,
                                                                                       __gm__ T* yGm,
                                                                                       __ubuf__ int32_t* params)
{
    // 步骤 0: 从 UB 参数区一次性读出属性（每线程读一次，循环外；VF 内仅整型/位模式读出）
    const int32_t pooledW = params[OFF_POOLED_W];
    const int32_t pooledH = params[OFF_POOLED_H];
    const int32_t channels = params[OFF_CHANNELS];
    const int32_t height = params[OFF_HEIGHT];
    const int32_t width = params[OFF_WIDTH];
    const int32_t samplingRatio = params[OFF_SAMPLING_RATIO];
    RoiParamWord scaleWord;
    scaleWord.i = params[OFF_SPATIAL_SCALE];
    const float spatialScale = scaleWord.f;
    const bool aligned = params[OFF_ALIGNED] != 0;
    const bool clockwise = params[OFF_CLOCKWISE] != 0;
    for (uint64_t index = static_cast<uint64_t>(blockIdx.x * blockDim.x + threadIdx.x); index < totalElements;
         index += static_cast<uint64_t>(blockDim.x * gridDim.x)) {
        // 坐标分解: pw = index % pooled_w（最内层），ph、c、r 逐级外推
        const uint64_t n1 = index / static_cast<uint64_t>(pooledW);
        const int32_t pw = static_cast<int32_t>(index - n1 * pooledW);
        const uint64_t n2 = n1 / static_cast<uint64_t>(pooledH);
        const int32_t ph = static_cast<int32_t>(n1 - n2 * pooledH);
        const uint64_t r = n2 / static_cast<uint64_t>(channels);
        const int32_t c = static_cast<int32_t>(n2 - r * channels);
        // 单输出元素完整计算（RoI 预处理 + 采样循环 + 平均池化）并写回 GM
        yGm[index] = static_cast<T>(ComputeBinValue<T>(xGm, roisGm, r, c, ph, pw, pooledW, pooledH, channels, height,
                                                       width, samplingRatio, spatialScale, aligned, clockwise));
    }
}

/*!
 * \brief Process 入口：R=0 空切分静默返回；正常路径获取 GM 地址、
 *        属性参数打包 UB 后启动 VF
 */
template <typename T>
__aicore__ inline void Process(GM_ADDR x, GM_ADDR rois, GM_ADDR y, const RoiAlignRotatedArch35TilingData* tilingData)
{
    // R=0 空 rois：静默返回，VF 不启动，输出保持框架分配的空 tensor 状态
    if (tilingData->totalElements <= 0) {
        return;
    }
    __gm__ T* xGm = (__gm__ T*)x;       // 特征图 (N,C,H,W) float32，NCHW 语义
    __gm__ T* roisGm = (__gm__ T*)rois; // RoI (R,6) 行主序
    __gm__ T* yGm = (__gm__ T*)y;       // 输出 (R,C,pooled_h,pooled_w)
    // 9 个属性参数打包进动态 UB（64B，32B 对齐；scalar 写 UB 后必须 barrier 再 VF）
    LocalMemAllocator<AscendC::Hardware::UB> ubAlloc;
    LocalTensor<int32_t> paramsTensor = ubAlloc.Alloc<int32_t>(PARAMS_UB_ELEMS);
    RoiParamWord scaleWord;
    scaleWord.f = tilingData->spatialScale;
    paramsTensor.SetValue(OFF_POOLED_W, tilingData->pooledW);
    paramsTensor.SetValue(OFF_POOLED_H, tilingData->pooledH);
    paramsTensor.SetValue(OFF_CHANNELS, tilingData->channels);
    paramsTensor.SetValue(OFF_HEIGHT, tilingData->height);
    paramsTensor.SetValue(OFF_WIDTH, tilingData->width);
    paramsTensor.SetValue(OFF_SAMPLING_RATIO, tilingData->samplingRatio);
    paramsTensor.SetValue(OFF_SPATIAL_SCALE, scaleWord.i);
    paramsTensor.SetValue(OFF_ALIGNED, tilingData->aligned);
    paramsTensor.SetValue(OFF_CLOCKWISE, tilingData->clockwise);
    DataSyncBarrier<MemDsbT::UB>(); // S→V 写可见性
    // VF 标量参数仅 totalElements（1 个 ≤8），属性经 __ubuf__ 指针间接访问
    asc_vf_call<OpRoiAlignRotatedSimt<T>>(dim3(THREAD_NUM), (uint64_t)tilingData->totalElements, xGm, roisGm, yGm,
                                          (__ubuf__ int32_t*)paramsTensor.GetPhyAddr());
}

} // namespace NsRoiAlignRotated
#endif // ROI_ALIGN_ROTATED_SIMT_H
