#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ----------------------------------------------------------------------------

# Generated By CANNBot

"""
DeformableRoiPoolGrad 算子 UT 数据生成脚本（含 golden 计算）。
对齐 SE 文档第 6 章 golden_deformable_roi_pool_grad 实现。
"""

import sys
import pathlib
import numpy as np


def parse_str_to_shape_list(shape_str):
    """解析形如 '(2, 4, 3, 3)' 的字符串为 numpy 数组。"""
    shape_str = shape_str.strip("(").strip(")")
    shape_list = [int(x) for x in shape_str.split(",")]
    return np.array(shape_list)


def adaptive_grid_size(value):
    """将自适应采样网格限制在 Kernel 可安全表示的范围内。"""
    value = float(value)
    if not np.isfinite(value) or value <= 0.0 or value > 46340.0:
        return 0
    return int(np.ceil(value))


def finite_or_zero(value):
    return value if np.isfinite(value) else np.float32(0.0)


def golden_deformable_roi_pool_grad(
    grad_output,
    input,
    rois,
    offset,
    output_size,
    spatial_scale=1.0,
    sampling_ratio=0,
    gamma=0.1,
):
    """
    DeformableRoiPoolGrad 核心计算逻辑（对齐 mmcv CUDA kernel）。

    参数：
        grad_output: (N, C, pH, pW) 上游梯度
        input: (B, C, H, W) feature_map（前向输入）
        rois: (N, 5) [batch_ind, x1, y1, x2, y2]
        offset: (N, 2, pH, pW) 或 None
        output_size: [pooled_height, pooled_width]
        spatial_scale: float, 默认1.0
        sampling_ratio: int, 默认0（自适应）
        gamma: float, 默认0.1

    返回：
        grad_input: (B, C, H, W)
        grad_offset: (N, 2, pH, pW)（offset 为空时返回零张量）
    """
    pooled_height, pooled_width = output_size
    B, C, H, W = input.shape
    num_rois = rois.shape[0]

    grad_input = np.zeros((B, C, H, W), dtype=np.float32)
    has_offset = offset is not None and offset.size > 0
    if has_offset:
        grad_offset = np.zeros_like(offset, dtype=np.float32)
    else:
        grad_offset = np.zeros(
            (num_rois, 2, pooled_height, pooled_width), dtype=np.float32
        )

    grad_output_f = grad_output.astype(np.float32)
    input_f = input.astype(np.float32)
    rois_f = rois.astype(np.float32)
    offset_f = offset.astype(np.float32) if has_offset else None
    if B <= 0:
        return grad_input, grad_offset

    for n in range(num_rois):
        roi_batch_value = float(rois_f[n, 0])
        roi_batch_ind = int(roi_batch_value) if np.isfinite(roi_batch_value) else 0
        roi_batch_ind = max(0, min(roi_batch_ind, B - 1))

        spatial_scale_f = np.float32(spatial_scale)
        gamma_f = np.float32(gamma)
        roi_start_w = finite_or_zero(rois_f[n, 1]) * spatial_scale_f - np.float32(0.5)
        roi_start_h = finite_or_zero(rois_f[n, 2]) * spatial_scale_f - np.float32(0.5)
        roi_end_w = finite_or_zero(rois_f[n, 3]) * spatial_scale_f - np.float32(0.5)
        roi_end_h = finite_or_zero(rois_f[n, 4]) * spatial_scale_f - np.float32(0.5)

        roi_width = roi_end_w - roi_start_w
        roi_height = roi_end_h - roi_start_h

        bin_size_h = roi_height / np.float32(pooled_height)
        bin_size_w = roi_width / np.float32(pooled_width)

        if sampling_ratio > 0:
            roi_bin_grid_h = sampling_ratio
            roi_bin_grid_w = sampling_ratio
        else:
            roi_bin_grid_h = adaptive_grid_size(roi_height / np.float32(pooled_height))
            roi_bin_grid_w = adaptive_grid_size(roi_width / np.float32(pooled_width))

        count = roi_bin_grid_h * roi_bin_grid_w

        for c in range(C):
            for ph in range(pooled_height):
                for pw in range(pooled_width):
                    cur_roi_start_w = roi_start_w
                    cur_roi_start_h = roi_start_h
                    if has_offset:
                        raw_offset_w = offset_f[n, 0, ph, pw]
                        raw_offset_h = offset_f[n, 1, ph, pw]
                        offset_w_finite = np.isfinite(raw_offset_w)
                        offset_h_finite = np.isfinite(raw_offset_h)
                        offset_roi_w = (
                            gamma_f * roi_width * finite_or_zero(raw_offset_w)
                        )
                        offset_roi_h = (
                            gamma_f * roi_height * finite_or_zero(raw_offset_h)
                        )
                        cur_roi_start_w += offset_roi_w
                        cur_roi_start_h += offset_roi_h

                    grad_output_this_bin = (
                        grad_output_f[n, c, ph, pw] / np.float32(count)
                        if count > 0
                        else np.float32(0.0)
                    )

                    for iy in range(roi_bin_grid_h):
                        raw_y = (
                            cur_roi_start_h
                            + np.float32(ph) * bin_size_h
                            + (np.float32(iy) + np.float32(0.5))
                            * bin_size_h
                            / np.float32(roi_bin_grid_h)
                        )
                        for ix in range(roi_bin_grid_w):
                            raw_x = (
                                cur_roi_start_w
                                + np.float32(pw) * bin_size_w
                                + (np.float32(ix) + np.float32(0.5))
                                * bin_size_w
                                / np.float32(roi_bin_grid_w)
                            )

                            if (
                                not np.isfinite(raw_y)
                                or not np.isfinite(raw_x)
                                or raw_y < np.float32(-1.0)
                                or raw_y > np.float32(H)
                                or raw_x < np.float32(-1.0)
                                or raw_x > np.float32(W)
                            ):
                                continue

                            # Keep sampling coordinates immutable across ix. The
                            # same raw_y belongs to every sample in this iy row.
                            sample_y = raw_y
                            sample_x = raw_x
                            if sample_y <= np.float32(0):
                                sample_y = np.float32(0.0)
                            if sample_x <= np.float32(0):
                                sample_x = np.float32(0.0)

                            y_low = int(sample_y)
                            x_low = int(sample_x)

                            if y_low >= H - 1:
                                y_high = y_low = H - 1
                                sample_y = np.float32(y_low)
                            else:
                                y_high = y_low + 1

                            if x_low >= W - 1:
                                x_high = x_low = W - 1
                                sample_x = np.float32(x_low)
                            else:
                                x_high = x_low + 1

                            ly = sample_y - np.float32(y_low)
                            lx = sample_x - np.float32(x_low)
                            hy = np.float32(1.0) - ly
                            hx = np.float32(1.0) - lx

                            w1 = hy * hx
                            w2 = hy * lx
                            w3 = ly * hx
                            w4 = ly * lx

                            if (
                                x_low >= 0
                                and x_high >= 0
                                and y_low >= 0
                                and y_high >= 0
                            ):
                                grad_input[roi_batch_ind, c, y_low, x_low] += (
                                    grad_output_this_bin * w1
                                )
                                grad_input[roi_batch_ind, c, y_low, x_high] += (
                                    grad_output_this_bin * w2
                                )
                                grad_input[roi_batch_ind, c, y_high, x_low] += (
                                    grad_output_this_bin * w3
                                )
                                grad_input[roi_batch_ind, c, y_high, x_high] += (
                                    grad_output_this_bin * w4
                                )

                                if has_offset:
                                    input_00 = input_f[roi_batch_ind, c, y_low, x_low]
                                    input_10 = input_f[roi_batch_ind, c, y_low, x_high]
                                    input_01 = input_f[roi_batch_ind, c, y_high, x_low]
                                    input_11 = input_f[roi_batch_ind, c, y_high, x_high]

                                    ogx = (
                                        gamma_f
                                        * roi_width
                                        * grad_output_this_bin
                                        * (
                                            input_11 * (raw_y - np.float32(y_low))
                                            + input_10 * (np.float32(y_high) - raw_y)
                                            + input_01 * (np.float32(y_low) - raw_y)
                                            + input_00 * (raw_y - np.float32(y_high))
                                        )
                                    )

                                    ogy = (
                                        gamma_f
                                        * roi_height
                                        * grad_output_this_bin
                                        * (
                                            input_11 * (raw_x - np.float32(x_low))
                                            + input_01 * (np.float32(x_high) - raw_x)
                                            + input_10 * (np.float32(x_low) - raw_x)
                                            + input_00 * (raw_x - np.float32(x_high))
                                        )
                                    )

                                    if offset_w_finite:
                                        grad_offset[n, 0, ph, pw] += ogx
                                    if offset_h_finite:
                                        grad_offset[n, 1, ph, pw] += ogy

    return grad_input, grad_offset


def gen_data_and_golden(shape_str, d_type="float32"):
    """生成测试输入和 golden 输出 bin 文件。"""
    d_type_dict = {"float32": np.float32}
    np_type = d_type_dict[d_type]

    # 测试 shape：使用与典型网络用例对齐的小规模 shape
    # grad: (N, C, pH, pW), x: (B, C, H, W), rois: (N, 5), offset: (N, 2, pH, pW)
    N, C, pH, pW = 2, 4, 3, 3
    B, H, W = 2, 8, 8

    np.random.seed(42)
    # 上游梯度 grad
    grad = np.random.randn(N, C, pH, pW).astype(np_type)
    # feature_map x
    x = np.random.randn(B, C, H, W).astype(np_type)
    # rois: [batch_ind, x1, y1, x2, y2]，确保 batch_ind 合法且 x1<x2, y1<y2
    rois = np.array(
        [
            [0, 1.0, 1.0, 5.0, 5.0],
            [1, 0.0, 0.0, 6.0, 7.0],
        ],
        dtype=np_type,
    )
    # offset
    offset = np.random.randn(N, 2, pH, pW).astype(np_type) * 0.1

    output_size = [pH, pW]
    spatial_scale = 1.0
    sampling_ratio = 2
    gamma = 0.1

    # 计算 golden
    grad_x, grad_offset = golden_deformable_roi_pool_grad(
        grad.astype(np.float32),
        x.astype(np.float32),
        rois.astype(np.float32),
        offset.astype(np.float32),
        output_size,
        spatial_scale,
        sampling_ratio,
        gamma,
    )

    # 输出 bin 文件
    grad.astype(np_type).tofile(f"{d_type}_input_grad.bin")
    x.astype(np_type).tofile(f"{d_type}_input_x.bin")
    rois.astype(np_type).tofile(f"{d_type}_input_rois.bin")
    offset.astype(np_type).tofile(f"{d_type}_input_offset.bin")
    grad_x.astype(np_type).tofile(f"{d_type}_golden_grad_x.bin")
    grad_offset.astype(np_type).tofile(f"{d_type}_golden_grad_offset.bin")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Param num must be 3.")
        exit(1)
    dtype = sys.argv[2]
    if dtype != "float32":
        raise ValueError(f"unsupported dtype: {dtype}")
    # 仅清理本算子本 dtype 会生成的固定文件，避免删除调用目录中的无关 bin。
    output_names = (
        "input_grad",
        "input_x",
        "input_rois",
        "input_offset",
        "golden_grad_x",
        "golden_grad_offset",
    )
    for output_name in output_names:
        bin_file = pathlib.Path.cwd() / f"{dtype}_{output_name}.bin"
        if bin_file.is_file():
            bin_file.unlink()
    gen_data_and_golden(sys.argv[1], dtype)
