/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file upsample_bilinear2d_grad_tiling_arch35.cpp
 * \brief Tiling implementation for upsample_bilinear2d_grad (arch35)
 */

#include "log/log.h"
#include "register/op_impl_registry.h"
#include "platform/platform_ascendc.h"
#include "util/math_util.h"
#include "util/platform_util.h"
#include "op_host/tiling_util.h"
#include "op_host/tiling_templates_registry.h"
#include "image/upsample_bilinear2d_grad/op_kernel/arch35/upsample_bilinear2d_grad_tiling_data.h"
#include "image/upsample_bilinear2d_grad/op_kernel/arch35/upsample_bilinear2d_grad_tiling_key.h"

namespace optiling {

using namespace Ops::Cv::OpTiling;

constexpr uint32_t DCACHE_SIZE = 128 * 1024;
constexpr uint32_t STATIC_UB_ESTIMATE = 0;
constexpr int64_t PER_CORE_MIN = 1024;

static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t& ubSize, int64_t& coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus GetShapeAttrsInfo(gert::TilingContext* context, int64_t& nBatch, int64_t& channels,
                                         int64_t& outputHeight, int64_t& outputWidth, int64_t& inputHeight,
                                         int64_t& inputWidth, bool& alignCorners, double& scalesH, double& scalesW)
{
    auto gradOutputShape = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, gradOutputShape);
    auto storageShape = gradOutputShape->GetStorageShape();
    OP_CHECK_IF(storageShape.GetDimNum() != 4,
                OP_LOGE(context, "grad_output must be 4D, got %zu", storageShape.GetDimNum()), return ge::GRAPH_FAILED);

    nBatch = storageShape.GetDim(0);
    channels = storageShape.GetDim(1);
    outputHeight = storageShape.GetDim(2);
    outputWidth = storageShape.GetDim(3);

    auto attrs = context->GetAttrs();
    OP_CHECK_NULL_WITH_CONTEXT(context, attrs);

    const auto* inputSizeVec = attrs->GetListInt(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputSizeVec);
    OP_CHECK_IF(inputSizeVec->GetSize() != 4,
                OP_LOGE(context, "input_size must have 4 elements, got %zu", inputSizeVec->GetSize()),
                return ge::GRAPH_FAILED);

    const int64_t* inputSizeData = inputSizeVec->GetData();
    inputHeight = inputSizeData[2];
    inputWidth = inputSizeData[3];

    const bool* alignCornersPtr = attrs->GetBool(2);
    alignCorners = (alignCornersPtr != nullptr) ? *alignCornersPtr : false;

    const float* scalesHPtr = attrs->GetFloat(3);
    scalesH = (scalesHPtr != nullptr) ? static_cast<double>(*scalesHPtr) : 0.0;

    const float* scalesWPtr = attrs->GetFloat(4);
    scalesW = (scalesWPtr != nullptr) ? static_cast<double>(*scalesWPtr) : 0.0;

    return ge::GRAPH_SUCCESS;
}

static void ComputeScales(bool alignCorners, double& scalesH, double& scalesW, int64_t inputHeight, int64_t inputWidth,
                          int64_t outputHeight, int64_t outputWidth)
{
    if (scalesH == 0.0) {
        if (alignCorners) {
            scalesH = (outputHeight > 1) ? static_cast<double>(inputHeight - 1) / (outputHeight - 1) : 0.0;
        } else {
            scalesH = (outputHeight > 0) ? static_cast<double>(inputHeight) / outputHeight : 0.0;
        }
    }
    if (scalesW == 0.0) {
        if (alignCorners) {
            scalesW = (outputWidth > 1) ? static_cast<double>(inputWidth - 1) / (outputWidth - 1) : 0.0;
        } else {
            scalesW = (outputWidth > 0) ? static_cast<double>(inputWidth) / outputWidth : 0.0;
        }
    }
}

static ge::graphStatus GetWorkspaceSize(gert::TilingContext* context)
{
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(context->GetPlatformInfo());
    uint64_t sysWorkspaceSize = ascendcPlatform.GetLibApiWorkSpaceSize();
    size_t* currentWorkspace = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = static_cast<size_t>(sysWorkspaceSize);
    return ge::GRAPH_SUCCESS;
}

static int64_t ComputeCoreAllocation(int64_t totalElements, int64_t coreNum)
{
    if (totalElements <= 0) {
        return 0;
    }
    int64_t perCoreElements = Ops::Base::CeilDiv(totalElements, coreNum);
    if (perCoreElements < PER_CORE_MIN) {
        perCoreElements = PER_CORE_MIN;
    }
    perCoreElements = Ops::Base::CeilDiv(perCoreElements, static_cast<int64_t>(32)) * 32;
    return Ops::Base::CeilDiv(totalElements, perCoreElements);
}

static ge::graphStatus FillArch35TilingData(gert::TilingContext* context, int64_t totalElements, int64_t nBatch,
                                            int64_t channels, int64_t inputHeight, int64_t inputWidth,
                                            int64_t outputHeight, int64_t outputWidth, double scalesH, double scalesW,
                                            bool alignCorners)
{
    UpsampleBilinear2dGradTilingData* tiling = context->GetTilingData<UpsampleBilinear2dGradTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(
        memset_s(tiling, sizeof(UpsampleBilinear2dGradTilingData), 0, sizeof(UpsampleBilinear2dGradTilingData)) != EOK,
        OP_LOGE(context, "memset tiling data error"), return ge::GRAPH_FAILED);

    OP_CHECK_IF(nBatch > INT32_MAX || channels > INT32_MAX || inputHeight > INT32_MAX || inputWidth > INT32_MAX ||
                    outputHeight > INT32_MAX || outputWidth > INT32_MAX,
                OP_LOGE(context, "dimension exceeds INT32_MAX"), return ge::GRAPH_FAILED);

    tiling->totalElements = totalElements;
    tiling->inputTotalElements = nBatch * channels * inputHeight * inputWidth;
    tiling->nBatch = static_cast<int32_t>(nBatch);
    tiling->channels = static_cast<int32_t>(channels);
    tiling->inputHeight = static_cast<int32_t>(inputHeight);
    tiling->inputWidth = static_cast<int32_t>(inputWidth);
    tiling->outputHeight = static_cast<int32_t>(outputHeight);
    tiling->outputWidth = static_cast<int32_t>(outputWidth);
    tiling->scalesH = static_cast<float>(scalesH);
    tiling->scalesW = static_cast<float>(scalesW);
    tiling->alignCorners = alignCorners ? 1 : 0;
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ComputeArch35TilingKey(gert::TilingContext* context, bool alignCorners)
{
    auto inputDesc = context->GetInputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDesc);
    auto inputDataType = inputDesc->GetDataType();

    uint64_t tilingKey = 0;
    if (inputDataType == ge::DT_FLOAT16) {
        tilingKey = alignCorners ? GET_TPL_TILING_KEY(UPSAMPLE_BILINEAR2D_GRAD_MODE_FP16_ALIGN) :
                                   GET_TPL_TILING_KEY(UPSAMPLE_BILINEAR2D_GRAD_MODE_FP16_NOALIGN);
    } else if (inputDataType == ge::DT_FLOAT) {
        tilingKey = alignCorners ? GET_TPL_TILING_KEY(UPSAMPLE_BILINEAR2D_GRAD_MODE_FP32_ALIGN) :
                                   GET_TPL_TILING_KEY(UPSAMPLE_BILINEAR2D_GRAD_MODE_FP32_NOALIGN);
    } else if (inputDataType == ge::DT_BF16) {
        tilingKey = alignCorners ? GET_TPL_TILING_KEY(UPSAMPLE_BILINEAR2D_GRAD_MODE_BF16_ALIGN) :
                                   GET_TPL_TILING_KEY(UPSAMPLE_BILINEAR2D_GRAD_MODE_BF16_NOALIGN);
    } else {
        OP_LOGE(context, "unsupported dtype");
        return ge::GRAPH_FAILED;
    }
    context->SetTilingKey(tilingKey);
    return ge::GRAPH_SUCCESS;
}

ge::graphStatus UpsampleBilinear2dGradTilingArch35(gert::TilingContext* context)
{
    uint64_t ubSize = 0;
    int64_t coreNum = 0;
    OP_CHECK_IF(GetPlatformInfo(context, ubSize, coreNum) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetPlatformInfo error"), return ge::GRAPH_FAILED);

    int64_t nBatch = 0, channels = 0, outputHeight = 0, outputWidth = 0;
    int64_t inputHeight = 0, inputWidth = 0;
    bool alignCorners = false;
    double scalesH = 0.0, scalesW = 0.0;
    OP_CHECK_IF(GetShapeAttrsInfo(context, nBatch, channels, outputHeight, outputWidth, inputHeight, inputWidth,
                                  alignCorners, scalesH, scalesW) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetShapeAttrsInfo error"), return ge::GRAPH_FAILED);

    ComputeScales(alignCorners, scalesH, scalesW, inputHeight, inputWidth, outputHeight, outputWidth);

    OP_CHECK_IF(GetWorkspaceSize(context) != ge::GRAPH_SUCCESS, OP_LOGE(context, "GetWorkspaceSize error"),
                return ge::GRAPH_FAILED);

    int64_t totalElements = nBatch * channels * outputHeight * outputWidth;
    if (totalElements == 0) {
        context->SetBlockDim(1);
        return ge::GRAPH_SUCCESS;
    }
    int64_t needCoreNum = ComputeCoreAllocation(totalElements, coreNum);

    OP_CHECK_IF(FillArch35TilingData(context, totalElements, nBatch, channels, inputHeight, inputWidth, outputHeight,
                                     outputWidth, scalesH, scalesW, alignCorners) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "FillArch35TilingData failed"), return ge::GRAPH_FAILED);

    context->SetBlockDim(static_cast<uint32_t>(needCoreNum));

    OP_CHECK_IF(ubSize <= DCACHE_SIZE + STATIC_UB_ESTIMATE,
                OP_LOGE(context, "ubSize %lu <= DCACHE_SIZE + STATIC_UB_ESTIMATE", ubSize), return ge::GRAPH_FAILED);
    auto res = context->SetLocalMemorySize(static_cast<uint32_t>(ubSize - DCACHE_SIZE - STATIC_UB_ESTIMATE));
    OP_CHECK_IF(res != ge::GRAPH_SUCCESS, OP_LOGE(context, "SetLocalMemorySize failed"), return ge::GRAPH_FAILED);

    OP_CHECK_IF(ComputeArch35TilingKey(context, alignCorners) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "ComputeArch35TilingKey failed"), return ge::GRAPH_FAILED);

    return ge::GRAPH_SUCCESS;
}

} // namespace optiling
