/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file test_rotated_box_encode_tiling.cpp
 * \brief RotatedBoxEncode tiling UT: 覆盖 fp16(KEY=0) / fp32(KEY=1) 两分支
 *        平台参数: coreNumAiv=48, ubSize=253952 (ascend950 arch35)
 *        输入契约: anchor_box=(B,5,N), gt_box=(B,5,N)；5 通道 corner form (x0,y0,x1,y1,θ_deg)
 *        分支: fp16 → tilingKey=0 (fp16-upcast, perBoxBytes=70, ubFormer=3584)
 *              fp32 → tilingKey=1 (fp32-direct, perBoxBytes=60, ubFormer=4224)
 */

#include <cstring>
#include <vector>
#include <gtest/gtest.h>
#include "tiling_case_executor.h"
#include "tiling_context_faker.h"
#include "../../../../op_kernel/arch35/rotated_box_encode_tiling_data.h"

namespace {

using TensorDesc = gert::TilingContextPara::TensorDescription;
using OpAttr = gert::TilingContextPara::OpAttr;

struct RotatedBoxEncodeCompileInfoForTest {
    uint32_t coreNumAiv;
    uint64_t ubSize;
};

RotatedBoxEncodeCompileInfoForTest g_compileInfo{48, 253952};

gert::StorageShape MakeStorageShape(const std::vector<int64_t>& dims)
{
    gert::StorageShape shape;
    for (int64_t dim : dims) {
        shape.MutableOriginShape().AppendDim(dim);
        shape.MutableStorageShape().AppendDim(dim);
    }
    return shape;
}

gert::TilingContextPara MakeContext(const std::vector<int64_t>& shape, ge::DataType dtype,
                                    const std::vector<float>& weight)
{
    const gert::StorageShape storageShape = MakeStorageShape(shape);
    std::vector<TensorDesc> inputs = {
        {storageShape, dtype, ge::FORMAT_ND},
        {storageShape, dtype, ge::FORMAT_ND},
    };
    std::vector<TensorDesc> outputs = {
        {storageShape, dtype, ge::FORMAT_ND},
    };
    if (weight.empty()) {
        return gert::TilingContextPara("RotatedBoxEncode", inputs, outputs, {}, &g_compileInfo, "Ascend950", 48, 253952,
                                       4096);
    }
    std::vector<OpAttr> attrs = {
        OpAttr("weight", Ops::Cv::AnyValue::CreateFrom<std::vector<float>>(weight)),
    };
    return gert::TilingContextPara("RotatedBoxEncode", inputs, outputs, attrs, &g_compileInfo, "Ascend950", 48, 253952,
                                   4096);
}

bool RunTiling(const gert::TilingContextPara& context, TilingInfo& info, RotatedBoxEncodeTilingData& tilingData)
{
    if (!ExecuteTiling(context, info) || info.tilingDataSize < sizeof(RotatedBoxEncodeTilingData)) {
        return false;
    }
    std::memcpy(&tilingData, info.tilingData.get(), sizeof(tilingData));
    return true;
}

} // namespace

class RotatedBoxEncodeTiling : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "RotatedBoxEncodeTiling SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "RotatedBoxEncodeTiling TearDown" << std::endl; }
};

// Branch-0 (fp16): (2,5,8) → tilingKey=0, dim0=16, coreNum=1, ubFormer=3584
TEST_F(RotatedBoxEncodeTiling, tiling_case0_fp16_small)
{
    TilingInfo info;
    RotatedBoxEncodeTilingData td{};
    ASSERT_TRUE(RunTiling(MakeContext({2, 5, 8}, ge::DT_FLOAT16, {1.0f, 1.0f, 1.0f, 1.0f, 1.0f}), info, td));
    EXPECT_EQ(info.tilingKey, 0);
    EXPECT_EQ(td.dim0, 16);
    EXPECT_EQ(td.N, 8);
    EXPECT_EQ(td.coreNum, 1);
    EXPECT_EQ(td.ubFormer, 3584);
    EXPECT_EQ(td.blockFormer, 512);
    EXPECT_EQ(td.blockNum, 1);
    EXPECT_EQ(td.ubLoopOfFormerBlock, 1);
    EXPECT_EQ(td.ubTailOfFormerBlock, 512);
    EXPECT_EQ(td.ubLoopOfTailBlock, 1);
    EXPECT_EQ(td.ubTailOfTailBlock, 16);
    EXPECT_FLOAT_EQ(td.weight[0], 1.0f);
    EXPECT_FLOAT_EQ(td.weight[4], 1.0f);
}

// Branch-1 (fp32): (2,5,8) → tilingKey=1, dim0=16, coreNum=1, ubFormer=4224
TEST_F(RotatedBoxEncodeTiling, tiling_case1_fp32_small)
{
    TilingInfo info;
    RotatedBoxEncodeTilingData td{};
    ASSERT_TRUE(RunTiling(MakeContext({2, 5, 8}, ge::DT_FLOAT, {1.0f, 1.0f, 1.0f, 1.0f, 1.0f}), info, td));
    EXPECT_EQ(info.tilingKey, 1);
    EXPECT_EQ(td.dim0, 16);
    EXPECT_EQ(td.N, 8);
    EXPECT_EQ(td.coreNum, 1);
    EXPECT_EQ(td.ubFormer, 4224);
    EXPECT_EQ(td.blockFormer, 512);
    EXPECT_EQ(td.blockNum, 1);
    EXPECT_EQ(td.ubLoopOfFormerBlock, 1);
    EXPECT_EQ(td.ubTailOfFormerBlock, 512);
    EXPECT_EQ(td.ubLoopOfTailBlock, 1);
    EXPECT_EQ(td.ubTailOfTailBlock, 16);
}

// Branch-0 (fp16) empty: (0,5,8) → tilingKey=0, dim0=0, coreNum=0
TEST_F(RotatedBoxEncodeTiling, tiling_case2_fp16_empty)
{
    TilingInfo info;
    RotatedBoxEncodeTilingData td{};
    ASSERT_TRUE(RunTiling(MakeContext({0, 5, 8}, ge::DT_FLOAT16, {1.0f, 1.0f, 1.0f, 1.0f, 1.0f}), info, td));
    EXPECT_EQ(info.tilingKey, 0);
    EXPECT_EQ(td.dim0, 0);
    EXPECT_EQ(td.N, 8);
    EXPECT_EQ(td.coreNum, 0);
    EXPECT_EQ(td.ubFormer, 0);
    EXPECT_EQ(td.blockFormer, 0);
    EXPECT_EQ(td.blockNum, 0);
}

// Branch-1 (fp32) empty: (0,5,8) → tilingKey=1, dim0=0, coreNum=0
TEST_F(RotatedBoxEncodeTiling, tiling_case3_fp32_empty)
{
    TilingInfo info;
    RotatedBoxEncodeTilingData td{};
    ASSERT_TRUE(RunTiling(MakeContext({0, 5, 8}, ge::DT_FLOAT, {1.0f, 1.0f, 1.0f, 1.0f, 1.0f}), info, td));
    EXPECT_EQ(info.tilingKey, 1);
    EXPECT_EQ(td.dim0, 0);
    EXPECT_EQ(td.N, 8);
    EXPECT_EQ(td.coreNum, 0);
    EXPECT_EQ(td.ubFormer, 0);
    EXPECT_EQ(td.blockFormer, 0);
    EXPECT_EQ(td.blockNum, 0);
}

// Branch-0 (fp16) large: (4,5,256) weight=[2,2,1,1,0.5] → tilingKey=0, dim0=1024, coreNum=3
TEST_F(RotatedBoxEncodeTiling, tiling_case4_fp16_large_custom_weight)
{
    TilingInfo info;
    RotatedBoxEncodeTilingData td{};
    ASSERT_TRUE(RunTiling(MakeContext({4, 5, 256}, ge::DT_FLOAT16, {2.0f, 2.0f, 1.0f, 1.0f, 0.5f}), info, td));
    EXPECT_EQ(info.tilingKey, 0);
    EXPECT_EQ(td.dim0, 1024);
    EXPECT_EQ(td.N, 256);
    EXPECT_EQ(td.coreNum, 3);
    EXPECT_EQ(td.ubFormer, 3584);
    EXPECT_EQ(td.blockFormer, 512);
    EXPECT_EQ(td.blockNum, 2);
    EXPECT_EQ(td.ubLoopOfFormerBlock, 1);
    EXPECT_EQ(td.ubTailOfFormerBlock, 512);
    EXPECT_EQ(td.ubLoopOfTailBlock, 1);
    EXPECT_EQ(td.ubTailOfTailBlock, 512);
    EXPECT_FLOAT_EQ(td.weight[0], 2.0f);
    EXPECT_FLOAT_EQ(td.weight[1], 2.0f);
    EXPECT_FLOAT_EQ(td.weight[2], 1.0f);
    EXPECT_FLOAT_EQ(td.weight[3], 1.0f);
    EXPECT_FLOAT_EQ(td.weight[4], 0.5f);
}

// Branch-1 (fp32) large: (8,5,4096) → tilingKey=1, dim0=32768, coreNum=48
TEST_F(RotatedBoxEncodeTiling, tiling_case5_fp32_large_multicore)
{
    TilingInfo info;
    RotatedBoxEncodeTilingData td{};
    ASSERT_TRUE(RunTiling(MakeContext({8, 5, 4096}, ge::DT_FLOAT, {1.0f, 1.0f, 1.0f, 1.0f, 1.0f}), info, td));
    EXPECT_EQ(info.tilingKey, 1);
    EXPECT_EQ(td.dim0, 32768);
    EXPECT_EQ(td.N, 4096);
    EXPECT_EQ(td.coreNum, 48);
    EXPECT_EQ(td.ubFormer, 4224);
    EXPECT_EQ(td.blockFormer, 1024);
    EXPECT_EQ(td.blockNum, 32);
    EXPECT_EQ(td.ubLoopOfFormerBlock, 1);
    EXPECT_EQ(td.ubTailOfFormerBlock, 1024);
    EXPECT_EQ(td.ubLoopOfTailBlock, 1);
    EXPECT_EQ(td.ubTailOfTailBlock, 1024);
}

// Branch-0 (fp16) default weight (no attr): (2,5,8) → tilingKey=0, weight=[1,1,1,1,1]
TEST_F(RotatedBoxEncodeTiling, tiling_case6_fp16_default_weight)
{
    TilingInfo info;
    RotatedBoxEncodeTilingData td{};
    ASSERT_TRUE(RunTiling(MakeContext({2, 5, 8}, ge::DT_FLOAT16, {}), info, td));
    EXPECT_EQ(info.tilingKey, 0);
    EXPECT_EQ(td.dim0, 16);
    EXPECT_EQ(td.N, 8);
    EXPECT_EQ(td.coreNum, 1);
    EXPECT_EQ(td.ubFormer, 3584);
    EXPECT_FLOAT_EQ(td.weight[0], 1.0f);
    EXPECT_FLOAT_EQ(td.weight[1], 1.0f);
    EXPECT_FLOAT_EQ(td.weight[2], 1.0f);
    EXPECT_FLOAT_EQ(td.weight[3], 1.0f);
    EXPECT_FLOAT_EQ(td.weight[4], 1.0f);
}
