/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <gtest/gtest.h>
#include <iostream>
#include "infershape_context_faker.h"
#include "infershape_case_executor.h"

class YoloxBoundingBoxDecodeInfershape : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "YoloxBoundingBoxDecodeInfershape SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "YoloxBoundingBoxDecodeInfershape TearDown" << std::endl; }
};

// Test case 1: legal shape, float32, output shape = bboxes shape (B, N, 4)
TEST_F(YoloxBoundingBoxDecodeInfershape, yolox_bounding_box_decode_infershape_fp32)
{
    gert::InfershapeContextPara infershapeContextPara(
        "YoloxBoundingBoxDecode",
        {
            {{{4, 4}, {4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},         // input priors: (N, 4)
            {{{32, 4, 4}, {32, 4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input bboxes: (B, N, 4)
        },
        {
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND}, // output decoded_bboxes, shape inferred
        });
    std::vector<std::vector<int64_t>> expectOutputShape = {
        {32, 4, 4},
    };
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_SUCCESS, expectOutputShape);
}

// Test case 2: legal shape, float16, output shape = bboxes shape (B, N, 4)
TEST_F(YoloxBoundingBoxDecodeInfershape, yolox_bounding_box_decode_infershape_fp16)
{
    gert::InfershapeContextPara infershapeContextPara(
        "YoloxBoundingBoxDecode",
        {
            {{{4, 4}, {4, 4}}, ge::DT_FLOAT16, ge::FORMAT_ND},         // input priors: (N, 4)
            {{{32, 4, 4}, {32, 4, 4}}, ge::DT_FLOAT16, ge::FORMAT_ND}, // input bboxes: (B, N, 4)
        },
        {
            {{{}, {}}, ge::DT_FLOAT16, ge::FORMAT_ND}, // output decoded_bboxes, shape inferred
        });
    std::vector<std::vector<int64_t>> expectOutputShape = {
        {32, 4, 4},
    };
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_SUCCESS, expectOutputShape);
}

// Test case 3: invalid, priors is not 2D
TEST_F(YoloxBoundingBoxDecodeInfershape, yolox_bounding_box_decode_infershape_invalid_priors_rank)
{
    gert::InfershapeContextPara infershapeContextPara(
        "YoloxBoundingBoxDecode",
        {
            {{{4, 4, 4}, {4, 4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},   // input priors: 3D (invalid)
            {{{32, 4, 4}, {32, 4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input bboxes: (B, N, 4)
        },
        {
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
        });
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_FAILED);
}

// Test case 4: invalid, bboxes is not 3D
TEST_F(YoloxBoundingBoxDecodeInfershape, yolox_bounding_box_decode_infershape_invalid_bboxes_rank)
{
    gert::InfershapeContextPara infershapeContextPara(
        "YoloxBoundingBoxDecode",
        {
            {{{4, 4}, {4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input priors: (N, 4)
            {{{4, 4}, {4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input bboxes: 2D (invalid)
        },
        {
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
        });
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_FAILED);
}

// Test case 5: invalid, N mismatch between priors and bboxes
TEST_F(YoloxBoundingBoxDecodeInfershape, yolox_bounding_box_decode_infershape_invalid_n_mismatch)
{
    gert::InfershapeContextPara infershapeContextPara(
        "YoloxBoundingBoxDecode",
        {
            {{{5, 4}, {5, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},         // input priors: (5, 4), N=5
            {{{32, 4, 4}, {32, 4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input bboxes: (32, 4, 4), N=4 (mismatch)
        },
        {
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
        });
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_FAILED);
}

// Test case 6: invalid, last dim is not 4
TEST_F(YoloxBoundingBoxDecodeInfershape, yolox_bounding_box_decode_infershape_invalid_last_dim)
{
    gert::InfershapeContextPara infershapeContextPara(
        "YoloxBoundingBoxDecode",
        {
            {{{4, 3}, {4, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},         // input priors: (4, 3), last dim != 4
            {{{32, 4, 3}, {32, 4, 3}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input bboxes: (32, 4, 3), last dim != 4
        },
        {
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
        });
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_FAILED);
}

// Test case 7: invalid, dtype mismatch between priors and bboxes
TEST_F(YoloxBoundingBoxDecodeInfershape, yolox_bounding_box_decode_infershape_invalid_dtype)
{
    gert::InfershapeContextPara infershapeContextPara(
        "YoloxBoundingBoxDecode",
        {
            {{{4, 4}, {4, 4}}, ge::DT_FLOAT16, ge::FORMAT_ND},       // input priors: float16
            {{{32, 4, 4}, {32, 4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input bboxes: float32 (mismatch)
        },
        {
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
        });
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_FAILED);
}

// Test case 8: unknown rank, priors = [-2], bboxes known
// expected: SUCCESS, output shape = bboxes shape (B, N, 4)
TEST_F(YoloxBoundingBoxDecodeInfershape, yolox_bounding_box_decode_infershape_unknown_rank_priors)
{
    gert::InfershapeContextPara infershapeContextPara(
        "YoloxBoundingBoxDecode",
        {
            {{{-2}, {-2}}, ge::DT_FLOAT, ge::FORMAT_ND},             // input priors: unknown rank [-2]
            {{{32, 4, 4}, {32, 4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input bboxes: (B, N, 4)
        },
        {
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
        });
    std::vector<std::vector<int64_t>> expectOutputShape = {
        {32, 4, 4},
    };
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_SUCCESS, expectOutputShape);
}

// Test case 9: unknown rank, bboxes = [-2], priors known
// expected: SUCCESS, output shape = bboxes shape (unknown rank 传递)
TEST_F(YoloxBoundingBoxDecodeInfershape, yolox_bounding_box_decode_infershape_unknown_rank_bboxes)
{
    gert::InfershapeContextPara infershapeContextPara(
        "YoloxBoundingBoxDecode",
        {
            {{{4, 4}, {4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input priors: (N, 4)
            {{{-2}, {-2}}, ge::DT_FLOAT, ge::FORMAT_ND},     // input bboxes: unknown rank [-2]
        },
        {
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
        });
    std::vector<std::vector<int64_t>> expectOutputShape = {
        {-2},
    };
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_SUCCESS, expectOutputShape);
}

// Test case 10: unknown rank, both inputs = [-2]
// expected: SUCCESS, output shape = bboxes shape (unknown rank 传递)
TEST_F(YoloxBoundingBoxDecodeInfershape, yolox_bounding_box_decode_infershape_unknown_rank_both)
{
    gert::InfershapeContextPara infershapeContextPara(
        "YoloxBoundingBoxDecode",
        {
            {{{-2}, {-2}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input priors: unknown rank [-2]
            {{{-2}, {-2}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input bboxes: unknown rank [-2]
        },
        {
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
        });
    std::vector<std::vector<int64_t>> expectOutputShape = {
        {-2},
    };
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_SUCCESS, expectOutputShape);
}

// Test case 11: unknown dim, priors = (N, -1), bboxes known
// expected: SUCCESS (末维=4 校验跳过), output shape = bboxes shape (B, N, 4)
TEST_F(YoloxBoundingBoxDecodeInfershape, yolox_bounding_box_decode_infershape_unknown_dim_priors_last)
{
    gert::InfershapeContextPara infershapeContextPara(
        "YoloxBoundingBoxDecode",
        {
            {{{4, -1}, {4, -1}}, ge::DT_FLOAT, ge::FORMAT_ND},       // input priors: (N, -1), last dim unknown
            {{{32, 4, 4}, {32, 4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input bboxes: (B, N, 4)
        },
        {
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
        });
    std::vector<std::vector<int64_t>> expectOutputShape = {
        {32, 4, 4},
    };
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_SUCCESS, expectOutputShape);
}

// Test case 12: unknown dim, bboxes = (B, N, -1), priors known
// expected: SUCCESS (末维=4 校验跳过), output shape = bboxes shape (B, N, -1)
TEST_F(YoloxBoundingBoxDecodeInfershape, yolox_bounding_box_decode_infershape_unknown_dim_bboxes_last)
{
    gert::InfershapeContextPara infershapeContextPara(
        "YoloxBoundingBoxDecode",
        {
            {{{4, 4}, {4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},           // input priors: (N, 4)
            {{{32, 4, -1}, {32, 4, -1}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input bboxes: (B, N, -1), last dim unknown
        },
        {
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
        });
    std::vector<std::vector<int64_t>> expectOutputShape = {
        {32, 4, -1},
    };
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_SUCCESS, expectOutputShape);
}

// Test case 13: unknown dim, N 相关 dim 未知 (priors (-1, 4) + bboxes (B, -1, 4))
// expected: SUCCESS (N 一致校验跳过), output shape = bboxes shape (B, -1, 4)
TEST_F(YoloxBoundingBoxDecodeInfershape, yolox_bounding_box_decode_infershape_unknown_dim_n_skip)
{
    gert::InfershapeContextPara infershapeContextPara(
        "YoloxBoundingBoxDecode",
        {
            {{{-1, 4}, {-1, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},         // input priors: (-1, 4), N unknown
            {{{32, -1, 4}, {32, -1, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input bboxes: (B, -1, 4), N unknown
        },
        {
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
        });
    std::vector<std::vector<int64_t>> expectOutputShape = {
        {32, -1, 4},
    };
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_SUCCESS, expectOutputShape);
}

// Test case 14: unknown dim 场景下 rank 校验仍生效
// bboxes 含 unknown dim (-1)，但 priors 3D rank 非法，应 FAIL
TEST_F(YoloxBoundingBoxDecodeInfershape, yolox_bounding_box_decode_infershape_unknown_dim_rank_still_checked)
{
    gert::InfershapeContextPara infershapeContextPara(
        "YoloxBoundingBoxDecode",
        {
            {{{4, 4, 4}, {4, 4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},     // input priors: 3D (invalid rank)
            {{{32, -1, 4}, {32, -1, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input bboxes: (B, -1, 4), has unknown dim
        },
        {
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
        });
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_FAILED);
}

// Test case 15: dtype mismatch + unknown rank
// priors 为 unknown rank [-2] 且 fp16，bboxes 已知 fp32，dtype 校验仍应 FAIL
TEST_F(YoloxBoundingBoxDecodeInfershape, yolox_bounding_box_decode_infershape_unknown_rank_dtype_mismatch)
{
    gert::InfershapeContextPara infershapeContextPara(
        "YoloxBoundingBoxDecode",
        {
            {{{-2}, {-2}}, ge::DT_FLOAT16, ge::FORMAT_ND},           // input priors: unknown rank, float16
            {{{32, 4, 4}, {32, 4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input bboxes: float32 (mismatch)
        },
        {
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
        });
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_FAILED);
}
