/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file grid_sampler2_d_graph_infer.cpp
 * \brief grid_sampler2_d operator graph infer resource
 */

#include "register/op_impl_registry.h"
#include "log/log.h"

namespace ops {
using namespace ge;

static constexpr int64_t X_INDEX = 0;
static constexpr int64_t GRID_INDEX = 1;
static constexpr int64_t Y_INDEX = 0;

static ge::graphStatus InferDataTypeGridSampler2D(gert::InferDataTypeContext* context)
{
    OP_CHECK_IF(context == nullptr, OP_LOGE("GridSampler2D", "InferDataTypeContext is nullptr"),
                return ge::GRAPH_FAILED);
    OP_LOGD(context->GetNodeName(), "Begin to do InferDataTypeGridSampler2D");

    const ge::DataType xDtype = context->GetInputDataType(X_INDEX);
    const ge::DataType gridDtype = context->GetInputDataType(GRID_INDEX);
    OP_CHECK_IF(xDtype != ge::DT_FLOAT16 && xDtype != ge::DT_FLOAT,
                OP_LOGE_FOR_INVALID_DTYPE(context->GetNodeName(), "x", Ops::Base::ToString(xDtype).c_str(),
                                          "float16 or float32"),
                return ge::GRAPH_FAILED);
    const std::string dtypeMsg = Ops::Base::ToString(xDtype) + " and " + Ops::Base::ToString(gridDtype);
    OP_CHECK_IF(gridDtype != xDtype,
                OP_LOGE_FOR_INVALID_DTYPES_WITH_REASON(context->GetNodeName(), "x and grid", dtypeMsg.c_str(),
                                                       "x and grid must have the same dtype"),
                return ge::GRAPH_FAILED);

    context->SetOutputDataType(Y_INDEX, xDtype);
    OP_LOGD(context->GetNodeName(), "End to do InferDataTypeGridSampler2D");
    return ge::GRAPH_SUCCESS;
}

IMPL_OP(GridSampler2D).InferDataType(InferDataTypeGridSampler2D);
} // namespace ops
