/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License).
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

/*!
 * \file roi_align_rotated_grad_apt.cpp
 * \brief Kernel entry for roi_align_rotated_grad operator
 *
 * 入口参数顺序与 REG_OP 原型 INPUT/OUTPUT 顺序一致：x_grad, rois → y_grad，
 * 固定尾参数 workspace/tiling；ATTR 不出现在入口参数（经 TilingData 传递）。
 * 单一场景模式 SCH_MODE_SCATTER：DTYPE_X_GRAD 宏自动按 dtype 实例化
 * （float32 唯一组合），TilingKey 不枚举 dtype。
 */

#include "arch35/roi_align_rotated_grad_simt.h"

template <uint32_t schMode>
__global__ __aicore__ void roi_align_rotated_grad(GM_ADDR x_grad, GM_ADDR rois, GM_ADDR y_grad, GM_ADDR workspace,
                                                  GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(RoiAlignRotatedGradTilingData);
    GET_TILING_DATA_WITH_STRUCT(RoiAlignRotatedGradTilingData, tilingData, tiling);

    if constexpr (schMode == ROI_ALIGN_ROTATED_GRAD_TPL_SCATTER) {
        // DTYPE_X_GRAD 宏自动按 dtype 实例化（float32 唯一组合），TilingKey 不枚举 dtype
        NsRoiAlignRotatedGrad::Process<DTYPE_X_GRAD>(x_grad, rois, y_grad, &tilingData);
    }
}
