/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <gtest/gtest.h>
#include <iostream>
#include "infershape_context_faker.h"
#include "infershape_case_executor.h"

class GIoUGradInfershape : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "GIoUGradInfershape SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "GIoUGradInfershape TearDown" << std::endl; }
};

// Test: float32, N=1000
TEST_F(GIoUGradInfershape, g_io_u_grad_infershape_float32)
{
    int64_t N = 1000;
    gert::InfershapeContextPara infershapeContextPara(
        "GIoUGrad",
        {
            {{{N}, {N}}, ge::DT_FLOAT, ge::FORMAT_ND},       // dy: (N,)
            {{{4, N}, {4, N}}, ge::DT_FLOAT, ge::FORMAT_ND}, // bboxes: (4, N)
            {{{4, N}, {4, N}}, ge::DT_FLOAT, ge::FORMAT_ND}, // gtboxes: (4, N)
        },
        {
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND}, // dbboxes
            {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND}, // dgtboxes
        });
    std::vector<std::vector<int64_t>> expectOutputShape = {
        {4, N}, // dbboxes shape = (4, N)
        {4, N}, // dgtboxes shape = (4, N)
    };
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_SUCCESS, expectOutputShape);
}

// Test: float16, N=500
TEST_F(GIoUGradInfershape, g_io_u_grad_infershape_float16)
{
    int64_t N = 500;
    gert::InfershapeContextPara infershapeContextPara(
        "GIoUGrad",
        {
            {{{N}, {N}}, ge::DT_FLOAT16, ge::FORMAT_ND},       // dy: (N,)
            {{{4, N}, {4, N}}, ge::DT_FLOAT16, ge::FORMAT_ND}, // bboxes: (4, N)
            {{{4, N}, {4, N}}, ge::DT_FLOAT16, ge::FORMAT_ND}, // gtboxes: (4, N)
        },
        {
            {{{}, {}}, ge::DT_FLOAT16, ge::FORMAT_ND}, // dbboxes
            {{{}, {}}, ge::DT_FLOAT16, ge::FORMAT_ND}, // dgtboxes
        });
    std::vector<std::vector<int64_t>> expectOutputShape = {
        {4, N}, // dbboxes shape = (4, N)
        {4, N}, // dgtboxes shape = (4, N)
    };
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_SUCCESS, expectOutputShape);
}

// Negative: dy is 2D (should be 1D)
TEST_F(GIoUGradInfershape, g_io_u_grad_infershape_neg_dy_not_1d)
{
    int64_t N = 1000;
    gert::InfershapeContextPara infershapeContextPara("GIoUGrad",
                                                      {
                                                          {{{N, N}, {N, N}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                          {{{4, N}, {4, N}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                          {{{4, N}, {4, N}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                      },
                                                      {
                                                          {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                          {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                      });
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_FAILED);
}

// Negative: bboxes dim[0] != 4
TEST_F(GIoUGradInfershape, g_io_u_grad_infershape_neg_bboxes_dim0_not4)
{
    int64_t N = 1000;
    gert::InfershapeContextPara infershapeContextPara("GIoUGrad",
                                                      {
                                                          {{{N}, {N}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                          {{{3, N}, {3, N}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                          {{{4, N}, {4, N}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                      },
                                                      {
                                                          {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                          {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                      });
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_FAILED);
}

// Negative: dtype mismatch (dy=float32, bboxes=float16)
TEST_F(GIoUGradInfershape, g_io_u_grad_infershape_neg_dtype_mismatch)
{
    int64_t N = 1000;
    gert::InfershapeContextPara infershapeContextPara("GIoUGrad",
                                                      {
                                                          {{{N}, {N}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                          {{{4, N}, {4, N}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                                          {{{4, N}, {4, N}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                      },
                                                      {
                                                          {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                          {{{}, {}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                      });
    ExecuteTestCase(infershapeContextPara, ge::GRAPH_FAILED);
}
