/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file test_anchor_response_flags.cpp
 * \brief Kernel UT for anchor_response_flags operator
 */

#include "../../../op_kernel/anchor_response_flags.cpp"
#include "anchor_response_flags_tiling.h"
#include <array>
#include <vector>
#include <iostream>
#include <string>
#include <cstdint>
#include <cstdlib>
#include "gtest/gtest.h"
#include "tikicpulib.h"
#include "data_utils.h"

using namespace std;

class AnchorResponseFlagsTest : public testing::Test {
protected:
    static void SetUpTestCase()
    {
        cout << "AnchorResponseFlagsTest SetUp" << endl;
        const string cmd = "cp -rf " + dataPath + " ./";
        system(cmd.c_str());
        system("chmod -R 755 ./anchor_response_flags_data/");
    }
    static void TearDownTestCase()
    {
        cout << "AnchorResponseFlagsTest TearDown" << endl;
    }
private:
    const static std::string rootPath;
    const static std::string dataPath;
};

const std::string AnchorResponseFlagsTest::rootPath = "../../../../";
const std::string AnchorResponseFlagsTest::dataPath = rootPath + "objdetect/anchor_response_flags/tests/ut/op_kernel/anchor_response_flags_data";

TEST_F(AnchorResponseFlagsTest, test_case_float32)
{
    // Test case: YOLOv3 large target detection layer
    // gt_bboxes: [100, 4] float32, featmap_size=[60,60], strides=[2,2], num_base_anchors=9
    // output: [32400] uint8
    int32_t N = 100;
    int32_t featH = 60;
    int32_t featW = 60;
    int32_t strideH = 2;
    int32_t strideW = 2;
    int32_t numBaseAnchors = 9;
    int64_t totalAnchors = (int64_t)featH * featW * numBaseAnchors;  // 32400

    size_t xByteSize = N * 4 * sizeof(float);  // gt_bboxes
    size_t zByteSize = totalAnchors * sizeof(uint8_t);  // flags output
    size_t tiling_data_size = sizeof(AnchorResponseFlagsTilingData);
    uint32_t numBlocks = 32;  // <= 64 (ascend950 max cores)

    system("cd ./anchor_response_flags_data/ && python3 gen_data.py '(100, 4)' 'float32' '60' '60' '2' '2' '9'");
    std::string fileName = "./anchor_response_flags_data/float32_input_anchor_response_flags.bin";
    uint8_t* x = (uint8_t*)AscendC::GmAlloc(xByteSize);
    ReadFile(fileName, xByteSize, x, xByteSize);
    uint8_t* z = (uint8_t*)AscendC::GmAlloc(zByteSize);
    uint8_t* workspace = (uint8_t*)AscendC::GmAlloc(32);
    uint8_t* tiling = (uint8_t*)AscendC::GmAlloc(tiling_data_size);

    char* path_ = get_current_dir_name();
    string path(path_);

    AnchorResponseFlagsTilingData* tilingDatafromBin = reinterpret_cast<AnchorResponseFlagsTilingData*>(tiling);
    tilingDatafromBin->needCoreNum = 32;
    tilingDatafromBin->n = N;
    tilingDatafromBin->featH = featH;
    tilingDatafromBin->featW = featW;
    tilingDatafromBin->strideH = strideH;
    tilingDatafromBin->strideW = strideW;
    tilingDatafromBin->numBaseAnchors = numBaseAnchors;
    tilingDatafromBin->totalAnchors = totalAnchors;

    // TilingKey: schMode=0 (float32), is32Bit=1 (totalAnchors=32400 <= INT32_MAX)
    ICPU_SET_TILING_KEY(2);
    AscendC::SetKernelMode(KernelMode::AIV_MODE);

    auto kernelFunc0 = anchor_response_flags<0, 1>;
    ICPU_RUN_KF(kernelFunc0,
        numBlocks,
        x,
        z,
        workspace,
        (uint8_t *)(tilingDatafromBin));

    fileName = "./anchor_response_flags_data/float32_output_anchor_response_flags.bin";
    WriteFile(fileName, z, zByteSize);

    AscendC::GmFree(x);
    AscendC::GmFree(z);
    AscendC::GmFree(workspace);
    AscendC::GmFree(tiling);

    system("cd ./anchor_response_flags_data/ && python3 compare_data.py 'float32'");
    free(path_);
}

TEST_F(AnchorResponseFlagsTest, test_case_float16)
{
    // Test case: YOLOv3 medium target detection layer
    // gt_bboxes: [200, 4] float16, featmap_size=[10,10], strides=[32,32], num_base_anchors=3
    // output: [300] uint8
    int32_t N = 200;
    int32_t featH = 10;
    int32_t featW = 10;
    int32_t strideH = 32;
    int32_t strideW = 32;
    int32_t numBaseAnchors = 3;
    int64_t totalAnchors = (int64_t)featH * featW * numBaseAnchors;  // 300

    size_t xByteSize = N * 4 * sizeof(uint16_t);  // gt_bboxes float16
    size_t zByteSize = totalAnchors * sizeof(uint8_t);  // flags output
    size_t tiling_data_size = sizeof(AnchorResponseFlagsTilingData);
    uint32_t numBlocks = 1;  // small output, 1 core is enough

    system("cd ./anchor_response_flags_data/ && python3 gen_data.py '(200, 4)' 'float16' '10' '10' '32' '32' '3'");
    std::string fileName = "./anchor_response_flags_data/float16_input_anchor_response_flags.bin";
    uint8_t* x = (uint8_t*)AscendC::GmAlloc(xByteSize);
    ReadFile(fileName, xByteSize, x, xByteSize);
    uint8_t* z = (uint8_t*)AscendC::GmAlloc(zByteSize);
    uint8_t* workspace = (uint8_t*)AscendC::GmAlloc(32);
    uint8_t* tiling = (uint8_t*)AscendC::GmAlloc(tiling_data_size);

    char* path_ = get_current_dir_name();
    string path(path_);

    AnchorResponseFlagsTilingData* tilingDatafromBin = reinterpret_cast<AnchorResponseFlagsTilingData*>(tiling);
    tilingDatafromBin->needCoreNum = 1;
    tilingDatafromBin->n = N;
    tilingDatafromBin->featH = featH;
    tilingDatafromBin->featW = featW;
    tilingDatafromBin->strideH = strideH;
    tilingDatafromBin->strideW = strideW;
    tilingDatafromBin->numBaseAnchors = numBaseAnchors;
    tilingDatafromBin->totalAnchors = totalAnchors;

    // TilingKey: schMode=1 (float16), is32Bit=1 (totalAnchors=300 <= INT32_MAX)
    ICPU_SET_TILING_KEY(3);
    AscendC::SetKernelMode(KernelMode::AIV_MODE);

    auto kernelFunc1 = anchor_response_flags<1, 1>;
    ICPU_RUN_KF(kernelFunc1,
        numBlocks,
        x,
        z,
        workspace,
        (uint8_t *)(tilingDatafromBin));

    fileName = "./anchor_response_flags_data/float16_output_anchor_response_flags.bin";
    WriteFile(fileName, z, zByteSize);

    AscendC::GmFree(x);
    AscendC::GmFree(z);
    AscendC::GmFree(workspace);
    AscendC::GmFree(tiling);

    system("cd ./anchor_response_flags_data/ && python3 compare_data.py 'float16'");
    free(path_);
}
