/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file yuv4442_yuv422_graph_infer.cpp
 * \brief yuv4442_yuv422 operater graph infer resource
 */

#include "register/op_impl_registry.h"
#include "log/log.h"

namespace ops {
using namespace ge;

static constexpr int64_t IDX_0 = 0;

static ge::graphStatus InferDataTypeYuv4442yuv422(gert::InferDataTypeContext* context)
{
    OP_LOGD(context->GetNodeName(), "Begin to do InferDataTypeYuv4442yuv422");

    // Output dtype is always uint8 regardless of input dtype
    context->SetOutputDataType(IDX_0, ge::DT_UINT8);

    OP_LOGD(context->GetNodeName(), "End to do InferDataTypeYuv4442yuv422");
    return GRAPH_SUCCESS;
}

IMPL_OP(YUV4442YUV422).InferDataType(InferDataTypeYuv4442yuv422);

}; // namespace ops
