/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file roi_align_tiling.cpp
 * \brief Tiling implementation for ROIAlign operator
 *        Multi-core partition by output elements, Grid-Stride pattern
 *        TilingKey encodes pool_mode(2) x roi_end_mode(3) = 6 modes
 */

#include "log/log.h"
#include "platform/platform_ascendc.h"
#include "util/math_util.h"
#include "util/platform_util.h"
#include "op_host/tiling_util.h"
#include "op_host/tiling_templates_registry.h"
#include "../../op_kernel/arch35/roi_align_tiling_data.h"
#include "../../op_kernel/arch35/roi_align_tiling_key.h"
#include <cstring>
#include <string>

namespace optiling {

using namespace Ops::Cv::OpTiling;

constexpr int64_t PER_CORE_MIN = 1024;
constexpr int64_t WARP_SIZE = 32;
constexpr uint32_t DCACHE_SIZE = 128 * 1024;
constexpr uint32_t STATIC_UB_ESTIMATE = 0;

// Input indices
static constexpr size_t IDX_FEATURES = 0;
static constexpr size_t IDX_ROIS = 1;
static constexpr size_t IDX_ROIS_N = 2;
// Output index
static constexpr size_t IDX_OUTPUT = 0;

// Features layout: [N, C, H, W]
static constexpr size_t FEATURES_DIM_NUM = 4;
static constexpr size_t FEATURES_DIM_N = 0;
static constexpr size_t FEATURES_DIM_C = 1;
static constexpr size_t FEATURES_DIM_H = 2;
static constexpr size_t FEATURES_DIM_W = 3;

// Rois layout: [K, 5]
static constexpr size_t ROIS_DIM_NUM = 2;
static constexpr size_t ROIS_DIM_K = 0;
static constexpr size_t ROIS_DIM_COORDS = 1;
static constexpr size_t ROIS_COORDS_PER_ROI = 5;
// rois_n layout: [K]
static constexpr size_t ROIS_N_DIM_NUM = 1;
static constexpr size_t ROIS_DIM_ROIS_N_COUNT = 0;

// Attribute indices (matching REG_OP attr order)
static constexpr size_t ATTR_IDX_SPATIAL_SCALE = 0;
static constexpr size_t ATTR_IDX_POOLED_HEIGHT = 1;
static constexpr size_t ATTR_IDX_POOLED_WIDTH = 2;
static constexpr size_t ATTR_IDX_SAMPLE_NUM = 3;
static constexpr size_t ATTR_IDX_ROI_END_MODE = 4;
static constexpr size_t ATTR_IDX_POOL_MODE = 5;

// Default attribute values
static constexpr float DEFAULT_SPATIAL_SCALE = 1.0f;
static constexpr int32_t DEFAULT_POOLED_SIZE = 1;
static constexpr int32_t DEFAULT_SAMPLE_NUM = 2;
static constexpr int32_t DEFAULT_ROI_END_MODE = 1;

// User-facing roi_end_mode values
static constexpr int32_t ROI_END_MODE_OFFSET_NONE = 0;
static constexpr int32_t ROI_END_MODE_OFFSET_PLUS1 = 1;
static constexpr int32_t ROI_END_MODE_MIN = 0;
static constexpr int32_t ROI_END_MODE_MAX = 3;

// Validation bounds
static constexpr int32_t MIN_POOLED_SIZE = 1;
static constexpr int32_t MIN_NEED_CORE_NUM = 1;
static constexpr int32_t ROIS_N_PRESENT = 1;
static constexpr int32_t ROIS_N_ABSENT = 0;

// Workspace count (system workspace only)
static constexpr size_t SYS_WORKSPACE_COUNT = 1;

struct ROIAlignCompileInfo {};

static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t& ubSize, int64_t& coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ROIAlignTilingFunc(gert::TilingContext* context)
{
    uint64_t ubSize;
    int64_t maxCoreNum;
    OP_CHECK_IF(GetPlatformInfo(context, ubSize, maxCoreNum) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetPlatformInfo error"), return ge::GRAPH_FAILED);

    // Get input shapes
    auto featuresInput = context->GetInputShape(IDX_FEATURES);
    OP_CHECK_NULL_WITH_CONTEXT(context, featuresInput);
    auto roisInput = context->GetInputShape(IDX_ROIS);
    OP_CHECK_NULL_WITH_CONTEXT(context, roisInput);
    auto featuresShape = EnsureNotScalar(featuresInput->GetStorageShape());
    auto roisShape = EnsureNotScalar(roisInput->GetStorageShape());

    // README约束#1: features 必须为 4D 张量 (N, C, H, W)
    OP_CHECK_IF(featuresShape.GetDimNum() != FEATURES_DIM_NUM,
                OP_LOGE_FOR_INVALID_SHAPEDIM(context->GetNodeName(), "features",
                                             std::to_string(featuresShape.GetDimNum()).c_str(), "4D [N,C,H,W]"),
                return ge::GRAPH_FAILED);
    // README约束#2: rois 必须为 2D 张量 (K, 5)
    OP_CHECK_IF(roisShape.GetDimNum() != ROIS_DIM_NUM,
                OP_LOGE_FOR_INVALID_SHAPEDIM(context->GetNodeName(), "rois",
                                             std::to_string(roisShape.GetDimNum()).c_str(), "2D [K,5]"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(roisShape.GetDim(ROIS_DIM_COORDS) != ROIS_COORDS_PER_ROI,
                OP_LOGE_FOR_INVALID_SHAPEDIM(context->GetNodeName(), "rois",
                                             std::to_string(roisShape.GetDim(ROIS_DIM_COORDS)).c_str(), "5"),
                return ge::GRAPH_FAILED);
    // README约束#4: features 和 rois 必须使用相同 dtype (float16 或 float32)
    auto featuresTensor = context->GetInputTensor(IDX_FEATURES);
    auto roisTensor = context->GetInputTensor(IDX_ROIS);
    OP_CHECK_NULL_WITH_CONTEXT(context, featuresTensor);
    OP_CHECK_NULL_WITH_CONTEXT(context, roisTensor);
    if (featuresTensor->GetDataType() != roisTensor->GetDataType()) {
        std::string dtypeMsg = Ops::Base::ToString(featuresTensor->GetDataType()) + " and " +
                               Ops::Base::ToString(roisTensor->GetDataType());
        OP_LOGE_FOR_INVALID_DTYPES_WITH_REASON(context->GetNodeName(), "features and rois", dtypeMsg.c_str(),
                                               "features and rois must have the same dtype");
        return ge::GRAPH_FAILED;
    }
    if (featuresTensor->GetDataType() != ge::DT_FLOAT16 && featuresTensor->GetDataType() != ge::DT_FLOAT) {
        OP_LOGE_FOR_INVALID_DTYPE(context->GetNodeName(), "features",
                                  Ops::Base::ToString(featuresTensor->GetDataType()).c_str(), "FLOAT16 or FLOAT32");
        return ge::GRAPH_FAILED;
    }
    auto outputShape = context->GetOutputShape(IDX_OUTPUT);
    OP_CHECK_NULL_WITH_CONTEXT(context, outputShape);

    int64_t cDim = featuresShape.GetDim(FEATURES_DIM_C);
    int64_t hDim = featuresShape.GetDim(FEATURES_DIM_H);
    int64_t wDim = featuresShape.GetDim(FEATURES_DIM_W);
    int64_t kDim = roisShape.GetDim(ROIS_DIM_K);
    int64_t C = cDim;
    int64_t H = hDim;
    int64_t W = wDim;
    int64_t K = kDim;
    // Get attributes by index (matching REG_OP attr order):
    const gert::RuntimeAttrs* attrs = context->GetAttrs();
    OP_CHECK_NULL_WITH_CONTEXT(context, attrs);
    const float* spatialScalePtr = attrs->GetFloat(ATTR_IDX_SPATIAL_SCALE);
    const int64_t* pooledHPtr = attrs->GetInt(ATTR_IDX_POOLED_HEIGHT);
    const int64_t* pooledWPtr = attrs->GetInt(ATTR_IDX_POOLED_WIDTH);
    const int64_t* sampleNumPtr = attrs->GetInt(ATTR_IDX_SAMPLE_NUM);
    OP_CHECK_IF(*pooledHPtr > INT32_MAX,
                OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "pooled_height", std::to_string(*pooledHPtr).c_str(),
                                          "<= INT32_MAX"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(*pooledWPtr > INT32_MAX,
                OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "pooled_width", std::to_string(*pooledWPtr).c_str(),
                                          "<= INT32_MAX"),
                return ge::GRAPH_FAILED);
    OP_CHECK_IF(*sampleNumPtr > std::sqrt(INT32_MAX),
                OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "sample_num", std::to_string(*sampleNumPtr).c_str(),
                                          "<= sqrt(INT32_MAX)"),
                return ge::GRAPH_FAILED);
    const int64_t* roiEndModePtr = attrs->GetInt(ATTR_IDX_ROI_END_MODE);
    const char* poolModeStr = attrs->GetStr(ATTR_IDX_POOL_MODE);

    float spatialScale = (spatialScalePtr != nullptr) ? *spatialScalePtr : DEFAULT_SPATIAL_SCALE;
    int32_t pooledH = (pooledHPtr != nullptr) ? static_cast<int32_t>(*pooledHPtr) : DEFAULT_POOLED_SIZE;
    int32_t pooledW = (pooledWPtr != nullptr) ? static_cast<int32_t>(*pooledWPtr) : DEFAULT_POOLED_SIZE;
    int32_t sampleNum = (sampleNumPtr != nullptr) ? static_cast<int32_t>(*sampleNumPtr) : DEFAULT_SAMPLE_NUM;
    int32_t roiEndMode = (roiEndModePtr != nullptr) ? static_cast<int32_t>(*roiEndModePtr) : DEFAULT_ROI_END_MODE;
    // SE约束: pool_mode 必须为 "avg" 或 "max"
    OP_CHECK_IF(poolModeStr != nullptr && strcmp(poolModeStr, "avg") != 0 && strcmp(poolModeStr, "max") != 0,
                OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "pool_mode", poolModeStr, "\"avg\" or \"max\""),
                return ge::GRAPH_FAILED);
    int32_t poolMode = (poolModeStr != nullptr && strcmp(poolModeStr, "max") == 0) ? ROI_ALIGN_POOL_MAX :
                                                                                     ROI_ALIGN_POOL_AVG;
    // SE约束: sample_num 必须 >= 0
    OP_CHECK_IF(
        sampleNum < 0,
        OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "sample_num", std::to_string(sampleNum).c_str(), ">= 0"),
        return ge::GRAPH_FAILED);
    // SE约束: roi_end_mode 取值范围为 {0, 1, 2, 3}
    OP_CHECK_IF(roiEndMode < ROI_END_MODE_MIN || roiEndMode > ROI_END_MODE_MAX,
                OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "roi_end_mode", std::to_string(roiEndMode).c_str(),
                                          "0, 1, 2 or 3"),
                return ge::GRAPH_FAILED);

    // README约束#5: pooled_height 和 pooled_width 必须 >= 1
    OP_CHECK_IF(
        pooledH < MIN_POOLED_SIZE,
        OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "pooled_height", std::to_string(pooledH).c_str(), ">= 1"),
        return ge::GRAPH_FAILED);
    OP_CHECK_IF(
        pooledW < MIN_POOLED_SIZE,
        OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "pooled_width", std::to_string(pooledW).c_str(), ">= 1"),
        return ge::GRAPH_FAILED);
    // README约束#6: spatial_scale 必须 > 0
    OP_CHECK_IF(spatialScale <= 0.0f,
                OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "spatial_scale",
                                                      std::to_string(spatialScale).c_str(), "must be > 0"),
                return ge::GRAPH_FAILED);

    // Check optional input rois_n
    int32_t hasRoisN = ROIS_N_ABSENT;
    auto roisNInput = context->GetInputShape(IDX_ROIS_N);
    if (roisNInput != nullptr) {
        auto roisNStorageShape = roisNInput->GetStorageShape();
        if (roisNStorageShape.GetDimNum() > 0 && roisNStorageShape.GetDim(ROIS_DIM_ROIS_N_COUNT) > 0) {
            OP_CHECK_IF(roisNStorageShape.GetDimNum() != ROIS_N_DIM_NUM,
                        OP_LOGE_FOR_INVALID_SHAPEDIM(context->GetNodeName(), "rois_n",
                                                     std::to_string(roisNStorageShape.GetDimNum()).c_str(), "1D [K]"),
                        return ge::GRAPH_FAILED);
            auto roisNTensor = context->GetInputTensor(IDX_ROIS_N);
            OP_CHECK_NULL_WITH_CONTEXT(context, roisNTensor);
            OP_CHECK_IF(roisNTensor->GetDataType() != ge::DT_INT32,
                        OP_LOGE_FOR_INVALID_DTYPE(context->GetNodeName(), "rois_n",
                                                  Ops::Base::ToString(roisNTensor->GetDataType()).c_str(), "INT32"),
                        return ge::GRAPH_FAILED);
            OP_CHECK_IF(roisNStorageShape.GetDim(ROIS_DIM_ROIS_N_COUNT) != K,
                        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(
                            context->GetNodeName(), "rois_n",
                            std::to_string(roisNStorageShape.GetDim(ROIS_DIM_ROIS_N_COUNT)).c_str(),
                            "rois_n count must equal rois K"),
                        return ge::GRAPH_FAILED);
            hasRoisN = ROIS_N_PRESENT;
        }
    }

    // Compute total output elements
    int64_t totalElements = K * C * pooledH * pooledW;
    int32_t idxMode = (totalElements > INT32_MAX) ? ROI_ALIGN_IDX_INT64 : ROI_ALIGN_IDX_INT32;
    // Multi-core partition (two-step method)
    int64_t perCoreElements = (totalElements > 0) ? Ops::Base::CeilDiv(totalElements, maxCoreNum) : 0;
    if (perCoreElements > 0 && perCoreElements < PER_CORE_MIN) {
        perCoreElements = PER_CORE_MIN;
    }
    if (perCoreElements > 0) {
        perCoreElements = ((perCoreElements + WARP_SIZE - 1) / WARP_SIZE) * WARP_SIZE;
    }
    int64_t needCoreNum = (totalElements > 0) ? Ops::Base::CeilDiv(totalElements, perCoreElements) : MIN_NEED_CORE_NUM;

    // Fill tiling data
    ROIAlignTilingData* tiling = context->GetTilingData<ROIAlignTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(memset_s(tiling, sizeof(ROIAlignTilingData), 0, sizeof(ROIAlignTilingData)) != EOK,
                OP_LOGE(context, "memset_s tiling data error"), return ge::GRAPH_FAILED);

    tiling->totalElements = totalElements;
    tiling->needCoreNum = static_cast<int32_t>(needCoreNum);
    tiling->channels = C;
    tiling->height = H;
    tiling->width = W;
    tiling->pooledHeight = pooledH;
    tiling->pooledWidth = pooledW;
    tiling->sampleNum = sampleNum;
    tiling->spatialScale = spatialScale;
    tiling->hasRoisN = hasRoisN;

    context->SetBlockDim(static_cast<uint32_t>(needCoreNum));

    // Set tiling key based on pool_mode and roi_end_mode
    uint32_t schModeVal;
    if (roiEndMode == ROI_END_MODE_OFFSET_NONE) {
        schModeVal = ROI_ALIGN_MODE_0;
    } else if (roiEndMode == ROI_END_MODE_OFFSET_PLUS1) {
        schModeVal = ROI_ALIGN_MODE_1;
    } else {
        schModeVal = ROI_ALIGN_MODE_2;
    }
    uint32_t poolKey = static_cast<uint32_t>(poolMode);
    uint32_t idxKey = static_cast<uint32_t>(idxMode);
    uint64_t tilingKey = GET_TPL_TILING_KEY(poolKey, schModeVal, idxKey);
    context->SetTilingKey(tilingKey);

    // Workspace (mandatory GetWorkspaceSizes(1) for system workspace)
    size_t* ws = context->GetWorkspaceSizes(SYS_WORKSPACE_COUNT);
    OP_CHECK_NULL_WITH_CONTEXT(context, ws);
    ws[0] = 0;

    // Set local memory size
    OP_CHECK_IF((ubSize <= DCACHE_SIZE + STATIC_UB_ESTIMATE),
                OP_LOGE(context, "ubSize %lu <= DCACHE_SIZE + STATIC_UB_ESTIMATE", ubSize), return ge::GRAPH_FAILED);
    auto res = context->SetLocalMemorySize(static_cast<uint32_t>(ubSize - DCACHE_SIZE - STATIC_UB_ESTIMATE));
    OP_CHECK_IF((res != ge::GRAPH_SUCCESS), OP_LOGE(context, "SetLocalMemorySize failed"), return ge::GRAPH_FAILED);

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForROIAlign([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_OPTILING(ROIAlign).Tiling(ROIAlignTilingFunc).TilingParse<ROIAlignCompileInfo>(TilingParseForROIAlign);
} // namespace optiling
