/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file roi_align_grad_apt.cpp
 * \brief Kernel entry for roi_align_grad operator
 *
 * Template parameter:
 *   schMode (uint32_t): ROI end mode (0-3), encoded in tiling key.
 */

#include "arch35/roi_align_grad_simt.h"

template <uint32_t schMode>
__global__ __aicore__ void roi_align_grad(GM_ADDR ydiff, GM_ADDR rois, GM_ADDR rois_n, GM_ADDR xdiff, GM_ADDR workspace,
                                          GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(ROIAlignGradTilingData);
    GET_TILING_DATA_WITH_STRUCT(ROIAlignGradTilingData, tilingData, tiling);

    if constexpr (schMode == ROI_END_MODE_0) {
        NsROIAlignGrad::Process<float, ROI_END_MODE_0>(ydiff, rois, rois_n, xdiff, &tilingData);
    } else if constexpr (schMode == ROI_END_MODE_1) {
        NsROIAlignGrad::Process<float, ROI_END_MODE_1>(ydiff, rois, rois_n, xdiff, &tilingData);
    } else if constexpr (schMode == ROI_END_MODE_2) {
        NsROIAlignGrad::Process<float, ROI_END_MODE_2>(ydiff, rois, rois_n, xdiff, &tilingData);
    } else if constexpr (schMode == ROI_END_MODE_3) {
        NsROIAlignGrad::Process<float, ROI_END_MODE_3>(ydiff, rois, rois_n, xdiff, &tilingData);
    }
}
