/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file yolox_bounding_box_decode_infershape.cpp
 * \brief Infershape implementation for yolox_bounding_box_decode operator
 */
#include "register/op_impl_registry.h"
#include "log/log.h"
#include "op_common/op_host/util/shape_util.h"

using namespace ge;

namespace ops {
static constexpr int64_t IDX_0 = 0;
static constexpr int64_t IDX_1 = 1;
static constexpr size_t PRIORS_RANK = 2;
static constexpr size_t BBOXES_RANK = 3;
static constexpr size_t BBOXES_LAST_DIM_INDEX = 2;
static constexpr int64_t BOX_PARAM_NUM = 4;

static ge::graphStatus InferShapeYoloxBoundingBoxDecode(gert::InferShapeContext* context)
{
    OP_LOGD(context->GetNodeName(), "Begin to do InferShapeYoloxBoundingBoxDecode");

    const gert::Shape* priorsShape = context->GetInputShape(IDX_0);
    OP_CHECK_NULL_WITH_CONTEXT(context, priorsShape);
    const gert::Shape* bboxesShape = context->GetInputShape(IDX_1);
    OP_CHECK_NULL_WITH_CONTEXT(context, bboxesShape);

    gert::Shape* yShape = context->GetOutputShape(IDX_0);
    OP_CHECK_NULL_WITH_CONTEXT(context, yShape);

    const auto* priorsDesc = context->GetInputDesc(IDX_0);
    OP_CHECK_NULL_WITH_CONTEXT(context, priorsDesc);
    const auto* bboxesDesc = context->GetInputDesc(IDX_1);
    OP_CHECK_NULL_WITH_CONTEXT(context, bboxesDesc);
    if (priorsDesc->GetDataType() != bboxesDesc->GetDataType()) {
        OP_LOGE(context, "priors.dtype must equal bboxes.dtype, only same-dtype supported");
        return GRAPH_FAILED;
    }

    *yShape = *bboxesShape;

    // Unknown rank is propagated through the output shape.
    if (Ops::Base::IsUnknownRank(*priorsShape) || Ops::Base::IsUnknownRank(*bboxesShape)) {
        OP_LOGD(context->GetNodeName(),
                "input shape has unknown rank, skip rank/dim validation (output = bboxes shape)");
        return GRAPH_SUCCESS;
    }

    const bool priorsHasUnknownDim = Ops::Base::IsUnknownShape(*priorsShape);
    const bool bboxesHasUnknownDim = Ops::Base::IsUnknownShape(*bboxesShape);

    if (priorsShape->GetDimNum() != PRIORS_RANK || bboxesShape->GetDimNum() != BBOXES_RANK) {
        OP_LOGE(context, "priors rank must be 2, bboxes rank must be 3, got %zu/%zu", priorsShape->GetDimNum(),
                bboxesShape->GetDimNum());
        return GRAPH_FAILED;
    }
    if (!priorsHasUnknownDim && !bboxesHasUnknownDim && priorsShape->GetDim(0) != bboxesShape->GetDim(1)) {
        OP_LOGE(context, "priors[0] must equal bboxes[1], got %ld vs %ld", priorsShape->GetDim(0),
                bboxesShape->GetDim(1));
        return GRAPH_FAILED;
    }
    if (!priorsHasUnknownDim && priorsShape->GetDim(1) != BOX_PARAM_NUM) {
        OP_LOGE(context, "last dim must be 4, priors[1]=%ld", priorsShape->GetDim(1));
        return GRAPH_FAILED;
    }
    if (!bboxesHasUnknownDim && bboxesShape->GetDim(BBOXES_LAST_DIM_INDEX) != BOX_PARAM_NUM) {
        OP_LOGE(context, "last dim must be 4, bboxes[2]=%ld", bboxesShape->GetDim(BBOXES_LAST_DIM_INDEX));
        return GRAPH_FAILED;
    }

    OP_LOGD(context->GetNodeName(), "End to do InferShapeYoloxBoundingBoxDecode");
    return GRAPH_SUCCESS;
}

IMPL_OP_INFERSHAPE(YoloxBoundingBoxDecode).InferShape(InferShapeYoloxBoundingBoxDecode);
} // namespace ops
