/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file img_warp_resize_infershape.cpp
 * \brief InferShape implementation for img_warp_resize operator
 *
 * Output shape: [N, C, H, W] derived from img [N, 4, C, H, W].
 * Output dtype: same as img dtype (handled by framework).
 * Supports unknownshape (-1, per-dim) and unknownrank (-2, whole shape).
 */

#include "register/op_impl_registry.h"
#include "log/log.h"
#include "op_common/op_host/util/shape_util.h"

using namespace ge;

namespace ops {
static constexpr int64_t IDX_0 = 0;
static constexpr int64_t IDX_1 = 1;
static constexpr int64_t UNKNOWN_DIM = -1;

static inline bool BothKnownAndNotEqual(int64_t a, int64_t b) { return a != UNKNOWN_DIM && b != UNKNOWN_DIM && a != b; }

static ge::graphStatus InferShapeIMGWarpResize(gert::InferShapeContext* context)
{
    OP_LOGD(context->GetNodeName(), "Begin to do InferShapeIMGWarpResize");

    const gert::Shape* imgShape = context->GetInputShape(IDX_0);
    OP_CHECK_NULL_WITH_CONTEXT(context, imgShape);
    const gert::Shape* warpIndexShape = context->GetInputShape(IDX_1);
    OP_CHECK_NULL_WITH_CONTEXT(context, warpIndexShape);

    gert::Shape* warpImgShape = context->GetOutputShape(IDX_0);
    OP_CHECK_NULL_WITH_CONTEXT(context, warpImgShape);

    // -2 unknownrank: if either input is unknownrank, output is unknownrank
    if (Ops::Base::IsUnknownRank(*imgShape) || Ops::Base::IsUnknownRank(*warpIndexShape)) {
        OP_LOGD(context->GetNodeName(), "input is UnknownRank, set output as UnknownRank");
        Ops::Base::SetUnknownRank(*warpImgShape);
        return GRAPH_SUCCESS;
    }

    // Validate img is 5D [N, 4, C, H, W]
    OP_CHECK_IF(imgShape->GetDimNum() != 5, OP_LOGE(context, "img must be 5D, got %zu dims", imgShape->GetDimNum()),
                return GRAPH_FAILED);
    // Validate warp_index is 4D [N, 2, H, W]
    OP_CHECK_IF(warpIndexShape->GetDimNum() != 4,
                OP_LOGE(context, "warp_index must be 4D, got %zu dims", warpIndexShape->GetDimNum()),
                return GRAPH_FAILED);

    // Validate img.shape[1] == 4 (four corners), skip when -1
    OP_CHECK_IF(imgShape->GetDim(1) != UNKNOWN_DIM && imgShape->GetDim(1) != 4,
                OP_LOGE(context, "img.shape[1] must be 4, got %ld", imgShape->GetDim(1)), return GRAPH_FAILED);
    // Validate warp_index.shape[1] == 2 (x, y coordinates), skip when -1
    OP_CHECK_IF(warpIndexShape->GetDim(1) != UNKNOWN_DIM && warpIndexShape->GetDim(1) != 2,
                OP_LOGE(context, "warp_index.shape[1] must be 2, got %ld", warpIndexShape->GetDim(1)),
                return GRAPH_FAILED);

    // Validate N/H/W consistency between img and warp_index, skip when either is -1
    OP_CHECK_IF(BothKnownAndNotEqual(imgShape->GetDim(0), warpIndexShape->GetDim(0)),
                OP_LOGE(context, "N mismatch: img=%ld, warp_index=%ld", imgShape->GetDim(0), warpIndexShape->GetDim(0)),
                return GRAPH_FAILED);
    OP_CHECK_IF(BothKnownAndNotEqual(imgShape->GetDim(3), warpIndexShape->GetDim(2)),
                OP_LOGE(context, "H mismatch: img=%ld, warp_index=%ld", imgShape->GetDim(3), warpIndexShape->GetDim(2)),
                return GRAPH_FAILED);
    OP_CHECK_IF(BothKnownAndNotEqual(imgShape->GetDim(4), warpIndexShape->GetDim(3)),
                OP_LOGE(context, "W mismatch: img=%ld, warp_index=%ld", imgShape->GetDim(4), warpIndexShape->GetDim(3)),
                return GRAPH_FAILED);

    // Output shape: [N, C, H, W], -1 propagated naturally
    warpImgShape->SetDimNum(4);
    warpImgShape->SetDim(0, imgShape->GetDim(0)); // N
    warpImgShape->SetDim(1, imgShape->GetDim(2)); // C
    warpImgShape->SetDim(2, imgShape->GetDim(3)); // H
    warpImgShape->SetDim(3, imgShape->GetDim(4)); // W

    OP_LOGD(context->GetNodeName(), "End to do InferShapeIMGWarpResize");
    return GRAPH_SUCCESS;
}

IMPL_OP_INFERSHAPE(IMGWarpResize).InferShape(InferShapeIMGWarpResize);
} // namespace ops
