/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <iostream>
#include <gtest/gtest.h>
#include "tiling_context_faker.h"
#include "tiling_case_executor.h"
#include "../../../../op_kernel/arch35/upsample_bilinear2d_grad_tiling_data.h"

using namespace std;
using namespace ge;

class UpsampleBilinear2dGradTiling : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "UpsampleBilinear2dGradTiling SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "UpsampleBilinear2dGradTiling TearDown" << std::endl; }
};

TEST_F(UpsampleBilinear2dGradTiling, fp32_noalign)
{
    struct UpsampleBilinear2dGradCompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "UpsampleBilinear2dGrad",
        {
            {{{1, 1, 4, 4}, {1, 1, 4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},
        },
        {
            {{{1, 1, 2, 2}, {1, 1, 2, 2}}, ge::DT_FLOAT, ge::FORMAT_ND},
        },
        {
            gert::TilingContextPara::OpAttr("output_size", Ops::Cv::AnyValue::CreateFrom(std::vector<int64_t>{4, 4})),
            gert::TilingContextPara::OpAttr("input_size",
                                            Ops::Cv::AnyValue::CreateFrom(std::vector<int64_t>{1, 1, 2, 2})),
            gert::TilingContextPara::OpAttr("align_corners", Ops::Cv::AnyValue::CreateFrom(false)),
            gert::TilingContextPara::OpAttr("scales_h", Ops::Cv::AnyValue::CreateFrom(0.0f)),
            gert::TilingContextPara::OpAttr("scales_w", Ops::Cv::AnyValue::CreateFrom(0.0f)),
        },
        &compileInfo, "Ascend950", 64, 262144, 4096);
    uint64_t expectTilingKey = 3;
    string expectTilingData = "16 4 4294967297 8589934594 17179869188 4539628425446424576 0 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

TEST_F(UpsampleBilinear2dGradTiling, fp16_align)
{
    struct UpsampleBilinear2dGradCompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "UpsampleBilinear2dGrad",
        {
            {{{1, 1, 4, 4}, {1, 1, 4, 4}}, ge::DT_FLOAT16, ge::FORMAT_ND},
        },
        {
            {{{1, 1, 2, 2}, {1, 1, 2, 2}}, ge::DT_FLOAT16, ge::FORMAT_ND},
        },
        {
            gert::TilingContextPara::OpAttr("output_size", Ops::Cv::AnyValue::CreateFrom(std::vector<int64_t>{4, 4})),
            gert::TilingContextPara::OpAttr("input_size",
                                            Ops::Cv::AnyValue::CreateFrom(std::vector<int64_t>{1, 1, 2, 2})),
            gert::TilingContextPara::OpAttr("align_corners", Ops::Cv::AnyValue::CreateFrom(true)),
            gert::TilingContextPara::OpAttr("scales_h", Ops::Cv::AnyValue::CreateFrom(0.0f)),
            gert::TilingContextPara::OpAttr("scales_w", Ops::Cv::AnyValue::CreateFrom(0.0f)),
        },
        &compileInfo, "Ascend950", 64, 262144, 4096);
    uint64_t expectTilingKey = 0;
    string expectTilingData = "16 4 4294967297 8589934594 17179869188 4515609228859845291 1 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}
