/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software; you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the License).
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file test_roi_align_rotated_grad_tiling.cpp
 * \brief Tiling UT for roi_align_rotated_grad operator
 */

#include <iostream>
#include <map>
#include <string>
#include <vector>
#include <gtest/gtest.h>
#include "any_value.h"
#include "tiling_context_faker.h"
#include "tiling_case_executor.h"
#include "../../../../op_kernel/arch35/roi_align_rotated_grad_tiling_data.h"

using namespace std;
using namespace ge;

class RoiAlignRotatedGradTiling : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "RoiAlignRotatedGradTiling SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "RoiAlignRotatedGradTiling TearDown" << std::endl; }
};

std::map<std::string, std::string> soc_version_infos = {{"Short_SoC_version", "Ascend950"}};

// 用例1：常规场景 float32（唯一 dtype 组合）
// x_grad[10,2,2,6] + rois[6,10] + y_grad_shape=[5,8,8,6]，pooled 2x2，scale 0.0625，ratio 1，aligned/clockwise 开
// expectTilingData 13 段按 int64 内存解释：
//   needCoreNum=64 batchSize=5 height=8 width=8 channelNum=6 roiNum=10 pooledHeight=2 pooledWidth=2
//   samplingRatio=1 segsPerRow=1 totalUnits=320
//   第12段 = spatialScale(0.0625f 位模式 0x3D800000) 低32位 | aligned=1 高32位 = 5326766080
//   第13段 = clockwise=1（尾部 padding 为 0）
TEST_F(RoiAlignRotatedGradTiling, roi_align_rotated_grad_tiling_0)
{
    struct RoiAlignRotatedGradCompileInfoUT {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "RoiAlignRotatedGrad",
        {
            {{{10, 2, 2, 6}, {10, 2, 2, 6}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input x_grad [N, PH, PW, C]
            {{{6, 10}, {6, 10}}, ge::DT_FLOAT, ge::FORMAT_ND},             // input rois [6, N]
        },
        {
            {{{5, 8, 8, 6}, {5, 8, 8, 6}}, ge::DT_FLOAT, ge::FORMAT_ND}, // output y_grad [B, H, W, C]
        },
        {
            // attrs（顺序与 def.cpp 声明一致）
            gert::TilingContextPara::OpAttr("y_grad_shape",
                                            Ops::Cv::AnyValue::CreateFrom<std::vector<int64_t>>({5, 8, 8, 6})),
            gert::TilingContextPara::OpAttr("pooled_h", Ops::Cv::AnyValue::CreateFrom<int64_t>(2)),
            gert::TilingContextPara::OpAttr("pooled_w", Ops::Cv::AnyValue::CreateFrom<int64_t>(2)),
            gert::TilingContextPara::OpAttr("spatial_scale", Ops::Cv::AnyValue::CreateFrom<float>(0.0625f)),
            gert::TilingContextPara::OpAttr("sampling_ratio", Ops::Cv::AnyValue::CreateFrom<int64_t>(1)),
            gert::TilingContextPara::OpAttr("aligned", Ops::Cv::AnyValue::CreateFrom<bool>(true)),
            gert::TilingContextPara::OpAttr("clockwise", Ops::Cv::AnyValue::CreateFrom<bool>(true)),
        },
        &compileInfo, "Ascend950",
        64,     // number of cores obtained in the tiling phase
        262144, // the ubsize obtained in the tiling phase
        4096);  // specifies the maximum size of the tiling data in the tiling phase
    uint64_t expectTilingKey = 0;
    string expectTilingData = "64 5 8 8 6 10 2 2 1 1 320 5326766080 1 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

// 用例2：稠密采样 + aligned/clockwise 关闭
// x_grad[3,1,1,4] + rois[6,3] + y_grad_shape=[2,4,4,4]，pooled 1x1，scale 1.0，ratio 0（稠密），aligned/clockwise 关
// segsPerRow=ceil(4/32)=1，totalUnits=2*4*4*1=32，needCoreNum=min(64,32)=32
// 第12段 = spatialScale(1.0f 位模式 0x3F800000) | aligned=0 = 1065353216
// 第13段 = clockwise=0
TEST_F(RoiAlignRotatedGradTiling, roi_align_rotated_grad_tiling_1)
{
    struct RoiAlignRotatedGradCompileInfoUT {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "RoiAlignRotatedGrad",
        {
            {{{3, 1, 1, 4}, {3, 1, 1, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input x_grad [N, PH, PW, C]
            {{{6, 3}, {6, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},             // input rois [6, N]
        },
        {
            {{{2, 4, 4, 4}, {2, 4, 4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // output y_grad [B, H, W, C]
        },
        {
            gert::TilingContextPara::OpAttr("y_grad_shape",
                                            Ops::Cv::AnyValue::CreateFrom<std::vector<int64_t>>({2, 4, 4, 4})),
            gert::TilingContextPara::OpAttr("pooled_h", Ops::Cv::AnyValue::CreateFrom<int64_t>(1)),
            gert::TilingContextPara::OpAttr("pooled_w", Ops::Cv::AnyValue::CreateFrom<int64_t>(1)),
            gert::TilingContextPara::OpAttr("spatial_scale", Ops::Cv::AnyValue::CreateFrom<float>(1.0f)),
            gert::TilingContextPara::OpAttr("sampling_ratio", Ops::Cv::AnyValue::CreateFrom<int64_t>(0)),
            gert::TilingContextPara::OpAttr("aligned", Ops::Cv::AnyValue::CreateFrom<bool>(false)),
            gert::TilingContextPara::OpAttr("clockwise", Ops::Cv::AnyValue::CreateFrom<bool>(false)),
        },
        &compileInfo, "Ascend950",
        64,     // number of cores obtained in the tiling phase
        262144, // the ubsize obtained in the tiling phase
        4096);  // specifies the maximum size of the tiling data in the tiling phase
    uint64_t expectTilingKey = 0;
    string expectTilingData = "32 2 4 4 4 3 1 1 0 1 32 1065353216 0 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

// 用例3：空 ROI 边界（N=0，totalUnits 正常，roiNum=0）
// x_grad[0,2,2,6] + rois[6,0] + y_grad_shape=[5,8,8,6]
// needCoreNum=min(64,320)=64，roiNum=0（kernel VF 循环无 ROI 贡献，输出全零）
TEST_F(RoiAlignRotatedGradTiling, roi_align_rotated_grad_tiling_2)
{
    struct RoiAlignRotatedGradCompileInfoUT {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "RoiAlignRotatedGrad",
        {
            {{{0, 2, 2, 6}, {0, 2, 2, 6}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input x_grad（空 N）
            {{{6, 0}, {6, 0}}, ge::DT_FLOAT, ge::FORMAT_ND},             // input rois（空 N）
        },
        {
            {{{5, 8, 8, 6}, {5, 8, 8, 6}}, ge::DT_FLOAT, ge::FORMAT_ND}, // output y_grad
        },
        {
            gert::TilingContextPara::OpAttr("y_grad_shape",
                                            Ops::Cv::AnyValue::CreateFrom<std::vector<int64_t>>({5, 8, 8, 6})),
            gert::TilingContextPara::OpAttr("pooled_h", Ops::Cv::AnyValue::CreateFrom<int64_t>(2)),
            gert::TilingContextPara::OpAttr("pooled_w", Ops::Cv::AnyValue::CreateFrom<int64_t>(2)),
            gert::TilingContextPara::OpAttr("spatial_scale", Ops::Cv::AnyValue::CreateFrom<float>(0.0625f)),
            gert::TilingContextPara::OpAttr("sampling_ratio", Ops::Cv::AnyValue::CreateFrom<int64_t>(1)),
            gert::TilingContextPara::OpAttr("aligned", Ops::Cv::AnyValue::CreateFrom<bool>(true)),
            gert::TilingContextPara::OpAttr("clockwise", Ops::Cv::AnyValue::CreateFrom<bool>(true)),
        },
        &compileInfo, "Ascend950", 64, 262144, 4096);
    uint64_t expectTilingKey = 0;
    string expectTilingData = "64 5 8 8 6 0 2 2 1 1 320 5326766080 1 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

// 用例4：约束校验失败场景——x_grad 与 pooled_h/pooled_w 不匹配（C4 违反，期望 GRAPH_FAILED）
TEST_F(RoiAlignRotatedGradTiling, roi_align_rotated_grad_tiling_invalid_shape)
{
    struct RoiAlignRotatedGradCompileInfoUT {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "RoiAlignRotatedGrad",
        {
            {{{10, 3, 2, 6}, {10, 3, 2, 6}}, ge::DT_FLOAT, ge::FORMAT_ND}, // x_grad dim1=3 != pooled_h=2
            {{{6, 10}, {6, 10}}, ge::DT_FLOAT, ge::FORMAT_ND},
        },
        {
            {{{5, 8, 8, 6}, {5, 8, 8, 6}}, ge::DT_FLOAT, ge::FORMAT_ND},
        },
        {
            gert::TilingContextPara::OpAttr("y_grad_shape",
                                            Ops::Cv::AnyValue::CreateFrom<std::vector<int64_t>>({5, 8, 8, 6})),
            gert::TilingContextPara::OpAttr("pooled_h", Ops::Cv::AnyValue::CreateFrom<int64_t>(2)),
            gert::TilingContextPara::OpAttr("pooled_w", Ops::Cv::AnyValue::CreateFrom<int64_t>(2)),
            gert::TilingContextPara::OpAttr("spatial_scale", Ops::Cv::AnyValue::CreateFrom<float>(0.0625f)),
            gert::TilingContextPara::OpAttr("sampling_ratio", Ops::Cv::AnyValue::CreateFrom<int64_t>(1)),
            gert::TilingContextPara::OpAttr("aligned", Ops::Cv::AnyValue::CreateFrom<bool>(true)),
            gert::TilingContextPara::OpAttr("clockwise", Ops::Cv::AnyValue::CreateFrom<bool>(true)),
        },
        &compileInfo, "Ascend950", 64, 262144, 4096);
    uint64_t expectTilingKey = 0;
    string expectTilingData = "";
    std::vector<size_t> expectWorkspaces = {};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_FAILED, expectTilingKey, expectTilingData, expectWorkspaces);
}
