/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <iostream>
#include <gtest/gtest.h>
#include "tiling_context_faker.h"
#include "tiling_case_executor.h"
#include "../../../../op_kernel/arch35/upsample_nearest2d_grad_tiling_data.h"

using namespace std;
using namespace ge;

class UpsampleNearest2dGradTiling : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "UpsampleNearest2dGradTiling SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "UpsampleNearest2dGradTiling TearDown" << std::endl; }
};

TEST_F(UpsampleNearest2dGradTiling, upsample_nearest2d_grad_fp32)
{
    struct UpsampleNearest2dGradCompileInfo {
    } compileInfo;
    // grad_output: [1, 1, 4, 4] float32
    // grad_input:  [1, 1, 2, 2] float32
    // attrs: output_size=[4,4], input_size=[1,1,2,2], scales_h=0.0, scales_w=0.0
    std::vector<gert::TilingContextPara::OpAttr> attrs = {
        {"output_size", Ops::Cv::AnyValue::CreateFrom(std::vector<int64_t>{4, 4})},
        {"input_size", Ops::Cv::AnyValue::CreateFrom(std::vector<int64_t>{1, 1, 2, 2})},
        {"scales_h", Ops::Cv::AnyValue::CreateFrom(0.0f)},
        {"scales_w", Ops::Cv::AnyValue::CreateFrom(0.0f)}};
    gert::TilingContextPara tilingContextPara(
        "UpsampleNearest2dGrad",
        {
            {{{1, 1, 4, 4}, {1, 1, 4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // grad_output
        },
        {
            {{{1, 1, 2, 2}, {1, 1, 2, 2}}, ge::DT_FLOAT, ge::FORMAT_ND}, // grad_input
        },
        attrs, &compileInfo, "Ascend950",
        64,     // number of cores
        262144, // ubsize
        4096);  // max tiling data size
    uint64_t expectTilingKey = 0;
    // Tiling data is read as int64_t values. Struct layout:
    // [int32 needCoreNum | pad] [int64 totalElements] [int32 dimN | int32 dimC] [int32 dimHin | int32 dimWin]
    // [int32 dimHout | int32 dimWout] [float scaleH | float scaleW]
    string expectTilingData = "1 4 4294967297 8589934594 17179869188 4611686019501129728 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

TEST_F(UpsampleNearest2dGradTiling, upsample_nearest2d_grad_fp16)
{
    struct UpsampleNearest2dGradCompileInfo {
    } compileInfo;
    // grad_output: [1, 64, 64, 64] float16
    // grad_input:  [1, 64, 32, 32] float16
    // attrs: output_size=[64,64], input_size=[1,64,32,32], scales_h=0.0, scales_w=0.0
    std::vector<gert::TilingContextPara::OpAttr> attrs = {
        {"output_size", Ops::Cv::AnyValue::CreateFrom(std::vector<int64_t>{64, 64})},
        {"input_size", Ops::Cv::AnyValue::CreateFrom(std::vector<int64_t>{1, 64, 32, 32})},
        {"scales_h", Ops::Cv::AnyValue::CreateFrom(0.0f)},
        {"scales_w", Ops::Cv::AnyValue::CreateFrom(0.0f)}};
    gert::TilingContextPara tilingContextPara(
        "UpsampleNearest2dGrad",
        {
            {{{1, 64, 64, 64}, {1, 64, 64, 64}}, ge::DT_FLOAT16, ge::FORMAT_ND}, // grad_output
        },
        {
            {{{1, 64, 32, 32}, {1, 64, 32, 32}}, ge::DT_FLOAT16, ge::FORMAT_ND}, // grad_input
        },
        attrs, &compileInfo, "Ascend950", 64, 262144, 4096);
    uint64_t expectTilingKey = 0;
    // totalElements = 64*32*32 = 65536, perCoreElements = ceil(65536/64)=1024, align32=1024, needCoreNum=64
    // scaleH = 64/32 = 2.0, scaleW = 64/32 = 2.0
    // Tiling data as int64_t: [needCoreNum|pad] [totalElements] [dimN|dimC] [dimHin|dimWin] [dimHout|dimWout]
    // [scaleH|scaleW]
    string expectTilingData = "64 65536 274877906945 137438953504 274877907008 4611686019501129728 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

// Negative: dimHin=0 (input_size=[1,1,0,2])
TEST_F(UpsampleNearest2dGradTiling, upsample_nearest2d_grad_neg_dimHin_zero)
{
    struct UpsampleNearest2dGradCompileInfo {
    } compileInfo;
    std::vector<gert::TilingContextPara::OpAttr> attrs = {
        {"output_size", Ops::Cv::AnyValue::CreateFrom(std::vector<int64_t>{4, 4})},
        {"input_size", Ops::Cv::AnyValue::CreateFrom(std::vector<int64_t>{1, 1, 0, 2})},
        {"scales_h", Ops::Cv::AnyValue::CreateFrom(0.0f)},
        {"scales_w", Ops::Cv::AnyValue::CreateFrom(0.0f)}};
    gert::TilingContextPara tilingContextPara("UpsampleNearest2dGrad",
                                              {
                                                  {{{1, 1, 4, 4}, {1, 1, 4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{1, 1, 0, 2}, {1, 1, 0, 2}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              attrs, &compileInfo, "Ascend950", 64, 262144, 4096);
    ExecuteTestCase(tilingContextPara, ge::GRAPH_FAILED);
}

// Negative: dimC=0 (input_size=[1,0,2,2])
TEST_F(UpsampleNearest2dGradTiling, upsample_nearest2d_grad_neg_dimC_zero)
{
    struct UpsampleNearest2dGradCompileInfo {
    } compileInfo;
    std::vector<gert::TilingContextPara::OpAttr> attrs = {
        {"output_size", Ops::Cv::AnyValue::CreateFrom(std::vector<int64_t>{4, 4})},
        {"input_size", Ops::Cv::AnyValue::CreateFrom(std::vector<int64_t>{1, 0, 2, 2})},
        {"scales_h", Ops::Cv::AnyValue::CreateFrom(0.0f)},
        {"scales_w", Ops::Cv::AnyValue::CreateFrom(0.0f)}};
    gert::TilingContextPara tilingContextPara("UpsampleNearest2dGrad",
                                              {
                                                  {{{1, 1, 4, 4}, {1, 1, 4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{1, 0, 2, 2}, {1, 0, 2, 2}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              attrs, &compileInfo, "Ascend950", 64, 262144, 4096);
    ExecuteTestCase(tilingContextPara, ge::GRAPH_FAILED);
}

// Negative: dimHout=0 (output_size=[0,4])
TEST_F(UpsampleNearest2dGradTiling, upsample_nearest2d_grad_neg_dimHout_zero)
{
    struct UpsampleNearest2dGradCompileInfo {
    } compileInfo;
    std::vector<gert::TilingContextPara::OpAttr> attrs = {
        {"output_size", Ops::Cv::AnyValue::CreateFrom(std::vector<int64_t>{0, 4})},
        {"input_size", Ops::Cv::AnyValue::CreateFrom(std::vector<int64_t>{1, 1, 2, 2})},
        {"scales_h", Ops::Cv::AnyValue::CreateFrom(0.0f)},
        {"scales_w", Ops::Cv::AnyValue::CreateFrom(0.0f)}};
    gert::TilingContextPara tilingContextPara("UpsampleNearest2dGrad",
                                              {
                                                  {{{1, 1, 0, 4}, {1, 1, 0, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{1, 1, 2, 2}, {1, 1, 2, 2}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              attrs, &compileInfo, "Ascend950", 64, 262144, 4096);
    ExecuteTestCase(tilingContextPara, ge::GRAPH_FAILED);
}
