/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <iostream>
#include <gtest/gtest.h>
#include "tiling_context_faker.h"
#include "tiling_case_executor.h"
#include "../../../../op_kernel/arch35/upsample_bicubic2d_tiling_data.h"

using namespace std;
using namespace ge;

class UpsampleBicubic2dTiling : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "UpsampleBicubic2dTiling SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "UpsampleBicubic2dTiling TearDown" << std::endl; }
};

std::map<std::string, std::string> soc_version_infos = {{"Short_SoC_version", "Ascend950"}};

TEST_F(UpsampleBicubic2dTiling, upsample_bicubic2d_float32_align_false)
{
    struct UpsampleBicubic2dCompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "UpsampleBicubic2d",
        {
            {{{1, 1, 4, 4}, {1, 1, 4, 4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // input x
        },
        {
            {{{1, 1, 8, 8}, {1, 1, 8, 8}}, ge::DT_FLOAT, ge::FORMAT_ND}, // output y
        },
        {
            gert::TilingContextPara::OpAttr(
                "output_size", Ops::Cv::AnyValue::CreateFrom<std::vector<int64_t>>(std::vector<int64_t>{8, 8})),
            gert::TilingContextPara::OpAttr("align_corners", Ops::Cv::AnyValue::CreateFrom<bool>(false)),
            gert::TilingContextPara::OpAttr("scales_h", Ops::Cv::AnyValue::CreateFrom<float>(0.0f)),
            gert::TilingContextPara::OpAttr("scales_w", Ops::Cv::AnyValue::CreateFrom<float>(0.0f)),
        },
        &compileInfo, "Ascend950",
        64,                       // number of cores
        262144,                   // ub size
        4096);                    // tiling data max size
    uint64_t expectTilingKey = 0; // ALIGN_CORNERS_FALSE
    string expectTilingData = "1 64 17179869185 34359738372 4539628424389459976 1056964608 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

TEST_F(UpsampleBicubic2dTiling, upsample_bicubic2d_float16_align_true)
{
    struct UpsampleBicubic2dCompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "UpsampleBicubic2d",
        {
            {{{2, 3, 4, 4}, {2, 3, 4, 4}}, ge::DT_FLOAT16, ge::FORMAT_ND}, // input x
        },
        {
            {{{2, 3, 8, 8}, {2, 3, 8, 8}}, ge::DT_FLOAT16, ge::FORMAT_ND}, // output y
        },
        {
            gert::TilingContextPara::OpAttr(
                "output_size", Ops::Cv::AnyValue::CreateFrom<std::vector<int64_t>>(std::vector<int64_t>{8, 8})),
            gert::TilingContextPara::OpAttr("align_corners", Ops::Cv::AnyValue::CreateFrom<bool>(true)),
            gert::TilingContextPara::OpAttr("scales_h", Ops::Cv::AnyValue::CreateFrom<float>(0.0f)),
            gert::TilingContextPara::OpAttr("scales_w", Ops::Cv::AnyValue::CreateFrom<float>(0.0f)),
        },
        &compileInfo, "Ascend950",
        64,                       // number of cores
        262144,                   // ub size
        4096);                    // tiling data max size
    uint64_t expectTilingKey = 1; // ALIGN_CORNERS_TRUE
    string expectTilingData = "1 384 17179869190 34359738372 4529334482997608456 1054567863 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}
