#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ----------------------------------------------------------------------------

# Generated By CANNBot

import numpy as np
import torch

__spec__ = {
    "rotated_feature_align": "RotatedFeatureAlignTestSpec",
}


def _load_mmcv_op():
    try:
        from mmcv.ops import rotated_feature_align
    except Exception as exc:
        raise RuntimeError(
            f"rotated_feature_align requires mmcv>=1.5.1 with ops compiled. "
            f"Import failed: {exc!r}. "
            f"See https://mmcv.readthedocs.io/en/latest/get_started/installation.html"
        ) from exc
    return rotated_feature_align


# Per-request layout cache: transpose chain materializes once per bboxes.
_layout_cache = {}


def _bilinear_interpolate_sim(x, y, x_, height, width):
    hf, wf = float(height), float(width)
    oob = (y < -1.0) | (y > hf) | (x_ < -1.0) | (x_ > wf)
    zero_y = torch.zeros_like(y)
    zero_x = torch.zeros_like(x_)
    y = torch.fmax(y, zero_y)
    x_ = torch.fmax(x_, zero_x)
    y_low = torch.floor(y)
    x_low = torch.floor(x_)
    y_sat = y_low >= (hf - 1.0)
    x_sat = x_low >= (wf - 1.0)
    y_low_f = torch.where(y_sat, torch.full_like(y_low, hf - 1.0), y_low)
    x_low_f = torch.where(x_sat, torch.full_like(x_low, wf - 1.0), x_low)
    y_high_f = torch.where(y_sat, y_low_f, y_low_f + 1.0)
    x_high_f = torch.where(x_sat, x_low_f, x_low_f + 1.0)
    y_eff = torch.where(y_sat, y_low_f, y)
    x_eff = torch.where(x_sat, x_low_f, x_)
    ly = y_eff - y_low_f
    lx = x_eff - x_low_f
    hy = 1.0 - ly
    hx = 1.0 - lx
    yli = y_low_f.long().clamp(0, height - 1)
    yhi = y_high_f.long().clamp(0, height - 1)
    xli = x_low_f.long().clamp(0, width - 1)
    xhi = x_high_f.long().clamp(0, width - 1)
    n_idx = torch.arange(x.shape[0], device=x.device)[:, None, None, None]
    c_idx = torch.arange(x.shape[1], device=x.device)[None, :, None, None]
    yli4 = yli[:, None, :, :]
    yhi4 = yhi[:, None, :, :]
    xli4 = xli[:, None, :, :]
    xhi4 = xhi[:, None, :, :]
    v1 = x[n_idx, c_idx, yli4, xli4]
    v2 = x[n_idx, c_idx, yli4, xhi4]
    v3 = x[n_idx, c_idx, yhi4, xli4]
    v4 = x[n_idx, c_idx, yhi4, xhi4]
    w1 = (hy * hx).unsqueeze(1)
    w2 = (hy * lx).unsqueeze(1)
    w3 = (ly * hx).unsqueeze(1)
    w4 = (ly * lx).unsqueeze(1)
    res = w1 * v1 + w2 * v2 + w3 * v3 + w4 * v4
    res = torch.where(oob.unsqueeze(1), torch.zeros_like(res), res)
    return res


def _safe_mmcv_rotated_feature_align(x, bboxes_mmcv, spatial_scale, points):
    rotated_feature_align = _load_mmcv_op()
    finite_params = torch.isfinite(bboxes_mmcv)
    if points == 1:
        safe_params = finite_params[..., 0] & finite_params[..., 1]
    else:
        safe_params = finite_params.all(dim=-1)
    unsafe_pos = ~safe_params  # (N,H,W)
    has_unsafe = bool(unsafe_pos.any())
    if has_unsafe:
        safe_bboxes = torch.where(
            finite_params, bboxes_mmcv, torch.zeros_like(bboxes_mmcv)
        )
    else:
        safe_bboxes = bboxes_mmcv
    result = rotated_feature_align(
        x,
        safe_bboxes,
        spatial_scale=float(spatial_scale),
        points=int(points),
    )
    if has_unsafe:
        scale = float(spatial_scale)
        height, width = int(x.shape[-2]), int(x.shape[-1])
        x_sim = x.float() if x.dtype != torch.float32 else x
        bboxes_f32 = (
            bboxes_mmcv.float() if bboxes_mmcv.dtype != torch.float32 else bboxes_mmcv
        )
        roi_y = bboxes_f32[..., 0] * scale
        roi_x = bboxes_f32[..., 1] * scale
        sim_out = x_sim + _bilinear_interpolate_sim(x_sim, roi_y, roi_x, height, width)
        if points == 5:
            w2 = bboxes_f32[..., 2] * scale * 0.5
            h2 = bboxes_f32[..., 3] * scale * 0.5
            cosa = torch.cos(bboxes_f32[..., 4])
            sina = torch.sin(bboxes_f32[..., 4])
            wx, wy = cosa * w2, sina * w2
            hx, hy = -sina * h2, cosa * h2
            for py, px in (
                (roi_y + wy + hy, roi_x + wx + hx),
                (roi_y - wy + hy, roi_x - wx + hx),
                (roi_y - wy - hy, roi_x - wx - hx),
                (roi_y + wy - hy, roi_x + wx - hx),
            ):
                sim_out = sim_out + _bilinear_interpolate_sim(
                    x_sim, py, px, height, width
                )
        sim_out = sim_out.to(result.dtype)
        result = torch.where(unsafe_pos.unsqueeze(1), sim_out, result)
    return result


def _rotated_feature_align_impl(x, bboxes, spatial_scale, points):
    if points not in (1, 5):
        raise ValueError(f"points must be 1 or 5, got {points}")
    result = _safe_mmcv_rotated_feature_align(
        x,
        bboxes.transpose(1, 2).transpose(2, 3).contiguous(),
        spatial_scale,
        points,
    )
    return result


class RotatedFeatureAlignTestSpec:
    @staticmethod
    def golden(x, bboxes, spatial_scale, points=1, **kwargs):
        x_t = torch.from_numpy(np.ascontiguousarray(x))
        bboxes_t = torch.from_numpy(np.ascontiguousarray(bboxes))
        result = _rotated_feature_align_impl(
            x_t, bboxes_t, float(spatial_scale), int(points)
        )
        return [result.detach().cpu().numpy()]

    class ThirdPartyImpl:
        def __init__(self, bboxes, spatial_scale, points=1, **kwargs):
            self.spatial_scale = float(spatial_scale)
            self.points = int(points)
            key = (bboxes.data_ptr(), tuple(bboxes.shape), str(bboxes.device))
            cached = _layout_cache.get(key)
            if cached is None:
                cached = bboxes.transpose(1, 2).transpose(2, 3).contiguous()
                _layout_cache[key] = cached
            self._bboxes_mmcv = cached

        def __call__(self, x, bboxes, **kwargs):
            return [
                _safe_mmcv_rotated_feature_align(
                    x, self._bboxes_mmcv, self.spatial_scale, self.points
                )
            ]

    class MmcvImpl:
        def __init__(self, bboxes, spatial_scale, points=1, **kwargs):
            self.spatial_scale = float(spatial_scale)
            self.points = int(points)
            key = (bboxes.data_ptr(), tuple(bboxes.shape), str(bboxes.device))
            cached = _layout_cache.get(key)
            if cached is None:
                cached = bboxes.transpose(1, 2).transpose(2, 3).contiguous()
                _layout_cache[key] = cached
            self._bboxes_mmcv = cached

        def __call__(self, x, bboxes, **kwargs):
            return [
                _safe_mmcv_rotated_feature_align(
                    x, self._bboxes_mmcv, self.spatial_scale, self.points
                )
            ]

    third_party = {"torch": ThirdPartyImpl, "mmcv": MmcvImpl}
    tolerance = {
        "float32": {"standard": "cross_check", "level": "L1"},
    }
