/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file resize_grad_tiling_data.h
 * \brief resize grad tiling data
 */

#ifndef RESIZE_GRAD_TILING_DATA_H
#define RESIZE_GRAD_TILING_DATA_H

#include <cstdint>

struct ResizeGradTilingData {
    int64_t lenN = 0;
    int64_t lenC = 0; // channel 维 C
    int64_t lenSrcH = 0;
    int64_t lenSrcW = 0;
    int64_t lenDstH = 0;
    int64_t lenDstW = 0;
    int64_t yTotal = 0;         // y 元素总数
    int64_t useCoreNum = 0;     // 实际启动核数
    int64_t coreFactor = 0;     // 每核基础元素数
    int64_t coreTailFactor = 0; // 余数核数
    int64_t format = 0;
    int64_t alignCorners = 0;
    float scaleH = 0.0f;
    float scaleW = 0.0f; // W 向缩放比
    float inverseScaleH = 0.0f;
    float inverseScaleW = 0.0f;
    float scaleH0 = 0.0f;
    float scaleH1 = 0.0f;
    float scaleH2 = 0.0f;
    float scaleW0 = 0.0f;
    float scaleW1 = 0.0f;
    float scaleW2 = 0.0f;
};

#endif
