/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file resize_grad_copy.h
 * \brief resize grad copy
 */

#ifndef RESIZE_GRAD_COPY_H
#define RESIZE_GRAD_COPY_H

#include "resize_grad_simt_base.h"
#include "resize_grad_tiling_data.h"

namespace NsResizeGrad {
using namespace AscendC;

template <typename T, typename T_IDX>
__simt_callee__ __aicore__ __attribute__((always_inline)) inline void SimtCopyCompute(__gm__ T* grads, __gm__ T* y,
                                                                                      T_IDX coreFactor,
                                                                                      T_IDX coreOffset)
{
    for (T_IDX idx = static_cast<T_IDX>(threadIdx.x); idx < coreFactor; idx += static_cast<T_IDX>(blockDim.x)) {
        y[coreOffset + idx] = grads[coreOffset + idx];
    }
}

template <typename T, typename T_IDX>
__simt_vf__ __aicore__ __launch_bounds__(COPY_THREAD_NUM) inline void ResizeGradCopySimt(__gm__ T* grads, __gm__ T* y,
                                                                                         T_IDX coreFactor,
                                                                                         T_IDX coreOffset)
{
    SimtCopyCompute<T, T_IDX>(grads, y, coreFactor, coreOffset);
}

template <typename T, typename T_IDX>
__aicore__ inline void ProcessCopy(GM_ADDR grads, GM_ADDR y, const ResizeGradTilingData* tilingData)
{
    const T_IDX coreIdx = static_cast<T_IDX>(GetBlockIdx());
    if (coreIdx >= static_cast<T_IDX>(tilingData->useCoreNum)) {
        return;
    }
    T_IDX coreFactor = static_cast<T_IDX>(tilingData->coreFactor) +
                       (coreIdx < static_cast<T_IDX>(tilingData->coreTailFactor) ? 1 : 0);
    T_IDX coreOffset = coreIdx * static_cast<T_IDX>(tilingData->coreFactor) +
                       (coreIdx < static_cast<T_IDX>(tilingData->coreTailFactor) ?
                            coreIdx :
                            static_cast<T_IDX>(tilingData->coreTailFactor));

    asc_vf_call<ResizeGradCopySimt<T, T_IDX>>(dim3(COPY_THREAD_NUM), (__gm__ T*)grads, (__gm__ T*)y, coreFactor,
                                              coreOffset);
}

} // namespace NsResizeGrad

#endif
