/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file yolo_proto.h
 * \brief
 */
#ifndef OPS_OP_PROTO_INC_YOLO_H_
#define OPS_OP_PROTO_INC_YOLO_H_

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
 *@brief Yolo operator: parse detection results from yolo network output.
 *@par Inputs:
 *One input, including:
 * x: A NCHW Tensor with shape (N, C, H, W), where C = boxes*(coords+1+classes).
 *    Must be one of the following types: float16, float32. \n

 *@par Outputs:
 *Three outputs, including:
 * @li coord_data: A 3D Tensor with shape (N, boxes*coords, H*W). Must be one of the following types: float16, float32.
 * @li obj_prob: A 2D Tensor with shape (N, boxes*H*W). Must be one of the following types: float16, float32.
 * @li classes_prob: A 3D Tensor with shape (N, classes, boxes*H*W). Must be one of the following types: float16,
 float32. \n

 *@par Attributes:
 * @li boxes: An optional int, the number of anchor boxes, default value is 3.
 * @li coords: An optional int, the number of coordinate values per box, default value is 4.
 * @li classes: An optional int, the number of object classes, default value is 80.
 * @li yolo_version: An optional string, the yolo network version, default value is "V3".
 * @li softmax: An optional bool, whether apply softmax on classes_prob, default value is false.
 * @li background: An optional bool, whether the classes include background, default value is false.
 * @li softmaxtree: An optional bool, whether apply softmaxtree, default value is false. \n

 *@par Third-party framework compatibility
 *Compatible with the Yolo operator in darknet.
 */
REG_OP(Yolo)
    .INPUT(x, TensorType({DT_FLOAT16, DT_FLOAT}))
    .OUTPUT(coord_data, TensorType({DT_FLOAT16, DT_FLOAT}))
    .OUTPUT(obj_prob, TensorType({DT_FLOAT16, DT_FLOAT}))
    .OUTPUT(classes_prob, TensorType({DT_FLOAT16, DT_FLOAT}))
    .ATTR(boxes, Int, 3)
    .ATTR(coords, Int, 4)
    .ATTR(classes, Int, 80)
    .ATTR(yolo_version, String, "V3")
    .ATTR(softmax, Bool, false)
    .ATTR(background, Bool, false)
    .ATTR(softmaxtree, Bool, false)
    .OP_END_FACTORY_REG(Yolo)

} // namespace ge

#endif // OPS_OP_PROTO_INC_YOLO_H_
