/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file img_warp_resize_proto.h
 * \brief REG_OP definition for IMGWarpResize operator
 */

#ifndef OPS_OP_PROTO_INC_IMG_WARP_RESIZE_H_
#define OPS_OP_PROTO_INC_IMG_WARP_RESIZE_H_

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
*@brief Resizes "images" with "offset" using bilinear interpolation. \n

*@par Inputs:
*@li img: input image, A 5-D tensor of shape `[n, 4, c, h, w]`,
and 4 mean input[(h_top, w_left), (h_top, w_right), (h_bottom, w_left),
(h_bottom, w_right)]. Must be one of the following types: float16, float32.
The format support ND.
*@li warp_index: the resize offset A 4-D float tensor of shape `[n, 2, h, w]`,
2 means (x, y) for resize point. The format support ND. Must be the type float32.

*@par Outputs:
*warp_img: A Tensor after ResizeBilinear, A 4-D tensor of shape `[n, c, h, w]`.
The format support ND. Must be one of the following types: float16, float32.
Must has the same type as "img". \n
*/

REG_OP(IMGWarpResize)
    .INPUT(img, TensorType({DT_FLOAT16, DT_FLOAT32}))
    .INPUT(warp_index, TensorType({DT_FLOAT32}))
    .OUTPUT(warp_img, TensorType({DT_FLOAT16, DT_FLOAT32}))
    .OP_END_FACTORY_REG(IMGWarpResize)

} // namespace ge

#endif // OPS_OP_PROTO_INC_IMG_WARP_RESIZE_H_
