/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <iostream>
#include <gtest/gtest.h>
#include "tiling_context_faker.h"
#include "tiling_case_executor.h"
#include "any_value.h"
#include "../../../../op_kernel/arch35/d_io_u_grad_tiling_data.h"
#include "../../../../op_kernel/arch35/d_io_u_grad_tiling_key.h"

using namespace std;
using namespace ge;

class DIoUGradTiling : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "DIoUGradTiling SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "DIoUGradTiling TearDown" << std::endl; }
};

static gert::TilingContextPara::OpAttr MakeBoolAttr(const std::string& name, bool val)
{
    return gert::TilingContextPara::OpAttr(name, Ops::Cv::AnyValue::CreateFrom<bool>(val));
}

static gert::TilingContextPara::OpAttr MakeStrAttr(const std::string& name, const std::string& val)
{
    return gert::TilingContextPara::OpAttr(name, Ops::Cv::AnyValue::CreateFrom<std::string>(val));
}

TEST_F(DIoUGradTiling, d_io_u_grad_float32)
{
    struct DIoUGradCompileInfo {
    } compileInfo;
    std::vector<gert::TilingContextPara::OpAttr> attrs = {
        MakeBoolAttr("trans", true),
        MakeBoolAttr("is_cross", false),
        MakeStrAttr("mode", "iou"),
    };
    gert::TilingContextPara tilingContextPara("DIoUGrad",
                                              {
                                                  {{{100}, {100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{4, 100}, {4, 100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{4, 100}, {4, 100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{4, 100}, {4, 100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{4, 100}, {4, 100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              attrs, &compileInfo, "Ascend950", 64, 262144, 4096);
    uint64_t expectTilingKey = 5;
    string expectTilingData = "429496729601 1 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

// Negative: dy is 2D (should be 1D)
TEST_F(DIoUGradTiling, d_io_u_grad_neg_dy_not_1d)
{
    struct DIoUGradCompileInfo {
    } compileInfo;
    std::vector<gert::TilingContextPara::OpAttr> attrs = {
        MakeBoolAttr("trans", false),
        MakeBoolAttr("is_cross", false),
        MakeStrAttr("mode", "iou"),
    };
    gert::TilingContextPara tilingContextPara("DIoUGrad",
                                              {
                                                  {{{100, 100}, {100, 100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{4, 100}, {4, 100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{4, 100}, {4, 100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{4, 100}, {4, 100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{4, 100}, {4, 100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              attrs, &compileInfo, "Ascend950", 64, 262144, 4096);
    ExecuteTestCase(tilingContextPara, ge::GRAPH_FAILED);
}

// Negative: is_cross=true (not supported)
TEST_F(DIoUGradTiling, d_io_u_grad_neg_is_cross_true)
{
    struct DIoUGradCompileInfo {
    } compileInfo;
    std::vector<gert::TilingContextPara::OpAttr> attrs = {
        MakeBoolAttr("trans", false),
        MakeBoolAttr("is_cross", true),
        MakeStrAttr("mode", "iou"),
    };
    gert::TilingContextPara tilingContextPara("DIoUGrad",
                                              {
                                                  {{{100}, {100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{4, 100}, {4, 100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{4, 100}, {4, 100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{4, 100}, {4, 100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{4, 100}, {4, 100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              attrs, &compileInfo, "Ascend950", 64, 262144, 4096);
    ExecuteTestCase(tilingContextPara, ge::GRAPH_FAILED);
}

// Negative: mode="iof" (not supported)
TEST_F(DIoUGradTiling, d_io_u_grad_neg_mode_iof)
{
    struct DIoUGradCompileInfo {
    } compileInfo;
    std::vector<gert::TilingContextPara::OpAttr> attrs = {
        MakeBoolAttr("trans", false),
        MakeBoolAttr("is_cross", false),
        MakeStrAttr("mode", "iof"),
    };
    gert::TilingContextPara tilingContextPara("DIoUGrad",
                                              {
                                                  {{{100}, {100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{4, 100}, {4, 100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{4, 100}, {4, 100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{4, 100}, {4, 100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{4, 100}, {4, 100}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              attrs, &compileInfo, "Ascend950", 64, 262144, 4096);
    ExecuteTestCase(tilingContextPara, ge::GRAPH_FAILED);
}

TEST_F(DIoUGradTiling, d_io_u_grad_large_n)
{
    struct DIoUGradCompileInfo {
    } compileInfo;
    std::vector<gert::TilingContextPara::OpAttr> attrs = {
        MakeBoolAttr("trans", false),
        MakeBoolAttr("is_cross", false),
        MakeStrAttr("mode", "iou"),
    };
    gert::TilingContextPara tilingContextPara("DIoUGrad",
                                              {
                                                  {{{100000}, {100000}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{4, 100000}, {4, 100000}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{4, 100000}, {4, 100000}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{4, 100000}, {4, 100000}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{4, 100000}, {4, 100000}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              attrs, &compileInfo, "Ascend950", 64, 262144, 4096);
    uint64_t expectTilingKey = 0;
    string expectTilingData = "429496729600064 0 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

TEST_F(DIoUGradTiling, d_io_u_grad_float16_small)
{
    struct DIoUGradCompileInfo {
    } compileInfo;
    std::vector<gert::TilingContextPara::OpAttr> attrs = {
        MakeBoolAttr("trans", true),
        MakeBoolAttr("is_cross", false),
        MakeStrAttr("mode", "iou"),
    };
    gert::TilingContextPara tilingContextPara("DIoUGrad",
                                              {
                                                  {{{8}, {8}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                                  {{{4, 8}, {4, 8}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                                  {{{4, 8}, {4, 8}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{4, 8}, {4, 8}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                                  {{{4, 8}, {4, 8}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                              },
                                              attrs, &compileInfo, "Ascend950", 64, 262144, 4096);
    uint64_t expectTilingKey = 5;
    string expectTilingData = "34359738369 1 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}
