/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/**
 * @file test_geir_grid_sampler2_d.cpp
 * @brief GE IR graph-mode calling example for GridSampler2D on arch35.
 *
 * Builds and executes a single-node graph that samples the four corner
 * pixels of a 2x2 float32 input. With align_corners enabled, the output is
 * expected to equal the input tensor.
 */

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <ctime>
#include <map>
#include <string>
#include <vector>

#include "ge_api.h"
#include "ge_api_types.h"
#include "ge_error_codes.h"
#include "graph.h"
#include "array_ops.h"
#include "tensor.h"
#include "types.h"

#include "../../op_graph/grid_sampler2_d_proto.h"

#define FAILED (-1)
#define SUCCESS 0

using namespace ge;
using std::string;
using std::vector;

static string GetTime()
{
    time_t timep;
    time(&timep);
    char tmp[64];
    strftime(tmp, sizeof(tmp), "%Y-%m-%d %H:%M:%S", localtime(&timep));
    return tmp;
}

static Tensor MakeFloatTensor(const vector<int64_t>& shape, Format format, const vector<float>& data)
{
    TensorDesc desc(ge::Shape(shape), format, DT_FLOAT);
    desc.SetPlacement(ge::kPlacementHost);
    desc.SetFormat(format);
    desc.SetRealDimCnt(shape.size());
    Tensor tensor(desc);
    tensor.SetData(reinterpret_cast<const uint8_t*>(data.data()), data.size() * sizeof(float));
    return tensor;
}

static bool CheckOutput(const Tensor& output, const vector<float>& expected)
{
    if (output.GetSize() != expected.size() * sizeof(float) || output.GetData() == nullptr) {
        return false;
    }
    const float* actual = reinterpret_cast<const float*>(output.GetData());
    for (size_t i = 0; i < expected.size(); ++i) {
        printf("  output[%zu] = %.6f, expected = %.6f\n", i, actual[i], expected[i]);
        if (std::fabs(actual[i] - expected[i]) > 1e-4f) {
            return false;
        }
    }
    return true;
}

int main()
{
    const vector<int64_t> xShape = {1, 1, 2, 2};
    const vector<int64_t> gridShape = {1, 2, 2, 2};
    const vector<float> xData = {1.0f, 2.0f, 3.0f, 4.0f};
    const vector<float> gridData = {
        -1.0f, -1.0f, 1.0f, -1.0f, -1.0f, 1.0f, 1.0f, 1.0f,
    };

    printf("%s - INFO - [GEIR]: Initialize GE\n", GetTime().c_str());
    std::map<AscendString, AscendString> globalOptions = {
        {"ge.exec.deviceId", "0"},
        {"ge.graphRunMode", "1"},
    };
    Status ret = ge::GEInitialize(globalOptions);
    if (ret != SUCCESS) {
        printf("%s - ERROR - [GEIR]: GEInitialize failed\n", GetTime().c_str());
        return FAILED;
    }

    Graph graph("grid_sampler2_d_geir_graph");
    auto x = op::Data("x").set_attr_index(0);
    TensorDesc xDesc(ge::Shape(xShape), FORMAT_NCHW, DT_FLOAT);
    xDesc.SetPlacement(ge::kPlacementHost);
    x.update_input_desc_x(xDesc);

    auto grid = op::Data("grid").set_attr_index(1);
    TensorDesc gridDesc(ge::Shape(gridShape), FORMAT_NHWC, DT_FLOAT);
    gridDesc.SetPlacement(ge::kPlacementHost);
    grid.update_input_desc_x(gridDesc);

    auto gridSampler2D = op::GridSampler2D("grid_sampler2_d");
    gridSampler2D.set_input_x(x);
    gridSampler2D.set_input_grid(grid);
    gridSampler2D.set_attr_interpolation_mode("bilinear");
    gridSampler2D.set_attr_padding_mode("zeros");
    gridSampler2D.set_attr_align_corners(true);
    gridSampler2D.update_input_desc_x(xDesc);
    gridSampler2D.update_input_desc_grid(gridDesc);
    TensorDesc outputDesc(ge::Shape(xShape), FORMAT_NCHW, DT_FLOAT);
    gridSampler2D.update_output_desc_y(outputDesc);

    graph.SetInputs({x, grid}).SetOutputs({gridSampler2D});

    std::map<AscendString, AscendString> buildOptions;
    ge::Session* session = new Session(buildOptions);
    if (session == nullptr) {
        printf("%s - ERROR - [GEIR]: Create Session failed\n", GetTime().c_str());
        ge::GEFinalize();
        return FAILED;
    }

    constexpr uint32_t graphId = 0;
    std::map<AscendString, AscendString> graphOptions;
    ret = session->AddGraph(graphId, graph, graphOptions);
    if (ret != SUCCESS) {
        printf("%s - ERROR - [GEIR]: AddGraph failed: %s\n", GetTime().c_str(), ge::GEGetErrorMsgV2().GetString());
        delete session;
        ge::GEFinalize();
        return FAILED;
    }

    vector<Tensor> inputs = {
        MakeFloatTensor(xShape, FORMAT_NCHW, xData),
        MakeFloatTensor(gridShape, FORMAT_NHWC, gridData),
    };
    vector<Tensor> outputs;
    printf("%s - INFO - [GEIR]: RunGraph\n", GetTime().c_str());
    ret = session->RunGraph(graphId, inputs, outputs);
    if (ret != SUCCESS) {
        printf("%s - ERROR - [GEIR]: RunGraph failed: %s\n", GetTime().c_str(), ge::GEGetErrorMsgV2().GetString());
        delete session;
        ge::GEFinalize();
        return FAILED;
    }

    bool passed = outputs.size() == 1 && CheckOutput(outputs[0], xData);
    printf("%s - INFO - [GEIR]: GridSampler2D graph-mode example %s\n", GetTime().c_str(),
           passed ? "PASSED" : "FAILED");

    delete session;
    ret = ge::GEFinalize();
    if (ret != SUCCESS) {
        printf("%s - ERROR - [GEIR]: GEFinalize failed\n", GetTime().c_str());
        return FAILED;
    }
    return passed ? SUCCESS : FAILED;
}
