/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <iostream>
#include <gtest/gtest.h>
#include "tiling_context_faker.h"
#include "tiling_case_executor.h"
#include "any_value.h"
#include "../../../op_kernel/arch35/dilation2_d_backprop_filter_tiling_data.h"

using namespace std;
using namespace ge;

class Dilation2DBackpropFilterTiling : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "Dilation2DBackpropFilterTiling SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "Dilation2DBackpropFilterTiling TearDown" << std::endl; }
};

static std::map<std::string, std::string> soc_version_infos = {{"Short_SoC_version", "Ascend950"}};

// Test case 1: float32, NHWC, filter=2x2, strides=[1,1,1,1], rates=[1,1,1,1], VALID
TEST_F(Dilation2DBackpropFilterTiling, dilation2_d_backprop_filter_fp32_valid)
{
    struct Dilation2DBackpropFilterCompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Dilation2DBackpropFilter",
        {
            {{{1, 3, 3, 1}, {1, 3, 3, 1}}, ge::DT_FLOAT, ge::FORMAT_ND}, // x
            {{{2, 2, 1}, {2, 2, 1}}, ge::DT_FLOAT, ge::FORMAT_ND},       // filter
            {{{1, 2, 2, 1}, {1, 2, 2, 1}}, ge::DT_FLOAT, ge::FORMAT_ND}, // out_backprop
        },
        {
            {{{2, 2, 1}, {2, 2, 1}}, ge::DT_FLOAT, ge::FORMAT_ND}, // y
        },
        {
            gert::TilingContextPara::OpAttr("strides",
                                            Ops::Cv::AnyValue::CreateFrom<std::vector<int64_t>>({1, 1, 1, 1})),
            gert::TilingContextPara::OpAttr("rates", Ops::Cv::AnyValue::CreateFrom<std::vector<int64_t>>({1, 1, 1, 1})),
            gert::TilingContextPara::OpAttr("padding_mode", Ops::Cv::AnyValue::CreateFrom<std::string>("VALID")),
            gert::TilingContextPara::OpAttr("pads", Ops::Cv::AnyValue::CreateFrom<std::vector<int64_t>>({0, 0, 0, 0})),
            gert::TilingContextPara::OpAttr("ceil_mode", Ops::Cv::AnyValue::CreateFrom<bool>(false)),
            gert::TilingContextPara::OpAttr("data_format", Ops::Cv::AnyValue::CreateFrom<std::string>("NHWC")),
        },
        &compileInfo, "Ascend950",
        64,     // number of cores
        262144, // ubsize
        4096);  // max tiling data size
    uint64_t expectTilingKey = 1;
    std::string expectTilingData = "4 4 1 0 1 3 3 1 2 2 2 2 1 1 1 1 0 0 3 3 0 ";
    // non-deterministic mode (default): workspace = sysWorkspace only (16777216)
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

// Test case 2: float32, NHWC, filter=3x3, strides=[1,2,2,1], rates=[1,1,1,1], SAME
TEST_F(Dilation2DBackpropFilterTiling, dilation2_d_backprop_filter_fp32_same)
{
    struct Dilation2DBackpropFilterCompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Dilation2DBackpropFilter",
        {
            {{{1, 4, 4, 2}, {1, 4, 4, 2}}, ge::DT_FLOAT, ge::FORMAT_ND}, // x
            {{{3, 3, 2}, {3, 3, 2}}, ge::DT_FLOAT, ge::FORMAT_ND},       // filter
            {{{1, 2, 2, 2}, {1, 2, 2, 2}}, ge::DT_FLOAT, ge::FORMAT_ND}, // out_backprop
        },
        {
            {{{3, 3, 2}, {3, 3, 2}}, ge::DT_FLOAT, ge::FORMAT_ND}, // y
        },
        {
            gert::TilingContextPara::OpAttr("strides",
                                            Ops::Cv::AnyValue::CreateFrom<std::vector<int64_t>>({1, 2, 2, 1})),
            gert::TilingContextPara::OpAttr("rates", Ops::Cv::AnyValue::CreateFrom<std::vector<int64_t>>({1, 1, 1, 1})),
            gert::TilingContextPara::OpAttr("padding_mode", Ops::Cv::AnyValue::CreateFrom<std::string>("SAME")),
            gert::TilingContextPara::OpAttr("pads", Ops::Cv::AnyValue::CreateFrom<std::vector<int64_t>>({0, 0, 0, 0})),
            gert::TilingContextPara::OpAttr("ceil_mode", Ops::Cv::AnyValue::CreateFrom<bool>(false)),
            gert::TilingContextPara::OpAttr("data_format", Ops::Cv::AnyValue::CreateFrom<std::string>("NHWC")),
        },
        &compileInfo, "Ascend950",
        64,     // number of cores
        262144, // ubsize
        4096);  // max tiling data size
    uint64_t expectTilingKey = 1;
    std::string expectTilingData = "8 18 1 0 1 4 4 2 3 3 2 2 2 2 1 1 0 0 4 4 0 ";
    // non-deterministic mode (default): workspace = sysWorkspace only (16777216)
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}
