/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file roi_align_graph_infer.cpp
 * \brief roi_align operator graph infer resource
 */

#include "register/op_impl_registry.h"
#include "log/log.h"

namespace ops {
using namespace ge;

static constexpr int64_t IDX_FEATURES = 0;
static constexpr int64_t IDX_OUTPUT = 0;

static ge::graphStatus InferDataTypeROIAlign(gert::InferDataTypeContext* context)
{
    OP_LOGD(context->GetNodeName(), "Begin to do InferDataTypeROIAlign");

    // Output dtype = features dtype (SE 5.5)
    ge::DataType featuresDtype = context->GetInputDataType(IDX_FEATURES);
    context->SetOutputDataType(IDX_OUTPUT, featuresDtype);

    OP_LOGD(context->GetNodeName(), "End to do InferDataTypeROIAlign");
    return GRAPH_SUCCESS;
}

IMPL_OP(ROIAlign).InferDataType(InferDataTypeROIAlign);

}; // namespace ops
