/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file g_io_u_grad_tiling.cpp
 * \brief GIoUGrad tiling implementation
 */

#include "log/log.h"
#include "platform/platform_ascendc.h"
#include "util/math_util.h"
#include "util/platform_util.h"
#include "op_host/tiling_util.h"
#include "op_host/tiling_templates_registry.h"
#include "../../op_kernel/arch35/g_io_u_grad_tiling_data.h"
#include "../../op_kernel/arch35/g_io_u_grad_tiling_key.h"

namespace optiling {

constexpr uint32_t DCACHE_SIZE = 128 * 1024;
constexpr uint32_t STATIC_UB_ESTIMATE = 0;
constexpr int64_t PER_CORE_MIN = 96; // 3 warps, warp-aligned

struct GIoUGradCompileInfo {};

static ge::graphStatus GIoUGradTilingFunc(gert::TilingContext* context)
{
    // 1. Get platform info
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    int64_t coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    uint64_t ubSize = 0;
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);

    // 2. Get input shape info
    auto dyShape = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, dyShape);
    auto bboxesShape = context->GetInputShape(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, bboxesShape);
    auto gtboxesShape = context->GetInputShape(2);
    OP_CHECK_NULL_WITH_CONTEXT(context, gtboxesShape);

    int64_t N = dyShape->GetStorageShape().GetDim(0);

    // 3. Get attributes (ordered as in REG_OP: trans=0, is_cross=1, mode=2)
    const gert::RuntimeAttrs* runtimeAttrs = context->GetAttrs();
    OP_CHECK_NULL_WITH_CONTEXT(context, runtimeAttrs);
    const bool* transPtr = runtimeAttrs->GetBool(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, transPtr);
    bool trans = *transPtr;
    const bool* isCrossPtr = runtimeAttrs->GetBool(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, isCrossPtr);
    bool isCross = *isCrossPtr;
    const char* modeStr = runtimeAttrs->GetStr(2);
    OP_CHECK_NULL_WITH_CONTEXT(context, modeStr);

    // 4. Validation
    if (N <= 0) {
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "dy", std::to_string(N).c_str(),
                                              "N (dy dim[0]) must be greater than 0");
        return ge::GRAPH_FAILED;
    }

    if (isCross) {
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "is_cross", "true",
                                              "only is_cross=false is supported");
        return ge::GRAPH_FAILED;
    }

    if (strcmp(modeStr, "iou") != 0) {
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "mode", modeStr, "only mode='iou' is supported");
        return ge::GRAPH_FAILED;
    }

    // 5. Compute core count
    int64_t perCoreElements = std::max((N + coreNum - 1) / coreNum, PER_CORE_MIN);
    int64_t needCoreNum = (N + perCoreElements - 1) / perCoreElements;

    // 6. Set tiling data
    GIoUGradTilingData* tiling = context->GetTilingData<GIoUGradTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(memset_s(tiling, sizeof(GIoUGradTilingData), 0, sizeof(GIoUGradTilingData)) != EOK,
                OP_LOGE(context, "memset tiling data error"), return ge::GRAPH_FAILED);
    tiling->totalElements = N;

    // 7. Set block dim
    context->SetBlockDim(needCoreNum);

    // 8. Set local memory size
    OP_CHECK_IF((ubSize <= DCACHE_SIZE + STATIC_UB_ESTIMATE),
                OP_LOGE(context, "ubSize %lu <= DCACHE_SIZE + STATIC_UB_ESTIMATE", ubSize), return ge::GRAPH_FAILED);
    auto res = context->SetLocalMemorySize(static_cast<uint32_t>(ubSize - DCACHE_SIZE - STATIC_UB_ESTIMATE));
    OP_CHECK_IF((res != ge::GRAPH_SUCCESS), OP_LOGE(context, "SetLocalMemorySize failed"), return ge::GRAPH_FAILED);

    // 9. Set tiling key (encodes trans attribute)
    uint64_t tilingKey;
    if (trans) {
        tilingKey = GET_TPL_TILING_KEY(GIOU_GRAD_TPL_SCH_MODE_1);
    } else {
        tilingKey = GET_TPL_TILING_KEY(GIOU_GRAD_TPL_SCH_MODE_0);
    }
    context->SetTilingKey(tilingKey);

    // 10. Set workspace (system workspace only)
    uint64_t sysWorkspaceSize = ascendcPlatform.GetLibApiWorkSpaceSize();
    size_t* ws = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, ws);
    ws[0] = static_cast<size_t>(sysWorkspaceSize);

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForGIoUGrad([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

// Tiling registration entry
IMPL_OP_OPTILING(GIoUGrad).Tiling(GIoUGradTilingFunc).TilingParse<GIoUGradCompileInfo>(TilingParseForGIoUGrad);

} // namespace optiling
