/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file extract_glimpse_v2_tiling_key.h
 * \brief tiling key declaration for extract_glimpse_v2
 */

#ifndef __EXTRACT_GLIMPSE_V2_TILING_KEY_H__
#define __EXTRACT_GLIMPSE_V2_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"

#define SCENE_MODE_0 0
#define SCENE_MODE_1 1
#define SCENE_MODE_2 2
#define SCENE_MODE_3 3

ASCENDC_TPL_ARGS_DECL(
    ExtractGlimpseV2,
    ASCENDC_TPL_UINT_DECL(schMode, 2, ASCENDC_TPL_UI_LIST,
        SCENE_MODE_0, SCENE_MODE_1, SCENE_MODE_2, SCENE_MODE_3));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(
    ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST,
        SCENE_MODE_0, SCENE_MODE_1, SCENE_MODE_2, SCENE_MODE_3)));

#endif // __EXTRACT_GLIMPSE_V2_TILING_KEY_H__
