/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file extract_glimpse_v2_simt.h
 * \brief SIMT kernel implementation for extract_glimpse_v2
 */

#ifndef __EXTRACT_GLIMPSE_V2_SIMT_H__
#define __EXTRACT_GLIMPSE_V2_SIMT_H__

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "simt_api/common_functions.h"
#include "simt_api/math_functions.h"
#include "extract_glimpse_v2_tiling_data.h"
#include "extract_glimpse_v2_tiling_key.h"

namespace NsExtractGlimpseV2 {

using namespace AscendC;

constexpr uint32_t THREADS_UINT32 = 2048;
constexpr uint32_t THREADS_UINT64 = 1024;
constexpr size_t UINT32_BYTE_WIDTH = 4;
constexpr int32_t OFFSETS_STRIDE = 2;
constexpr float CENTERED_SCALE = 0.5f;

template <typename IDX_T>
static constexpr uint32_t THREADS = (sizeof(IDX_T) == UINT32_BYTE_WIDTH) ? THREADS_UINT32 : THREADS_UINT64;

template <typename T, typename IDX_T>
__simt_callee__ inline void ProcessPixel(IDX_T idx, int32_t b, int32_t oh, int32_t ow, int32_t c, int32_t inputW,
                                         int32_t channels, int32_t startY, int32_t startX, int32_t baseY, int32_t baseX,
                                         int32_t copyH, int32_t copyW, int64_t inputSliceSize, __gm__ T* input,
                                         __gm__ T* output)
{
    int32_t localY = oh - baseY;
    int32_t localX = ow - baseX;
    if (copyH > 0 && copyW > 0 && localY >= 0 && localY < copyH && localX >= 0 && localX < copyW) {
        int32_t srcY = startY + localY;
        int32_t srcX = startX + localX;
        int64_t inputIdx = static_cast<int64_t>(b) * inputSliceSize + static_cast<int64_t>(srcY) * inputW * channels +
                           static_cast<int64_t>(srcX) * channels + c;
        output[idx] = input[inputIdx];
    } else {
        output[idx] = static_cast<T>(0);
    }
}

template <typename T, bool Centered, bool Normalized, typename IDX_T>
__simt_vf__ __aicore__ __launch_bounds__(THREADS<IDX_T>) inline void OpExtractGlimpseV2SimtKernel(
    IDX_T outputTotalElements, int32_t inputH, int32_t inputW, int32_t channels, int32_t glimpseH, int32_t glimpseW,
    IDX_T magicChannels, IDX_T shiftChannels, IDX_T magicGlimpseW, IDX_T shiftGlimpseW, IDX_T magicGlimpseH,
    IDX_T shiftGlimpseH, __gm__ T* input, __gm__ float* offsets, __gm__ T* output)
{
    const int64_t inputSliceSize = static_cast<int64_t>(inputH) * inputW * channels;

    for (IDX_T idx = static_cast<IDX_T>(blockIdx.x * blockDim.x + threadIdx.x); idx < outputTotalElements;
         idx += static_cast<IDX_T>(blockDim.x * gridDim.x)) {
        IDX_T remaining = idx;

        IDX_T q1 = Simt::UintDiv<IDX_T>(remaining, magicChannels, shiftChannels);
        int32_t c = static_cast<int32_t>(remaining - q1 * static_cast<IDX_T>(channels));
        remaining = q1;

        IDX_T q2 = Simt::UintDiv<IDX_T>(remaining, magicGlimpseW, shiftGlimpseW);
        int32_t ow = static_cast<int32_t>(remaining - q2 * static_cast<IDX_T>(glimpseW));
        remaining = q2;

        IDX_T q3 = Simt::UintDiv<IDX_T>(remaining, magicGlimpseH, shiftGlimpseH);
        int32_t oh = static_cast<int32_t>(remaining - q3 * static_cast<IDX_T>(glimpseH));
        int32_t b = static_cast<int32_t>(q3);

        float offsetY = offsets[b * OFFSETS_STRIDE];
        float offsetX = offsets[b * OFFSETS_STRIDE + 1];

        if (offsetY != offsetY || offsetX != offsetX) {
            output[idx] = static_cast<T>(0);
            continue;
        }

        if constexpr (Normalized) {
            offsetY = offsetY * static_cast<float>(inputH);
            offsetX = offsetX * static_cast<float>(inputW);
        }
        if constexpr (Centered) {
            if constexpr (Normalized) {
                offsetY = offsetY * CENTERED_SCALE + static_cast<float>(inputH) * CENTERED_SCALE -
                          static_cast<float>(glimpseH) * CENTERED_SCALE;
                offsetX = offsetX * CENTERED_SCALE + static_cast<float>(inputW) * CENTERED_SCALE -
                          static_cast<float>(glimpseW) * CENTERED_SCALE;
            } else {
                offsetY = offsetY + static_cast<float>(inputH) * CENTERED_SCALE;
                offsetX = offsetX + static_cast<float>(inputW) * CENTERED_SCALE;
            }
        }

        int32_t startY = static_cast<int32_t>(floorf(fmaxf(0.0f, offsetY)));
        int32_t startX = static_cast<int32_t>(floorf(fmaxf(0.0f, offsetX)));
        int32_t endY = static_cast<int32_t>(
            ceilf(fminf(static_cast<float>(inputH), offsetY + static_cast<float>(glimpseH))));
        int32_t endX = static_cast<int32_t>(
            ceilf(fminf(static_cast<float>(inputW), offsetX + static_cast<float>(glimpseW))));
        int32_t baseY = static_cast<int32_t>(floorf(fmaxf(0.0f, -offsetY)));
        int32_t baseX = static_cast<int32_t>(floorf(fmaxf(0.0f, -offsetX)));
        int32_t copyH = endY - startY;
        int32_t copyW = endX - startX;

        ProcessPixel<T, IDX_T>(idx, b, oh, ow, c, inputW, channels, startY, startX, baseY, baseX, copyH, copyW,
                               inputSliceSize, input, output);
    }
}

template <typename T, bool Centered, bool Normalized>
__aicore__ inline void Process(GM_ADDR input, GM_ADDR size, GM_ADDR offsets, GM_ADDR output, GM_ADDR workspace,
                               const ExtractGlimpseV2TilingData* tilingData)
{
    int64_t outputTotalElements = tilingData->outputTotalElements;
    if (outputTotalElements == 0) {
        return;
    }

    __gm__ T* inputGm = (__gm__ T*)input;
    __gm__ float* offsetsGm = (__gm__ float*)offsets;
    __gm__ T* outputGm = (__gm__ T*)output;

    int32_t inputH = tilingData->inputH;
    int32_t inputW = tilingData->inputW;
    int32_t channels = tilingData->channels;
    int32_t glimpseH = tilingData->glimpseH;
    int32_t glimpseW = tilingData->glimpseW;

    if (outputTotalElements <= static_cast<int64_t>(INT32_MAX)) {
        uint32_t mCh = 0, sCh = 0;
        uint32_t mGW = 0, sGW = 0;
        uint32_t mGH = 0, sGH = 0;
        GetUintDivMagicAndShift<uint32_t>(mCh, sCh, static_cast<uint32_t>(channels));
        GetUintDivMagicAndShift<uint32_t>(mGW, sGW, static_cast<uint32_t>(glimpseW));
        GetUintDivMagicAndShift<uint32_t>(mGH, sGH, static_cast<uint32_t>(glimpseH));

        asc_vf_call<OpExtractGlimpseV2SimtKernel<T, Centered, Normalized, uint32_t>>(
            dim3(THREADS<uint32_t>), static_cast<uint32_t>(outputTotalElements), inputH, inputW, channels, glimpseH,
            glimpseW, mCh, sCh, mGW, sGW, mGH, sGH, inputGm, offsetsGm, outputGm);
    } else {
        uint64_t mCh = 0, sCh = 0;
        uint64_t mGW = 0, sGW = 0;
        uint64_t mGH = 0, sGH = 0;
        GetUintDivMagicAndShift<uint64_t>(mCh, sCh, static_cast<uint64_t>(channels));
        GetUintDivMagicAndShift<uint64_t>(mGW, sGW, static_cast<uint64_t>(glimpseW));
        GetUintDivMagicAndShift<uint64_t>(mGH, sGH, static_cast<uint64_t>(glimpseH));

        asc_vf_call<OpExtractGlimpseV2SimtKernel<T, Centered, Normalized, uint64_t>>(
            dim3(THREADS<uint64_t>), static_cast<uint64_t>(outputTotalElements), inputH, inputW, channels, glimpseH,
            glimpseW, mCh, sCh, mGW, sGW, mGH, sGH, inputGm, offsetsGm, outputGm);
    }
}

} // namespace NsExtractGlimpseV2

#endif // __EXTRACT_GLIMPSE_V2_SIMT_H__
