; This file mainly affects the value filled by the --simplified_key_mode option when opc compiles the binary kernel.
; The format is as follows:
; [SomeOp]
; default=xx
; ascendxx=xx
; Among them, 'default' is the default mode, 'ascendxx' is an optional mode.
; If different chips have differentiated requirements, they need to be configured.
; 1) If not configured: non-AscendC operators continue to be processed as empty,
;    i.e. the --simplified_key_mode option is not added in the opc compilation command,
;    and AscendC operators are processed as simplified_key_mode=0
; 2) If only default configuration: each version follows the default
; 3) If only some platform configurations, no default configuration:
;    corresponding platforms follow the configured value,
;    non-corresponding platforms: non-AscendC operators continue to be processed as empty,
;    AscendC operators are processed as simplified_key_mode=0
; 4) If both default and platform configurations are available:
;    corresponding platforms use the platform value,
;    non-corresponding platforms use the default value
; 5) For custom simplified key cases, explicitly configure as None
;    in the binary_simplified_key_mode.ini file,
;    not passing the --simplified_key_mode option,
;    and let opc and FE framework determine which mode to use by themselves
; 6) Whether it is an AscendC operator is determined by the operator name
;    and corresponding platform configured in ops/build-in/tbe/op_info_cfg/parser/ascendc_config.json
[DIoUGrad]
default=0
