/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file test_resize_grad_tiling.cpp
 * \brief test resize grad tiling
 */

#include <iostream>
#include <vector>
#include <string>
#include <gtest/gtest.h>
#include "tiling_context_faker.h"
#include "tiling_case_executor.h"
#include "../../../../op_kernel/arch35/resize_grad_tiling_data.h"
#include "../../../../op_kernel/arch35/resize_grad_tiling_key.h"

using namespace std;
using namespace ge;

class ResizeGradTiling : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "ResizeGradTiling SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "ResizeGradTiling TearDown" << std::endl; }
};

namespace {
struct ResizeGradCompileInfo {};

std::vector<gert::TilingContextPara::OpAttr> MakeAttrs(const std::string& mode, const std::string& dataFormat,
                                                       const std::string& ctm = "half_pixel")
{
    return {
        gert::TilingContextPara::OpAttr("coordinate_transformation_mode",
                                        Ops::Math::AnyValue::CreateFrom<std::string>(ctm)),
        gert::TilingContextPara::OpAttr("cubic_coeff_a", Ops::Math::AnyValue::CreateFrom<float>(-0.75f)),
        gert::TilingContextPara::OpAttr("exclude_outside", Ops::Math::AnyValue::CreateFrom<int64_t>(0)),
        gert::TilingContextPara::OpAttr("extrapolation_value", Ops::Math::AnyValue::CreateFrom<float>(0.0f)),
        gert::TilingContextPara::OpAttr("mode", Ops::Math::AnyValue::CreateFrom<std::string>(mode)),
        gert::TilingContextPara::OpAttr("nearest_mode",
                                        Ops::Math::AnyValue::CreateFrom<std::string>("round_prefer_floor")),
        gert::TilingContextPara::OpAttr("data_format", Ops::Math::AnyValue::CreateFrom<std::string>(dataFormat)),
    };
}
} // namespace

TEST_F(ResizeGradTiling, resize_grad_tiling_cubic_nchw_fp32)
{
    struct ResizeGradCompileInfo compileInfo;
    int64_t oriData[4] = {1, 3, 32, 32};
    float scalesData[2] = {0.0f, 0.0f};
    gert::TilingContextPara tilingContextPara(
        "ResizeGrad",
        {
            {{{1, 3, 64, 64}, {1, 3, 64, 64}}, ge::DT_FLOAT, ge::FORMAT_ND}, // grads (idx0)
            {{{4}, {4}}, ge::DT_FLOAT, ge::FORMAT_ND},
            {{{2}, {2}}, ge::DT_FLOAT, ge::FORMAT_ND, true, scalesData},
            {{{4}, {4}}, ge::DT_INT64, ge::FORMAT_ND, true, oriData},
        },
        {
            {{{1, 3, 32, 32}, {1, 3, 32, 32}}, ge::DT_FLOAT, ge::FORMAT_ND}, // y
        },
        MakeAttrs("cubic", "NCHW"), &compileInfo, 64, 262144, 4096);

    TilingInfo tilingInfo;
    ASSERT_TRUE(ExecuteTiling(tilingContextPara, tilingInfo));
    EXPECT_EQ(tilingInfo.tilingKey, TILING_KEY_CUBIC_DETERMINE);
    EXPECT_EQ(tilingInfo.blockNum, 64U);

    auto* td = reinterpret_cast<const ResizeGradTilingData*>(tilingInfo.tilingData.get());
    EXPECT_EQ(td->lenN, 1);
    EXPECT_EQ(td->lenC, 3);
    EXPECT_EQ(td->lenSrcH, 32);
    EXPECT_EQ(td->lenSrcW, 32);
    EXPECT_EQ(td->lenDstH, 64);
    EXPECT_EQ(td->lenDstW, 64);
    EXPECT_EQ(td->yTotal, 3072);
    EXPECT_EQ(td->useCoreNum, 64);
    EXPECT_EQ(td->coreFactor, 48);
    EXPECT_EQ(td->coreTailFactor, 0);
    EXPECT_EQ(td->format, 0);       // NCHW
    EXPECT_EQ(td->alignCorners, 0); // half_pixel
    EXPECT_FLOAT_EQ(td->scaleH, 0.5f);
    EXPECT_FLOAT_EQ(td->scaleW, 0.5f);
    EXPECT_FLOAT_EQ(td->inverseScaleH, 2.0f);
    EXPECT_FLOAT_EQ(td->inverseScaleW, 2.0f);
    EXPECT_FLOAT_EQ(td->scaleH0, 0.5f);
    EXPECT_FLOAT_EQ(td->scaleH1, 0.0f);
    EXPECT_FLOAT_EQ(td->scaleH2, 0.0f);
    EXPECT_FLOAT_EQ(td->scaleW0, 0.5f);
    EXPECT_FLOAT_EQ(td->scaleW1, 0.0f);
    EXPECT_FLOAT_EQ(td->scaleW2, 0.0f);
}

TEST_F(ResizeGradTiling, resize_grad_tiling_cubic_hwnc_fp16)
{
    struct ResizeGradCompileInfo compileInfo;
    int64_t oriData[4] = {1, 3, 32, 32};
    float scalesData[2] = {0.0f, 0.0f};
    gert::TilingContextPara tilingContextPara("ResizeGrad",
                                              {
                                                  {{{64, 64, 1, 3}, {64, 64, 1, 3}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                                  {{{4}, {4}}, ge::DT_FLOAT16, ge::FORMAT_ND},                 // roi
                                                  {{{2}, {2}}, ge::DT_FLOAT, ge::FORMAT_ND, true, scalesData}, // scales
                                                  {{{4}, {4}}, ge::DT_INT64, ge::FORMAT_ND, true, oriData},
                                              },
                                              {
                                                  {{{32, 32, 1, 3}, {32, 32, 1, 3}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                              },
                                              MakeAttrs("cubic", "HWNC"), &compileInfo);

    TilingInfo tilingInfo;
    ASSERT_TRUE(ExecuteTiling(tilingContextPara, tilingInfo));
    EXPECT_EQ(tilingInfo.tilingKey, TILING_KEY_CUBIC_DETERMINE);
    EXPECT_EQ(tilingInfo.blockNum, 64U);

    auto* td = reinterpret_cast<const ResizeGradTilingData*>(tilingInfo.tilingData.get());
    EXPECT_EQ(td->lenN, 1);
    EXPECT_EQ(td->lenC, 3);
    EXPECT_EQ(td->lenSrcH, 32);
    EXPECT_EQ(td->lenSrcW, 32);
    EXPECT_EQ(td->lenDstH, 64);
    EXPECT_EQ(td->lenDstW, 64);
    EXPECT_EQ(td->yTotal, 3072);
    EXPECT_EQ(td->useCoreNum, 64);
    EXPECT_EQ(td->coreFactor, 48);
    EXPECT_EQ(td->coreTailFactor, 0);
    EXPECT_EQ(td->format, 1); // HWNC
    EXPECT_EQ(td->alignCorners, 0);
    EXPECT_FLOAT_EQ(td->scaleH, 0.5f);
    EXPECT_FLOAT_EQ(td->scaleW, 0.5f);
    EXPECT_FLOAT_EQ(td->inverseScaleH, 2.0f);
    EXPECT_FLOAT_EQ(td->inverseScaleW, 2.0f);
}

TEST_F(ResizeGradTiling, resize_grad_tiling_linear_fp32_int32_ori)
{
    struct ResizeGradCompileInfo compileInfo;
    int32_t oriData[3] = {1, 3, 64};
    float scalesData[1] = {0.0f};
    gert::TilingContextPara tilingContextPara("ResizeGrad",
                                              {
                                                  {{{1, 3, 1, 128}, {1, 3, 1, 128}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{4}, {4}}, ge::DT_FLOAT, ge::FORMAT_ND}, // roi
                                                  {{{1}, {1}}, ge::DT_FLOAT, ge::FORMAT_ND, true, scalesData},
                                                  {{{3}, {3}}, ge::DT_INT32, ge::FORMAT_ND, true, oriData},
                                              },
                                              {
                                                  {{{1, 3, 1, 64}, {1, 3, 1, 64}}, ge::DT_FLOAT, ge::FORMAT_ND}, // y
                                              },
                                              MakeAttrs("linear", "NCHW"), &compileInfo);

    TilingInfo tilingInfo;
    ASSERT_TRUE(ExecuteTiling(tilingContextPara, tilingInfo));
    EXPECT_EQ(tilingInfo.tilingKey, TILING_KEY_LINEAR_DETERMINE);
    EXPECT_EQ(tilingInfo.blockNum, 64U);

    auto* td = reinterpret_cast<const ResizeGradTilingData*>(tilingInfo.tilingData.get());
    EXPECT_EQ(td->lenN, 1);
    EXPECT_EQ(td->lenC, 3);
    EXPECT_EQ(td->lenSrcH, 1); // linear 固定 1
    EXPECT_EQ(td->lenSrcW, 64);
    EXPECT_EQ(td->lenDstH, 1); // linear 固定 1
    EXPECT_EQ(td->lenDstW, 128);
    EXPECT_EQ(td->yTotal, 192);
    EXPECT_EQ(td->useCoreNum, 64);
    EXPECT_EQ(td->coreFactor, 3);
    EXPECT_EQ(td->coreTailFactor, 0);
    EXPECT_EQ(td->format, 0);
    EXPECT_EQ(td->alignCorners, 0);
    EXPECT_FLOAT_EQ(td->scaleH, 0.0f);
    EXPECT_FLOAT_EQ(td->scaleW, 0.5f);
    EXPECT_FLOAT_EQ(td->inverseScaleH, 0.0f);
    EXPECT_FLOAT_EQ(td->inverseScaleW, 2.0f);
    EXPECT_FLOAT_EQ(td->scaleH0, 0.0f);
    EXPECT_FLOAT_EQ(td->scaleH1, 0.0f);
    EXPECT_FLOAT_EQ(td->scaleH2, 0.0f);
    EXPECT_FLOAT_EQ(td->scaleW0, 0.5f);
}

TEST_F(ResizeGradTiling, resize_grad_tiling_linear_scales_fp16)
{
    struct ResizeGradCompileInfo compileInfo;
    int64_t oriData[3] = {1, 3, 64};
    float scalesData[1] = {2.0f};
    gert::TilingContextPara tilingContextPara(
        "ResizeGrad",
        {
            {{{1, 3, 1, 128}, {1, 3, 1, 128}}, ge::DT_FLOAT16, ge::FORMAT_ND}, // grads
            {{{4}, {4}}, ge::DT_FLOAT16, ge::FORMAT_ND},                       // roi
            {{{1}, {1}}, ge::DT_FLOAT, ge::FORMAT_ND, true, scalesData},       // scales 生效
            {{{3}, {3}}, ge::DT_INT64, ge::FORMAT_ND, true, oriData},
        },
        {
            {{{1, 3, 1, 64}, {1, 3, 1, 64}}, ge::DT_FLOAT16, ge::FORMAT_ND}, // y
        },
        MakeAttrs("linear", "NCHW"), &compileInfo);

    TilingInfo tilingInfo;
    ASSERT_TRUE(ExecuteTiling(tilingContextPara, tilingInfo));
    EXPECT_EQ(tilingInfo.tilingKey, TILING_KEY_LINEAR_DETERMINE);

    auto* td = reinterpret_cast<const ResizeGradTilingData*>(tilingInfo.tilingData.get());
    EXPECT_EQ(td->lenSrcW, 64);
    EXPECT_EQ(td->lenDstW, 128);
    EXPECT_EQ(td->yTotal, 192);
    EXPECT_FLOAT_EQ(td->scaleW, 0.5f); // 1/scales[0]
    EXPECT_FLOAT_EQ(td->inverseScaleW, 2.0f);
}

TEST_F(ResizeGradTiling, resize_grad_tiling_copy_fp32)
{
    struct ResizeGradCompileInfo compileInfo;
    int64_t oriData[4] = {1, 3, 32, 32};
    float scalesData[2] = {0.0f, 0.0f};
    gert::TilingContextPara tilingContextPara(
        "ResizeGrad",
        {
            {{{1, 3, 32, 32}, {1, 3, 32, 32}}, ge::DT_FLOAT, ge::FORMAT_ND}, // grads
            {{{4}, {4}}, ge::DT_FLOAT, ge::FORMAT_ND},                       // roi
            {{{2}, {2}}, ge::DT_FLOAT, ge::FORMAT_ND, true, scalesData},     // scales
            {{{4}, {4}}, ge::DT_INT64, ge::FORMAT_ND, true, oriData},
        },
        {
            {{{1, 3, 32, 32}, {1, 3, 32, 32}}, ge::DT_FLOAT, ge::FORMAT_ND}, // y
        },
        MakeAttrs("cubic", "NCHW"), &compileInfo);

    TilingInfo tilingInfo;
    ASSERT_TRUE(ExecuteTiling(tilingContextPara, tilingInfo));
    EXPECT_EQ(tilingInfo.tilingKey, TILING_KEY_COPY);
    EXPECT_EQ(tilingInfo.blockNum, 64U);

    auto* td = reinterpret_cast<const ResizeGradTilingData*>(tilingInfo.tilingData.get());
    EXPECT_EQ(td->lenSrcH, 32);
    EXPECT_EQ(td->lenSrcW, 32);
    EXPECT_EQ(td->lenDstH, 32);
    EXPECT_EQ(td->lenDstW, 32);
    EXPECT_EQ(td->yTotal, 3072);
    EXPECT_EQ(td->useCoreNum, 64);
    EXPECT_EQ(td->coreFactor, 48);
    EXPECT_EQ(td->coreTailFactor, 0);
    EXPECT_FLOAT_EQ(td->scaleH, 1.0f);
    EXPECT_FLOAT_EQ(td->scaleW, 1.0f);
    EXPECT_FLOAT_EQ(td->inverseScaleH, 1.0f);
    EXPECT_FLOAT_EQ(td->inverseScaleW, 1.0f);
}

TEST_F(ResizeGradTiling, resize_grad_tiling_nearest_failed)
{
    struct ResizeGradCompileInfo compileInfo;
    int64_t oriData[4] = {1, 3, 32, 32};
    float scalesData[2] = {0.0f, 0.0f};
    gert::TilingContextPara tilingContextPara(
        "ResizeGrad",
        {
            {{{1, 3, 64, 64}, {1, 3, 64, 64}}, ge::DT_FLOAT, ge::FORMAT_ND}, // grads
            {{{4}, {4}}, ge::DT_FLOAT, ge::FORMAT_ND},                       // roi
            {{{2}, {2}}, ge::DT_FLOAT, ge::FORMAT_ND, true, scalesData},     // scales
            {{{4}, {4}}, ge::DT_INT64, ge::FORMAT_ND, true, oriData},
        },
        {
            {{{1, 3, 32, 32}, {1, 3, 32, 32}}, ge::DT_FLOAT, ge::FORMAT_ND}, // y
        },
        MakeAttrs("nearest", "NCHW"), &compileInfo);
    uint64_t expectTilingKey = 0;
    std::vector<size_t> expectWorkspaces = {};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_FAILED, expectTilingKey, expectWorkspaces);
}

TEST_F(ResizeGradTiling, resize_grad_tiling_linear_hwnc_failed)
{
    struct ResizeGradCompileInfo compileInfo;
    int64_t oriData[3] = {1, 3, 64};
    float scalesData[1] = {0.0f};
    gert::TilingContextPara tilingContextPara(
        "ResizeGrad",
        {
            {{{1, 3, 1, 128}, {1, 3, 1, 128}}, ge::DT_FLOAT, ge::FORMAT_ND}, // grads
            {{{4}, {4}}, ge::DT_FLOAT, ge::FORMAT_ND},                       // roi
            {{{1}, {1}}, ge::DT_FLOAT, ge::FORMAT_ND, true, scalesData},     // scales
            {{{3}, {3}}, ge::DT_INT64, ge::FORMAT_ND, true, oriData},
        },
        {
            {{{1, 3, 1, 64}, {1, 3, 1, 64}}, ge::DT_FLOAT, ge::FORMAT_ND}, // y
        },
        MakeAttrs("linear", "HWNC"), &compileInfo);
    uint64_t expectTilingKey = 0;
    std::vector<size_t> expectWorkspaces = {};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_FAILED, expectTilingKey, expectWorkspaces);
}
