/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file rotated_feature_align_grad_tiling.cpp
 * \brief tiling implementation for rotated_feature_align_grad operator
 */

#include "log/log.h"
#include "tiling/platform/platform_ascendc.h"
#include "op_host/tiling_util.h"
#include "op_host/tiling_templates_registry.h"
#include "objdetect/rotated_feature_align_grad/op_kernel/rotated_feature_align_grad_tiling_data.h"
#include "objdetect/rotated_feature_align_grad/op_kernel/rotated_feature_align_grad_tiling_key.h"
#include <cstring>
#include <algorithm>
#include <string>

namespace optiling {

using namespace Ops::Cv::OpTiling;

constexpr uint32_t DCACHE_SIZE = 128 * 1024;
constexpr uint32_t STATIC_UB_ESTIMATE = 0;
constexpr int64_t PER_CORE_MIN_NHW = 32;
constexpr uint32_t DEFAULT_BLOCK_DIM = 1;

constexpr size_t DY_DIM_NUM = 4;
constexpr size_t BBOXES_DIM_NUM = 4;
constexpr int32_t BBOXES_LAST_DIM = 5;
// TilingData 字段为 int32，单维超过 INT32_MAX 会截断为负值，需在此前置拦截
constexpr int64_t DIM_VALUE_MAX = 2147483647;
// dy/bboxes 需保持一致的 N/H/W 三个对齐维
constexpr size_t ALIGNED_DIM_NUM = 3;
// shape 各维下标：N/H/W/C
constexpr size_t DIM_IDX_N = 0;
constexpr size_t DIM_IDX_H = 1;
constexpr size_t DIM_IDX_W = 2;
constexpr size_t DIM_IDX_C = 3;

static constexpr size_t ATTR_SPATIAL_SCALE = 0;
static constexpr size_t ATTR_POINTS = 1;
// points 属性合法取值：1（仅中心点）或 5（中心点+4 旋转角点）
constexpr int64_t POINTS_FULL_SAMPLING = 5;

static constexpr size_t kDyIdx = 0;
static constexpr size_t kBboxesIdx = 1;
static constexpr size_t kDataGroup[] = {kDyIdx, kBboxesIdx};

struct RotatedFeatureAlignGradCompileInfo {};

static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t& ubSize, int64_t& coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus GetWorkspaceSize(gert::TilingContext* context)
{
    int64_t userWorkspaceSize = 0;
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(context->GetPlatformInfo());
    uint64_t sysWorkspaceSize = ascendcPlatform.GetLibApiWorkSpaceSize();
    size_t* currentWorkspace = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = static_cast<size_t>(userWorkspaceSize + static_cast<int64_t>(sysWorkspaceSize));
    return ge::GRAPH_SUCCESS;
}

// SE "参数约束"小节单参数约束: dy/bboxes dtype ∈ {float32}
static ge::graphStatus ValidateDtype(gert::TilingContext* context)
{
    auto dyDesc = context->GetInputDesc(kDyIdx);
    if (dyDesc != nullptr) {
        auto dyDtype = dyDesc->GetDataType();
        if (dyDtype != ge::DT_FLOAT) {
            OP_LOGE_FOR_INVALID_DTYPE(context->GetNodeName(), "dy",
                                      ge::TypeUtils::DataTypeToSerialString(dyDtype).c_str(), "float32");
            return ge::GRAPH_FAILED;
        }
    }
    auto bboxesDesc = context->GetInputDesc(kBboxesIdx);
    if (bboxesDesc != nullptr) {
        auto bboxesDtype = bboxesDesc->GetDataType();
        if (bboxesDtype != ge::DT_FLOAT) {
            OP_LOGE_FOR_INVALID_DTYPE(context->GetNodeName(), "bboxes",
                                      ge::TypeUtils::DataTypeToSerialString(bboxesDtype).c_str(), "float32");
            return ge::GRAPH_FAILED;
        }
    }
    return ge::GRAPH_SUCCESS;
}

// SE "参数约束"小节: dy 4D, bboxes 4D last dim=5, N/H/W consistent
static ge::graphStatus ValidateShape(gert::TilingContext* context)
{
    auto dyShape = context->GetInputShape(kDyIdx);
    OP_CHECK_NULL_WITH_CONTEXT(context, dyShape);
    auto bboxesShape = context->GetInputShape(kBboxesIdx);
    OP_CHECK_NULL_WITH_CONTEXT(context, bboxesShape);
    auto dyS = dyShape->GetStorageShape();
    auto bboxesS = bboxesShape->GetStorageShape();
    if (dyS.GetDimNum() != DY_DIM_NUM) {
        OP_LOGE_FOR_INVALID_SHAPEDIM(context->GetNodeName(), "dy", std::to_string(dyS.GetDimNum()).c_str(), "4D");
        return ge::GRAPH_FAILED;
    }
    if (bboxesS.GetDimNum() != BBOXES_DIM_NUM) {
        OP_LOGE_FOR_INVALID_SHAPEDIM(context->GetNodeName(), "bboxes", std::to_string(bboxesS.GetDimNum()).c_str(),
                                     "4D");
        return ge::GRAPH_FAILED;
    }
    for (size_t i = 0; i < dyS.GetDimNum(); i++) {
        if (dyS.GetDim(i) > DIM_VALUE_MAX) {
            OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "dy", std::to_string(dyS.GetDim(i)).c_str(),
                                                  "each dim of dy must not exceed INT32_MAX");
            return ge::GRAPH_FAILED;
        }
    }
    for (size_t i = 0; i < bboxesS.GetDimNum(); i++) {
        if (bboxesS.GetDim(i) > DIM_VALUE_MAX) {
            OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "bboxes",
                                                  std::to_string(bboxesS.GetDim(i)).c_str(),
                                                  "each dim of bboxes must not exceed INT32_MAX");
            return ge::GRAPH_FAILED;
        }
    }
    if (bboxesS.GetDim(BBOXES_DIM_NUM - 1) != BBOXES_LAST_DIM) {
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "bboxes",
                                              std::to_string(bboxesS.GetDim(BBOXES_DIM_NUM - 1)).c_str(),
                                              "the last dim of bboxes must be 5");
        return ge::GRAPH_FAILED;
    }
    for (size_t i = 0; i < ALIGNED_DIM_NUM; i++) {
        if (dyS.GetDim(i) != bboxesS.GetDim(i)) {
            std::string shapeMsg = Ops::Base::ToString(dyS) + " and " + Ops::Base::ToString(bboxesS);
            OP_LOGE_FOR_INVALID_SHAPES_WITH_REASON(context->GetNodeName(), "dy and bboxes", shapeMsg.c_str(),
                                                   "dy and bboxes must have the same N, H and W dims");
            return ge::GRAPH_FAILED;
        }
    }
    return ge::GRAPH_SUCCESS;
}

// SE "参数约束"小节: points ∈ {1, 5}
static ge::graphStatus ValidateAttr(gert::TilingContext* context,
                                    [[maybe_unused]] const RotatedFeatureAlignGradCompileInfo* compileInfo)
{
    const gert::RuntimeAttrs* attrs = context->GetAttrs();
    OP_CHECK_NULL_WITH_CONTEXT(context, attrs);
    const int64_t* pointsPtr = attrs->GetInt(ATTR_POINTS);
    int64_t points = (pointsPtr != nullptr) ? *pointsPtr : 1;
    if (points != 1 && points != POINTS_FULL_SAMPLING) {
        OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "points", std::to_string(points).c_str(), "1 or 5");
        return ge::GRAPH_FAILED;
    }
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ValidateInputs(gert::TilingContext* context)
{
    if (ValidateDtype(context) != ge::GRAPH_SUCCESS) {
        return ge::GRAPH_FAILED;
    }
    if (ValidateShape(context) != ge::GRAPH_SUCCESS) {
        return ge::GRAPH_FAILED;
    }
    if (ValidateAttr(context, nullptr) != ge::GRAPH_SUCCESS) {
        return ge::GRAPH_FAILED;
    }
    return ge::GRAPH_SUCCESS;
}

static bool HasZeroDimension(const gert::Shape& s)
{
    for (size_t i = 0; i < s.GetDimNum(); ++i) {
        if (s.GetDim(i) == 0) {
            return true;
        }
    }
    return false;
}

static void DumpTilingData(gert::TilingContext* context, const RotatedFeatureAlignGradTilingData* tiling)
{
    OP_LOGD(context,
            "RotatedFeatureAlignGradTilingData: N=%d, H=%d, W=%d, C=%d, needCoreNum=%d, spatial_scale=%.6f, points=%d",
            tiling->N, tiling->H, tiling->W, tiling->C, tiling->needCoreNum, tiling->spatial_scale, tiling->points);
}

static ge::graphStatus FillTilingData(gert::TilingContext* context, int32_t N, int32_t H, int32_t W, int32_t C,
                                      float spatial_scale, int32_t points, int64_t maxCoreNum)
{
    int64_t totalNHW = static_cast<int64_t>(N) * H * W;
    int32_t needCoreNum = 0;
    if (totalNHW > 0) {
        int64_t needCore = (totalNHW + PER_CORE_MIN_NHW - 1) / PER_CORE_MIN_NHW;
        needCoreNum = static_cast<int32_t>(std::min(needCore, maxCoreNum));
    }
    RotatedFeatureAlignGradTilingData* tiling = context->GetTilingData<RotatedFeatureAlignGradTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    if (memset_s(tiling, sizeof(RotatedFeatureAlignGradTilingData), 0, sizeof(RotatedFeatureAlignGradTilingData)) !=
        EOK) {
        OP_LOGE(context, "set tiling data error");
        return ge::GRAPH_FAILED;
    }
    tiling->N = N;
    tiling->H = H;
    tiling->W = W;
    tiling->C = C;
    tiling->needCoreNum = needCoreNum;
    tiling->spatial_scale = spatial_scale;
    tiling->points = points;
    DumpTilingData(context, tiling);
    uint32_t blockDim = (needCoreNum > 0) ? static_cast<uint32_t>(needCoreNum) : DEFAULT_BLOCK_DIM;
    context->SetBlockDim(blockDim);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus RotatedFeatureAlignGradTilingFunc(gert::TilingContext* context)
{
    uint64_t ubSize;
    int64_t maxCoreNum;
    if (GetPlatformInfo(context, ubSize, maxCoreNum) != ge::GRAPH_SUCCESS) {
        return ge::GRAPH_FAILED;
    }
    if (GetWorkspaceSize(context) != ge::GRAPH_SUCCESS) {
        return ge::GRAPH_FAILED;
    }
    auto dyInput = context->GetInputShape(kDyIdx);
    OP_CHECK_NULL_WITH_CONTEXT(context, dyInput);
    auto dyShape = EnsureNotScalar(dyInput->GetStorageShape());
    auto bboxesInput = context->GetInputShape(kBboxesIdx);
    OP_CHECK_NULL_WITH_CONTEXT(context, bboxesInput);
    auto bboxesShape = EnsureNotScalar(bboxesInput->GetStorageShape());
    const gert::RuntimeAttrs* attrs = context->GetAttrs();
    OP_CHECK_NULL_WITH_CONTEXT(context, attrs);
    const int64_t* pointsPtr = attrs->GetInt(ATTR_POINTS);
    int32_t points = static_cast<int32_t>((pointsPtr != nullptr) ? *pointsPtr : 1);
    // Zero-dimension check BEFORE validation: if dy or bboxes has 0 dim, return zero tiling
    if (HasZeroDimension(dyShape) || HasZeroDimension(bboxesShape)) {
        RotatedFeatureAlignGradTilingData* zeroTiling = context->GetTilingData<RotatedFeatureAlignGradTilingData>();
        if (zeroTiling != nullptr) {
            (void)memset_s(zeroTiling, sizeof(RotatedFeatureAlignGradTilingData), 0,
                           sizeof(RotatedFeatureAlignGradTilingData));
            // Set N/H/W/C from dy so kernel knows output size for zero-fill
            if (dyShape.GetDimNum() == DY_DIM_NUM) {
                zeroTiling->N = static_cast<int32_t>(dyShape.GetDim(DIM_IDX_N));
                zeroTiling->H = static_cast<int32_t>(dyShape.GetDim(DIM_IDX_H));
                zeroTiling->W = static_cast<int32_t>(dyShape.GetDim(DIM_IDX_W));
                zeroTiling->C = static_cast<int32_t>(dyShape.GetDim(DIM_IDX_C));
            }
            zeroTiling->points = points;
            zeroTiling->isEmpty = 1;
        }
        context->SetBlockDim(DEFAULT_BLOCK_DIM);
        uint64_t tilingKey = (points == 1) ? GET_TPL_TILING_KEY(ROTATED_FEATURE_ALIGN_GRAD_MODE_POINTS_1) :
                                             GET_TPL_TILING_KEY(ROTATED_FEATURE_ALIGN_GRAD_MODE_POINTS_5);
        context->SetTilingKey(tilingKey);
        return ge::GRAPH_SUCCESS;
    }
    if (ValidateInputs(context) != ge::GRAPH_SUCCESS) {
        return ge::GRAPH_FAILED;
    }
    const float* spatialScalePtr = attrs->GetFloat(ATTR_SPATIAL_SCALE);
    OP_CHECK_NULL_WITH_CONTEXT(context, spatialScalePtr);
    float spatial_scale = *spatialScalePtr;
    int32_t N = static_cast<int32_t>(dyShape.GetDim(DIM_IDX_N));
    int32_t H = static_cast<int32_t>(dyShape.GetDim(DIM_IDX_H));
    int32_t W = static_cast<int32_t>(dyShape.GetDim(DIM_IDX_W));
    int32_t C = static_cast<int32_t>(dyShape.GetDim(DIM_IDX_C));
    if (FillTilingData(context, N, H, W, C, spatial_scale, points, maxCoreNum) != ge::GRAPH_SUCCESS) {
        return ge::GRAPH_FAILED;
    }
    OP_CHECK_IF((ubSize <= DCACHE_SIZE + STATIC_UB_ESTIMATE),
                OP_LOGE(context, "ubSize %lu <= DCACHE_SIZE + STATIC_UB_ESTIMATE", ubSize), return ge::GRAPH_FAILED);
    auto res = context->SetLocalMemorySize(static_cast<uint32_t>(ubSize - DCACHE_SIZE - STATIC_UB_ESTIMATE));
    OP_CHECK_IF((res != ge::GRAPH_SUCCESS), OP_LOGE(context, "SetLocalMemorySize failed"), return ge::GRAPH_FAILED);
    uint64_t tilingKey = (points == 1) ? GET_TPL_TILING_KEY(ROTATED_FEATURE_ALIGN_GRAD_MODE_POINTS_1) :
                                         GET_TPL_TILING_KEY(ROTATED_FEATURE_ALIGN_GRAD_MODE_POINTS_5);
    context->SetTilingKey(tilingKey);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForRotatedFeatureAlignGrad([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_OPTILING(RotatedFeatureAlignGrad)
    .Tiling(RotatedFeatureAlignGradTilingFunc)
    .TilingParse<RotatedFeatureAlignGradCompileInfo>(TilingParseForRotatedFeatureAlignGrad);

} // namespace optiling
