/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <iostream>
#include <gtest/gtest.h>
#include "tiling_context_faker.h"
#include "tiling_case_executor.h"
#include "../../../../op_kernel/arch35/rgb2yuv422_tiling_data.h"

using namespace std;
using namespace ge;

class Rgb2yuv422Tiling : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "Rgb2yuv422Tiling SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "Rgb2yuv422Tiling TearDown" << std::endl; }
};

static std::map<std::string, std::string> soc_versions_infos = {{"Short_SoC_version", "Ascend950"}};

TEST_F(Rgb2yuv422Tiling, rgb2yuv422_uint8_nhwc)
{
    struct Rgb2yuv422CompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Rgb2yuv422",
        {
            {{{4, 8, 3}, {4, 8, 3}}, ge::DT_UINT8, ge::FORMAT_ND},
        },
        {
            {{{4, 8, 2}, {4, 8, 2}}, ge::DT_UINT8, ge::FORMAT_ND},
        },
        {
            gert::TilingContextPara::OpAttr("data_format", Ops::Cv::AnyValue::CreateFrom<std::string>("NHWC")),
        },
        &compileInfo, "Ascend950", 64, 262144, 4096);
    uint64_t expectTilingKey = 0;
    string expectTilingData = "1 4 34359738372 1 4 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

TEST_F(Rgb2yuv422Tiling, rgb2yuv422_float32_nhwc)
{
    struct Rgb2yuv422CompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Rgb2yuv422",
        {
            {{{4, 16, 3}, {4, 16, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
        },
        {
            {{{4, 16, 2}, {4, 16, 2}}, ge::DT_FLOAT, ge::FORMAT_ND},
        },
        {
            gert::TilingContextPara::OpAttr("data_format", Ops::Cv::AnyValue::CreateFrom<std::string>("NHWC")),
        },
        &compileInfo, "Ascend950");
    uint64_t expectTilingKey = 0;
    string expectTilingData = "1 4 68719476740 1 8 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

TEST_F(Rgb2yuv422Tiling, rgb2yuv422_float16_nchw_3d)
{
    struct Rgb2yuv422CompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Rgb2yuv422",
        {
            {{{3, 4, 8}, {3, 4, 8}}, ge::DT_FLOAT16, ge::FORMAT_ND},
        },
        {
            {{{2, 4, 8}, {2, 4, 8}}, ge::DT_FLOAT16, ge::FORMAT_ND},
        },
        {
            gert::TilingContextPara::OpAttr("data_format", Ops::Cv::AnyValue::CreateFrom<std::string>("NCHW")),
        },
        &compileInfo, "Ascend950");
    uint64_t expectTilingKey = 1;
    string expectTilingData = "1 4 34359738372 4294967297 4 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

TEST_F(Rgb2yuv422Tiling, rgb2yuv422_w_int32_max_nhwc)
{
    struct Rgb2yuv422CompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Rgb2yuv422",
        {
            {{{1, 2147483647, 3}, {1, 2147483647, 3}}, ge::DT_UINT8, ge::FORMAT_ND},
        },
        {
            {{{1, 2147483647, 2}, {1, 2147483647, 2}}, ge::DT_UINT8, ge::FORMAT_ND},
        },
        {
            gert::TilingContextPara::OpAttr("data_format", Ops::Cv::AnyValue::CreateFrom<std::string>("NHWC")),
        },
        &compileInfo, "Ascend950", 64, 262144, 4096);
    uint64_t expectTilingKey = 0;
    // needCoreNum=1, totalRows=1, perCoreRows=1 | W=2147483647 << 32, outerDims=1 | dataFormat=0 << 32,
    // pairsPerRow=1073741824
    string expectTilingData = "1 1 9223372032559808513 1 1073741824 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

TEST_F(Rgb2yuv422Tiling, rgb2yuv422_w_exceeds_int32_nhwc_rejected)
{
    struct Rgb2yuv422CompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Rgb2yuv422",
        {
            {{{4, 2147483649, 3}, {4, 2147483649, 3}}, ge::DT_UINT8, ge::FORMAT_ND},
        },
        {
            {{{4, 2147483649, 2}, {4, 2147483649, 2}}, ge::DT_UINT8, ge::FORMAT_ND},
        },
        {
            gert::TilingContextPara::OpAttr("data_format", Ops::Cv::AnyValue::CreateFrom<std::string>("NHWC")),
        },
        &compileInfo, "Ascend950", 64, 262144, 4096);
    ExecuteTestCase(tilingContextPara, ge::GRAPH_FAILED);
}

TEST_F(Rgb2yuv422Tiling, rgb2yuv422_h_exceeds_int32_nchw_rejected)
{
    struct Rgb2yuv422CompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara(
        "Rgb2yuv422",
        {
            {{{1, 3, 2147483649, 8}, {1, 3, 2147483649, 8}}, ge::DT_FLOAT, ge::FORMAT_ND},
        },
        {
            {{{1, 3, 2147483649, 4}, {1, 3, 2147483649, 4}}, ge::DT_FLOAT, ge::FORMAT_ND},
        },
        {
            gert::TilingContextPara::OpAttr("data_format", Ops::Cv::AnyValue::CreateFrom<std::string>("NCHW")),
        },
        &compileInfo, "Ascend950", 64, 262144, 4096);
    ExecuteTestCase(tilingContextPara, ge::GRAPH_FAILED);
}
