/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include "rgb2yuv422.h"
#include "op_api/aclnn_check.h"
#include "opdev/make_op_executor.h"
#include "opdev/op_log.h"
#include "opdev/op_dfx.h"
#include "opdev/op_executor.h"
#include "opdev/shape_utils.h"
#include "opdev/platform.h"

using namespace op;

namespace l0op {

OP_TYPE_REGISTER(Rgb2yuv422);

static const std::initializer_list<DataType> ASCEND950_AICORE_DTYPE_SUPPORT_LIST = {
    DataType::DT_UINT8, DataType::DT_FLOAT16, DataType::DT_FLOAT
};

static inline const std::initializer_list<DataType>& GetAiCoreDtypeSupportListBySocVersion()
{
    auto curArch = GetCurrentPlatformInfo().GetCurNpuArch();
    OP_LOGI("Rgb2yuv422", "curArch is %u", static_cast<uint32_t>(curArch));
    switch (curArch) {
        case NpuArch::DAV_3102: {
            return ASCEND950_AICORE_DTYPE_SUPPORT_LIST;
        }
        default: {
            return ASCEND950_AICORE_DTYPE_SUPPORT_LIST;
        }
    }
}

static inline bool IsAiCoreSupport(const aclTensor* x)
{
    return CheckType(x->GetDataType(), GetAiCoreDtypeSupportListBySocVersion());
}

static const aclTensor* Rgb2yuv422AiCore(
    const aclTensor* x, const char* dataFormat, aclTensor* y, aclOpExecutor* executor)
{
    L0_DFX(Rgb2yuv422AiCore, x, y);
    auto ret = ADD_TO_LAUNCHER_LIST_AICORE(Rgb2yuv422, OP_INPUT(x), OP_ATTR(dataFormat), OP_OUTPUT(y));
    OP_CHECK(
        ret == ACL_SUCCESS, OP_LOGE(ACLNN_ERR_INNER_NULLPTR, "Rgb2yuv422AiCore ADD_TO_LAUNCHER_LIST_AICORE failed."),
        return nullptr);
    return y;
}

const aclTensor* Rgb2yuv422(const aclTensor* x, const char* dataFormat, aclOpExecutor* executor)
{
    if (!IsAiCoreSupport(x)) {
        OP_LOGE(ACLNN_ERR_PARAM_INVALID, "Rgb2yuv422 does not support dtype %s on current platform.",
            op::ToString(x->GetDataType()).GetString());
        return nullptr;
    }

    auto yShape = x->GetViewShape();
    auto y = executor->AllocTensor(yShape, x->GetDataType());
    return Rgb2yuv422AiCore(x, dataFormat, y, executor);
}

} // namespace l0op
