/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file extract_glimpse_v2_tiling.cpp
 * \brief Tiling implementation for extract_glimpse_v2
 */

#include "log/log.h"
#include "platform/platform_ascendc.h"
#include "util/math_util.h"
#include "util/platform_util.h"
#include "op_host/tiling_util.h"
#include "op_host/tiling_templates_registry.h"
#include "../../op_kernel/arch35/extract_glimpse_v2_tiling_data.h"
#include "../../op_kernel/arch35/extract_glimpse_v2_tiling_key.h"

namespace optiling {

constexpr int64_t PER_CORE_MIN = 1024;
constexpr uint32_t DCACHE_SIZE = 32 * 1024;
constexpr uint32_t STATIC_UB_ESTIMATE = 0;
constexpr uint32_t ATTR_IDX_CENTERED = 0;
constexpr uint32_t ATTR_IDX_NORMALIZED = 1;
constexpr uint32_t ATTR_IDX_UNIFORM_NOISE = 2;
constexpr uint32_t ATTR_IDX_NOISE = 3;
constexpr uint32_t SCENE_CENTERED_BIT = 2;
constexpr uint32_t SCENE_NORMALIZED_BIT = 1;
constexpr uint32_t WORKSPACE_COUNT = 1;

struct ExtractGlimpseV2CompileInfo {};

struct ShapeInfo {
    int32_t batchSize;
    int32_t inputH;
    int32_t inputW;
    int32_t channels;
    int32_t glimpseH;
    int32_t glimpseW;
    int64_t maxCoreNum;
    uint64_t ubSize;
};

static ge::graphStatus GetPlatformAndShapeInfo(gert::TilingContext* context, ShapeInfo& info)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    info.maxCoreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(info.maxCoreNum == 0, OP_LOGE(context, "maxCoreNum is 0"), return ge::GRAPH_FAILED);
    info.ubSize = 0;
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, info.ubSize);
    OP_CHECK_IF(info.ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);

    auto inputShape = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputShape);
    int64_t batchSize = inputShape->GetShape().GetDim(0);
    int64_t inputH = inputShape->GetShape().GetDim(1);
    int64_t inputW = inputShape->GetShape().GetDim(2);
    int64_t channels = inputShape->GetShape().GetDim(3);

    auto outputShape = context->GetOutputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, outputShape);
    int64_t glimpseH = outputShape->GetShape().GetDim(1);
    int64_t glimpseW = outputShape->GetShape().GetDim(2);

    if (glimpseH <= 0 || glimpseW <= 0) {
        std::string valMsg = "[" + std::to_string(glimpseH) + ", " + std::to_string(glimpseW) + "]";
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "output_size", valMsg.c_str(),
                                              "output_size elements must be greater than 0");
        return ge::GRAPH_FAILED;
    }

    OP_CHECK_IF(batchSize > INT32_MAX || inputH > INT32_MAX || inputW > INT32_MAX || channels > INT32_MAX ||
                    glimpseH > INT32_MAX || glimpseW > INT32_MAX,
                OP_LOGE(context, "dimension exceeds int32_t range"), return ge::GRAPH_FAILED);

    info.batchSize = static_cast<int32_t>(batchSize);
    info.inputH = static_cast<int32_t>(inputH);
    info.inputW = static_cast<int32_t>(inputW);
    info.channels = static_cast<int32_t>(channels);
    info.glimpseH = static_cast<int32_t>(glimpseH);
    info.glimpseW = static_cast<int32_t>(glimpseW);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ValidateAttributes(gert::TilingContext* context, bool& centered, bool& normalized)
{
    const gert::RuntimeAttrs* attrs = context->GetAttrs();
    OP_CHECK_NULL_WITH_CONTEXT(context, attrs);
    const bool* centeredPtr = attrs->GetBool(ATTR_IDX_CENTERED);
    const bool* normalizedPtr = attrs->GetBool(ATTR_IDX_NORMALIZED);
    const bool* uniformNoisePtr = attrs->GetBool(ATTR_IDX_UNIFORM_NOISE);
    const char* noiseStr = attrs->GetStr(ATTR_IDX_NOISE);
    OP_CHECK_IF(centeredPtr == nullptr || normalizedPtr == nullptr || uniformNoisePtr == nullptr || noiseStr == nullptr,
                OP_LOGE(context, "attr pointer is null"), return ge::GRAPH_FAILED);
    if (*uniformNoisePtr) {
        OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "uniform_noise", "true", "false");
        return ge::GRAPH_FAILED;
    }
    if (strcmp(noiseStr, "zero") != 0) {
        OP_LOGE_FOR_INVALID_VALUE(context->GetNodeName(), "noise", noiseStr, "zero");
        return ge::GRAPH_FAILED;
    }
    centered = *centeredPtr;
    normalized = *normalizedPtr;
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ComputeAndSetTiling(gert::TilingContext* context, const ShapeInfo& info, bool centered,
                                           bool normalized)
{
    int64_t outputTotalElements = static_cast<int64_t>(info.batchSize) * info.glimpseH * info.glimpseW * info.channels;

    int64_t perCoreElements = (outputTotalElements + info.maxCoreNum - 1) / info.maxCoreNum;
    if (perCoreElements < PER_CORE_MIN) {
        perCoreElements = PER_CORE_MIN;
    }
    int32_t needCoreNum = static_cast<int32_t>((outputTotalElements + perCoreElements - 1) / perCoreElements);
    if (needCoreNum > static_cast<int32_t>(info.maxCoreNum)) {
        needCoreNum = static_cast<int32_t>(info.maxCoreNum);
    }
    if (needCoreNum < 1) {
        needCoreNum = 1;
    }

    auto* tiling = context->GetTilingData<ExtractGlimpseV2TilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(memset_s(tiling, sizeof(ExtractGlimpseV2TilingData), 0, sizeof(ExtractGlimpseV2TilingData)) != EOK,
                OP_LOGE(context, "set tiling data error"), return ge::GRAPH_FAILED);
    tiling->needCoreNum = needCoreNum;
    tiling->batchSize = info.batchSize;
    tiling->inputH = info.inputH;
    tiling->inputW = info.inputW;
    tiling->channels = info.channels;
    tiling->glimpseH = info.glimpseH;
    tiling->glimpseW = info.glimpseW;
    tiling->centered = centered ? 1 : 0;
    tiling->normalized = normalized ? 1 : 0;
    tiling->outputTotalElements = outputTotalElements;
    tiling->perCoreElements = perCoreElements;

    context->SetBlockDim(needCoreNum);
    uint32_t sceneMode = (centered ? SCENE_CENTERED_BIT : 0) + (normalized ? SCENE_NORMALIZED_BIT : 0);
    context->SetTilingKey(GET_TPL_TILING_KEY(sceneMode));
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus SetupMemoryAndWorkspace(gert::TilingContext* context, uint64_t ubSize)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);

    OP_CHECK_IF((ubSize <= DCACHE_SIZE + STATIC_UB_ESTIMATE),
                OP_LOGE(context, "ubSize %lu <= DCACHE_SIZE + STATIC_UB_ESTIMATE", ubSize), return ge::GRAPH_FAILED);
    auto res = context->SetLocalMemorySize(static_cast<uint32_t>(ubSize - DCACHE_SIZE - STATIC_UB_ESTIMATE));
    OP_CHECK_IF((res != ge::GRAPH_SUCCESS), OP_LOGE(context, "SetLocalMemorySize failed"), return ge::GRAPH_FAILED);

    uint64_t sysWorkspaceSize = ascendcPlatform.GetLibApiWorkSpaceSize();
    size_t* ws = context->GetWorkspaceSizes(WORKSPACE_COUNT);
    OP_CHECK_NULL_WITH_CONTEXT(context, ws);
    ws[0] = static_cast<size_t>(sysWorkspaceSize);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ExtractGlimpseV2TilingFunc(gert::TilingContext* context)
{
    ShapeInfo shapeInfo{};
    if (GetPlatformAndShapeInfo(context, shapeInfo) != ge::GRAPH_SUCCESS) {
        return ge::GRAPH_FAILED;
    }

    bool centered = false;
    bool normalized = false;
    if (ValidateAttributes(context, centered, normalized) != ge::GRAPH_SUCCESS) {
        return ge::GRAPH_FAILED;
    }

    if (ComputeAndSetTiling(context, shapeInfo, centered, normalized) != ge::GRAPH_SUCCESS) {
        return ge::GRAPH_FAILED;
    }

    if (SetupMemoryAndWorkspace(context, shapeInfo.ubSize) != ge::GRAPH_SUCCESS) {
        return ge::GRAPH_FAILED;
    }

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForExtractGlimpseV2([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_OPTILING(ExtractGlimpseV2)
    .InputsDataDependency({1})
    .Tiling(ExtractGlimpseV2TilingFunc)
    .TilingParse<ExtractGlimpseV2CompileInfo>(TilingParseForExtractGlimpseV2);

} // namespace optiling
