/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file blend_face_bg_part_two_def.cpp
 * \brief OpDef for BlendFaceBgPartTwo
 *
 * 迭代 2：双 TilingKey（KEY_FP32 + KEY_UINT8）。
 *   DataType 列表按并行组合数组声明，共 2 个组合（构建系统据此注入 DTYPE_BG_IMG）：
 *     组合 0：acc_face/acc_mask/max_mask=float32, bg_img=float32, fused_img=float32 → KEY_FP32
 *     组合 1：acc_face/acc_mask/max_mask=float32, bg_img=uint8,   fused_img=float32 → KEY_UINT8
 *   四输入 acc_face/acc_mask/max_mask 恒 float32；bg_img 支持 float32 / uint8；输出 fused_img 恒 float32。
 *   属性 epsilon（Float，默认 1e-12），与 proto/infershape/tiling 索引一致（idx=0）。
 * Generated By CANNBot
 */
#include "register/op_def_registry.h"

namespace ops {

class BlendFaceBgPartTwo : public OpDef {
public:
    explicit BlendFaceBgPartTwo(const char* name) : OpDef(name)
    {
        // 并行组合数组：索引 0=组合0(bg=float32/KEY_FP32)，索引 1=组合1(bg=uint8/KEY_UINT8)。
        // acc_face/acc_mask/max_mask/fused_img 两组合恒 float32，仅 bg_img 变化。
        // 输入 acc_face：累积人脸图（来自 PartOne），float32，shape (H,W,C)。
        this->Input("acc_face")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT, ge::DT_FLOAT})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND})
            .AutoContiguous();
        // 输入 acc_mask：累积掩码（归一化分母），float32。
        this->Input("acc_mask")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT, ge::DT_FLOAT})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND})
            .AutoContiguous();
        // 输入 max_mask：最大掩码（Alpha 权重，值域 [0,1]），float32。
        this->Input("max_mask")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT, ge::DT_FLOAT})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND})
            .AutoContiguous();
        // 输入 bg_img：背景图。组合0=float32（直算），组合1=uint8（算子内两级 Cast）。
        this->Input("bg_img")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT, ge::DT_UINT8})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND})
            .AutoContiguous();
        // 输出 fused_img：Alpha 合成融合图，dtype 固定 float32（两组合均 float32）。
        this->Output("fused_img")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT, ge::DT_FLOAT})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND})
            .AutoContiguous();

        // 属性 epsilon：防除零小量，默认 1e-12（与 proto/infershape/tiling 索引对齐，idx=0）。
        this->Attr("epsilon").AttrType(OPTIONAL).Float(1e-12f);

        OpAICoreConfig aiCoreConfig;
        aiCoreConfig.DynamicCompileStaticFlag(true)
            .DynamicFormatFlag(false)
            .DynamicRankSupportFlag(true)
            .DynamicShapeSupportFlag(true)
            .NeedCheckSupportFlag(false)
            .PrecisionReduceFlag(true)
            .ExtendCfgInfo("opFile.value", "blend_face_bg_part_two");
        this->AICore().AddConfig("ascend950", aiCoreConfig);
    }
};

OP_ADD(BlendFaceBgPartTwo);

} // namespace ops
