/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <iostream>
#include <gtest/gtest.h>
#include "tiling_context_faker.h"
#include "tiling_case_executor.h"
#include "../../../op_kernel/arch35/three_interpolate_tiling_data.h"

using namespace std;
using namespace ge;

class ThreeInterpolateTiling : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "ThreeInterpolateTiling SetUp" << std::endl; }

    static void TearDownTestCase() { std::cout << "ThreeInterpolateTiling TearDown" << std::endl; }
};

TEST_F(ThreeInterpolateTiling, three_interpolate_fp32_int32)
{
    struct ThreeInterpolateCompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara("ThreeInterpolate",
                                              {
                                                  {{{2, 4, 3}, {2, 4, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{2, 2, 3}, {2, 2, 3}}, ge::DT_INT32, ge::FORMAT_ND},
                                                  {{{2, 2, 3}, {2, 2, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{2, 2, 3}, {2, 2, 3}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              &compileInfo, "Ascend950");
    uint64_t expectTilingKey = 0;
    string expectTilingData = "8589934594 17179869187 1 12 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

TEST_F(ThreeInterpolateTiling, three_interpolate_fp16_int64)
{
    struct ThreeInterpolateCompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara("ThreeInterpolate",
                                              {
                                                  {{{8, 128, 128}, {8, 128, 128}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                                  {{{8, 512, 3}, {8, 512, 3}}, ge::DT_INT64, ge::FORMAT_ND},
                                                  {{{8, 512, 3}, {8, 512, 3}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                              },
                                              {
                                                  {{{8, 512, 128}, {8, 512, 128}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                              },
                                              &compileInfo, "Ascend950");
    uint64_t expectTilingKey = 0;
    string expectTilingData = "2199023255560 549755814016 64 524288 ";
    std::vector<size_t> expectWorkspaces = {16777216};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}
