/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file to_absolute_b_box_apt.cpp
 * \brief ToAbsoluteBBox 算子 kernel 入口（arch35 / DAV_3510）
 *
 * 单入口约束：arch35 的唯一 __global__ 入口。采用 **def 驱动 dtype** 模式：
 *   - dtype:        由构建系统注入的 DTYPE_NORMALIZED_BOXES 宏提供（def DataType 列表驱动），
 *                   非 tiling_key 模板参数。
 *   - REVERSED_BOX: 唯一的 tiling_key 模板参数，与 to_absolute_b_box_tiling_key.h 的
 *                   ASCENDC_TPL_ARGS_DECL 一一对应（0=false / 1=true）。
 *
 * 核函数参数顺序（固定）：输入... 输出... workspace tiling
 */

#include "arch35/to_absolute_b_box.h"

// 入口符号名须与 autogen 对 OpType "ToAbsoluteBBox" 的 snake_case 结果一致：to_absolute_b_box
template <uint32_t REVERSED_BOX>
__global__ __aicore__ void to_absolute_b_box(GM_ADDR normalized_boxes, GM_ADDR shape_hw, GM_ADDR y, GM_ADDR workspace,
                                             GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(ToAbsoluteBBoxTilingData);
    GET_TILING_DATA_WITH_STRUCT(ToAbsoluteBBoxTilingData, tilingData, tiling);
    NsToAbsoluteBBox::ToAbsoluteBBox<DTYPE_NORMALIZED_BOXES, REVERSED_BOX> op;
    op.Init(normalized_boxes, shape_hw, y, &tilingData);
    op.Process();
}
