/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file test_geir_roi_align_rotated.cpp
 * \brief GE IR 图模式调用示例 for RoiAlignRotated（Ascend 950PR/Ascend 950DT，arch35）。
 *
 * 本示例面向 Ascend 950：x 为 FORMAT_NCHW 或 FORMAT_ND shape (N,C,H,W)（mmcv 契约；ND 为
 * 无布局声明，按 NCHW 维度序解释），rois 为 FORMAT_ND shape (R,6) 行主序，输出
 * y=(R,C,pooled_h,pooled_w)；覆盖 dtype × shape × S/D 双模式全矩阵正向用例（含 ND 等价正例），
 * 以及 format 闸门负向用例（NHWC 输入预期被 tiling ValidateFormat 显式拒绝，run_ok=false 即 PASS）。
 *
 * 动态 shape 泛化补充（dyn_list，graph desc 显式声明）：
 *   - 部分 -1（unknown dim，rank 已知）：x={-1,16,8,8}/rois={-1,6} 等组合，未知的 N/R/C 透传到输出；
 *   - rois 末维未知：rois={-1,-1}（dim1 不再是常量 6，验证推导/tiling 对 unknown dim 的容忍）；
 *   - -2（unknown rank，UNKNOWN_DIM_NUM）：x/rois 单侧或双侧 {-2}，entry infershape
 *     IsUnknownRank → SetUnknownRank(output) 透传（需 def.cpp DynamicRankSupportFlag=true）。
 * 动态 graph desc 的 format 恒为 FORMAT_ND：FE 对含 -1/-2 的 desc 会做格式归一（NCHW 会被改写），
 * ND 无布局声明与 def.cpp unknownshape_format=ND 对齐，按 NCHW 维度序解释。
 * 老芯片（NHWC/ND cv 契约，rois (6,R) 转置）版本见 examples/test_geir_roi_align_rotated.cpp。
 */

/* Generated By CANNBot */

#include <cstddef>
#include <cstdint>
#include <iostream>
#include <fstream>
#include <string.h>
#include <stdint.h>
#include <vector>
#include <string>
#include <map>
#include "assert.h"

#include "graph.h"
#include "types.h"
#include "tensor.h"
#include "ge_error_codes.h"
#include "ge_api_types.h"
#include "ge_api.h"
#include "array_ops.h"
#include "ge_ir_build.h"

#include "experiment_ops.h"
#include "nn_other.h"
#include "../../op_graph/roi_align_rotated_proto.h"

#define FAILED -1
#define SUCCESS 0

using namespace ge;
using std::map;
using std::string;
using std::vector;

enum RunMode { RUN_MODE_S = 0, RUN_MODE_D = 1 };

struct CaseResult {
    std::string case_name;
    bool build_ok;
    bool run_ok;
    bool output_exists;
    int output_count;
    std::string err_msg;
    bool expect_reject; // 预期 RunGraph 被 tiling 显式拒绝（run_ok=false 即 PASS）
};

// 动态 shape 泛化用例：graph shape（给图引擎，可含 -1/-2）与 real shape（RunGraph 实际下发，
// 恒具体）成对给出；yGraphShape 为输出 graph desc 镜像（-1 透传 / {-2} unknown rank）。
struct DynCombo {
    std::vector<int64_t> xReal;
    std::vector<int64_t> xGraph;
    std::vector<int64_t> roisReal;
    std::vector<int64_t> roisGraph;
    std::vector<int64_t> yGraph;
    std::string name;
};

// ====== 以下三个宏定义必须原样复用，禁止重写、禁止改签名、禁止删行 ======
// ADD_INPUT_MODE 内部封装了三个关键逻辑，重写会丢失：
//   1. S/D 双 desc 分离：_desc_graph（D 模式含 -1，给图引擎做 infershape）和 _desc_real（具体值，给 GenOnesData 构造
//   Tensor）
//   2. #intputIndex 字符串化：生成 "placeholder1" 等合法 op 名（用 + 会变成指针算术）
//   3. update_output_desc_y：Data op 需要同时设置 input 和 output desc
// 多输入依赖算子只需在宏调用处传入各输入的 shape，无需修改宏定义。
// 新增 intputFormat 参数——x 取 FORMAT_NCHW（显式布局声明）或 FORMAT_ND（无布局声明，950 按
// NCHW 维度序解释），rois 恒 FORMAT_ND（2 维 tensor 无布局含义）。
// D 模式（全 -1）时 graph desc 的 format 归一为 FORMAT_ND：FE 对含未知维（-1）的 desc 会做格式
// 归一（NCHW 声明无法保留，实测被改写为 NHWC 并触发 tiling ValidateFormat 闸门拒绝），ND 为无布局
// 声明、与 def.cpp unknownshape_format=ND 对齐，语义仍按 NCHW 维度序解释；real desc 保持原 format。
#define ADD_INPUT_MODE(intputIndex, intputName, intputDtype, intputFormat, inputShape, mode)                       \
    vector<int64_t> placeholder##intputIndex##_real_shape = inputShape;                                            \
    vector<int64_t> placeholder##intputIndex##_graph_shape = ((mode) == RUN_MODE_D) ?                              \
                                                                 vector<int64_t>(                                  \
                                                                     placeholder##intputIndex##_real_shape.size(), \
                                                                     -1) :                                         \
                                                                 placeholder##intputIndex##_real_shape;            \
    Format placeholder##intputIndex##_graph_format = ((mode) == RUN_MODE_D) ? FORMAT_ND : ((Format)intputFormat);  \
    auto placeholder##intputIndex = op::Data("placeholder" #intputIndex).set_attr_index(0);                        \
    TensorDesc placeholder##intputIndex##_desc_graph = TensorDesc(                                                 \
        ge::Shape(placeholder##intputIndex##_graph_shape), placeholder##intputIndex##_graph_format, intputDtype);  \
    placeholder##intputIndex##_desc_graph.SetPlacement(ge::kPlacementHost);                                        \
    placeholder##intputIndex##_desc_graph.SetFormat(placeholder##intputIndex##_graph_format);                      \
    TensorDesc placeholder##intputIndex##_desc_real = TensorDesc(ge::Shape(placeholder##intputIndex##_real_shape), \
                                                                 intputFormat, intputDtype);                       \
    placeholder##intputIndex##_desc_real.SetPlacement(ge::kPlacementHost);                                         \
    placeholder##intputIndex##_desc_real.SetFormat(intputFormat);                                                  \
    placeholder##intputIndex##_desc_real.SetRealDimCnt(placeholder##intputIndex##_real_shape.size());              \
    Tensor tensor_placeholder##intputIndex;                                                                        \
    ret = GenOnesData(placeholder##intputIndex##_real_shape, tensor_placeholder##intputIndex,                      \
                      placeholder##intputIndex##_desc_real, intputDtype, 2);                                       \
    if (ret != SUCCESS) {                                                                                          \
        printf("%s - ERROR - [XIR]: Generate input data failed\n", GetTime().c_str());                             \
        return FAILED;                                                                                             \
    }                                                                                                              \
    placeholder##intputIndex.update_input_desc_x(placeholder##intputIndex##_desc_graph);                           \
    placeholder##intputIndex.update_output_desc_y(placeholder##intputIndex##_desc_graph);                          \
    input.push_back(tensor_placeholder##intputIndex);                                                              \
    graph.AddOp(placeholder##intputIndex);                                                                         \
    add1.set_input_##intputName(placeholder##intputIndex);                                                         \
    inputs.push_back(placeholder##intputIndex);

// ADD_INPUT_DYN：动态 shape 泛化用例专用。graph desc 的 shape 由 inputGraphShape 显式给出——
// 可为部分 -1（unknown dim，rank 已知）、全 -1，或 {-2}（UNKNOWN_DIM_NUM，unknown rank，
// 经 TensorDesc::SetUnknownDimNumShape 声明）；real tensor 恒为具体 shape（RunGraph 实际下发数据）。
// 关键逻辑与 ADD_INPUT_MODE 一致：_desc_graph（含 -1/-2，给图引擎做 infershape）与 _desc_real
// （具体值，给 GenOnesData 构造 Tensor）双 desc 分离；format 恒 FORMAT_ND（FE 对含未知维的 desc
// 会做格式归一，ND 为无布局声明，按 NCHW 维度序解释）。
#define ADD_INPUT_DYN(intputIndex, intputName, intputDtype, inputRealShape, inputGraphShape)                         \
    vector<int64_t> placeholder##intputIndex##_real_shape = inputRealShape;                                          \
    vector<int64_t> placeholder##intputIndex##_graph_shape = inputGraphShape;                                        \
    auto placeholder##intputIndex = op::Data("placeholder" #intputIndex).set_attr_index(0);                          \
    TensorDesc placeholder##intputIndex##_desc_graph = TensorDesc(ge::Shape(placeholder##intputIndex##_graph_shape), \
                                                                  FORMAT_ND, intputDtype);                           \
    if (placeholder##intputIndex##_graph_shape.size() == 1 && placeholder##intputIndex##_graph_shape[0] == -2) {     \
        placeholder##intputIndex##_desc_graph.SetUnknownDimNumShape();                                               \
    }                                                                                                                \
    placeholder##intputIndex##_desc_graph.SetPlacement(ge::kPlacementHost);                                          \
    placeholder##intputIndex##_desc_graph.SetFormat(FORMAT_ND);                                                      \
    TensorDesc placeholder##intputIndex##_desc_real = TensorDesc(ge::Shape(placeholder##intputIndex##_real_shape),   \
                                                                 FORMAT_ND, intputDtype);                            \
    placeholder##intputIndex##_desc_real.SetPlacement(ge::kPlacementHost);                                           \
    placeholder##intputIndex##_desc_real.SetFormat(FORMAT_ND);                                                       \
    placeholder##intputIndex##_desc_real.SetRealDimCnt(placeholder##intputIndex##_real_shape.size());                \
    Tensor tensor_placeholder##intputIndex;                                                                          \
    ret = GenOnesData(placeholder##intputIndex##_real_shape, tensor_placeholder##intputIndex,                        \
                      placeholder##intputIndex##_desc_real, intputDtype, 2);                                         \
    if (ret != SUCCESS) {                                                                                            \
        printf("%s - ERROR - [XIR]: Generate input data failed\n", GetTime().c_str());                               \
        return FAILED;                                                                                               \
    }                                                                                                                \
    placeholder##intputIndex.update_input_desc_x(placeholder##intputIndex##_desc_graph);                             \
    placeholder##intputIndex.update_output_desc_y(placeholder##intputIndex##_desc_graph);                            \
    input.push_back(tensor_placeholder##intputIndex);                                                                \
    graph.AddOp(placeholder##intputIndex);                                                                           \
    add1.set_input_##intputName(placeholder##intputIndex);                                                           \
    inputs.push_back(placeholder##intputIndex);

#define ADD_CONST_INPUT(intputIndex, intputName, intputDtype, inputShape)                                           \
    vector<int64_t> placeholder##intputIndex##_shape = inputShape;                                                  \
    auto placeholder##intputIndex = op::Const("placeholder" #intputIndex);                                          \
    TensorDesc placeholder##intputIndex##_desc = TensorDesc(ge::Shape(placeholder##intputIndex##_shape), FORMAT_ND, \
                                                            intputDtype);                                           \
    placeholder##intputIndex##_desc.SetPlacement(ge::kPlacementHost);                                               \
    placeholder##intputIndex##_desc.SetFormat(FORMAT_ND);                                                           \
    Tensor tensor_placeholder##intputIndex;                                                                         \
    ret = GenOnesData(placeholder##intputIndex##_shape, tensor_placeholder##intputIndex,                            \
                      placeholder##intputIndex##_desc, intputDtype, 2);                                             \
    if (ret != SUCCESS) {                                                                                           \
        printf("%s - ERROR - [XIR]: Generate input data failed\n", GetTime().c_str());                              \
        return FAILED;                                                                                              \
    }                                                                                                               \
    placeholder##intputIndex.SetAttr("value", tensor_placeholder##intputIndex);                                     \
    placeholder##intputIndex.update_output_desc_y(placeholder##intputIndex##_desc);                                 \
    graph.AddOp(placeholder##intputIndex);                                                                          \
    add1.set_input_##intputName(placeholder##intputIndex);                                                          \
    add1.update_input_desc_##intputName(placeholder##intputIndex##_desc);                                           \
    inputs.push_back(placeholder##intputIndex);

// ADD_OUTPUT_MODE 内部封装了 S/D 模式 graph_shape 自动生成（D 模式含 -1），禁止重写。
#define ADD_OUTPUT_MODE(outputIndex, outputName, outputDtype, outputFormat, outputShape, mode)                         \
    vector<int64_t> output##outputIndex##_graph_shape = ((mode) == RUN_MODE_D) ?                                       \
                                                            vector<int64_t>(outputShape.size(), -1) :                  \
                                                            outputShape;                                               \
    TensorDesc outputName##outputIndex##_desc = TensorDesc(ge::Shape(output##outputIndex##_graph_shape), outputFormat, \
                                                           outputDtype);                                               \
    add1.update_output_desc_##outputName(outputName##outputIndex##_desc);

string GetTime()
{
    time_t timep;
    time(&timep);
    char tmp[64];
    strftime(tmp, sizeof(tmp), "%Y-%m-%d %H:%M:%S,000", localtime(&timep));
    return tmp;
}

uint32_t GetDataTypeSize(DataType dt)
{
    uint32_t dilation = 1;
    uint32_t oneByte = 1;
    uint32_t twoByte = 2;
    uint32_t fourByte = 4;
    uint32_t eightByte = 8;

    if (dt == ge::DT_FLOAT) {
        dilation = fourByte;
    } else if (dt == ge::DT_FLOAT16) {
        dilation = twoByte;
    } else if (dt == ge::DT_BF16) {
        dilation = twoByte;
    } else if (dt == ge::DT_INT16) {
        dilation = twoByte;
    } else if (dt == ge::DT_UINT16) {
        dilation = twoByte;
    } else if (dt == ge::DT_INT32) {
        dilation = fourByte;
    } else if (dt == ge::DT_UINT32) {
        dilation = fourByte;
    } else if (dt == ge::DT_INT64) {
        dilation = eightByte;
    } else if (dt == ge::DT_UINT64) {
        dilation = eightByte;
    } else if (dt == ge::DT_INT8) {
        dilation = oneByte;
    }
    return dilation;
}

int32_t GenOnesDataFloat32(vector<int64_t> shapes, Tensor& input_tensor, TensorDesc& input_tensor_desc, float value)
{
    input_tensor_desc.SetRealDimCnt(shapes.size());
    size_t size = 1;
    for (uint32_t i = 0; i < shapes.size(); i++) {
        size *= shapes[i];
    }
    uint32_t byteSizeFloat32 = 4;
    uint32_t data_len = size * byteSizeFloat32;
    float* pData = new (std::nothrow) float[size];
    if (pData == nullptr) {
        printf("%s - ERROR - [XIR]: GenOnesDataFloat32 alloc failed\n", GetTime().c_str());
        return FAILED;
    }

    for (size_t i = 0; i < size; ++i) {
        *(pData + i) = value;
    }
    input_tensor = Tensor(input_tensor_desc, (uint8_t*)pData, data_len);
    return SUCCESS;
}

int32_t GenOnesData(vector<int64_t> shapes, Tensor& input_tensor, TensorDesc& input_tensor_desc, DataType data_type,
                    int value)
{
    input_tensor_desc.SetRealDimCnt(shapes.size());
    size_t size = 1;
    for (uint32_t i = 0; i < shapes.size(); i++) {
        size *= shapes[i];
    }
    uint32_t data_len = size * GetDataTypeSize(data_type);
    int32_t* pData = new (std::nothrow) int32_t[size];
    if (pData == nullptr) {
        printf("%s - ERROR - [XIR]: GenOnesData alloc failed\n", GetTime().c_str());
        return FAILED;
    }
    for (size_t i = 0; i < size; ++i) {
        *(pData + i) = value;
    }
    input_tensor = Tensor(input_tensor_desc, reinterpret_cast<uint8_t*>(pData), data_len);
    return SUCCESS;
}

// RoiAlignRotated 为双输入依赖算子：x 恒为 4 维，rois 恒为 2 维，两输入 shape 不同且存在依赖
// （rois 的 batch_idx 需落在 [0,N)），因此 CreateOppInGraph 接受 x/rois 两组 shape（多输入适配），
// 不能共用单一 xShape。
// x format 取 NCHW（显式声明）或 ND（无布局声明，等价 NCHW 维度序），NHWC 由 tiling 闸门拒绝。
int CreateOppInGraph(RunMode mode, DataType inDtype, Format xFormat, const std::vector<int64_t>& xShape,
                     const std::vector<int64_t>& roisShape, std::vector<ge::Tensor>& input,
                     std::vector<Operator>& inputs, std::vector<Operator>& outputs, Graph& graph)
{
    Status ret = SUCCESS;
    // 自定义代码：添加单算子定义到图中
    auto add1 = op::RoiAlignRotated("add1");
    // x format=NCHW；rois format 恒 ND
    ADD_INPUT_MODE(1, x, inDtype, xFormat, xShape, mode);
    ADD_INPUT_MODE(2, rois, inDtype, FORMAT_ND, roisShape, mode);

    //   y = (R, C, 7, 7)，R = rois.dim(0)、C = x.dim(1)（NCHW 维度序，ND 输入同样按此解释）
    std::vector<int64_t> yShape = {roisShape[0], xShape[1], 7, 7};
    Format yFormat = xFormat;
    ADD_OUTPUT_MODE(1, y, inDtype, yFormat, yShape, mode);

    // 属性设置：强类型接口 set_attr_{name}(value)，按 REG_OP 声明类型传参（Int=int64_t, Float=float, Bool=bool）
    add1.set_attr_pooled_h(7);         // Int，必填，> 0
    add1.set_attr_pooled_w(7);         // Int，必填，> 0
    add1.set_attr_spatial_scale(1.0f); // Float，必填，> 0
    add1.set_attr_sampling_ratio(0);   // Int，0 表示密集采样 ceil(bin_size)
    add1.set_attr_aligned(true);       // Bool
    add1.set_attr_clockwise(false);    // Bool

    outputs.push_back(add1);
    // 添加完毕
    return SUCCESS;
}

CaseResult RunOneCase(ge::Session* session, uint32_t graph_id, RunMode mode, DataType dtype, Format xFormat,
                      const std::vector<int64_t>& xShape, const std::vector<int64_t>& roisShape,
                      const std::string& case_name, bool expectReject)
{
    CaseResult r;
    r.case_name = case_name;
    r.build_ok = false;
    r.run_ok = false;
    r.output_exists = false;
    r.output_count = 0;
    r.err_msg = "";
    r.expect_reject = expectReject;

    std::string graph_name = "tc_ge_irrun_test_" + std::to_string(graph_id);
    Graph graph(graph_name.c_str());
    std::vector<ge::Tensor> input;
    std::vector<Operator> inputs{};
    std::vector<Operator> outputs{};

    Status ret = CreateOppInGraph(mode, dtype, xFormat, xShape, roisShape, input, inputs, outputs, graph);
    if (ret != SUCCESS) {
        r.err_msg = "CreateOppInGraph failed";
        return r;
    }
    if (!inputs.empty() && !outputs.empty()) {
        graph.SetInputs(inputs).SetOutputs(outputs);
    }

    std::map<AscendString, AscendString> graph_options = {};
    ret = session->AddGraph(graph_id, graph, graph_options);
    if (ret != SUCCESS) {
        r.err_msg = "AddGraph failed, ret=" + std::to_string(ret);
        return r;
    }
    r.build_ok = true;

    std::vector<ge::Tensor> output;
    ret = session->RunGraph(graph_id, input, output);
    session->RemoveGraph(graph_id);
    if (ret != SUCCESS) {
        r.err_msg = "RunGraph failed, ret=" + std::to_string(ret);
        return r;
    }
    r.run_ok = true;
    r.output_count = output.size();
    r.output_exists = (output.size() > 0);

    for (size_t i = 0; i < output.size(); i++) {
        int64_t shape_size = output[i].GetTensorDesc().GetShape().GetShapeSize();
        printf("  [%s] output[%zu] dtype=%d shape_size=%lld\n", case_name.c_str(), i,
               output[i].GetTensorDesc().GetDataType(), (long long)shape_size);
    }

    return r;
}

// 动态泛化用例建图：graph shape（可含 -1 部分/全部未知维，或 {-2} 未知 rank）与 real shape
// （恒具体）显式分离传入；yGraphShape 与输入 graph shape 镜像（R=rois.dim(0)、C=x.dim(1) 处
// -1 透传，unknown rank 透传 {-2}）。属性与正向用例保持一致（pooled 7×7）。
int CreateOppInGraphDyn(DataType inDtype, const DynCombo& c, std::vector<ge::Tensor>& input,
                        std::vector<Operator>& inputs, std::vector<Operator>& outputs, Graph& graph)
{
    Status ret = SUCCESS;
    // 自定义代码：添加单算子定义到图中
    auto add1 = op::RoiAlignRotated("add1");
    // 动态 graph desc 恒 FORMAT_ND（无布局声明，按 NCHW 维度序解释）
    ADD_INPUT_DYN(1, x, inDtype, c.xReal, c.xGraph);
    ADD_INPUT_DYN(2, rois, inDtype, c.roisReal, c.roisGraph);

    TensorDesc yGraphDesc = TensorDesc(ge::Shape(c.yGraph), FORMAT_ND, inDtype);
    if (c.yGraph.size() == 1 && c.yGraph[0] == -2) {
        yGraphDesc.SetUnknownDimNumShape();
    }
    add1.update_output_desc_y(yGraphDesc);

    add1.set_attr_pooled_h(7);         // Int，必填，> 0
    add1.set_attr_pooled_w(7);         // Int，必填，> 0
    add1.set_attr_spatial_scale(1.0f); // Float，必填，> 0
    add1.set_attr_sampling_ratio(0);   // Int，0 表示密集采样 ceil(bin_size)
    add1.set_attr_aligned(true);       // Bool
    add1.set_attr_clockwise(false);    // Bool

    outputs.push_back(add1);
    // 添加完毕
    return SUCCESS;
}

CaseResult RunOneDynCase(ge::Session* session, uint32_t graph_id, DataType dtype, const DynCombo& c)
{
    CaseResult r;
    r.case_name = c.name;
    r.build_ok = false;
    r.run_ok = false;
    r.output_exists = false;
    r.output_count = 0;
    r.err_msg = "";
    r.expect_reject = false;

    std::string graph_name = "tc_ge_irrun_dyn_test_" + std::to_string(graph_id);
    Graph graph(graph_name.c_str());
    std::vector<ge::Tensor> input;
    std::vector<Operator> inputs{};
    std::vector<Operator> outputs{};

    Status ret = CreateOppInGraphDyn(dtype, c, input, inputs, outputs, graph);
    if (ret != SUCCESS) {
        r.err_msg = "CreateOppInGraphDyn failed";
        return r;
    }
    if (!inputs.empty() && !outputs.empty()) {
        graph.SetInputs(inputs).SetOutputs(outputs);
    }

    std::map<AscendString, AscendString> graph_options = {};
    ret = session->AddGraph(graph_id, graph, graph_options);
    if (ret != SUCCESS) {
        r.err_msg = "AddGraph failed, ret=" + std::to_string(ret);
        return r;
    }
    r.build_ok = true;

    std::vector<ge::Tensor> output;
    ret = session->RunGraph(graph_id, input, output);
    session->RemoveGraph(graph_id);
    if (ret != SUCCESS) {
        r.err_msg = "RunGraph failed, ret=" + std::to_string(ret);
        return r;
    }
    r.run_ok = true;
    r.output_count = output.size();
    r.output_exists = (output.size() > 0);

    for (size_t i = 0; i < output.size(); i++) {
        int64_t shape_size = output[i].GetTensorDesc().GetShape().GetShapeSize();
        printf("  [%s] output[%zu] dtype=%d shape_size=%lld\n", c.name.c_str(), i,
               output[i].GetTensorDesc().GetDataType(), (long long)shape_size);
    }

    return r;
}

void PrintReport(const std::vector<CaseResult>& results)
{
    printf("\n");
    printf("==========================================================================================================="
           "==========\n");
    printf("| %-30s | %-8s | %-9s | %-12s | %-7s | %-8s | %-24s\n", "Case", "Build", "RunGraph", "OutputExists",
           "OutCnt", "Expect", "ErrMsg");
    printf("-----------------------------------------------------------------------------------------------------------"
           "----------\n");
    int pass_cnt = 0;
    int total = results.size();
    for (const auto& r : results) {
        // 正向用例：build+run+output 三项全 OK 判 PASS；
        // format 闸门负向用例（expect_reject）：RunGraph 被 tiling ValidateFormat 显式拒绝
        // （run_ok=false，日志含 "only supports NCHW and ND"）即 PASS
        bool pass = r.expect_reject ? (!r.run_ok) : (r.build_ok && r.run_ok && r.output_exists);
        if (pass)
            pass_cnt++;
        printf("| %-30s | %-8s | %-9s | %-12s | %-7d | %-8s | %-24s\n", r.case_name.c_str(), r.build_ok ? "OK" : "FAIL",
               r.run_ok ? "OK" : "FAIL", r.output_exists ? "OK" : "FAIL", r.output_count,
               r.expect_reject ? "REJECT" : "OK", r.err_msg.empty() ? "-" : r.err_msg.c_str());
    }
    printf("==========================================================================================================="
           "==========\n");
    printf("Summary: %d/%d passed\n", pass_cnt, total);
}

int main(int argc, char* argv[])
{
    printf("%s - INFO - [XIR]: Start to initialize ge using ge global options\n", GetTime().c_str());
    // 设置全局选项
    std::map<AscendString, AscendString> global_options = {
        {"ge.exec.deviceId", "0"}, {"ge.graphRunMode", "0"}, {"ge.exec.precision_mode", "must_keep_origin_dtype"}};
    // 初始化图引擎
    Status ret = ge::GEInitialize(global_options);
    if (ret != SUCCESS) {
        printf("%s - INFO - [XIR]: Initialize ge using ge global options failed\n", GetTime().c_str());
        return FAILED;
    }
    printf("%s - INFO - [XIR]: Initialize ge using ge global options success\n", GetTime().c_str());

    // dtype 矩阵
    struct DtypeEntry {
        DataType dt;
        std::string name;
    };
    std::vector<DtypeEntry> dtype_list = {
        {DT_FLOAT, "FP32"},
    };

    // shape 场景矩阵：本算子为双输入依赖算子（x 恒 4 维，rois 恒 2 维），每个场景给出一组
    // (x_shape, rois_shape) 合法组合， 保证输出 y=(R,C,pooled_h,pooled_w)
    // 可正常构图运行，N/C/H/W/R 在算子约束内变化（C 上界 1024，R 上界 8192）。
    // 场景裁剪说明：参考模板的标量{1}/1维{64}/8维{2,2,2,2,2,2,2,2}场景对本算子不合法——本算子 rank 固定
    // （x 必须 4 维、rois 必须 2 维），构造标量/1 维/8 维输入会导致构图 infershape 校验失败，故按边界场景
    // 裁剪规则跳过；模板的空tensor场景{0,8}适配为本算子的合法空输入边界 R=0（rois={0,6}，输出 (0,C,7,7) 空tensor）。
    struct ShapeCombo {
        Format xFormat;
        std::vector<int64_t> xShape;
        std::vector<int64_t> roisShape;
        std::string name;
    };
    std::vector<ShapeCombo> shape_list = {
        {FORMAT_NCHW, {1, 16, 8, 8}, {2, 6}, "regular"},         // 基线场景：N=1, C=16, H=W=8, R=2
        {FORMAT_NCHW, {2, 32, 16, 16}, {8, 6}, "regular_batch"}, // 常规多维：N/C/H/W 变化
        {FORMAT_NCHW, {1, 64, 32, 32}, {16, 6}, "multi_rois"},   // RoI 数量增大：R=16
        {FORMAT_NCHW, {4, 8, 32, 64}, {32, 6}, "wide_hw"},       // H/W 拉大：H=32, W=64
        {FORMAT_NCHW, {1, 1024, 4, 4}, {1, 6}, "channel_upper"}, // 通道上界：C=1024
        {FORMAT_NCHW, {1, 16, 8, 8}, {0, 6}, "empty_rois_r0"},   // 空输入边界：R=0，输出 (0,C,7,7)
        {FORMAT_ND, {1, 16, 8, 8}, {2, 6}, "regular_nd"}, // ND 无布局声明：按 NCHW 维度序解释，同 regular
    };

    // 950 上 x format=NHWC 时tiling ValidateFormat 显式拒绝。shape 按 NCHW
    // 构造（x (N,C,H,W)、rois (R,6) 行主序，使 infershape 通过），确保拒绝发生在 tiling 闸门；
    // 预期 RunGraph 失败（run_ok=false 即 PASS，错误日志含 "only supports NCHW and ND"）。
    // ND 为无布局声明，950 按 NCHW 维度序正常承接（见 shape_list 的 regular_nd 正向用例）。
    struct RejectCombo {
        Format xFormat;
        std::vector<int64_t> xShape;
        std::vector<int64_t> roisShape;
        std::string name;
    };
    std::vector<RejectCombo> reject_list = {
        {FORMAT_NHWC, {1, 16, 8, 8}, {2, 6}, "nhwc_rejected"}, // NHWC→cv 契约布局（老芯片语义），950 拒绝
    };

    // 动态 shape 泛化用例矩阵（graph desc 显式声明，real 恒具体）：
    //   - 部分 -1（unknown dim，rank 已知）：未知的 N/R/C 透传到输出 y=(R,C,7,7) 对应位置；
    //   - rois 末维未知 {-1,-1}：dim1 不再是常量 6，验证推导/tiling 对 unknown dim 的容忍；
    //   - -2（unknown rank，UNKNOWN_DIM_NUM）：单侧/双侧输入 {-2}，entry infershape
    //     IsUnknownRank → SetUnknownRank(output) 透传（def.cpp DynamicRankSupportFlag=true）。
    // real 组合取 regular 基线（x={1,16,8,8}、rois={2,6}、y={2,16,7,7}=1568 元素）。
    std::vector<DynCombo> dyn_list = {
        // 部分 -1：仅 x 的 N 未知 + rois 的 R 未知
        {{1, 16, 8, 8}, {-1, 16, 8, 8}, {2, 6}, {-1, 6}, {-1, 16, 7, 7}, "dyn_xn_rois_r"},
        // 部分 -1：x 的 N/C 未知（C 透传到 y.dim(1)）
        {{1, 16, 8, 8}, {-1, -1, 8, 8}, {2, 6}, {-1, 6}, {-1, -1, 7, 7}, "dyn_xnc"},
        // x 全 -1（rank 4 已知）+ rois 仅 R 未知（dim1=6 已知）
        {{1, 16, 8, 8}, {-1, -1, -1, -1}, {2, 6}, {-1, 6}, {-1, -1, 7, 7}, "dyn_x_all"},
        // rois 末维未知：rois={-1,-1}，dim1 非常量（推导侧需容忍 -1）
        {{1, 16, 8, 8}, {1, 16, 8, 8}, {2, 6}, {-1, -1}, {2, 16, 7, 7}, "dyn_rois_d1_unknown"},
        // -2 未知 rank：双输入均 unknown rank，输出 unknown rank 透传
        {{1, 16, 8, 8}, {-2}, {2, 6}, {-2}, {-2}, "unknown_rank_both"},
        // -2 未知 rank：仅 x 侧（rois 侧部分 -1）
        {{1, 16, 8, 8}, {-2}, {2, 6}, {-1, 6}, {-2}, "unknown_rank_x"},
        // -2 未知 rank：仅 rois 侧（x 侧部分 -1）
        {{1, 16, 8, 8}, {-1, 16, 8, 8}, {2, 6}, {-2}, {-2}, "unknown_rank_rois"},
    };

    // 单 session 复用
    std::map<AscendString, AscendString> build_options = {};
    ge::Session* session = new Session(build_options);
    if (session == nullptr) {
        printf("%s - ERROR - [XIR]: create session failed\n", GetTime().c_str());
        ge::GEFinalize();
        return FAILED;
    }

    std::vector<CaseResult> results;
    uint32_t graph_id = 0;

    // N_dtype × N_shape × 2 mode 全矩阵（正向：x format=NCHW，950 实现分支）
    for (const auto& d : dtype_list) {
        for (const auto& s : shape_list) {
            for (auto mode : {RUN_MODE_S, RUN_MODE_D}) {
                std::string mode_name = (mode == RUN_MODE_S) ? "S" : "D";
                std::string case_name = d.name + "_" + s.name + "_" + mode_name;
                printf("\n%s - INFO - [XIR]: ===== %s =====\n", GetTime().c_str(), case_name.c_str());
                CaseResult r = RunOneCase(session, graph_id, mode, d.dt, s.xFormat, s.xShape, s.roisShape, case_name,
                                          false);
                results.push_back(r);
                graph_id++;
            }
        }
    }

    // format 路由负向用例（S 模式单档）：ND/NHWC 输入预期被 tiling 显式拒绝
    for (const auto& d : dtype_list) {
        for (const auto& rej : reject_list) {
            std::string case_name = d.name + "_" + rej.name;
            printf("\n%s - INFO - [XIR]: ===== %s (expect tiling reject) =====\n", GetTime().c_str(),
                   case_name.c_str());
            CaseResult r = RunOneCase(session, graph_id, RUN_MODE_S, d.dt, rej.xFormat, rej.xShape, rej.roisShape,
                                      case_name, true);
            results.push_back(r);
            graph_id++;
        }
    }

    // 动态 shape 泛化用例：部分 -1（unknown dim）× {-2}（unknown rank），全部预期正向通过
    for (const auto& d : dtype_list) {
        for (const auto& c : dyn_list) {
            std::string case_name = d.name + "_" + c.name;
            printf("\n%s - INFO - [XIR]: ===== %s (dynamic graph desc) =====\n", GetTime().c_str(), case_name.c_str());
            CaseResult r = RunOneDynCase(session, graph_id, d.dt, c);
            results.push_back(r);
            graph_id++;
        }
    }

    PrintReport(results);

    bool all_pass = true;
    for (const auto& r : results) {
        // 正向：三项全 OK；负向（expect_reject）：RunGraph 被拒绝（run_ok=false）
        bool pass = r.expect_reject ? (!r.run_ok) : (r.build_ok && r.run_ok && r.output_exists);
        if (!pass) {
            all_pass = false;
        }
    }
    if (all_pass) {
        printf("\n%s - INFO - [XIR]: ALL CASES PASSED\n", GetTime().c_str());
    } else {
        printf("\n%s - ERROR - [XIR]: SOME CASES FAILED, see report above\n", GetTime().c_str());
    }

    delete session;
    printf("%s - INFO - [XIR]: Start to finalize ir graph session\n", GetTime().c_str());
    ret = ge::GEFinalize();
    if (ret != SUCCESS) {
        printf("%s - INFO - [XIR]: Finalize ir graph session failed\n", GetTime().c_str());
        return FAILED;
    }
    printf("%s - INFO - [XIR]: Finalize ir graph session success\n", GetTime().c_str());
    return all_pass ? SUCCESS : FAILED;
}
