/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file extract_image_patches_tiling_key.h
 * \brief Tiling key declare for extract_image_patches operator
 *
 * TilingKey 编码场景模式（format + idxBit），禁止枚举 dtype。
 * dtype 由 DTYPE_ 宏自动实例化，每种 dtype 编译独立 binary。
 *
 * 模板参数:
 *   formatMode (UINT 2-bit): 数据格式
 *     0 = NHWC, 1 = NCHW
 *   idxBit (UINT 1-bit): 索引位宽
 *     0 = 64-bit (uint64_t), totalElements > INT32_MAX 时选择
 *     1 = 32-bit (uint32_t), totalElements ≤ INT32_MAX 时选择
 */

#ifndef EXTRACT_IMAGE_PATCHES_TILING_KEY_H_
#define EXTRACT_IMAGE_PATCHES_TILING_KEY_H_

#include "ascendc/host_api/tiling/template_argument.h"

#define EXTRACT_IMAGE_PATCHES_TPL_FORMAT_NHWC 0
#define EXTRACT_IMAGE_PATCHES_TPL_FORMAT_NCHW 1

#define EXTRACT_IMAGE_PATCHES_TPL_IDX_64BIT 0
#define EXTRACT_IMAGE_PATCHES_TPL_IDX_32BIT 1

ASCENDC_TPL_ARGS_DECL(ExtractImagePatches,
                      ASCENDC_TPL_UINT_DECL(formatMode, 2, ASCENDC_TPL_UI_LIST, EXTRACT_IMAGE_PATCHES_TPL_FORMAT_NHWC,
                                            EXTRACT_IMAGE_PATCHES_TPL_FORMAT_NCHW),
                      ASCENDC_TPL_UINT_DECL(idxBit, 1, ASCENDC_TPL_UI_LIST, EXTRACT_IMAGE_PATCHES_TPL_IDX_64BIT,
                                            EXTRACT_IMAGE_PATCHES_TPL_IDX_32BIT));

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(formatMode, ASCENDC_TPL_UI_LIST, EXTRACT_IMAGE_PATCHES_TPL_FORMAT_NHWC),
                         ASCENDC_TPL_UINT_SEL(idxBit, ASCENDC_TPL_UI_LIST, EXTRACT_IMAGE_PATCHES_TPL_IDX_64BIT),
                         ASCENDC_TPL_TILING_STRUCT_SEL(ExtractImagePatchesTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(formatMode, ASCENDC_TPL_UI_LIST, EXTRACT_IMAGE_PATCHES_TPL_FORMAT_NHWC),
                         ASCENDC_TPL_UINT_SEL(idxBit, ASCENDC_TPL_UI_LIST, EXTRACT_IMAGE_PATCHES_TPL_IDX_32BIT),
                         ASCENDC_TPL_TILING_STRUCT_SEL(ExtractImagePatchesTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(formatMode, ASCENDC_TPL_UI_LIST, EXTRACT_IMAGE_PATCHES_TPL_FORMAT_NCHW),
                         ASCENDC_TPL_UINT_SEL(idxBit, ASCENDC_TPL_UI_LIST, EXTRACT_IMAGE_PATCHES_TPL_IDX_64BIT),
                         ASCENDC_TPL_TILING_STRUCT_SEL(ExtractImagePatchesTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(formatMode, ASCENDC_TPL_UI_LIST, EXTRACT_IMAGE_PATCHES_TPL_FORMAT_NCHW),
                         ASCENDC_TPL_UINT_SEL(idxBit, ASCENDC_TPL_UI_LIST, EXTRACT_IMAGE_PATCHES_TPL_IDX_32BIT),
                         ASCENDC_TPL_TILING_STRUCT_SEL(ExtractImagePatchesTilingData)));

#endif // EXTRACT_IMAGE_PATCHES_TILING_KEY_H_
