/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file lut3_d_tiling.cpp
 * \brief Tiling implementation for lut3_d operator
 */

#include "log/log.h"
#include "platform/platform_ascendc.h"
#include "util/math_util.h"
#include "util/platform_util.h"
#include "op_host/tiling_util.h"
#include "op_host/tiling_templates_registry.h"
#include "../../op_kernel/arch35/lut3_d_tiling_data.h"
#include "../../op_kernel/arch35/lut3_d_tiling_key.h"

#include <string>

namespace optiling {

constexpr int64_t PER_CORE_MIN_PIXELS = 1024;
constexpr uint32_t DCACHE_SIZE = 128 * 1024;
constexpr uint32_t STATIC_UB_ESTIMATE = 0;

struct Lut3DCompileInfo {};

static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t& ubSize, int64_t& coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ValidateDtypes(gert::TilingContext* context)
{
    auto imgDesc = context->GetInputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, imgDesc);
    auto lutDesc = context->GetInputDesc(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, lutDesc);
    auto outDesc = context->GetOutputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, outDesc);

    auto imgDtype = imgDesc->GetDataType();
    auto lutDtype = lutDesc->GetDataType();

    if (imgDtype != lutDtype) {
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "img/lut_table dtype",
                                              std::to_string(imgDtype).c_str(),
                                              "img.dtype and lut_table.dtype must be the same");
        return ge::GRAPH_FAILED;
    }
    if (imgDtype != ge::DT_UINT8 && imgDtype != ge::DT_FLOAT) {
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "img dtype", std::to_string(imgDtype).c_str(),
                                              "img.dtype must be uint8 or float32");
        return ge::GRAPH_FAILED;
    }

    auto outDtype = outDesc->GetDataType();
    if (outDtype != ge::DT_FLOAT) {
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "lut_img dtype", std::to_string(outDtype).c_str(),
                                              "lut_img.dtype must be float32");
        return ge::GRAPH_FAILED;
    }
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ValidateShapes(gert::TilingContext* context, int64_t& totalPixels, int64_t& lutN)
{
    auto imgInput = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, imgInput);
    auto imgShape = imgInput->GetStorageShape();
    auto lutInput = context->GetInputShape(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, lutInput);
    auto lutShape = lutInput->GetStorageShape();

    int64_t imgDimNum = static_cast<int64_t>(imgShape.GetDimNum());
    if (imgDimNum != 3 && imgDimNum != 4) {
        OP_LOGE_FOR_INVALID_SHAPEDIM(context->GetNodeName(), "img", std::to_string(imgDimNum).c_str(), "3 or 4");
        return ge::GRAPH_FAILED;
    }
    if (imgShape.GetDim(imgDimNum - 1) != 3) {
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "img last dim",
                                              std::to_string(imgShape.GetDim(imgDimNum - 1)).c_str(),
                                              "img last dim must be 3");
        return ge::GRAPH_FAILED;
    }

    if (lutShape.GetDimNum() != 4) {
        OP_LOGE_FOR_INVALID_SHAPEDIM(context->GetNodeName(), "lut_table", std::to_string(lutShape.GetDimNum()).c_str(),
                                     "4");
        return ge::GRAPH_FAILED;
    }
    if (lutShape.GetDim(3) != 3) {
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "lut_table dim[3]",
                                              std::to_string(lutShape.GetDim(3)).c_str(), "must be 3");
        return ge::GRAPH_FAILED;
    }
    if (lutShape.GetDim(0) != lutShape.GetDim(1) || lutShape.GetDim(1) != lutShape.GetDim(2)) {
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "lut_table dims", "not equal",
                                              "dim[0], dim[1], dim[2] must be equal");
        return ge::GRAPH_FAILED;
    }
    lutN = lutShape.GetDim(0);
    if (lutN < 1) {
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "lut_table dim[0]", std::to_string(lutN).c_str(),
                                              "must not be less than 1");
        return ge::GRAPH_FAILED;
    }
    if (lutN > 20) {
        OP_LOGE_FOR_INVALID_VALUE_WITH_REASON(context->GetNodeName(), "lut_table dim[0]", std::to_string(lutN).c_str(),
                                              "must not be greater than 20");
        return ge::GRAPH_FAILED;
    }

    totalPixels = imgShape.GetShapeSize() / 3;
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus SetWorkspaceSize(gert::TilingContext* context)
{
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(context->GetPlatformInfo());
    uint64_t sysWorkspaceSize = ascendcPlatform.GetLibApiWorkSpaceSize();
    size_t* ws = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, ws);
    ws[0] = static_cast<size_t>(static_cast<int64_t>(sysWorkspaceSize));
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus Lut3DTilingFunc(gert::TilingContext* context)
{
    uint64_t ubSize = 0;
    int64_t coreNum = 0;
    OP_CHECK_IF(GetPlatformInfo(context, ubSize, coreNum) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetPlatformInfo error"), return ge::GRAPH_FAILED);

    OP_CHECK_IF(ValidateDtypes(context) != ge::GRAPH_SUCCESS, OP_LOGE(context, "ValidateDtypes error"),
                return ge::GRAPH_FAILED);
    int64_t totalPixels = 0;
    int64_t lutN = 0;
    OP_CHECK_IF(ValidateShapes(context, totalPixels, lutN) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "ValidateShapes error"), return ge::GRAPH_FAILED);

    int64_t perCorePixels = (totalPixels > 0) ? Ops::Base::CeilDiv(totalPixels, coreNum) : 1;
    if (perCorePixels < PER_CORE_MIN_PIXELS) {
        perCorePixels = PER_CORE_MIN_PIXELS;
    }
    int64_t needCoreNum = (totalPixels > 0) ? Ops::Base::CeilDiv(totalPixels, perCorePixels) : 1;

    Lut3DTilingData* tiling = context->GetTilingData<Lut3DTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(memset_s(tiling, sizeof(Lut3DTilingData), 0, sizeof(Lut3DTilingData)) != EOK,
                OP_LOGE(context, "Failed to set tiling data"), return ge::GRAPH_FAILED);
    tiling->totalPixels = totalPixels;
    tiling->lutN = static_cast<int32_t>(lutN);

    context->SetBlockDim(needCoreNum);

    OP_CHECK_IF((ubSize <= DCACHE_SIZE + STATIC_UB_ESTIMATE),
                OP_LOGE(context, "ubSize %lu <= DCACHE_SIZE + STATIC_UB_ESTIMATE", ubSize), return ge::GRAPH_FAILED);
    auto res = context->SetLocalMemorySize(static_cast<uint32_t>(ubSize - DCACHE_SIZE - STATIC_UB_ESTIMATE));
    OP_CHECK_IF((res != ge::GRAPH_SUCCESS), OP_LOGE(context, "SetLocalMemorySize failed"), return ge::GRAPH_FAILED);

    context->SetTilingKey(GET_TPL_TILING_KEY(LUT3D_MODE_DEFAULT));

    OP_CHECK_IF(SetWorkspaceSize(context) != ge::GRAPH_SUCCESS, OP_LOGE(context, "SetWorkspaceSize error"),
                return ge::GRAPH_FAILED);

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForLut3D([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_OPTILING(LUT3D).Tiling(Lut3DTilingFunc).TilingParse<Lut3DCompileInfo>(TilingParseForLut3D);

} // namespace optiling
