/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file dilation2_d_backprop_input_tiling_data.h
 * \brief Tiling data struct for dilation2_d_backprop_input operator
 */
/* Generated By CANNBot */

#ifndef DILATION2_D_BACKPROP_INPUT_TILING_DATA_H_
#define DILATION2_D_BACKPROP_INPUT_TILING_DATA_H_

struct Dilation2DBackpropInputTilingData {
    int64_t needCoreNum = 0;
    int64_t outTotalNum = 0;
    int64_t inTotalNum = 0;
    int64_t batch = 0;
    int64_t inputH = 0;
    int64_t inputW = 0;
    int64_t depth = 0;
    int64_t outputH = 0;
    int64_t outputW = 0;
    int64_t filterH = 0;
    int64_t filterW = 0;
    int64_t strideH = 0;
    int64_t strideW = 0;
    int64_t rateH = 0;
    int64_t rateW = 0;
    int64_t padTop = 0;
    int64_t padLeft = 0;
    int64_t paddingMode = 0;
};

#endif // DILATION2_D_BACKPROP_INPUT_TILING_DATA_H_
