/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file yolox_bounding_box_decode_tiling_key.h
 * \brief Tiling key declare for yolox_bounding_box_decode operator
 */

#ifndef YOLOX_BOUNDING_BOX_DECODE_TILING_KEY_H_
#define YOLOX_BOUNDING_BOX_DECODE_TILING_KEY_H_

#include "ascendc/host_api/tiling/template_argument.h"

#define YOLOX_BBOX_DECODE_SCH_MODE_BOX 0

ASCENDC_TPL_ARGS_DECL(YoloxBoundingBoxDecode,
                      ASCENDC_TPL_UINT_DECL(schMode, 1, ASCENDC_TPL_UI_LIST, YOLOX_BBOX_DECODE_SCH_MODE_BOX));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST,
                                                          YOLOX_BBOX_DECODE_SCH_MODE_BOX)));

#endif // YOLOX_BOUNDING_BOX_DECODE_TILING_KEY_H_
