/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file deformable_roi_pool_grad_tiling_key.h
 * \brief tiling key declare for deformable_roi_pool_grad
 *
 * TilingKey 编码“确定性开关 × 有无 offset”；算子原型仅支持 FP32。
 */

#ifndef DEFORMABLE_ROI_POOL_GRAD_TILING_KEY_H
#define DEFORMABLE_ROI_POOL_GRAD_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

#define MODE_NONDET_NO_OFFSET 0          // 非确定性，无 offset
#define MODE_NONDET_WITH_OFFSET 1        // 非确定性，有 offset
#define MODE_DETERMINISTIC_NO_OFFSET 2   // 确定性，无 offset
#define MODE_DETERMINISTIC_WITH_OFFSET 3 // 确定性，有 offset

ASCENDC_TPL_ARGS_DECL(DeformableRoiPoolGrad,
                      ASCENDC_TPL_UINT_DECL(schMode, 2, ASCENDC_TPL_UI_LIST, MODE_NONDET_NO_OFFSET,
                                            MODE_NONDET_WITH_OFFSET, MODE_DETERMINISTIC_NO_OFFSET,
                                            MODE_DETERMINISTIC_WITH_OFFSET));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, MODE_NONDET_NO_OFFSET,
                                                          MODE_NONDET_WITH_OFFSET, MODE_DETERMINISTIC_NO_OFFSET,
                                                          MODE_DETERMINISTIC_WITH_OFFSET)));

#endif // DEFORMABLE_ROI_POOL_GRAD_TILING_KEY_H
