/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file deformable_roi_pool_grad_simt_nondeterministic.h
 * \brief nondeterministic SIMT kernel implementation for deformable_roi_pool_grad
 *
 * grad_x/grad_offset 先并行清零，经 SyncAll 建立全核屏障后融合计算；
 * grad_x 折叠线程内同地址四邻点，grad_offset 在 channel tile 内做 warp 归约后原子累加。
 * 用户 workspace 为 0。
 */

#ifndef DEFORMABLE_ROI_POOL_GRAD_SIMT_NONDETERMINISTIC_H
#define DEFORMABLE_ROI_POOL_GRAD_SIMT_NONDETERMINISTIC_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "simt_api/common_functions.h"
#include "simt_api/asc_simt.h"
#include "simt_api/device_atomic_functions.h"
#include "simt_api/device_sync_functions.h"
#include "simt_api/device_warp_functions.h"
#include "simt_api/math_functions.h"
#include "deformable_roi_pool_grad_tiling_data.h"
#include "deformable_roi_pool_grad_tiling_key.h"

namespace NsDeformableRoiPoolGradNonDet {
using namespace AscendC;

// VF 线程数（MDE §2.2，constexpr 编译期常量，不入 TilingData）
constexpr uint32_t THREAD_NUM = 1024U;
constexpr float MAX_ADAPTIVE_GRID_SIZE = 46340.0f;
constexpr int32_t SAMPLE_CHUNK = 4;
constexpr int32_t WARP_SIZE = 32;
constexpr int32_t WARPS_PER_BLOCK = static_cast<int32_t>(THREAD_NUM) / WARP_SIZE;

__simt_callee__ inline float FiniteOrZero(float value) { return isfinite(value) ? value : 0.0f; }

__simt_callee__ inline int32_t GetAdaptiveGridSize(float roiSize, int32_t pooledSize)
{
    float gridSize = roiSize / static_cast<float>(pooledSize);
    if (!isfinite(gridSize) || gridSize <= 0.0f || gridSize > MAX_ADAPTIVE_GRID_SIZE) {
        return 0;
    }
    return static_cast<int32_t>(ceilf(gridSize));
}

__simt_callee__ inline bool GetRoiBatchIndex(float value, int32_t batchSize, int32_t& batchIndex)
{
    if (batchSize <= 0) {
        return false;
    }
    value = FiniteOrZero(value);
    float maxIndex = static_cast<float>(batchSize - 1);
    if (value <= 0.0f) {
        batchIndex = 0;
    } else if (value >= maxIndex) {
        batchIndex = batchSize - 1;
    } else {
        batchIndex = static_cast<int32_t>(value);
    }
    return true;
}

// A function boundary forces the SIMT backend to return an IEEE fp32 value
// instead of carrying an extended temporary across a multi-add expression.
static __attribute__((noinline)) __simt_callee__ float AddRounded(float lhs, float rhs)
{
#pragma clang fp contract(off)
    return lhs + rhs;
}

static __attribute__((noinline)) __simt_callee__ float MulRounded(float lhs, float rhs)
{
#pragma clang fp contract(off)
    return lhs * rhs;
}

__simt_vf__ __aicore__ __launch_bounds__(THREAD_NUM) inline void ClearNonDetOutputsSimt(
    int64_t gradXElems, int64_t gradOffsetElems, __gm__ volatile float* gradX, __gm__ volatile float* gradOffset)
{
    int64_t first = static_cast<int64_t>(blockIdx.x) * blockDim.x + threadIdx.x;
    int64_t stride = static_cast<int64_t>(blockDim.x) * gridDim.x;
    for (int64_t idx = first; idx < gradXElems; idx += stride) {
        gradX[idx] = 0.0f;
    }
    for (int64_t idx = first; idx < gradOffsetElems; idx += stride) {
        gradOffset[idx] = 0.0f;
    }
}

__simt_callee__ inline bool ClampSample(float rawY, float rawX, int32_t H, int32_t W, float& y, float& xCoord,
                                        int32_t& yLow, int32_t& yHigh, int32_t& xLow, int32_t& xHigh)
{
    if (!isfinite(rawY) || !isfinite(rawX) || rawY < -1.0f || rawY > static_cast<float>(H) || rawX < -1.0f ||
        rawX > static_cast<float>(W)) {
        return false;
    }
    y = rawY <= 0.0f ? 0.0f : rawY;
    xCoord = rawX <= 0.0f ? 0.0f : rawX;
    yLow = static_cast<int32_t>(y);
    xLow = static_cast<int32_t>(xCoord);
    if (yLow >= H - 1) {
        yHigh = yLow = H - 1;
        y = static_cast<float>(yLow);
    } else {
        yHigh = yLow + 1;
    }
    if (xLow >= W - 1) {
        xHigh = xLow = W - 1;
        xCoord = static_cast<float>(xLow);
    } else {
        xHigh = xLow + 1;
    }
    return xLow >= 0 && xHigh >= 0 && yLow >= 0 && yHigh >= 0;
}

__simt_callee__ inline void AtomicGradXFour(float y, float xCoord, int32_t yLow, int32_t yHigh, int32_t xLow,
                                            int32_t xHigh, int32_t W, float gradBin, int64_t xBase, __gm__ float* gradX)
{
    float ly = y - static_cast<float>(yLow);
    float lx = xCoord - static_cast<float>(xLow);
    float hy = 1.0f - ly;
    float hx = 1.0f - lx;
    int64_t idx00 = xBase + static_cast<int64_t>(yLow) * W + xLow;
    int64_t idx10 = xBase + static_cast<int64_t>(yLow) * W + xHigh;
    int64_t idx01 = xBase + static_cast<int64_t>(yHigh) * W + xLow;
    int64_t idx11 = xBase + static_cast<int64_t>(yHigh) * W + xHigh;
    float value00 = MulRounded(gradBin, hy * hx);
    float value10 = MulRounded(gradBin, hy * lx);
    float value01 = MulRounded(gradBin, ly * hx);
    float value11 = MulRounded(gradBin, ly * lx);
    if (xLow == xHigh && yLow == yHigh) {
        __asc_simt_vf::asc_atomic_add(gradX + idx00,
                                      AddRounded(AddRounded(value00, value10), AddRounded(value01, value11)));
    } else if (xLow == xHigh) {
        __asc_simt_vf::asc_atomic_add(gradX + idx00, AddRounded(value00, value10));
        __asc_simt_vf::asc_atomic_add(gradX + idx01, AddRounded(value01, value11));
    } else if (yLow == yHigh) {
        __asc_simt_vf::asc_atomic_add(gradX + idx00, AddRounded(value00, value01));
        __asc_simt_vf::asc_atomic_add(gradX + idx10, AddRounded(value10, value11));
    } else {
        __asc_simt_vf::asc_atomic_add(gradX + idx00, value00);
        __asc_simt_vf::asc_atomic_add(gradX + idx10, value10);
        __asc_simt_vf::asc_atomic_add(gradX + idx01, value01);
        __asc_simt_vf::asc_atomic_add(gradX + idx11, value11);
    }
}

__simt_callee__ inline void OffsetContribution(float rawY, float rawX, int32_t yLow, int32_t yHigh, int32_t xLow,
                                               int32_t xHigh, int32_t W, int64_t xBase, float factorW, float factorH,
                                               const __gm__ float* x, float& contributionW, float& contributionH)
{
    float input00 = x[xBase + static_cast<int64_t>(yLow) * W + xLow];
    float input10 = x[xBase + static_cast<int64_t>(yLow) * W + xHigh];
    float input01 = x[xBase + static_cast<int64_t>(yHigh) * W + xLow];
    float input11 = x[xBase + static_cast<int64_t>(yHigh) * W + xHigh];
    float innerW = AddRounded(AddRounded(AddRounded(input11 * (rawY - static_cast<float>(yLow)),
                                                    input10 * (static_cast<float>(yHigh) - rawY)),
                                         input01 * (static_cast<float>(yLow) - rawY)),
                              input00 * (rawY - static_cast<float>(yHigh)));
    float innerH = AddRounded(AddRounded(AddRounded(input11 * (rawX - static_cast<float>(xLow)),
                                                    input01 * (static_cast<float>(xHigh) - rawX)),
                                         input10 * (static_cast<float>(xLow) - rawX)),
                              input00 * (rawX - static_cast<float>(xHigh)));
    contributionW = MulRounded(factorW, innerW);
    contributionH = MulRounded(factorH, innerH);
}

template <int32_t HAS_OFFSET>
__simt_callee__ inline void AccumulateSample(float rawY, float rawX, int32_t H, int32_t W, float gradBin, float factorW,
                                             float factorH, int64_t xBase, const __gm__ float* x, __gm__ float* gradX,
                                             float& contributionW, float& contributionH)
{
#pragma clang fp contract(off)
    contributionW = 0.0f;
    contributionH = 0.0f;
    float y = 0.0f;
    float xCoord = 0.0f;
    int32_t yLow = 0;
    int32_t yHigh = 0;
    int32_t xLow = 0;
    int32_t xHigh = 0;
    if (!ClampSample(rawY, rawX, H, W, y, xCoord, yLow, yHigh, xLow, xHigh)) {
        return;
    }
    AtomicGradXFour(y, xCoord, yLow, yHigh, xLow, xHigh, W, gradBin, xBase, gradX);
    if constexpr (HAS_OFFSET != 0) {
        OffsetContribution(rawY, rawX, yLow, yHigh, xLow, xHigh, W, xBase, factorW, factorH, x, contributionW,
                           contributionH);
    }
}

template <int32_t HAS_OFFSET>
__simt_callee__ inline bool PrepareBin(int32_t n, int32_t ph, int32_t pw, int32_t B, int32_t pH, int32_t pW,
                                       int32_t samplingRatio, float spatialScale, float gamma, const __gm__ float* rois,
                                       const __gm__ float* offset, int32_t& roiBatchInd, int32_t& gridH, int32_t& gridW,
                                       float& baseY, float& baseX, float& stepY, float& stepX, float& invGridCount,
                                       float& gammaWidth, float& gammaHeight, bool& offsetWFinite, bool& offsetHFinite)
{
    int64_t roiBase = static_cast<int64_t>(n) * 5;
    if (!GetRoiBatchIndex(rois[roiBase], B, roiBatchInd)) {
        return false;
    }
    float roiStartW = FiniteOrZero(rois[roiBase + 1]) * spatialScale - 0.5f;
    float roiStartH = FiniteOrZero(rois[roiBase + 2]) * spatialScale - 0.5f;
    float roiWidth = FiniteOrZero(rois[roiBase + 3]) * spatialScale - 0.5f - roiStartW;
    float roiHeight = FiniteOrZero(rois[roiBase + 4]) * spatialScale - 0.5f - roiStartH;
    float binH = roiHeight / static_cast<float>(pH);
    float binW = roiWidth / static_cast<float>(pW);
    gridH = samplingRatio > 0 ? samplingRatio : GetAdaptiveGridSize(roiHeight, pH);
    gridW = samplingRatio > 0 ? samplingRatio : GetAdaptiveGridSize(roiWidth, pW);
    int64_t count = static_cast<int64_t>(gridH) * gridW;
    if (count <= 0) {
        return false;
    }
    float curStartW = roiStartW;
    float curStartH = roiStartH;
    gammaWidth = MulRounded(gamma, roiWidth);
    gammaHeight = MulRounded(gamma, roiHeight);
    offsetWFinite = true;
    offsetHFinite = true;
    if constexpr (HAS_OFFSET != 0) {
        int64_t offW = (static_cast<int64_t>(n) * 2 * pH + ph) * pW + pw;
        int64_t offH = (static_cast<int64_t>(n) * 2 * pH + pH + ph) * pW + pw;
        float rawOffsetW = offset[offW];
        float rawOffsetH = offset[offH];
        offsetWFinite = isfinite(rawOffsetW);
        offsetHFinite = isfinite(rawOffsetH);
        curStartW = AddRounded(roiStartW, MulRounded(gammaWidth, FiniteOrZero(rawOffsetW)));
        curStartH = AddRounded(roiStartH, MulRounded(gammaHeight, FiniteOrZero(rawOffsetH)));
    }
    invGridCount = 1.0f / static_cast<float>(count);
    stepY = binH / static_cast<float>(gridH);
    stepX = binW / static_cast<float>(gridW);
    baseY = AddRounded(AddRounded(curStartH, static_cast<float>(ph) * binH), 0.5f * stepY);
    baseX = AddRounded(AddRounded(curStartW, static_cast<float>(pw) * binW), 0.5f * stepX);
    return true;
}

__simt_callee__ inline void DecodeBin(int64_t bin, int32_t C, int32_t pH, int32_t pW, int32_t& n, int32_t& c,
                                      int32_t& ph, int32_t& pw)
{
    pw = static_cast<int32_t>(bin % pW);
    int64_t rem = bin / pW;
    ph = static_cast<int32_t>(rem % pH);
    rem /= pH;
    c = static_cast<int32_t>(rem % C);
    n = static_cast<int32_t>(rem / C);
}

__simt_callee__ inline void DecodeWarpGroup(int64_t group, int32_t channelTiles, int32_t chunkCount, int32_t pH,
                                            int32_t pW, int32_t& n, int32_t& ph, int32_t& pw, int32_t& chunk,
                                            int32_t& channelTile)
{
    channelTile = static_cast<int32_t>(group % channelTiles);
    int64_t rem = group / channelTiles;
    chunk = static_cast<int32_t>(rem % chunkCount);
    rem /= chunkCount;
    pw = static_cast<int32_t>(rem % pW);
    rem /= pW;
    ph = static_cast<int32_t>(rem % pH);
    n = static_cast<int32_t>(rem / pH);
}

__simt_callee__ inline void ProcessNoOffsetSample(int32_t sample, int32_t gridW, float baseY, float baseX, float stepY,
                                                  float stepX, int32_t H, int32_t W, float gradBin, int64_t xBase,
                                                  __gm__ float* gradX)
{
    int32_t iy = sample / gridW;
    int32_t ix = sample - iy * gridW;
    float rawY = AddRounded(baseY, static_cast<float>(iy) * stepY);
    float rawX = AddRounded(baseX, static_cast<float>(ix) * stepX);
    float unusedW = 0.0f;
    float unusedH = 0.0f;
    AccumulateSample<0>(rawY, rawX, H, W, gradBin, 0.0f, 0.0f, xBase, nullptr, gradX, unusedW, unusedH);
}

__simt_callee__ inline void ProcessOffsetSampleWarp(bool active, int32_t lane, int32_t sample, int32_t gridW,
                                                    float baseY, float baseX, float stepY, float stepX, int32_t H,
                                                    int32_t W, float gradBin, float factorW, float factorH,
                                                    int64_t xBase, bool writeW, bool writeH, const __gm__ float* x,
                                                    __gm__ float* gradX, int64_t outW, int64_t outH,
                                                    __gm__ float* gradOffset)
{
    float contributionW = 0.0f;
    float contributionH = 0.0f;
    if (active) {
        int32_t iy = sample / gridW;
        int32_t ix = sample - iy * gridW;
        float rawY = AddRounded(baseY, static_cast<float>(iy) * stepY);
        float rawX = AddRounded(baseX, static_cast<float>(ix) * stepX);
        AccumulateSample<1>(rawY, rawX, H, W, gradBin, factorW, factorH, xBase, x, gradX, contributionW, contributionH);
    }
    float sumW = asc_reduce_add(contributionW);
    float sumH = asc_reduce_add(contributionH);
    if (lane == 0) {
        if (writeW) {
            __asc_simt_vf::asc_atomic_add(gradOffset + outW, sumW);
        }
        if (writeH) {
            __asc_simt_vf::asc_atomic_add(gradOffset + outH, sumH);
        }
    }
}

__simt_vf__ __aicore__ __launch_bounds__(THREAD_NUM) inline void ComputeFusedAtomicFixedNoOffset(
    int32_t N, int32_t C, int32_t pH, int32_t pW, int32_t B, int32_t H, int32_t W, int32_t samplingRatio,
    float spatialScale, float gamma, const __gm__ float* grad, const __gm__ float* rois, __gm__ float* gradX)
{
    int64_t first = static_cast<int64_t>(blockIdx.x) + static_cast<int64_t>(threadIdx.x) * gridDim.x;
    int64_t stride = static_cast<int64_t>(blockDim.x) * gridDim.x;
    int64_t sampleCount = static_cast<int64_t>(samplingRatio) * samplingRatio;
    int32_t chunkCount = static_cast<int32_t>((sampleCount + SAMPLE_CHUNK - 1) / SAMPLE_CHUNK);
    int64_t binWork = static_cast<int64_t>(N) * C * pH * pW;
    for (int64_t task = first; task < binWork * chunkCount; task += stride) {
        int32_t chunk = static_cast<int32_t>(task % chunkCount);
        int64_t bin = task / chunkCount;
        int32_t n, c, ph, pw;
        DecodeBin(bin, C, pH, pW, n, c, ph, pw);
        int32_t roiBatchInd, gridH, gridW;
        float baseY, baseX, stepY, stepX, invCount, gammaW, gammaH;
        bool offsetWFinite, offsetHFinite;
        if (!PrepareBin<0>(n, ph, pw, B, pH, pW, samplingRatio, spatialScale, gamma, rois, nullptr, roiBatchInd, gridH,
                           gridW, baseY, baseX, stepY, stepX, invCount, gammaW, gammaH, offsetWFinite, offsetHFinite)) {
            continue;
        }
        int64_t gradIdx = ((static_cast<int64_t>(n) * C + c) * pH + ph) * pW + pw;
        float gradBin = MulRounded(grad[gradIdx], invCount);
        int64_t xBase = (static_cast<int64_t>(roiBatchInd) * C + c) * H * W;
        for (int32_t k = 0; k < SAMPLE_CHUNK; ++k) {
            int64_t sample = static_cast<int64_t>(chunk) * SAMPLE_CHUNK + k;
            if (sample < sampleCount) {
                ProcessNoOffsetSample(static_cast<int32_t>(sample), gridW, baseY, baseX, stepY, stepX, H, W, gradBin,
                                      xBase, gradX);
            }
        }
    }
}

__simt_vf__ __aicore__ __launch_bounds__(THREAD_NUM) inline void ComputeFusedAtomicAdaptiveNoOffset(
    int32_t N, int32_t C, int32_t pH, int32_t pW, int32_t B, int32_t H, int32_t W, float spatialScale, float gamma,
    const __gm__ float* grad, const __gm__ float* rois, __gm__ float* gradX)
{
    int64_t first = static_cast<int64_t>(blockIdx.x) + static_cast<int64_t>(threadIdx.x) * gridDim.x;
    int64_t stride = static_cast<int64_t>(blockDim.x) * gridDim.x;
    int64_t binWork = static_cast<int64_t>(N) * C * pH * pW;
    for (int64_t bin = first; bin < binWork; bin += stride) {
        int32_t n, c, ph, pw;
        DecodeBin(bin, C, pH, pW, n, c, ph, pw);
        int32_t roiBatchInd, gridH, gridW;
        float baseY, baseX, stepY, stepX, invCount, gammaW, gammaH;
        bool offsetWFinite, offsetHFinite;
        if (!PrepareBin<0>(n, ph, pw, B, pH, pW, 0, spatialScale, gamma, rois, nullptr, roiBatchInd, gridH, gridW,
                           baseY, baseX, stepY, stepX, invCount, gammaW, gammaH, offsetWFinite, offsetHFinite)) {
            continue;
        }
        int64_t gradIdx = ((static_cast<int64_t>(n) * C + c) * pH + ph) * pW + pw;
        float gradBin = MulRounded(grad[gradIdx], invCount);
        int64_t xBase = (static_cast<int64_t>(roiBatchInd) * C + c) * H * W;
        int64_t sampleCount = static_cast<int64_t>(gridH) * gridW;
        for (int64_t sample = 0; sample < sampleCount; ++sample) {
            ProcessNoOffsetSample(static_cast<int32_t>(sample), gridW, baseY, baseX, stepY, stepX, H, W, gradBin, xBase,
                                  gradX);
        }
    }
}

__simt_callee__ inline void ProcessOffsetChunk(int32_t lane, bool validBin, bool validChannel, int32_t chunk,
                                               int32_t sampleCount, int32_t gridW, float baseY, float baseX,
                                               float stepY, float stepX, int32_t H, int32_t W, float gradBin,
                                               float gammaW, float gammaH, int64_t xBase, bool offsetWFinite,
                                               bool offsetHFinite, const __gm__ float* x, __gm__ float* gradX,
                                               int64_t outW, int64_t outH, __gm__ float* gradOffset)
{
    float factorW = MulRounded(gammaW, gradBin);
    float factorH = MulRounded(gammaH, gradBin);
    for (int32_t k = 0; k < SAMPLE_CHUNK; ++k) {
        int32_t sample = chunk * SAMPLE_CHUNK + k;
        bool validSample = sample < sampleCount;
        bool active = validBin && validChannel && validSample;
        ProcessOffsetSampleWarp(active, lane, sample, gridW, baseY, baseX, stepY, stepX, H, W, gradBin, factorW,
                                factorH, xBase, validBin && validSample && offsetWFinite,
                                validBin && validSample && offsetHFinite, x, gradX, outW, outH, gradOffset);
    }
}

__simt_vf__ __aicore__ __launch_bounds__(THREAD_NUM) inline void ComputeFusedAtomicFixedWithOffset(
    int32_t N, int32_t C, int32_t pH, int32_t pW, int32_t B, int32_t H, int32_t W, int32_t samplingRatio,
    float spatialScale, float gamma, const __gm__ float* grad, const __gm__ float* x, const __gm__ float* rois,
    const __gm__ float* offset, __gm__ float* gradX, __gm__ float* gradOffset)
{
    int32_t lane = static_cast<int32_t>(threadIdx.x) & (WARP_SIZE - 1);
    int32_t warpInBlock = static_cast<int32_t>(threadIdx.x) / WARP_SIZE;
    int64_t first = static_cast<int64_t>(blockIdx.x) * WARPS_PER_BLOCK + warpInBlock;
    int64_t stride = static_cast<int64_t>(gridDim.x) * WARPS_PER_BLOCK;
    int32_t sampleCount = samplingRatio * samplingRatio;
    int32_t chunkCount = (sampleCount + SAMPLE_CHUNK - 1) / SAMPLE_CHUNK;
    int32_t channelTiles = (C + WARP_SIZE - 1) / WARP_SIZE;
    int64_t groupCount = static_cast<int64_t>(N) * pH * pW * chunkCount * channelTiles;
    for (int64_t group = first; group < groupCount; group += stride) {
        int32_t n, ph, pw, chunk, channelTile;
        DecodeWarpGroup(group, channelTiles, chunkCount, pH, pW, n, ph, pw, chunk, channelTile);
        int32_t c = channelTile * WARP_SIZE + lane;
        bool validChannel = c < C;
        int32_t roiBatchInd = 0, gridH = samplingRatio, gridW = samplingRatio;
        float baseY = 0.0f, baseX = 0.0f, stepY = 0.0f, stepX = 0.0f;
        float invCount = 0.0f, gammaW = 0.0f, gammaH = 0.0f;
        bool offsetWFinite = false, offsetHFinite = false;
        bool validBin = PrepareBin<1>(n, ph, pw, B, pH, pW, samplingRatio, spatialScale, gamma, rois, offset,
                                      roiBatchInd, gridH, gridW, baseY, baseX, stepY, stepX, invCount, gammaW, gammaH,
                                      offsetWFinite, offsetHFinite);
        float gradBin = 0.0f;
        int64_t xBase = 0;
        if (validBin && validChannel) {
            int64_t gradIdx = ((static_cast<int64_t>(n) * C + c) * pH + ph) * pW + pw;
            gradBin = MulRounded(grad[gradIdx], invCount);
            xBase = (static_cast<int64_t>(roiBatchInd) * C + c) * H * W;
        }
        int64_t outW = (static_cast<int64_t>(n) * 2 * pH + ph) * pW + pw;
        int64_t outH = (static_cast<int64_t>(n) * 2 * pH + pH + ph) * pW + pw;
        ProcessOffsetChunk(lane, validBin, validChannel, chunk, sampleCount, gridW, baseY, baseX, stepY, stepX, H, W,
                           gradBin, gammaW, gammaH, xBase, offsetWFinite, offsetHFinite, x, gradX, outW, outH,
                           gradOffset);
    }
}

__simt_vf__ __aicore__ __launch_bounds__(THREAD_NUM) inline void ComputeFusedAtomicAdaptiveWithOffset(
    int32_t N, int32_t C, int32_t pH, int32_t pW, int32_t B, int32_t H, int32_t W, float spatialScale, float gamma,
    const __gm__ float* grad, const __gm__ float* x, const __gm__ float* rois, const __gm__ float* offset,
    __gm__ float* gradX, __gm__ float* gradOffset)
{
    int32_t lane = static_cast<int32_t>(threadIdx.x) & (WARP_SIZE - 1);
    int32_t warpInBlock = static_cast<int32_t>(threadIdx.x) / WARP_SIZE;
    int64_t first = static_cast<int64_t>(blockIdx.x) * WARPS_PER_BLOCK + warpInBlock;
    int64_t stride = static_cast<int64_t>(gridDim.x) * WARPS_PER_BLOCK;
    int32_t channelTiles = (C + WARP_SIZE - 1) / WARP_SIZE;
    int64_t groupCount = static_cast<int64_t>(N) * pH * pW * channelTiles;
    for (int64_t group = first; group < groupCount; group += stride) {
        int32_t n, ph, pw, unusedChunk, channelTile;
        DecodeWarpGroup(group, channelTiles, 1, pH, pW, n, ph, pw, unusedChunk, channelTile);
        int32_t c = channelTile * WARP_SIZE + lane;
        bool validChannel = c < C;
        int32_t roiBatchInd = 0, gridH = 0, gridW = 1;
        float baseY = 0.0f, baseX = 0.0f, stepY = 0.0f, stepX = 0.0f;
        float invCount = 0.0f, gammaW = 0.0f, gammaH = 0.0f;
        bool offsetWFinite = false, offsetHFinite = false;
        bool validBin = PrepareBin<1>(n, ph, pw, B, pH, pW, 0, spatialScale, gamma, rois, offset, roiBatchInd, gridH,
                                      gridW, baseY, baseX, stepY, stepX, invCount, gammaW, gammaH, offsetWFinite,
                                      offsetHFinite);
        float gradBin = 0.0f;
        int64_t xBase = 0;
        if (validBin && validChannel) {
            int64_t gradIdx = ((static_cast<int64_t>(n) * C + c) * pH + ph) * pW + pw;
            gradBin = MulRounded(grad[gradIdx], invCount);
            xBase = (static_cast<int64_t>(roiBatchInd) * C + c) * H * W;
        }
        int64_t outW = (static_cast<int64_t>(n) * 2 * pH + ph) * pW + pw;
        int64_t outH = (static_cast<int64_t>(n) * 2 * pH + pH + ph) * pW + pw;
        int32_t sampleCount = validBin ? gridH * gridW : 0;
        float factorW = MulRounded(gammaW, gradBin);
        float factorH = MulRounded(gammaH, gradBin);
        for (int32_t sample = 0; sample < sampleCount; ++sample) {
            ProcessOffsetSampleWarp(validChannel, lane, sample, gridW, baseY, baseX, stepY, stepX, H, W, gradBin,
                                    factorW, factorH, xBase, offsetWFinite, offsetHFinite, x, gradX, outW, outH,
                                    gradOffset);
        }
    }
}

template <int32_t HAS_OFFSET>
__aicore__ inline void LaunchFused(const DeformableRoiPoolGradTilingData* tilingData, const __gm__ float* grad,
                                   const __gm__ float* x, const __gm__ float* rois, const __gm__ float* offset,
                                   __gm__ float* gradX, __gm__ float* gradOffset)
{
    if constexpr (HAS_OFFSET == 0) {
        if (tilingData->samplingRatio > 0) {
            asc_vf_call<ComputeFusedAtomicFixedNoOffset>(
                dim3(THREAD_NUM), tilingData->N, tilingData->C, tilingData->pooledHeight, tilingData->pooledWidth,
                tilingData->B, tilingData->H, tilingData->W, tilingData->samplingRatio, tilingData->spatialScale,
                tilingData->gamma, grad, rois, gradX);
        } else {
            asc_vf_call<ComputeFusedAtomicAdaptiveNoOffset>(
                dim3(THREAD_NUM), tilingData->N, tilingData->C, tilingData->pooledHeight, tilingData->pooledWidth,
                tilingData->B, tilingData->H, tilingData->W, tilingData->spatialScale, tilingData->gamma, grad, rois,
                gradX);
        }
    } else if (tilingData->samplingRatio > 0) {
        asc_vf_call<ComputeFusedAtomicFixedWithOffset>(
            dim3(THREAD_NUM), tilingData->N, tilingData->C, tilingData->pooledHeight, tilingData->pooledWidth,
            tilingData->B, tilingData->H, tilingData->W, tilingData->samplingRatio, tilingData->spatialScale,
            tilingData->gamma, grad, x, rois, offset, gradX, gradOffset);
    } else {
        asc_vf_call<ComputeFusedAtomicAdaptiveWithOffset>(
            dim3(THREAD_NUM), tilingData->N, tilingData->C, tilingData->pooledHeight, tilingData->pooledWidth,
            tilingData->B, tilingData->H, tilingData->W, tilingData->spatialScale, tilingData->gamma, grad, x, rois,
            offset, gradX, gradOffset);
    }
}

template <int32_t HAS_OFFSET>
__aicore__ inline void Process(GM_ADDR grad, GM_ADDR x, GM_ADDR rois, GM_ADDR offset, GM_ADDR gradX, GM_ADDR gradOffset,
                               GM_ADDR workspace, const DeformableRoiPoolGradTilingData* tilingData)
{
    const __gm__ float* gradGm = (const __gm__ float*)grad;
    const __gm__ float* roisGm = (const __gm__ float*)rois;
    __gm__ float* gradXGm = (__gm__ float*)gradX;
    __gm__ float* gradOffsetGm = (__gm__ float*)gradOffset;
    asc_vf_call<ClearNonDetOutputsSimt>(dim3(THREAD_NUM), tilingData->gradInputElemNum, tilingData->gradOffsetElemNum,
                                        (__gm__ volatile float*)gradXGm, (__gm__ volatile float*)gradOffsetGm);
    if (tilingData->N == 0 || tilingData->B == 0) {
        SetFlag<HardEvent::V_S>(0);
        WaitFlag<HardEvent::V_S>(0);
        return;
    }
    SyncAll();
    if constexpr (HAS_OFFSET == 0) {
        LaunchFused<0>(tilingData, gradGm, nullptr, roisGm, nullptr, gradXGm, gradOffsetGm);
    } else {
        LaunchFused<1>(tilingData, gradGm, (const __gm__ float*)x, roisGm, (const __gm__ float*)offset, gradXGm,
                       gradOffsetGm);
    }
    (void)workspace;
}

} // namespace NsDeformableRoiPoolGradNonDet
#endif // DEFORMABLE_ROI_POOL_GRAD_SIMT_NONDETERMINISTIC_H
