/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file deformable_roi_pool_grad_tiling_data.h
 * \brief tiling data struct for deformable_roi_pool_grad
 *
 * 字段定义对齐 MDE 文档 §3.1。线程数 THREAD_NUM 不入 TilingData（kernel 侧 constexpr）。
 */

#ifndef DEFORMABLE_ROI_POOL_GRAD_TILING_DATA_H
#define DEFORMABLE_ROI_POOL_GRAD_TILING_DATA_H

struct DeformableRoiPoolGradTilingData {
    int32_t needCoreNum = 0;           // 实际启动核数
    int32_t N = 0;                     // ROI 数量（grad 的 N 维）
    int32_t C = 0;                     // 通道数
    int32_t pooledHeight = 0;          // 池化高 pH
    int32_t pooledWidth = 0;           // 池化宽 pW
    int32_t B = 0;                     // feature_map batch
    int32_t H = 0;                     // feature_map 高
    int32_t W = 0;                     // feature_map 宽
    int32_t samplingRatio = 0;         // 采样比率（0=自适应）
    int32_t hasOffset = 0;             // 是否有 offset（0=无, 1=有），冗余于 TilingKey
    float spatialScale = 0.0f;         // 空间缩放比
    float gamma = 0.0f;                // offset 缩放因子
    int64_t totalElements = 0;         // Phase1 总元素数 N*C*pH*pW
    int64_t gradInputElemNum = 0;      // grad_x 元素数 B*C*H*W
    int64_t gradOffsetElemNum = 0;     // grad_offset 元素数 N*2*pH*pW
    int64_t wsGradInputStride = 0;     // 单份 float grad_input buffer 元素数（128B 对齐）
    int64_t wsGradOffsetStride = 0;    // 保留字段；确定性实现不需要 grad_offset workspace
    int64_t wsGradInputBaseElems = 0;  // grad_input workspace 总元素数
    int64_t wsGradOffsetBaseElems = 0; // 保留字段；等于 grad_input workspace 末尾
};

#endif // DEFORMABLE_ROI_POOL_GRAD_TILING_DATA_H
